/**
 * Sabian Symbols — 360 degree-based symbolic images for each degree of the zodiac.
 * Originally channeled by Marc Edmund Jones and Elsie Wheeler in 1925,
 * later revised by Dane Rudhyar. Each degree (1-30) of each sign has a unique symbol.
 *
 * Used in the almanac to show the Sabian symbol for the current Sun degree.
 */

export interface SabianSymbol {
  degree: number;       // 1-30 within the sign
  sign: string;
  symbol: string;       // the image/phrase
  keynote: string;      // Rudhyar-style one-line interpretation
}

// Full 360 symbols organized by sign, degree 1-30
const SYMBOLS: Record<string, string[]> = {
  Aries: [
    "A runner crouches at the starting line, eyes fixed ahead",
    "A match is struck in a dark room, revealing a doorway",
    "A child takes a running leap off a dock into summer water",
    "A woman cuts her own hair and feels suddenly free",
    "Sparks fly upward from a freshly lit campfire at dusk",
    "A cyclist races downhill with arms wide open",
    "A single red tulip pushes through a crack in concrete",
    "Someone packs a bag at midnight for an unplanned road trip",
    "A heartbeat quickens before a first kiss",
    "A blank canvas waits on an easel in morning light",
    "Thunder rolls across an open plain, energizing the air",
    "A person steps onto a stage and the crowd goes quiet",
    "A key turns in a lock that hasn't been opened in years",
    "Two friends dare each other to jump into a cold lake",
    "A kite catches an updraft and soars higher than expected",
    "The first crocus breaks through late-winter snow",
    "A deep breath taken before speaking a difficult truth",
    "An empty road stretches into the desert at sunrise",
    "A teenager spray-paints a bold mural on a bare wall",
    "A bird launches from a wire into a strong headwind",
    "Boxing gloves are laced tight before the bell rings",
    "A garden gate swings open to reveal a sunlit path",
    "A songwriter hums the first notes of something new",
    "Wind chimes ring wildly during a sudden spring gust",
    "A diver stands at the edge of a high cliff above blue water",
    "A street musician draws a crowd with raw, untrained talent",
    "A second chance arrives disguised as an ordinary morning",
    "A speaker finds courage mid-sentence and the room shifts",
    "Fireworks explode over a city skyline at midnight",
    "A newborn grips a parent's finger with surprising strength",
  ],
  Taurus: [
    "Morning light pours through a kitchen window onto fresh bread",
    "A couple slow-dances barefoot on a wooden porch",
    "Rain falls softly on a field of wildflowers in May",
    "A potter shapes clay on a wheel, lost in concentration",
    "A grandmother's quilt is spread across a sun-warmed bed",
    "Honey drips slowly from a wooden spoon into a ceramic bowl",
    "A stone cottage surrounded by an overgrown rose garden",
    "Someone closes their eyes and savors the first bite of a meal",
    "A cellist plays alone in an empty room with perfect acoustics",
    "An old oak tree provides shade for a family picnic",
    "A gardener kneels in rich soil, planting seeds by hand",
    "Two friends share a bottle of wine at a sidewalk cafe",
    "A worn leather journal filled with pressed flowers and notes",
    "Children run barefoot through warm grass after a rain shower",
    "A hand-thrown mug holds the first coffee of the morning",
    "A sunset paints the sky in shades of amber and rose",
    "A dog sleeps in a patch of afternoon sunlight on the floor",
    "Fresh laundry billows on a clothesline in a gentle breeze",
    "A mossy path leads to a hidden waterfall in the woods",
    "Candles flicker on a table set with care for someone loved",
    "A farmer's market overflows with ripe fruit and fresh herbs",
    "A wool blanket is pulled up to the chin on a cold night",
    "A jeweler polishes a simple gold band to a warm glow",
    "A meadow of lavender hums with bees in the late afternoon",
    "A park bench under a blooming magnolia tree invites rest",
    "Someone sings a lullaby from memory to a sleepy child",
    "A hand-built stone wall borders a green pasture",
    "The scent of jasmine drifts through an open bedroom window",
    "Two old friends sit together in comfortable silence at dusk",
    "A peacock spreads its tail feathers in a sunlit garden",
  ],
  Gemini: [
    "Two strangers strike up a conversation on a long train ride",
    "A bookshop with mismatched chairs and handwritten recommendations",
    "A child asks 'why' for the seventh time and gets a real answer",
    "Text messages fly back and forth late into the night",
    "A podcast host leans into the mic, delighted by a guest's story",
    "A student fills a notebook with sketches and margin notes",
    "Twins finish each other's sentences at a dinner party",
    "A crossword puzzle is solved in ink without hesitation",
    "A quiver of colorful pens spills across a desk",
    "A comedian riffs on the absurdity of everyday routines",
    "A traveler learns three phrases in a new language at a cafe",
    "A debate sparks laughter instead of argument between friends",
    "A pianist improvises, weaving two melodies into one",
    "A voice memo captures a fleeting idea during a morning walk",
    "Two neighbors swap stories and recipes over a garden fence",
    "A journalist's eyes light up when a source reveals the truth",
    "A teenager's bedroom wall is covered in quotes and postcards",
    "A bilingual child translates for a grandparent at the store",
    "A dusty library book falls open to a passage that resonates",
    "A food truck menu offers unexpected flavor combinations",
    "A protest sign uses humor to make its point unforgettable",
    "Friends teach each other card games on a rainy afternoon",
    "Three baby birds in a nest chirp for their mother's return",
    "Kids play a made-up game with ever-changing rules",
    "A window washer waves at office workers from the outside",
    "Frost patterns on glass catch the light like tiny galaxies",
    "A person on a rooftop gazes at the city and imagines leaving",
    "A fresh start arrives in the form of an unexpected phone call",
    "The first birdsong at dawn breaks through the quiet",
    "A street fair buzzes with music, laughter, and the smell of food",
  ],
  Cancer: [
    "A porch light is left on for someone coming home late",
    "A photo album falls open to a picture from childhood",
    "A warm kitchen fills with the smell of a family recipe",
    "A cat curls up in a box too small, perfectly content",
    "Rain taps on a tin roof while someone reads under a blanket",
    "A bird lines its nest with soft scraps of fabric and string",
    "Moonlight spills across a quiet lake at midnight",
    "A child carries a favorite stuffed animal everywhere they go",
    "A seashell held to the ear brings back a day at the beach",
    "A rough stone is tumbled smooth over many patient weeks",
    "A grandmother tells a bedtime story she heard as a child",
    "A candle is lit in the window on the longest night of the year",
    "A journal entry written on a hard day is re-read years later",
    "An elderly man sits on a bench where he once proposed",
    "Friends gather around a table overflowing with comfort food",
    "A tide pool reveals tiny worlds within its shallow walls",
    "A seedling is moved from a paper cup to the garden soil",
    "A mother bird shields her young from a sudden downpour",
    "Two people exchange vows in a living room, surrounded by family",
    "A gondola drifts beneath old bridges at twilight",
    "A singer's voice cracks with emotion and the audience leans in",
    "A woman watches the harbor from a pier, waiting for a boat",
    "A book club meets in someone's living room with tea and cookies",
    "A hammock swings gently between two trees near the water",
    "A firefly jar glows on a nightstand beside a sleeping child",
    "A reading nook is carved out of a cluttered apartment",
    "A sudden storm sends everyone running under the same awning",
    "A person learns to cook their grandmother's soup from memory",
    "Twins in a cradle reach for each other's hands",
    "An old house creaks and settles, full of history and warmth",
  ],
  Leo: [
    "A child runs to the front of the room to show their drawing",
    "A bonfire leaps high and lights up every face in the circle",
    "A woman wears a vintage dress that makes her feel invincible",
    "A trophy sits on a shelf beside childhood photos",
    "Sunlight hits a cathedral's stained glass, painting the floor",
    "A teenager performs their own song at an open mic night",
    "The night sky blazes with stars seen from a mountaintop",
    "A muralist paints a golden sun on the side of a building",
    "A glassblower shapes a glowing orb with steady breath",
    "Morning dew catches sunlight across a wide green field",
    "Children shriek with joy on a tire swing in the backyard",
    "A garden party glows with string lights and soft music",
    "An old storyteller holds a room spellbound with a single tale",
    "A dancer rehearses alone, preparing to move an audience",
    "A parade fills the street with color, drumbeats, and cheering",
    "After a summer storm, everything gleams in the returning sun",
    "A community choir lifts their voices in an unexpected harmony",
    "A teacher demonstrates a concept and a student's eyes light up",
    "Friends float on inner tubes down a lazy river, laughing",
    "A campfire circle passes a guitar from hand to hand",
    "A baby lion wobbles on new legs and tries to roar",
    "A love letter is slipped under a door and found at dawn",
    "An acrobat balances on a tightrope high above the crowd",
    "An artist paints for hours, forgetting to eat or check the time",
    "A lone hiker reaches the summit and raises their arms",
    "A double rainbow arcs over a valley after a fierce storm",
    "The first golden light of dawn spills over the eastern hills",
    "Songbirds gather on a single branch and sing in turns",
    "A shy person steps into the spotlight and finds their voice",
    "A handwritten note says everything the sender couldn't say aloud",
  ],
  Virgo: [
    "A portrait captures someone's kindest expression perfectly",
    "A lighthouse beam sweeps steadily across a foggy harbor",
    "A nurse checks on a patient at three in the morning",
    "Children of different backgrounds build a fort together",
    "A beekeeper tends hives with calm, deliberate movements",
    "A carousel horse is carefully repainted in bright colors",
    "A yoga class breathes together in a sunlit studio",
    "A five-year-old practices writing their name over and over",
    "A painter mixes the exact shade they've been searching for",
    "Two paths diverge and a hiker pauses to read the trail signs",
    "A parent watches their child solve a problem independently",
    "The first honest conversation after months of small talk",
    "A mechanic diagnoses an engine problem by sound alone",
    "A family tree is carefully sketched in a leather-bound notebook",
    "A tailor adjusts a hem with precise, invisible stitches",
    "A child presses their face to an aquarium, wide-eyed",
    "A dormant volcano is covered in wildflowers and silence",
    "A librarian places a perfect recommendation on the hold shelf",
    "Swimmers race to the far buoy and back on a summer morning",
    "Coworkers share a ride and discover unexpected common ground",
    "A pickup basketball game brings the whole block together",
    "A hand-lettered sign welcomes guests to a small-town festival",
    "A veterinarian calms a frightened animal with a steady hand",
    "A child follows a ladybug across a leaf with quiet fascination",
    "Flags are lowered in respectful memory of someone who served",
    "A volunteer sorts donations with care, thinking of who will need them",
    "Friends gather to prepare a meal together in a small kitchen",
    "A CEO rolls up their sleeves and cleans up after the team",
    "A researcher reads deep into the night, following a lead",
    "A craftsperson ignores distractions, absorbed in finishing their work",
  ],
  Libra: [
    "A butterfly lands on a sculpture in an outdoor gallery",
    "A lesson learned the hard way becomes advice freely given",
    "Sunrise reveals the world washed clean after overnight rain",
    "Friends sit around a fire pit, sharing stories under the stars",
    "A mentor reveals a perspective that changes everything",
    "An architect sees a finished building in an empty blueprint",
    "A neighbor brings soup to someone going through a hard time",
    "A fireplace crackles in a room no one has entered in years",
    "Three paintings in a gallery stop a visitor in their tracks",
    "A kayaker navigates rapids with calm, focused precision",
    "A wise teacher asks a question instead of giving an answer",
    "A miner emerges from underground into blinding daylight",
    "Children blow soap bubbles that drift across a summer lawn",
    "A hammock sways in the shade while the world rushes by",
    "A spiral staircase leads up to an unexpected rooftop view",
    "A dock is rebuilt plank by plank after a rough season",
    "A retired traveler watches planes take off from a cafe window",
    "Two people agree to disagree and keep their friendship intact",
    "A graffiti artist turns an ugly wall into something beautiful",
    "A mediator finds the one thing both sides can agree on",
    "A beach at sunset fills with people watching the same sky",
    "A child offers water to a thirsty pigeon in the park",
    "A rooster crows at first light, answered by birdsong everywhere",
    "A person discovers a hidden talent they never thought to try",
    "A leaf spirals down from a branch and lands in open palms",
    "A hawk and a dove perch on the same power line",
    "A paper airplane glides from a high window across the street",
    "A stranger offers an umbrella to someone caught in the rain",
    "A grandmother passes her recipe box to a grandchild",
    "A philosopher sits quietly in a garden, watching clouds change shape",
  ],
  Scorpio: [
    "A diver descends into deep blue water, leaving the surface behind",
    "A perfume bottle shatters on tile, flooding the room with scent",
    "Neighbors work together to rebuild a fence after a storm",
    "A candle is lit in a dark room and held with both hands",
    "A rocky shoreline absorbs wave after crashing wave, unmoved",
    "Someone walks away from comfort to chase what feels true",
    "A free diver descends past the point where light reaches",
    "A still lake reflects the full moon without a ripple",
    "A surgeon focuses completely, steady hands saving a life",
    "Old friends reunite and pick up exactly where they left off",
    "A lifeguard pulls a swimmer to safety through rough surf",
    "A masquerade ball where everyone knows more than they reveal",
    "A scientist stays up all night chasing a breakthrough",
    "Two tin cans and a string carry a secret between windows",
    "A child builds a sandcastle and then lets the tide take it",
    "A shy smile melts the tension in a difficult conversation",
    "A curtain is drawn back to reveal a hidden room full of light",
    "A forest in autumn blazes with color before letting go",
    "A parrot repeats a phrase that accidentally tells the truth",
    "Someone finally says the thing everyone was thinking",
    "A whistleblower slides an envelope under the right door",
    "A photographer waits hours for the perfect shot of a hawk",
    "A caterpillar dissolves completely inside its cocoon",
    "A crowd disperses after hearing words that changed them",
    "An X-ray reveals what no one could see from the outside",
    "A family sets up camp in unfamiliar territory and makes it home",
    "A marching band turns a gray street into a celebration",
    "A quiet person enters a room and everyone senses the shift",
    "A mother shields her children and speaks truth to power",
    "Kids in costumes knock on doors, fearless and laughing",
  ],
  Sagittarius: [
    "College friends gather years later and laugh until they cry",
    "Whitecaps roll across the open ocean under a vast sky",
    "Two chess players sit across from each other in a park",
    "A toddler takes wobbly first steps toward outstretched arms",
    "An owl watches the forest from the highest branch at dusk",
    "A group of friends invents a game with sticks and a ball",
    "A love note is tucked into someone's coat pocket before a trip",
    "Deep underground, pressure turns carbon into diamond",
    "A parent carries a sleepy child up a long flight of stairs",
    "A spotlight falls on someone who has been waiting for their moment",
    "A candle burns steadily in a window through a long winter night",
    "A flag catches the wind and snaps open against a bright sky",
    "A diary is discovered in an attic and read by candlelight",
    "A traveler stands before ancient ruins and feels the weight of time",
    "A groundhog emerges from its burrow and sniffs the warming air",
    "Seagulls follow a fishing boat, crying out over the wake",
    "A sunrise service on a hilltop draws people from every direction",
    "Children build blanket forts and tell stories by flashlight",
    "A wildlife sanctuary gives injured animals space to heal",
    "A community shares preserved food through a long winter",
    "A child puts on oversized sunglasses and poses for a photo",
    "A small restaurant with hand-washed dishes and no menu",
    "A newcomer arrives in a new city with one suitcase and big plans",
    "A bluebird lands on a fence post outside a cottage window",
    "A kid on a bike with training wheels races down the sidewalk",
    "Someone holds a lantern high while others find their footing",
    "A sculptor chips away marble to reveal the form within",
    "A wooden bridge over a stream has been crossed by generations",
    "A teenager mows the lawn while listening to their favorite album",
    "An elder blesses a gathering with words that still everyone",
  ],
  Capricorn: [
    "A CEO stands before their team and outlines a ten-year vision",
    "A stained-glass window shows cracks but still catches the light",
    "A college student moves into their first apartment alone",
    "A crew loads supplies into a boat before a long expedition",
    "A team hauls equipment up a steep trail at dawn",
    "Ten stepping stones cross a creek into deeper woods",
    "A keynote speaker takes a breath before the biggest talk of their life",
    "Songbirds fill a sunlit porch with effortless music",
    "A cellist plays at a memorial and every eye is wet",
    "A wild bird eats from a patient hand after weeks of trust",
    "A vineyard stretches in neat rows across a sunlit hillside",
    "A documentary reveals something hidden in plain sight",
    "A monk meditates at dawn, facing a snow-covered mountain",
    "An inscription on a bridge outlasts everything around it",
    "A children's hospital is filled with art made by young patients",
    "Athletes stretch and warm up before the race of their lives",
    "A woman quits her job and starts the business she always imagined",
    "A flag snaps in the wind atop a building that took years to build",
    "A child carries groceries inside without being asked",
    "A choir rehearses in an empty hall, their voices filling the space",
    "Relay runners pass a baton in perfect stride without looking",
    "A competitor congratulates the winner with genuine respect",
    "A firefighter receives a commendation at a quiet ceremony",
    "A person donates everything to enter a life of simple purpose",
    "A small shop filled with handmade goods from around the world",
    "A waterfall catches afternoon light and turns to mist and rainbows",
    "Stone steps worn smooth by centuries of devoted climbers",
    "A well-kept greenhouse shelters rare plants through winter",
    "A fortune teller reads tea leaves and smiles knowingly",
    "A late-night meeting shapes decisions that will matter for decades",
  ],
  Aquarius: [
    "A community garden thrives on a vacant city lot",
    "A sudden thunderstorm sends strangers running under the same tree",
    "Someone quits the expected path and nobody understands yet",
    "A teacher shares a radical idea and watches minds open",
    "An elder's advice echoes in a young leader's bold decision",
    "A street performer in a mask tells a story without words",
    "A child asks a question that stumps every adult in the room",
    "A diverse crowd marches together under a single banner",
    "A symbol spray-painted on a wall becomes a movement",
    "A celebrity steps off the pedestal and admits they are human",
    "A person sits alone in a quiet room and receives a sudden insight",
    "People from different backgrounds share an elevator in silence",
    "A weather vane spins, sensing a shift before anyone else",
    "A subway car disappears into a tunnel, lights flickering",
    "Two lovebirds sit on a wire, leaning into each other",
    "An entrepreneur works alone at a desk surrounded by blueprints",
    "A loyal dog waits by the door, ears up, listening",
    "A leaked document reveals what was hidden from the public",
    "Volunteers form a bucket brigade to fight a spreading fire",
    "A white dove carries an olive branch across a gray sky",
    "A woman walks forward on an empty road after a great loss",
    "A play mat on a cold floor turns a room into a world of imagination",
    "A bear in a river catches a fish and pauses, almost playful",
    "A mentor speaks from hard-won experience and the room listens",
    "A butterfly with one wing slightly larger still flies beautifully",
    "A mechanic fine-tunes an engine until it purrs",
    "A jar of wildflowers sits on a windowsill in a modern apartment",
    "A family stocks the pantry and checks the generator before winter",
    "A butterfly pulls free from its chrysalis and dries its wings",
    "A circle of people from many places hold hands in the dark",
  ],
  Pisces: [
    "A farmer's market at dawn, tables piled high with every color",
    "A fox hides behind a fallen log, watching hikers pass",
    "Driftwood washed ashore tells the story of a distant forest",
    "A bridge between two islands is packed with travelers going both ways",
    "A bake sale raises money for something the whole town needs",
    "A marching band moves in perfect sync down a sunlit street",
    "A lighthouse beam cuts through fog, guiding someone safely in",
    "A child blows a dandelion and watches the seeds scatter",
    "A surfer paddles hard to catch the wave of the day",
    "A pilot flies above the clouds and sees only blue and gold",
    "Hikers walk single file up a narrow mountain trail at sunrise",
    "A student sits for a final exam knowing they have prepared well",
    "A museum displays everyday objects from a forgotten era",
    "A silk scarf is draped over a chair in a quiet, elegant room",
    "A rock climber chalks their hands before the hardest pitch",
    "A writer stares out the window and the right words finally come",
    "A spring festival fills the town square with flowers and music",
    "A campfire storyteller holds an audience in the palm of their hand",
    "A student and teacher bow to each other after a final lesson",
    "A table is set with candles and flowers for a quiet dinner",
    "A child whispers a secret to a sleeping cat in a sunny room",
    "A visionary shares a new idea that shifts the conversation",
    "A medium sits still and the room fills with unexpected warmth",
    "An island village gathers for a meal as the sun goes down",
    "A community overcomes division by remembering shared values",
    "A thin crescent moon appears at sunset and everyone looks up",
    "A harvest moon rises over a quiet field at the end of the season",
    "A backyard garden yields more than anyone expected this year",
    "Sunlight passes through a prism and splits into a rainbow",
    "A child stares at a mountain and imagines who they will become",
  ],
};

// Keynotes — short interpretive phrases for each degree
const KEYNOTES: Record<string, string[]> = {
  Aries: [
    "The power of focused intention before action begins",
    "A small spark can illuminate an entire new direction",
    "Joy and bravery are natural partners in new beginnings",
    "Letting go of the old self makes room for who you are becoming",
    "Raw energy rises when purpose meets the moment",
    "Freedom is found in surrendering to forward momentum",
    "Life finds a way through even the hardest barriers",
    "Spontaneity unlocks doors that planning never could",
    "The body knows before the mind catches up",
    "Every creation begins with an empty space and a willingness",
    "Nature's power reminds us of our own untapped force",
    "Presence commands attention more than words ever can",
    "Some doors only open when you are finally ready",
    "Courage is contagious between those who trust each other",
    "Unexpected lift comes when you stop fighting the wind",
    "Persistence always outpaces the seasons of resistance",
    "Honesty requires its own kind of bravery",
    "The open road is an invitation, not a guarantee",
    "Self-expression is an act of claiming space in the world",
    "Strength reveals itself in the willingness to push forward",
    "Preparation sharpens the edge of every bold move",
    "Opportunity waits behind the willingness to step through",
    "Creativity begins with the courage to make the first sound",
    "Change arrives suddenly and stirs everything awake",
    "The leap matters more than the landing",
    "Authenticity draws people in more than polish ever could",
    "Renewal often wears the disguise of an ordinary day",
    "Conviction grows stronger in the act of speaking it",
    "Celebration marks the explosive arrival of something new",
    "Even the smallest life grips the world with fierce intention",
  ],
  Taurus: [
    "Simple pleasures hold the deepest nourishment",
    "Intimacy is built in unhurried, unguarded moments",
    "Nature's gentleness reminds us to soften our grip",
    "Craft is a conversation between the maker and the material",
    "What was made with love carries warmth across generations",
    "Patience and sweetness always arrive together",
    "Beauty endures longest when it grows wild",
    "Presence turns even ordinary meals into sacred acts",
    "Solitude and art create a space where the soul can breathe",
    "Deep roots provide shelter that nothing else can",
    "Growth begins when hands meet the earth directly",
    "Shared pleasure strengthens the bonds between people",
    "Memory lives in objects touched by many hands",
    "The body remembers joy even when the mind forgets",
    "Handmade things carry the spirit of their maker",
    "Beauty asks nothing of us but our attention",
    "Rest is not laziness but a form of trust",
    "Clean starts come from letting the wind carry things away",
    "Hidden places reward those who are willing to wander",
    "Care expressed through detail speaks louder than grand gestures",
    "Abundance is best when it is shared freely",
    "Comfort is the body's way of saying you are safe",
    "True value reveals itself through simplicity and care",
    "Nature hums with quiet industry beneath a calm surface",
    "The best invitations ask for nothing but your presence",
    "Songs passed down carry more than melody alone",
    "Strong boundaries create the conditions for flourishing",
    "The senses are trustworthy guides to what matters most",
    "The deepest friendships need no words to sustain them",
    "Confidence is most beautiful when it celebrates itself honestly",
  ],
  Gemini: [
    "Connection can begin with a single curious question",
    "Unexpected discoveries live in places that feel familiar",
    "Persistence in asking leads to understanding worth having",
    "Distance disappears when communication is honest",
    "Real conversation transforms both the speaker and the listener",
    "The mind grows sharpest when it plays freely with ideas",
    "Shared language creates a world only insiders can enter",
    "Confidence comes from trusting what you already know",
    "Creative tools are invitations to think differently",
    "Humor reveals truths that seriousness often hides",
    "Even a few words in someone's language open a door",
    "Disagreement can be playful when trust is present",
    "Synthesis is its own form of originality",
    "Fleeting thoughts deserve to be caught before they vanish",
    "Everyday exchange is where real wisdom circulates",
    "The truth is exciting to those who are ready for it",
    "We surround ourselves with the words that shape us",
    "Translation is an act of love between worlds",
    "Old books hold surprises for those who open them at random",
    "Surprise comes from combinations no one expected",
    "Wit is a form of intelligence that moves the heart",
    "Learning from each other turns strangers into friends",
    "Early vulnerability teaches us to ask for what we need",
    "Rules are best when they can bend with the moment",
    "A wave from the outside world can change your whole day",
    "Patterns appear in nature when we slow down to look",
    "Sometimes the view from above shows what must change below",
    "New beginnings can arrive through someone else's voice",
    "The day's first sounds set the tone for everything after",
    "Community is built from the simple act of showing up together",
  ],
  Cancer: [
    "Love is expressed through the small act of keeping watch",
    "The past comes alive when we give it our attention",
    "Tradition is a form of love passed through the senses",
    "Contentment has nothing to do with having the right size",
    "Safety sounds different to everyone, but it always comforts",
    "Care shows itself in the details others might overlook",
    "Stillness and reflected light reveal what daylight hides",
    "The things we carry say everything about what we treasure",
    "Objects become portals when memory charges them with feeling",
    "Transformation happens slowly for those with patience",
    "Stories are the thread that connects one generation to the next",
    "Ritual turns the darkest moments into something bearable",
    "Writing to ourselves is a form of future kindness",
    "Places hold feelings long after the events have passed",
    "Feeding people is one of the oldest forms of love",
    "Small worlds contain as much wonder as vast ones",
    "Every new planting is an act of faith in the future",
    "Protection is a fierce expression of tenderness",
    "The most meaningful ceremonies happen in living rooms",
    "Beauty drifts through the spaces between old and new",
    "Vulnerability connects us more deeply than perfection",
    "Waiting is its own form of devotion",
    "Shared reading creates bonds as strong as shared meals",
    "Rest is most restorative when surrounded by nature",
    "Small lights in the darkness are enough to guide us home",
    "Sanctuary can be carved out of even the smallest spaces",
    "Shared shelter makes strangers into temporary family",
    "We keep the people we love alive through their recipes",
    "Connection begins before words, in the simplest gestures",
    "A home is alive with every story its walls have absorbed",
  ],
  Leo: [
    "The desire to be seen is a healthy, human impulse",
    "Shared warmth magnifies every joy it touches",
    "What we wear can be an expression of inner truth",
    "Achievement means most in the context of who you were",
    "Light transforms ordinary spaces into something sacred",
    "Courage grows when someone believes in you enough to listen",
    "Vastness above us reminds us of the vastness within",
    "Art in public spaces is a gift to every passerby",
    "Steady breath gives shape to what fire alone cannot",
    "Small beauties multiply when morning light finds them",
    "Play is the body's way of expressing pure happiness",
    "Atmosphere is created by those who care about gathering",
    "One good story can be worth more than a thousand facts",
    "Practice is a private promise to your future self",
    "Collective joy moves through a crowd like a wave",
    "Clarity follows turbulence for those who are patient",
    "Voices blending together create something no soloist can",
    "The best teachers make understanding feel like discovery",
    "Laughter on the water is the sound of time well spent",
    "Music passes between people like a living thing",
    "Confidence is adorable when it is still learning itself",
    "Written words carry feelings that spoken ones cannot",
    "Grace under pressure is its own kind of genius",
    "Creative flow is what happens when ego steps aside",
    "Reaching the peak is less about the view and more about the climb",
    "After the storm comes beauty that could not exist without it",
    "Hope is renewed every time the light returns",
    "A single branch can hold a whole community of voices",
    "Your voice matters most when it surprises even you",
    "Some truths can only be expressed on paper, never aloud",
  ],
  Virgo: [
    "Seeing the best in someone helps them see it too",
    "Steadiness in service is its own kind of heroism",
    "Real care often happens when no one is watching",
    "Collaboration erases differences faster than conversation",
    "Calm attention transforms work into meditation",
    "Restoration is an act of love for what already exists",
    "Shared breath creates a bond that words cannot explain",
    "Mastery begins with the willingness to practice the basics",
    "Precision is how the inner vision meets the outer world",
    "Discernment means pausing long enough to see clearly",
    "Letting go is sometimes the greatest gift a parent gives",
    "Depth arrives only after the surface talk is set aside",
    "Expertise is built from thousands of hours of paying attention",
    "Knowing where you come from helps you choose where to go",
    "Invisible work often holds the most visible things together",
    "Wonder is available to anyone willing to look closely",
    "Quiet power does not need to announce itself",
    "The right recommendation at the right time changes a life",
    "Healthy competition brings out the best in everyone",
    "Shared journeys reveal people more honestly than shared words",
    "Teamwork turns individual limits into collective strength",
    "Generosity of spirit makes even small places feel grand",
    "Gentleness is a form of strength that animals recognize",
    "Attention to small things is a spiritual practice",
    "Honor is best expressed through quiet remembrance",
    "Service given with thought outlasts service given from obligation",
    "Cooking together is an act of trust and coordination",
    "True leaders serve alongside the people they guide",
    "Following a thread of curiosity is how breakthroughs happen",
    "Focus is the craftsperson's most essential tool",
  ],
  Libra: [
    "Beauty lands where art and nature meet without trying",
    "Hard-earned lessons become the most generous gifts",
    "Every ending carries the seed of a cleaner beginning",
    "Warmth shared under open sky dissolves loneliness",
    "One shift in perspective can redesign an entire life",
    "Imagination builds what reality has not yet caught up to",
    "Kindness in small gestures holds communities together",
    "Warmth lingers in places even after people leave them",
    "Great art stops you in your tracks and rearranges you inside",
    "Skill and calm are the truest companions in a crisis",
    "Wise questions open more doors than clever answers",
    "Emerging from difficulty makes the light almost unbearable",
    "Playfulness is a radical form of freedom",
    "Strategic rest is not avoidance but wisdom",
    "New perspectives come from climbing to unexpected places",
    "Rebuilding is an act of faith in what comes next",
    "There is peace in watching the world move without needing to join it",
    "Respectful disagreement is a sign of a healthy bond",
    "Transformation can turn neglect into something worth seeing",
    "Finding common ground is the foundation of every truce",
    "Shared wonder is the simplest form of connection",
    "Small acts of care cross every boundary that divides us",
    "The call to begin again comes from nature's own voice",
    "Hidden gifts emerge when we try something unfamiliar",
    "Impermanence is not loss but an invitation to presence",
    "Opposites coexist more easily than we expect",
    "Lightness of spirit carries ideas farther than force",
    "Help appears most often when it is least expected",
    "Legacy lives in the practical things we pass on",
    "Wisdom is the patience to watch before speaking",
  ],
  Scorpio: [
    "Depth is only accessible to those willing to leave the surface",
    "What breaks open releases an essence stronger than the container",
    "Community is strongest when tested by difficulty",
    "A single flame held with intention changes the atmosphere",
    "Resilience is built by standing firm against what comes",
    "Following inner truth often means walking away from security",
    "The unknown holds treasures that the known cannot imagine",
    "Stillness is the mirror in which the deepest truths appear",
    "Precision under pressure saves what nothing else can",
    "Real bonds survive distance, time, and silence",
    "Being saved requires both the rescuer's courage and your trust",
    "What is hidden at a gathering matters more than what is shown",
    "Obsession in service of discovery is its own reward",
    "Connection finds a way even through the most unlikely channels",
    "Building and releasing teaches the nature of all things",
    "Warmth dissolves defenses more effectively than force",
    "Behind every hidden truth is a room filled with light",
    "The most beautiful displays come just before letting go",
    "Accidental honesty often hits closer than intended words",
    "Naming the unspoken frees everyone in the room",
    "Integrity sometimes costs everything and is still worth it",
    "Patience and presence are the hunter's truest skills",
    "Total dissolution is required before total transformation",
    "Words that change people echo long after the speaker leaves",
    "Seeing beneath the surface changes what action you take",
    "Adaptability is the survival skill that matters most",
    "Joy can reclaim any space, no matter how gray",
    "Quiet intensity commands more respect than volume ever can",
    "Truth spoken with love is the most powerful force there is",
    "Playfulness is how we rehearse for the unknown",
  ],
  Sagittarius: [
    "Shared memories become more valuable with every passing year",
    "Vastness humbles us and wakes us up at the same time",
    "Strategy trains the mind as much as the move itself",
    "Encouragement at the right moment shapes an entire life",
    "Wisdom is knowing when to watch and when to act",
    "Invented games teach us more about each other than formal ones",
    "Love leaves clues for those who know where to look",
    "The most valuable transformations happen out of sight",
    "Carrying someone who trusts you is a sacred responsibility",
    "Readiness meets opportunity when both finally align",
    "A steady light in darkness is worth more than a bonfire in daylight",
    "Symbols become powerful when they catch the right wind",
    "The past has things to say if we are willing to listen",
    "Standing before history connects us to something larger",
    "Instinct knows the season before the calendar does",
    "Following what feeds you is a form of natural wisdom",
    "Collective hope is strongest at the edge of a new day",
    "Imagination thrives in cozy, self-made spaces",
    "Protecting what is vulnerable is a form of strength",
    "Preparing together builds bonds that last through hardship",
    "Playfulness is how wisdom first enters the body",
    "Simplicity and integrity often share the same table",
    "Arrival is the beginning, not the end, of the real journey",
    "Ordinary beauty rewards those who pause to notice it",
    "Ambition starts small and that is perfectly fine",
    "Lighting the way for others is the highest form of courage",
    "The artist's job is to remove everything that is not the truth",
    "What endures was built by people who cared about the future",
    "Responsibility and rhythm can coexist with pleasure",
    "A blessing is most powerful when it comes from lived experience",
  ],
  Capricorn: [
    "True authority grows from character, not from title",
    "Imperfection does not diminish what still shines through",
    "Independence begins the moment you decide it does",
    "Great journeys require careful preparation and shared effort",
    "Collective will conquers obstacles individual effort cannot",
    "Every step forward changes what the next step looks like",
    "The moment before speaking holds more power than the speech itself",
    "Happiness flows naturally when life aligns with its setting",
    "Music has the power to honor what words cannot reach",
    "Trust is built slowly and rewarded in surprising ways",
    "Patient cultivation turns raw land into lasting abundance",
    "Revealing hidden truths serves the greater understanding",
    "Contemplation is the foundation beneath all lasting action",
    "What is built with integrity outlasts everything around it",
    "Healing happens faster in the presence of creativity and play",
    "The body must be ready before the moment of truth arrives",
    "Sometimes the bravest act is choosing yourself",
    "Endurance and vision together create something that lasts",
    "Responsibility taken freely is a sign of maturity",
    "Voices in harmony create a power greater than any solo",
    "Seamless teamwork is the result of trust built over time",
    "Graciousness in defeat reveals more character than winning",
    "Recognition means most when it comes from those who understand",
    "Simplicity chosen freely is the ultimate luxury",
    "The world's beauty is best appreciated through craftsmanship",
    "Nature's spectacles remind us that magic requires no effort",
    "Devotion wears grooves into stone that become paths for others",
    "Careful stewardship protects what is fragile and valuable",
    "Intuition reads the patterns that logic overlooks",
    "The most important decisions are often made outside public view",
  ],
  Aquarius: [
    "Shared spaces grow community from the ground up",
    "Disruption reminds us how much we share in common",
    "Choosing your own path requires tolerating misunderstanding",
    "A single idea, shared freely, can reshape the world",
    "The past speaks through those who carry its lessons forward",
    "Art communicates what language alone cannot express",
    "Innocence asks the questions that expertise has forgotten",
    "Unity is most powerful when it celebrates difference",
    "Symbols become movements when they speak to what people feel",
    "Authenticity requires the courage to be imperfect in public",
    "Breakthroughs come to those who make space for silence",
    "Shared spaces hold more connection than we usually notice",
    "Sensitivity to change is a gift, not a weakness",
    "Growth often requires moving through the dark to reach light",
    "Love is the simplest rebellion against a complicated world",
    "Vision requires long hours alone with your own ideas",
    "Loyalty is its own language, understood without words",
    "Transparency, even when painful, is the basis of trust",
    "Collective action achieves what individual effort cannot",
    "The desire for peace is humanity's most enduring instinct",
    "Moving forward after loss is the bravest kind of walking",
    "Imagination needs warmth and safety to flourish",
    "Playfulness and power are not opposites but partners",
    "Teaching from experience creates credibility no textbook can",
    "Imperfection does not prevent beauty from being whole",
    "Precision and care turn good enough into something great",
    "The wild and the domestic can coexist beautifully",
    "Preparation is a form of love for your future self",
    "Transformation is complete only when the new form takes flight",
    "Human connection transcends every difference we can name",
  ],
  Pisces: [
    "Abundance is most beautiful when it is gathered and shared",
    "Self-preservation is a quiet and necessary intelligence",
    "Everything that washes ashore carries a story worth hearing",
    "Connection between worlds is always a two-way flow",
    "Small acts of community care ripple outward endlessly",
    "Moving together in rhythm creates a joy beyond words",
    "Guidance shines brightest in the moments we feel most lost",
    "Letting go is how seeds travel to where they need to be",
    "Timing and effort must meet for the wave to carry you",
    "Above the clouds, everything looks peaceful and possible",
    "The focused path upward rewards those who keep climbing",
    "Confidence comes from knowing you have done the inner work",
    "Everyday objects become sacred when seen through time",
    "Elegance is the art of making less feel like more",
    "The hardest challenges demand the most from our preparation",
    "Inspiration arrives when striving gives way to stillness",
    "Celebration renews the spirit of an entire community",
    "A great story holds people still and lets them feel everything",
    "Mutual respect is the highest form of learning together",
    "Setting a table with care is a prayer for togetherness",
    "Whispered secrets are how trust is built between the small and the wise",
    "New ideas change the world by first changing the conversation",
    "Stillness opens a door that noise keeps firmly shut",
    "Island communities know that survival depends on one another",
    "Remembering what unites us dissolves what divides us",
    "Paying attention to the sky connects us to something larger",
    "Harvest time rewards every risk taken in the planting season",
    "The earth gives back more than we put in when conditions are right",
    "Breaking something into parts reveals the wholeness it came from",
    "We become what we admire if we admire it long enough",
  ],
};

/**
 * Get the Sabian symbol for the Sun's current zodiacal degree.
 * @param sunLongitude - ecliptic longitude of the Sun (0-360)
 */
export function getSabianSymbol(sunLongitude: number): SabianSymbol {
  // Normalize to 0-360
  const lon = ((sunLongitude % 360) + 360) % 360;

  // Determine sign index (0=Aries, 1=Taurus, etc.)
  const signIndex = Math.floor(lon / 30);
  const signs = ["Aries", "Taurus", "Gemini", "Cancer", "Leo", "Virgo",
    "Libra", "Scorpio", "Sagittarius", "Capricorn", "Aquarius", "Pisces"];
  const sign = signs[signIndex];

  // Sabian degree is ceiling of the degree within sign (1-30)
  // e.g., 0.5° Aries = 1° Aries Sabian, 29.1° = 30° Aries
  const degreeInSign = lon - (signIndex * 30);
  const sabianDegree = Math.ceil(degreeInSign) || 1; // minimum 1

  const symbolIndex = sabianDegree - 1;
  const symbol = SYMBOLS[sign]?.[symbolIndex] || "A mysterious symbol yet to be revealed";
  const keynote = KEYNOTES[sign]?.[symbolIndex] || "A moment of unique significance";

  return { degree: sabianDegree, sign, symbol, keynote };
}

/**
 * Get Sabian symbol for a specific date using approximate Sun longitude.
 * Uses the same calculation as celestialMechanics for consistency.
 */
export function getSabianSymbolForDate(date: Date): SabianSymbol {
  const sunLon = approximateSunLongitude(date);
  return getSabianSymbol(sunLon);
}

/**
 * Approximate sun ecliptic longitude for a given date.
 * Accurate to ~1° which is sufficient for Sabian symbols.
 */
function approximateSunLongitude(date: Date): number {
  const J2000 = Date.UTC(2000, 0, 1, 12, 0, 0);
  const daysSinceJ2000 = (date.getTime() - J2000) / 86400000;

  // Mean longitude of the Sun
  const L = (280.460 + 0.9856474 * daysSinceJ2000) % 360;
  // Mean anomaly
  const g = ((357.528 + 0.9856003 * daysSinceJ2000) % 360) * (Math.PI / 180);
  // Ecliptic longitude
  const lambda = L + 1.915 * Math.sin(g) + 0.020 * Math.sin(2 * g);

  return ((lambda % 360) + 360) % 360;
}
