/**
 * Store product image variants (generated by scripts/make-thumbs.mjs).
 *
 *   .card.webp   600px — the product tile in the store grid
 *   .thumb.webp  300px — small fans and gallery thumbnails
 *   (original)   900px — the product hero on the detail page
 *
 * Each falls back to the full art if a variant was never generated, so adding
 * a deck to the catalog can never leave a hole where a product photo should be.
 */

export function storeCard(src: string): string {
  return src.replace(/\.webp$/i, ".card.webp");
}

/** onError: drop back to the full-size art, once, if a variant is missing. */
export function onStoreImageError(e: React.SyntheticEvent<HTMLImageElement>): void {
  const img = e.currentTarget;
  const fixed = img.src.replace(".card.webp", ".webp").replace(".thumb.webp", ".webp");
  if (fixed !== img.src) img.src = fixed;
}
