/**
 * Mapped Vibe Library
 *
 * All 293 phrases in this file are Mapped originals.
 * No copyrighted material is included.
 *
 * Breakdown: 180 paired phrases + 120 standalone phrases = 300 total.
 */

export type VibeType = "paired" | "standalone";
export type VoiceRegister = "core" | "text_fragment" | "literary" | "pop";
export type TrendRisk = "low" | "medium" | "high";

export interface VibePhrase {
  id: string;
  phrase: string;
  type: VibeType;
  planetaryTags: string[];
  elementTags: string[];
  functionTags: string[];
  voiceRegister: VoiceRegister;
  trendRisk: TrendRisk;
  audienceGender?: string[];
  audienceLifeStage?: string[];
}

export const VIBE_LIBRARY: VibePhrase[] = [
  // ============================================================
  // PAIRED PHRASES (180 total)
  // ============================================================

  // --- Saturnian (S01-S15) ---
  {
    id: "S01",
    phrase: "More 9pm bedtimes, less doomscrolling",
    type: "paired",
    planetaryTags: ["saturnian"],
    elementTags: ["earth"],
    functionTags: ["grounding", "discipline"],
    voiceRegister: "core",
    trendRisk: "low",
  },
  {
    id: "S02",
    phrase: "More finishing what you started, less buying a new project",
    type: "paired",
    planetaryTags: ["saturnian"],
    elementTags: ["earth"],
    functionTags: ["grounding", "discipline"],
    voiceRegister: "core",
    trendRisk: "low",
  },
  {
    id: "S03",
    phrase: "More saying no without the explainer, less the polite essay",
    type: "paired",
    planetaryTags: ["saturnian"],
    elementTags: ["earth"],
    functionTags: ["grounding", "discipline"],
    voiceRegister: "core",
    trendRisk: "low",
  },
  {
    id: "S04",
    phrase: "More therapy, less your friends as your therapist",
    type: "paired",
    planetaryTags: ["saturnian"],
    elementTags: ["earth"],
    functionTags: ["grounding", "discipline"],
    voiceRegister: "core",
    trendRisk: "low",
  },
  {
    id: "S05",
    phrase: "More boring routines, less moving across the country",
    type: "paired",
    planetaryTags: ["saturnian"],
    elementTags: ["earth"],
    functionTags: ["grounding", "discipline"],
    voiceRegister: "core",
    trendRisk: "low",
  },
  {
    id: "S06",
    phrase: "More leaving the group chat, less muting it for the third time",
    type: "paired",
    planetaryTags: ["saturnian"],
    elementTags: ["earth"],
    functionTags: ["grounding", "discipline"],
    voiceRegister: "core",
    trendRisk: "low",
  },
  {
    id: "S07",
    phrase: "More writing the email and waiting til morning, less hitting send angry",
    type: "paired",
    planetaryTags: ["saturnian"],
    elementTags: ["earth"],
    functionTags: ["grounding", "discipline"],
    voiceRegister: "core",
    trendRisk: "low",
  },
  {
    id: "S08",
    phrase: "More paying the bill today, less the reminder you keep dismissing",
    type: "paired",
    planetaryTags: ["saturnian"],
    elementTags: ["earth"],
    functionTags: ["grounding", "discipline"],
    voiceRegister: "core",
    trendRisk: "low",
  },
  {
    id: "S09",
    phrase: "More one project at a time, less seven open browser tabs",
    type: "paired",
    planetaryTags: ["saturnian"],
    elementTags: ["earth"],
    functionTags: ["grounding", "discipline"],
    voiceRegister: "core",
    trendRisk: "low",
  },
  {
    id: "S10",
    phrase: "More going to bed mad, less sending the text",
    type: "paired",
    planetaryTags: ["saturnian"],
    elementTags: ["earth"],
    functionTags: ["grounding", "discipline"],
    voiceRegister: "core",
    trendRisk: "low",
  },
  {
    id: "S11",
    phrase: "More the savings account you don't touch, less the manifestation board",
    type: "paired",
    planetaryTags: ["saturnian"],
    elementTags: ["earth"],
    functionTags: ["grounding", "discipline"],
    voiceRegister: "core",
    trendRisk: "low",
  },
  {
    id: "S12",
    phrase: "More the schedule, less the spreadsheet about the schedule",
    type: "paired",
    planetaryTags: ["saturnian"],
    elementTags: ["earth"],
    functionTags: ["grounding", "discipline"],
    voiceRegister: "core",
    trendRisk: "low",
  },
  {
    id: "S13",
    phrase: "More the early flight, less the anxious morning",
    type: "paired",
    planetaryTags: ["saturnian"],
    elementTags: ["earth"],
    functionTags: ["grounding", "discipline"],
    voiceRegister: "core",
    trendRisk: "low",
  },
  {
    id: "S14",
    phrase: "More the gym at 6am, less the elaborate plan to start Monday",
    type: "paired",
    planetaryTags: ["saturnian"],
    elementTags: ["earth"],
    functionTags: ["grounding", "discipline"],
    voiceRegister: "core",
    trendRisk: "low",
  },
  {
    id: "S15",
    phrase: "More the same coffee order, less the hour-long cafe pick",
    type: "paired",
    planetaryTags: ["saturnian"],
    elementTags: ["earth"],
    functionTags: ["grounding", "discipline"],
    voiceRegister: "core",
    trendRisk: "low",
  },

  // --- Venusian (V01-V15) ---
  {
    id: "V01",
    phrase: "More long baths, less checking Slack",
    type: "paired",
    planetaryTags: ["venusian"],
    elementTags: ["water", "earth"],
    functionTags: ["calming", "pleasure"],
    voiceRegister: "core",
    trendRisk: "low",
  },
  {
    id: "V02",
    phrase: "More reading smut, less working overtime",
    type: "paired",
    planetaryTags: ["venusian"],
    elementTags: ["water", "earth"],
    functionTags: ["calming", "pleasure"],
    voiceRegister: "core",
    trendRisk: "low",
  },
  {
    id: "V03",
    phrase: "More one album all the way through, less the algorithm",
    type: "paired",
    planetaryTags: ["venusian"],
    elementTags: ["water", "earth"],
    functionTags: ["calming", "pleasure"],
    voiceRegister: "core",
    trendRisk: "low",
  },
  {
    id: "V04",
    phrase: "More flowers on the table, less productivity podcasts",
    type: "paired",
    planetaryTags: ["venusian"],
    elementTags: ["water", "earth"],
    functionTags: ["calming", "pleasure"],
    voiceRegister: "core",
    trendRisk: "low",
  },
  {
    id: "V05",
    phrase: "More slow Sundays, less optimizing the weekend",
    type: "paired",
    planetaryTags: ["venusian"],
    elementTags: ["water", "earth"],
    functionTags: ["calming", "pleasure"],
    voiceRegister: "core",
    trendRisk: "low",
  },
  {
    id: "V06",
    phrase: "More calling someone you love, less liking their post",
    type: "paired",
    planetaryTags: ["venusian"],
    elementTags: ["water", "earth"],
    functionTags: ["calming", "pleasure"],
    voiceRegister: "core",
    trendRisk: "low",
  },
  {
    id: "V07",
    phrase: "More the good lotion, less the fifteen abandoned skincare bottles",
    type: "paired",
    planetaryTags: ["venusian"],
    elementTags: ["water", "earth"],
    functionTags: ["calming", "pleasure"],
    voiceRegister: "core",
    trendRisk: "low",
  },
  {
    id: "V08",
    phrase: "More wearing the nice thing, less saving it for never",
    type: "paired",
    planetaryTags: ["venusian"],
    elementTags: ["water", "earth"],
    functionTags: ["calming", "pleasure"],
    voiceRegister: "core",
    trendRisk: "low",
  },
  {
    id: "V09",
    phrase: "More sitting in the sun, less the to-do list",
    type: "paired",
    planetaryTags: ["venusian"],
    elementTags: ["water", "earth"],
    functionTags: ["calming", "pleasure"],
    voiceRegister: "core",
    trendRisk: "low",
  },
  {
    id: "V10",
    phrase: "More cooking just for yourself, less standing at the fridge",
    type: "paired",
    planetaryTags: ["venusian"],
    elementTags: ["water", "earth"],
    functionTags: ["calming", "pleasure"],
    voiceRegister: "core",
    trendRisk: "low",
  },
  {
    id: "V11",
    phrase: "More the dress, less the gym short",
    type: "paired",
    planetaryTags: ["venusian"],
    elementTags: ["water", "earth"],
    functionTags: ["calming", "pleasure"],
    voiceRegister: "core",
    trendRisk: "low",
  },
  {
    id: "V12",
    phrase: "More the slow lunch, less the desk salad",
    type: "paired",
    planetaryTags: ["venusian"],
    elementTags: ["water", "earth"],
    functionTags: ["calming", "pleasure"],
    voiceRegister: "core",
    trendRisk: "low",
  },
  {
    id: "V13",
    phrase: "More the glass of wine alone, less the group dinner you didn't want",
    type: "paired",
    planetaryTags: ["venusian"],
    elementTags: ["water", "earth"],
    functionTags: ["calming", "pleasure"],
    voiceRegister: "core",
    trendRisk: "low",
  },
  {
    id: "V14",
    phrase: "More the perfume on a Tuesday, less waiting for an occasion",
    type: "paired",
    planetaryTags: ["venusian"],
    elementTags: ["water", "earth"],
    functionTags: ["calming", "pleasure"],
    voiceRegister: "core",
    trendRisk: "low",
  },
  {
    id: "V15",
    phrase: "More the silk pillowcase, less the optimized morning routine",
    type: "paired",
    planetaryTags: ["venusian"],
    elementTags: ["water", "earth"],
    functionTags: ["calming", "pleasure"],
    voiceRegister: "core",
    trendRisk: "low",
  },

  // --- Martian (M01-M15) ---
  {
    id: "M01",
    phrase: "More lifting heavy things, less people-pleasing",
    type: "paired",
    planetaryTags: ["martian"],
    elementTags: ["fire"],
    functionTags: ["energizing", "releasing"],
    voiceRegister: "core",
    trendRisk: "low",
  },
  {
    id: "M02",
    phrase: "More leaving the situationship, less the long voice memo",
    type: "paired",
    planetaryTags: ["martian"],
    elementTags: ["fire"],
    functionTags: ["energizing", "releasing"],
    voiceRegister: "core",
    trendRisk: "low",
  },
  {
    id: "M03",
    phrase: "More walking fast, less spiraling in the Whole Foods parking lot",
    type: "paired",
    planetaryTags: ["martian"],
    elementTags: ["fire"],
    functionTags: ["energizing", "releasing"],
    voiceRegister: "core",
    trendRisk: "low",
  },
  {
    id: "M04",
    phrase: "More saying the hard thing, less rehearsing it for a week",
    type: "paired",
    planetaryTags: ["martian"],
    elementTags: ["fire"],
    functionTags: ["energizing", "releasing"],
    voiceRegister: "core",
    trendRisk: "low",
  },
  {
    id: "M05",
    phrase: "More cold water on your face, less crying in the bathroom at work",
    type: "paired",
    planetaryTags: ["martian"],
    elementTags: ["fire"],
    functionTags: ["energizing", "releasing"],
    voiceRegister: "core",
    trendRisk: "low",
  },
  {
    id: "M06",
    phrase: "More burning the list, less reading it again",
    type: "paired",
    planetaryTags: ["martian"],
    elementTags: ["fire"],
    functionTags: ["energizing", "releasing"],
    voiceRegister: "core",
    trendRisk: "low",
  },
  {
    id: "M07",
    phrase: "More throwing it away, less moving it to a different drawer",
    type: "paired",
    planetaryTags: ["martian"],
    elementTags: ["fire"],
    functionTags: ["energizing", "releasing"],
    voiceRegister: "core",
    trendRisk: "low",
  },
  {
    id: "M08",
    phrase: "More going outside in the cold, less the second nap",
    type: "paired",
    planetaryTags: ["martian"],
    elementTags: ["fire"],
    functionTags: ["energizing", "releasing"],
    voiceRegister: "core",
    trendRisk: "low",
  },
  {
    id: "M09",
    phrase: "More the short workout, less the elaborate plan you won't do",
    type: "paired",
    planetaryTags: ["martian"],
    elementTags: ["fire"],
    functionTags: ["energizing", "releasing"],
    voiceRegister: "core",
    trendRisk: "low",
  },
  {
    id: "M10",
    phrase: "More the no, less the maybe-next-time",
    type: "paired",
    planetaryTags: ["martian"],
    elementTags: ["fire"],
    functionTags: ["energizing", "releasing"],
    voiceRegister: "core",
    trendRisk: "low",
  },
  {
    id: "M11",
    phrase: "More the actual fight, less the passive-aggressive Instagram story",
    type: "paired",
    planetaryTags: ["martian"],
    elementTags: ["fire"],
    functionTags: ["energizing", "releasing"],
    voiceRegister: "core",
    trendRisk: "low",
  },
  {
    id: "M12",
    phrase: "More the leaving early, less the wine you didn't want",
    type: "paired",
    planetaryTags: ["martian"],
    elementTags: ["fire"],
    functionTags: ["energizing", "releasing"],
    voiceRegister: "core",
    trendRisk: "low",
  },
  {
    id: "M13",
    phrase: "More the unfollowing, less the resentful scroll",
    type: "paired",
    planetaryTags: ["martian"],
    elementTags: ["fire"],
    functionTags: ["energizing", "releasing"],
    voiceRegister: "core",
    trendRisk: "low",
  },
  {
    id: "M14",
    phrase: "More the workout class where you can't think, less the meditation app",
    type: "paired",
    planetaryTags: ["martian"],
    elementTags: ["fire"],
    functionTags: ["energizing", "releasing"],
    voiceRegister: "core",
    trendRisk: "low",
  },
  {
    id: "M15",
    phrase: "More the haircut, less the year of growing it out",
    type: "paired",
    planetaryTags: ["martian"],
    elementTags: ["fire"],
    functionTags: ["energizing", "releasing"],
    voiceRegister: "core",
    trendRisk: "low",
  },

  // --- Lunar (L01-L15) ---
  {
    id: "L01",
    phrase: "More crying when you need to, less holding it together",
    type: "paired",
    planetaryTags: ["lunar"],
    elementTags: ["water"],
    functionTags: ["calming", "grounding"],
    voiceRegister: "core",
    trendRisk: "low",
  },
  {
    id: "L02",
    phrase: "More calling your mom, less the long story to a stranger",
    type: "paired",
    planetaryTags: ["lunar"],
    elementTags: ["water"],
    functionTags: ["calming", "grounding"],
    voiceRegister: "core",
    trendRisk: "low",
  },
  {
    id: "L03",
    phrase: "More water, less coffee at 3pm",
    type: "paired",
    planetaryTags: ["lunar"],
    elementTags: ["water"],
    functionTags: ["calming", "grounding"],
    voiceRegister: "core",
    trendRisk: "low",
  },
  {
    id: "L04",
    phrase: "More naming the feeling, less performing the better one",
    type: "paired",
    planetaryTags: ["lunar"],
    elementTags: ["water"],
    functionTags: ["calming", "grounding"],
    voiceRegister: "core",
    trendRisk: "low",
  },
  {
    id: "L05",
    phrase: "More soft food, less skipping dinner",
    type: "paired",
    planetaryTags: ["lunar"],
    elementTags: ["water"],
    functionTags: ["calming", "grounding"],
    voiceRegister: "core",
    trendRisk: "low",
  },
  {
    id: "L06",
    phrase: "More going to bed early, less the second wind at midnight",
    type: "paired",
    planetaryTags: ["lunar"],
    elementTags: ["water"],
    functionTags: ["calming", "grounding"],
    voiceRegister: "core",
    trendRisk: "low",
  },
  {
    id: "L07",
    phrase: "More journaling badly, less waiting for clarity",
    type: "paired",
    planetaryTags: ["lunar"],
    elementTags: ["water"],
    functionTags: ["calming", "grounding"],
    voiceRegister: "core",
    trendRisk: "low",
  },
  {
    id: "L08",
    phrase: "More leaving a window open, less the white noise machine",
    type: "paired",
    planetaryTags: ["lunar"],
    elementTags: ["water"],
    functionTags: ["calming", "grounding"],
    voiceRegister: "core",
    trendRisk: "low",
  },
  {
    id: "L09",
    phrase: "More asking for the hug, less the joke about needing one",
    type: "paired",
    planetaryTags: ["lunar"],
    elementTags: ["water"],
    functionTags: ["calming", "grounding"],
    voiceRegister: "core",
    trendRisk: "low",
  },
  {
    id: "L10",
    phrase: "More being honest with yourself, less group-chat polling",
    type: "paired",
    planetaryTags: ["lunar"],
    elementTags: ["water"],
    functionTags: ["calming", "grounding"],
    voiceRegister: "core",
    trendRisk: "low",
  },
  {
    id: "L11",
    phrase: "More the bath at 3pm, less the productive afternoon",
    type: "paired",
    planetaryTags: ["lunar"],
    elementTags: ["water"],
    functionTags: ["calming", "grounding"],
    voiceRegister: "core",
    trendRisk: "low",
  },
  {
    id: "L12",
    phrase: "More the cry in the car, less the cry at dinner",
    type: "paired",
    planetaryTags: ["lunar"],
    elementTags: ["water"],
    functionTags: ["calming", "grounding"],
    voiceRegister: "core",
    trendRisk: "low",
  },
  {
    id: "L13",
    phrase: "More the long shower, less the explanation",
    type: "paired",
    planetaryTags: ["lunar"],
    elementTags: ["water"],
    functionTags: ["calming", "grounding"],
    voiceRegister: "core",
    trendRisk: "low",
  },
  {
    id: "L14",
    phrase: "More the nap, less the diagnosis",
    type: "paired",
    planetaryTags: ["lunar"],
    elementTags: ["water"],
    functionTags: ["calming", "grounding"],
    voiceRegister: "core",
    trendRisk: "low",
  },
  {
    id: "L15",
    phrase: "More the soft sweater, less the explanation of why you're tired",
    type: "paired",
    planetaryTags: ["lunar"],
    elementTags: ["water"],
    functionTags: ["calming", "grounding"],
    voiceRegister: "core",
    trendRisk: "low",
  },

  // --- Mercurial (Me01-Me14) ---
  {
    id: "Me01",
    phrase: "More writing it down, less rehearsing the sentence",
    type: "paired",
    planetaryTags: ["mercurial"],
    elementTags: ["air"],
    functionTags: ["clarifying", "grounding"],
    voiceRegister: "core",
    trendRisk: "low",
  },
  {
    id: "Me02",
    phrase: "More finishing the email, less the seventh re-read",
    type: "paired",
    planetaryTags: ["mercurial"],
    elementTags: ["air"],
    functionTags: ["clarifying", "grounding"],
    voiceRegister: "core",
    trendRisk: "low",
  },
  {
    id: "Me03",
    phrase: "More leaving things unsaid, less explaining yourself",
    type: "paired",
    planetaryTags: ["mercurial"],
    elementTags: ["air"],
    functionTags: ["clarifying", "grounding"],
    voiceRegister: "core",
    trendRisk: "low",
  },
  {
    id: "Me04",
    phrase: "More short answers, less the disclaimer",
    type: "paired",
    planetaryTags: ["mercurial"],
    elementTags: ["air"],
    functionTags: ["clarifying", "grounding"],
    voiceRegister: "core",
    trendRisk: "low",
  },
  {
    id: "Me05",
    phrase: "More reading something hard, less six articles half-skimmed",
    type: "paired",
    planetaryTags: ["mercurial"],
    elementTags: ["air"],
    functionTags: ["clarifying", "grounding"],
    voiceRegister: "core",
    trendRisk: "low",
  },
  {
    id: "Me06",
    phrase: "More the actual conversation, less the imagined one",
    type: "paired",
    planetaryTags: ["mercurial"],
    elementTags: ["air"],
    functionTags: ["clarifying", "grounding"],
    voiceRegister: "core",
    trendRisk: "low",
  },
  {
    id: "Me07",
    phrase: "More small decisive choices, less the spreadsheet",
    type: "paired",
    planetaryTags: ["mercurial"],
    elementTags: ["air"],
    functionTags: ["clarifying", "grounding"],
    voiceRegister: "core",
    trendRisk: "low",
  },
  {
    id: "Me08",
    phrase: 'More closing the tab, less "I\'ll come back to it"',
    type: "paired",
    planetaryTags: ["mercurial"],
    elementTags: ["air"],
    functionTags: ["clarifying", "grounding"],
    voiceRegister: "core",
    trendRisk: "low",
  },
  {
    id: "Me09",
    phrase: "More writing the unsent letter, less drafting the text seventeen times",
    type: "paired",
    planetaryTags: ["mercurial"],
    elementTags: ["air"],
    functionTags: ["clarifying", "grounding"],
    voiceRegister: "core",
    trendRisk: "low",
  },
  {
    id: "Me10",
    phrase: "More one notebook, less the four apps",
    type: "paired",
    planetaryTags: ["mercurial"],
    elementTags: ["air"],
    functionTags: ["clarifying", "grounding"],
    voiceRegister: "core",
    trendRisk: "low",
  },
  {
    id: "Me11",
    phrase: "More the call instead of the text, less the group chat clarification",
    type: "paired",
    planetaryTags: ["mercurial"],
    elementTags: ["air"],
    functionTags: ["clarifying", "grounding"],
    voiceRegister: "core",
    trendRisk: "low",
  },
  {
    id: "Me12",
    phrase: "More the book you started, less buying the new one",
    type: "paired",
    planetaryTags: ["mercurial"],
    elementTags: ["air"],
    functionTags: ["clarifying", "grounding"],
    voiceRegister: "core",
    trendRisk: "low",
  },
  {
    id: "Me13",
    phrase: "More the question, less the speech",
    type: "paired",
    planetaryTags: ["mercurial"],
    elementTags: ["air"],
    functionTags: ["clarifying", "grounding"],
    voiceRegister: "core",
    trendRisk: "low",
  },
  {
    id: "Me14",
    phrase: 'More the receipt, less the "I\'ll Venmo you later"',
    type: "paired",
    planetaryTags: ["mercurial"],
    elementTags: ["air"],
    functionTags: ["clarifying", "grounding"],
    voiceRegister: "core",
    trendRisk: "low",
  },

  // --- Jupiterian (J01-J14) ---
  {
    id: "J01",
    phrase: "More cooking for someone, less the dinner you cancelled",
    type: "paired",
    planetaryTags: ["jupiterian"],
    elementTags: ["fire"],
    functionTags: ["energizing", "expanding"],
    voiceRegister: "core",
    trendRisk: "low",
  },
  {
    id: "J02",
    phrase: "More going to the thing, less drafting the polite excuse",
    type: "paired",
    planetaryTags: ["jupiterian"],
    elementTags: ["fire"],
    functionTags: ["energizing", "expanding"],
    voiceRegister: "core",
    trendRisk: "low",
  },
  {
    id: "J03",
    phrase: "More finishing the book, less buying the new one",
    type: "paired",
    planetaryTags: ["jupiterian"],
    elementTags: ["fire"],
    functionTags: ["energizing", "expanding"],
    voiceRegister: "core",
    trendRisk: "low",
  },
  {
    id: "J04",
    phrase: "More the small trip, less waiting for the big one",
    type: "paired",
    planetaryTags: ["jupiterian"],
    elementTags: ["fire"],
    functionTags: ["energizing", "expanding"],
    voiceRegister: "core",
    trendRisk: "low",
  },
  {
    id: "J05",
    phrase: "More tipping well, less calculating",
    type: "paired",
    planetaryTags: ["jupiterian"],
    elementTags: ["fire"],
    functionTags: ["energizing", "expanding"],
    voiceRegister: "core",
    trendRisk: "low",
  },
  {
    id: "J06",
    phrase: "More telling someone you love them, less the inside-joke version",
    type: "paired",
    planetaryTags: ["jupiterian"],
    elementTags: ["fire"],
    functionTags: ["energizing", "expanding"],
    voiceRegister: "core",
    trendRisk: "low",
  },
  {
    id: "J07",
    phrase: "More taking the long way home, less the same route",
    type: "paired",
    planetaryTags: ["jupiterian"],
    elementTags: ["fire"],
    functionTags: ["energizing", "expanding"],
    voiceRegister: "core",
    trendRisk: "low",
  },
  {
    id: "J08",
    phrase: "More writing the recommendation, less the quick endorsement",
    type: "paired",
    planetaryTags: ["jupiterian"],
    elementTags: ["fire"],
    functionTags: ["energizing", "expanding"],
    voiceRegister: "core",
    trendRisk: "low",
  },
  {
    id: "J09",
    phrase: "More being early, less the apology",
    type: "paired",
    planetaryTags: ["jupiterian"],
    elementTags: ["fire"],
    functionTags: ["energizing", "expanding"],
    voiceRegister: "core",
    trendRisk: "low",
  },
  {
    id: "J10",
    phrase: "More the one good belief, less the seventeen contingency plans",
    type: "paired",
    planetaryTags: ["jupiterian"],
    elementTags: ["fire"],
    functionTags: ["energizing", "expanding"],
    voiceRegister: "core",
    trendRisk: "low",
  },
  {
    id: "J11",
    phrase: "More the friend's wedding three states away, less the polite gift",
    type: "paired",
    planetaryTags: ["jupiterian"],
    elementTags: ["fire"],
    functionTags: ["energizing", "expanding"],
    voiceRegister: "core",
    trendRisk: "low",
  },
  {
    id: "J12",
    phrase: "More the long phone call, less the catch-up text",
    type: "paired",
    planetaryTags: ["jupiterian"],
    elementTags: ["fire"],
    functionTags: ["energizing", "expanding"],
    voiceRegister: "core",
    trendRisk: "low",
  },
  {
    id: "J13",
    phrase: "More the book recommendation you actually act on, less the saved Substack",
    type: "paired",
    planetaryTags: ["jupiterian"],
    elementTags: ["fire"],
    functionTags: ["energizing", "expanding"],
    voiceRegister: "core",
    trendRisk: "low",
  },
  {
    id: "J14",
    phrase: "More cooking too much on purpose, less the perfect portion",
    type: "paired",
    planetaryTags: ["jupiterian"],
    elementTags: ["fire"],
    functionTags: ["energizing", "expanding"],
    voiceRegister: "core",
    trendRisk: "low",
  },

  // --- Plutonian (P01-P15) ---
  {
    id: "P01",
    phrase: "More therapy, less situationships",
    type: "paired",
    planetaryTags: ["plutonian"],
    elementTags: ["water"],
    functionTags: ["releasing", "transforming"],
    voiceRegister: "core",
    trendRisk: "low",
  },
  {
    id: "P02",
    phrase: "More the actual journal entry, less the cute one",
    type: "paired",
    planetaryTags: ["plutonian"],
    elementTags: ["water"],
    functionTags: ["releasing", "transforming"],
    voiceRegister: "core",
    trendRisk: "low",
  },
  {
    id: "P03",
    phrase: "More looking at the photo, less avoiding the album",
    type: "paired",
    planetaryTags: ["plutonian"],
    elementTags: ["water"],
    functionTags: ["releasing", "transforming"],
    voiceRegister: "core",
    trendRisk: "low",
  },
  {
    id: "P04",
    phrase: "More ending it, less the slow fade",
    type: "paired",
    planetaryTags: ["plutonian"],
    elementTags: ["water"],
    functionTags: ["releasing", "transforming"],
    voiceRegister: "core",
    trendRisk: "low",
  },
  {
    id: "P05",
    phrase: "More the truth you've been avoiding, less the version that protects everyone",
    type: "paired",
    planetaryTags: ["plutonian"],
    elementTags: ["water"],
    functionTags: ["releasing", "transforming"],
    voiceRegister: "core",
    trendRisk: "low",
  },
  {
    id: "P06",
    phrase: "More sitting with the rage, less making it palatable",
    type: "paired",
    planetaryTags: ["plutonian"],
    elementTags: ["water"],
    functionTags: ["releasing", "transforming"],
    voiceRegister: "core",
    trendRisk: "low",
  },
  {
    id: "P07",
    phrase: "More the hard conversation with yourself, less googling your symptoms",
    type: "paired",
    planetaryTags: ["plutonian"],
    elementTags: ["water"],
    functionTags: ["releasing", "transforming"],
    voiceRegister: "core",
    trendRisk: "low",
  },
  {
    id: "P08",
    phrase: "More burning what's already over, less moving it to storage",
    type: "paired",
    planetaryTags: ["plutonian"],
    elementTags: ["water"],
    functionTags: ["releasing", "transforming"],
    voiceRegister: "core",
    trendRisk: "low",
  },
  {
    id: "P09",
    phrase: "More naming the dynamic, less the running joke about it",
    type: "paired",
    planetaryTags: ["plutonian"],
    elementTags: ["water"],
    functionTags: ["releasing", "transforming"],
    voiceRegister: "core",
    trendRisk: "low",
  },
  {
    id: "P10",
    phrase: "More the pause before reacting, less the apology after",
    type: "paired",
    planetaryTags: ["plutonian"],
    elementTags: ["water"],
    functionTags: ["releasing", "transforming"],
    voiceRegister: "core",
    trendRisk: "low",
  },
  {
    id: "P11",
    phrase: "More the block, less the curiosity",
    type: "paired",
    planetaryTags: ["plutonian"],
    elementTags: ["water"],
    functionTags: ["releasing", "transforming"],
    voiceRegister: "core",
    trendRisk: "low",
  },
  {
    id: "P12",
    phrase: "More what you actually want, less the version your mother could approve",
    type: "paired",
    planetaryTags: ["plutonian"],
    elementTags: ["water"],
    functionTags: ["releasing", "transforming"],
    voiceRegister: "core",
    trendRisk: "low",
  },
  {
    id: "P13",
    phrase: "More the inheritance you're working through, less pretending you don't have one",
    type: "paired",
    planetaryTags: ["plutonian"],
    elementTags: ["water"],
    functionTags: ["releasing", "transforming"],
    voiceRegister: "core",
    trendRisk: "low",
  },
  {
    id: "P14",
    phrase: "More the rage at 3am, less the explanation at 9am",
    type: "paired",
    planetaryTags: ["plutonian"],
    elementTags: ["water"],
    functionTags: ["releasing", "transforming"],
    voiceRegister: "core",
    trendRisk: "low",
  },
  {
    id: "P15",
    phrase: "More the shadow, less the brand",
    type: "paired",
    planetaryTags: ["plutonian"],
    elementTags: ["water"],
    functionTags: ["releasing", "transforming"],
    voiceRegister: "core",
    trendRisk: "low",
  },

  // --- Neptunian (N01-N14) ---
  {
    id: "N01",
    phrase: "More naps, less making sense of it",
    type: "paired",
    planetaryTags: ["neptunian"],
    elementTags: ["water"],
    functionTags: ["calming", "surrendering"],
    voiceRegister: "core",
    trendRisk: "low",
  },
  {
    id: "N02",
    phrase: "More watching the same movie, less three new shows started",
    type: "paired",
    planetaryTags: ["neptunian"],
    elementTags: ["water"],
    functionTags: ["calming", "surrendering"],
    voiceRegister: "core",
    trendRisk: "low",
  },
  {
    id: "N03",
    phrase: "More floating, less doing",
    type: "paired",
    planetaryTags: ["neptunian"],
    elementTags: ["water"],
    functionTags: ["calming", "surrendering"],
    voiceRegister: "core",
    trendRisk: "low",
  },
  {
    id: "N04",
    phrase: "More the long shower, less the productivity podcast",
    type: "paired",
    planetaryTags: ["neptunian"],
    elementTags: ["water"],
    functionTags: ["calming", "surrendering"],
    voiceRegister: "core",
    trendRisk: "low",
  },
  {
    id: "N05",
    phrase: "More not knowing yet, less forcing the answer",
    type: "paired",
    planetaryTags: ["neptunian"],
    elementTags: ["water"],
    functionTags: ["calming", "surrendering"],
    voiceRegister: "core",
    trendRisk: "low",
  },
  {
    id: "N06",
    phrase: "More daydreaming on purpose, less scrolling on accident",
    type: "paired",
    planetaryTags: ["neptunian"],
    elementTags: ["water"],
    functionTags: ["calming", "surrendering"],
    voiceRegister: "core",
    trendRisk: "low",
  },
  {
    id: "N07",
    phrase: "More water on your skin, less in front of a screen",
    type: "paired",
    planetaryTags: ["neptunian"],
    elementTags: ["water"],
    functionTags: ["calming", "surrendering"],
    voiceRegister: "core",
    trendRisk: "low",
  },
  {
    id: "N08",
    phrase: "More sleeping in, less the alarm you don't need",
    type: "paired",
    planetaryTags: ["neptunian"],
    elementTags: ["water"],
    functionTags: ["calming", "surrendering"],
    voiceRegister: "core",
    trendRisk: "low",
  },
  {
    id: "N09",
    phrase: "More writing down the dream, less explaining it to yourself",
    type: "paired",
    planetaryTags: ["neptunian"],
    elementTags: ["water"],
    functionTags: ["calming", "surrendering"],
    voiceRegister: "core",
    trendRisk: "low",
  },
  {
    id: "N10",
    phrase: "More not having a take, less posting one anyway",
    type: "paired",
    planetaryTags: ["neptunian"],
    elementTags: ["water"],
    functionTags: ["calming", "surrendering"],
    voiceRegister: "core",
    trendRisk: "low",
  },
  {
    id: "N11",
    phrase: "More the bath with no plan, less the meditation timer",
    type: "paired",
    planetaryTags: ["neptunian"],
    elementTags: ["water"],
    functionTags: ["calming", "surrendering"],
    voiceRegister: "core",
    trendRisk: "low",
  },
  {
    id: "N12",
    phrase: "More the candle in the dark, less the productivity light",
    type: "paired",
    planetaryTags: ["neptunian"],
    elementTags: ["water"],
    functionTags: ["calming", "surrendering"],
    voiceRegister: "core",
    trendRisk: "low",
  },
  {
    id: "N13",
    phrase: "More the album from college, less the discover weekly",
    type: "paired",
    planetaryTags: ["neptunian"],
    elementTags: ["water"],
    functionTags: ["calming", "surrendering"],
    voiceRegister: "core",
    trendRisk: "low",
  },
  {
    id: "N14",
    phrase: "More forgetting on purpose, less remembering everything",
    type: "paired",
    planetaryTags: ["neptunian"],
    elementTags: ["water"],
    functionTags: ["calming", "surrendering"],
    voiceRegister: "core",
    trendRisk: "low",
  },

  // --- Uranian (U01-U15) ---
  {
    id: "U01",
    phrase: "More leaving early, less the tenth round of small talk",
    type: "paired",
    planetaryTags: ["uranian"],
    elementTags: ["air"],
    functionTags: ["energizing", "disrupting"],
    voiceRegister: "core",
    trendRisk: "low",
  },
  {
    id: "U02",
    phrase: "More the haircut, less the year of thinking about it",
    type: "paired",
    planetaryTags: ["uranian"],
    elementTags: ["air"],
    functionTags: ["energizing", "disrupting"],
    voiceRegister: "core",
    trendRisk: "low",
  },
  {
    id: "U03",
    phrase: "More deleting the app, less the screen time report",
    type: "paired",
    planetaryTags: ["uranian"],
    elementTags: ["air"],
    functionTags: ["energizing", "disrupting"],
    voiceRegister: "core",
    trendRisk: "low",
  },
  {
    id: "U04",
    phrase: "More the abrupt change, less the slow consideration",
    type: "paired",
    planetaryTags: ["uranian"],
    elementTags: ["air"],
    functionTags: ["energizing", "disrupting"],
    voiceRegister: "core",
    trendRisk: "low",
  },
  {
    id: "U05",
    phrase: "More taking the day off, less rescheduling rest",
    type: "paired",
    planetaryTags: ["uranian"],
    elementTags: ["air"],
    functionTags: ["energizing", "disrupting"],
    voiceRegister: "core",
    trendRisk: "low",
  },
  {
    id: "U06",
    phrase: "More the strange small experiment, less the five-year plan",
    type: "paired",
    planetaryTags: ["uranian"],
    elementTags: ["air"],
    functionTags: ["energizing", "disrupting"],
    voiceRegister: "core",
    trendRisk: "low",
  },
  {
    id: "U07",
    phrase: "More moving the furniture, less buying new furniture",
    type: "paired",
    planetaryTags: ["uranian"],
    elementTags: ["air"],
    functionTags: ["energizing", "disrupting"],
    voiceRegister: "core",
    trendRisk: "low",
  },
  {
    id: "U08",
    phrase: "More the unfollowed friend, less the resentful scroll",
    type: "paired",
    planetaryTags: ["uranian"],
    elementTags: ["air"],
    functionTags: ["energizing", "disrupting"],
    voiceRegister: "core",
    trendRisk: "low",
  },
  {
    id: "U09",
    phrase: "More breakfast for dinner, less the shopping list",
    type: "paired",
    planetaryTags: ["uranian"],
    elementTags: ["air"],
    functionTags: ["energizing", "disrupting"],
    voiceRegister: "core",
    trendRisk: "low",
  },
  {
    id: "U10",
    phrase: "More the unexpected detour, less Google Maps recalculating",
    type: "paired",
    planetaryTags: ["uranian"],
    elementTags: ["air"],
    functionTags: ["energizing", "disrupting"],
    voiceRegister: "core",
    trendRisk: "low",
  },
  {
    id: "U11",
    phrase: "More the email saying you've changed your mind, less the obligated yes",
    type: "paired",
    planetaryTags: ["uranian"],
    elementTags: ["air"],
    functionTags: ["energizing", "disrupting"],
    voiceRegister: "core",
    trendRisk: "low",
  },
  {
    id: "U12",
    phrase: "More the abrupt no, less the seven warning emails",
    type: "paired",
    planetaryTags: ["uranian"],
    elementTags: ["air"],
    functionTags: ["energizing", "disrupting"],
    voiceRegister: "core",
    trendRisk: "low",
  },
  {
    id: "U13",
    phrase: "More the new bar, less the same friends",
    type: "paired",
    planetaryTags: ["uranian"],
    elementTags: ["air"],
    functionTags: ["energizing", "disrupting"],
    voiceRegister: "core",
    trendRisk: "low",
  },
  {
    id: "U14",
    phrase: "More the strange book at the airport, less your saved articles",
    type: "paired",
    planetaryTags: ["uranian"],
    elementTags: ["air"],
    functionTags: ["energizing", "disrupting"],
    voiceRegister: "core",
    trendRisk: "low",
  },
  {
    id: "U15",
    phrase: "More leaving the party at 9pm, less the regret at 2am",
    type: "paired",
    planetaryTags: ["uranian"],
    elementTags: ["air"],
    functionTags: ["energizing", "disrupting"],
    voiceRegister: "core",
    trendRisk: "low",
  },

  // --- Solar (Su01-Su14) ---
  {
    id: "Su01",
    phrase: "More sun on your skin, less the windowless meeting",
    type: "paired",
    planetaryTags: ["solar"],
    elementTags: ["fire"],
    functionTags: ["energizing", "empowering"],
    voiceRegister: "core",
    trendRisk: "low",
  },
  {
    id: "Su02",
    phrase: "More speaking first, less waiting to be called on",
    type: "paired",
    planetaryTags: ["solar"],
    elementTags: ["fire"],
    functionTags: ["energizing", "empowering"],
    voiceRegister: "core",
    trendRisk: "low",
  },
  {
    id: "Su03",
    phrase: "More taking up the room, less apologizing for arriving",
    type: "paired",
    planetaryTags: ["solar"],
    elementTags: ["fire"],
    functionTags: ["energizing", "empowering"],
    voiceRegister: "core",
    trendRisk: "low",
  },
  {
    id: "Su04",
    phrase: "More the photo of yourself you actually like, less the one you'd post",
    type: "paired",
    planetaryTags: ["solar"],
    elementTags: ["fire"],
    functionTags: ["energizing", "empowering"],
    voiceRegister: "core",
    trendRisk: "low",
  },
  {
    id: "Su05",
    phrase: "More what you actually want, less polling everyone",
    type: "paired",
    planetaryTags: ["solar"],
    elementTags: ["fire"],
    functionTags: ["energizing", "empowering"],
    voiceRegister: "core",
    trendRisk: "low",
  },
  {
    id: "Su06",
    phrase: "More being seen on purpose, less hoping to be noticed",
    type: "paired",
    planetaryTags: ["solar"],
    elementTags: ["fire"],
    functionTags: ["energizing", "empowering"],
    voiceRegister: "core",
    trendRisk: "low",
  },
  {
    id: "Su07",
    phrase: "More wearing the color, less defaulting to black",
    type: "paired",
    planetaryTags: ["solar"],
    elementTags: ["fire"],
    functionTags: ["energizing", "empowering"],
    voiceRegister: "core",
    trendRisk: "low",
  },
  {
    id: "Su08",
    phrase: "More signing your full name, less initials",
    type: "paired",
    planetaryTags: ["solar"],
    elementTags: ["fire"],
    functionTags: ["energizing", "empowering"],
    voiceRegister: "core",
    trendRisk: "low",
  },
  {
    id: "Su09",
    phrase: "More the project that's actually yours, less the safe one",
    type: "paired",
    planetaryTags: ["solar"],
    elementTags: ["fire"],
    functionTags: ["energizing", "empowering"],
    voiceRegister: "core",
    trendRisk: "low",
  },
  {
    id: "Su10",
    phrase: "More applying for the job you're underqualified for, less the lateral move",
    type: "paired",
    planetaryTags: ["solar"],
    elementTags: ["fire"],
    functionTags: ["energizing", "empowering"],
    voiceRegister: "core",
    trendRisk: "low",
  },
  {
    id: "Su11",
    phrase: "More the front of the photo, less the back row",
    type: "paired",
    planetaryTags: ["solar"],
    elementTags: ["fire"],
    functionTags: ["energizing", "empowering"],
    voiceRegister: "core",
    trendRisk: "low",
  },
  {
    id: "Su12",
    phrase: "More posting the thing you actually made, less the curated grid",
    type: "paired",
    planetaryTags: ["solar"],
    elementTags: ["fire"],
    functionTags: ["energizing", "empowering"],
    voiceRegister: "core",
    trendRisk: "low",
  },
  {
    id: "Su13",
    phrase: "More the leadership role no one asked you to take, less the supportive one",
    type: "paired",
    planetaryTags: ["solar"],
    elementTags: ["fire"],
    functionTags: ["energizing", "empowering"],
    voiceRegister: "core",
    trendRisk: "low",
  },
  {
    id: "Su14",
    phrase: 'More taking credit, less "we"',
    type: "paired",
    planetaryTags: ["solar"],
    elementTags: ["fire"],
    functionTags: ["energizing", "empowering"],
    voiceRegister: "core",
    trendRisk: "low",
  },

  // --- Element-coded (E01-E12) ---
  {
    id: "E01",
    phrase: "More walking outside, less the gym app",
    type: "paired",
    planetaryTags: [],
    elementTags: ["earth"],
    functionTags: ["grounding"],
    voiceRegister: "core",
    trendRisk: "low",
  },
  {
    id: "E02",
    phrase: "More cooking dinner, less ordering it",
    type: "paired",
    planetaryTags: [],
    elementTags: ["earth"],
    functionTags: ["grounding"],
    voiceRegister: "core",
    trendRisk: "low",
  },
  {
    id: "E03",
    phrase: "More dirt under your nails, less the curated houseplant",
    type: "paired",
    planetaryTags: [],
    elementTags: ["earth"],
    functionTags: ["grounding"],
    voiceRegister: "core",
    trendRisk: "low",
  },
  {
    id: "E04",
    phrase: "More dancing alone, less the perfect playlist",
    type: "paired",
    planetaryTags: [],
    elementTags: ["fire"],
    functionTags: ["energizing"],
    voiceRegister: "core",
    trendRisk: "low",
  },
  {
    id: "E05",
    phrase: "More starting it badly, less perfecting the plan",
    type: "paired",
    planetaryTags: [],
    elementTags: ["fire"],
    functionTags: ["energizing"],
    voiceRegister: "core",
    trendRisk: "low",
  },
  {
    id: "E06",
    phrase: "More the candle, less the screen",
    type: "paired",
    planetaryTags: [],
    elementTags: ["fire"],
    functionTags: ["calming"],
    voiceRegister: "core",
    trendRisk: "low",
  },
  {
    id: "E07",
    phrase: "More the bath, less the scroll",
    type: "paired",
    planetaryTags: [],
    elementTags: ["water"],
    functionTags: ["calming"],
    voiceRegister: "core",
    trendRisk: "low",
  },
  {
    id: "E08",
    phrase: "More crying through it, less powering through",
    type: "paired",
    planetaryTags: [],
    elementTags: ["water"],
    functionTags: ["releasing"],
    voiceRegister: "core",
    trendRisk: "low",
  },
  {
    id: "E09",
    phrase: "More the slow tea, less the third coffee",
    type: "paired",
    planetaryTags: [],
    elementTags: ["water"],
    functionTags: ["calming"],
    voiceRegister: "core",
    trendRisk: "low",
  },
  {
    id: "E10",
    phrase: "More writing the letter, less drafting the text",
    type: "paired",
    planetaryTags: [],
    elementTags: ["air"],
    functionTags: ["clarifying"],
    voiceRegister: "core",
    trendRisk: "low",
  },
  {
    id: "E11",
    phrase: "More the long walk and the conversation, less the call",
    type: "paired",
    planetaryTags: [],
    elementTags: ["air"],
    functionTags: ["clarifying"],
    voiceRegister: "core",
    trendRisk: "low",
  },
  {
    id: "E12",
    phrase: 'More opening the window, less the candle named "fresh linen"',
    type: "paired",
    planetaryTags: [],
    elementTags: ["air"],
    functionTags: ["clarifying"],
    voiceRegister: "core",
    trendRisk: "low",
  },

  // --- Parent-coded paired (Pa01-Pa08) ---
  {
    id: "Pa01",
    phrase: "More the long drive home alone, less the school pickup performance",
    type: "paired",
    planetaryTags: ["lunar"],
    elementTags: ["water"],
    functionTags: ["calming", "grounding"],
    voiceRegister: "core",
    trendRisk: "low",
    audienceLifeStage: ["parent"],
  },
  {
    id: "Pa02",
    phrase: 'More texting your friend "I can\'t right now," less the seven-paragraph apology',
    type: "paired",
    planetaryTags: ["mercurial"],
    elementTags: ["air"],
    functionTags: ["clarifying", "grounding"],
    voiceRegister: "core",
    trendRisk: "low",
    audienceLifeStage: ["parent"],
  },
  {
    id: "Pa03",
    phrase: "More letting them be bored, less the entertainment director routine",
    type: "paired",
    planetaryTags: ["saturnian"],
    elementTags: ["earth"],
    functionTags: ["grounding", "discipline"],
    voiceRegister: "core",
    trendRisk: "low",
    audienceLifeStage: ["parent"],
  },
  {
    id: "Pa04",
    phrase: "More the bath after they're in bed, less the dishes",
    type: "paired",
    planetaryTags: ["venusian"],
    elementTags: ["water"],
    functionTags: ["calming", "pleasure"],
    voiceRegister: "core",
    trendRisk: "low",
    audienceLifeStage: ["parent"],
  },
  {
    id: "Pa05",
    phrase: "More telling your partner what you actually need, less the resentful sigh",
    type: "paired",
    planetaryTags: ["martian"],
    elementTags: ["fire"],
    functionTags: ["energizing", "releasing"],
    voiceRegister: "core",
    trendRisk: "low",
    audienceLifeStage: ["parent"],
  },
  {
    id: "Pa06",
    phrase: "More the conversation with your kid where you don't fix it, less the explanation",
    type: "paired",
    planetaryTags: ["lunar"],
    elementTags: ["water"],
    functionTags: ["calming", "grounding"],
    voiceRegister: "core",
    trendRisk: "low",
    audienceLifeStage: ["parent"],
  },
  {
    id: "Pa07",
    phrase: "More the coffee while it's still hot, less the cold one at noon",
    type: "paired",
    planetaryTags: ["venusian"],
    elementTags: ["earth"],
    functionTags: ["calming", "pleasure"],
    voiceRegister: "core",
    trendRisk: "low",
    audienceLifeStage: ["parent"],
  },
  {
    id: "Pa08",
    phrase: "More leaving the laundry, less performing the ease",
    type: "paired",
    planetaryTags: ["neptunian"],
    elementTags: ["water"],
    functionTags: ["calming", "surrendering"],
    voiceRegister: "core",
    trendRisk: "low",
    audienceLifeStage: ["parent"],
  },

  // --- Masc-coded paired (Ma01-Ma07) ---
  {
    id: "Ma01",
    phrase: "More the phone call to your dad, less the weekend silence",
    type: "paired",
    planetaryTags: ["lunar"],
    elementTags: ["water"],
    functionTags: ["calming", "grounding"],
    voiceRegister: "core",
    trendRisk: "low",
    audienceGender: ["masc"],
  },
  {
    id: "Ma02",
    phrase: "More the workout you don't post, less the optimized stack",
    type: "paired",
    planetaryTags: ["martian"],
    elementTags: ["fire"],
    functionTags: ["energizing", "releasing"],
    voiceRegister: "core",
    trendRisk: "low",
    audienceGender: ["masc"],
  },
  {
    id: "Ma03",
    phrase: "More the friend you text first, less the assumption he'll text first",
    type: "paired",
    planetaryTags: ["jupiterian"],
    elementTags: ["fire"],
    functionTags: ["energizing", "expanding"],
    voiceRegister: "core",
    trendRisk: "low",
    audienceGender: ["masc"],
  },
  {
    id: "Ma04",
    phrase: "More the doctor appointment you've been putting off, less the data",
    type: "paired",
    planetaryTags: ["saturnian"],
    elementTags: ["earth"],
    functionTags: ["grounding", "discipline"],
    voiceRegister: "core",
    trendRisk: "low",
    audienceGender: ["masc"],
  },
  {
    id: "Ma05",
    phrase: "More the actual hobby, less the project that's secretly a job",
    type: "paired",
    planetaryTags: ["venusian"],
    elementTags: ["earth"],
    functionTags: ["calming", "pleasure"],
    voiceRegister: "core",
    trendRisk: "low",
    audienceGender: ["masc"],
  },
  {
    id: "Ma06",
    phrase: "More crying on a Tuesday, less the gym at midnight",
    type: "paired",
    planetaryTags: ["lunar"],
    elementTags: ["water"],
    functionTags: ["calming", "grounding"],
    voiceRegister: "core",
    trendRisk: "low",
    audienceGender: ["masc"],
  },
  {
    id: "Ma07",
    phrase: "More telling him you love him, less the inside joke",
    type: "paired",
    planetaryTags: ["jupiterian"],
    elementTags: ["fire"],
    functionTags: ["energizing", "expanding"],
    voiceRegister: "core",
    trendRisk: "low",
    audienceGender: ["masc"],
  },

  // --- 45+ paired (O01-O07) ---
  {
    id: "O01",
    phrase: "More the friend who's known you twenty years, less the network event",
    type: "paired",
    planetaryTags: ["saturnian"],
    elementTags: ["earth"],
    functionTags: ["grounding", "discipline"],
    voiceRegister: "core",
    trendRisk: "low",
    audienceLifeStage: ["45+"],
  },
  {
    id: "O02",
    phrase: "More the haircut, less the explanation",
    type: "paired",
    planetaryTags: ["uranian"],
    elementTags: ["air"],
    functionTags: ["energizing", "disrupting"],
    voiceRegister: "core",
    trendRisk: "low",
    audienceLifeStage: ["45+"],
  },
  {
    id: "O03",
    phrase: "More the second career, less the lateral move",
    type: "paired",
    planetaryTags: ["jupiterian"],
    elementTags: ["fire"],
    functionTags: ["energizing", "expanding"],
    voiceRegister: "core",
    trendRisk: "low",
    audienceLifeStage: ["45+"],
  },
  {
    id: "O04",
    phrase: "More the doctor you trust, less the second opinion you're stalling with",
    type: "paired",
    planetaryTags: ["saturnian"],
    elementTags: ["earth"],
    functionTags: ["grounding", "discipline"],
    voiceRegister: "core",
    trendRisk: "low",
    audienceLifeStage: ["45+"],
  },
  {
    id: "O05",
    phrase: "More the friend you've outgrown out loud, less the polite drift",
    type: "paired",
    planetaryTags: ["plutonian"],
    elementTags: ["water"],
    functionTags: ["releasing", "transforming"],
    voiceRegister: "core",
    trendRisk: "low",
    audienceLifeStage: ["45+"],
  },
  {
    id: "O06",
    phrase: "More telling the younger version of you the truth, less the curated origin story",
    type: "paired",
    planetaryTags: ["plutonian"],
    elementTags: ["water"],
    functionTags: ["releasing", "transforming"],
    voiceRegister: "core",
    trendRisk: "low",
    audienceLifeStage: ["45+"],
  },
  {
    id: "O07",
    phrase: "More what you actually want now, less the version you wanted at 32",
    type: "paired",
    planetaryTags: ["solar"],
    elementTags: ["fire"],
    functionTags: ["energizing", "empowering"],
    voiceRegister: "core",
    trendRisk: "low",
    audienceLifeStage: ["45+"],
  },

  // ============================================================
  // STANDALONE PHRASES (120 total)
  // ============================================================

  // --- "Call coming from inside the chart" (D01-D10) ---
  {
    id: "D01",
    phrase: "The call is coming from inside the chart.",
    type: "standalone",
    planetaryTags: ["plutonian"],
    elementTags: ["water"],
    functionTags: ["clarifying"],
    voiceRegister: "pop",
    trendRisk: "low",
  },
  {
    id: "D02",
    phrase: "The avoidance is the personality.",
    type: "standalone",
    planetaryTags: ["plutonian"],
    elementTags: ["water"],
    functionTags: ["clarifying"],
    voiceRegister: "pop",
    trendRisk: "low",
  },
  {
    id: "D03",
    phrase: "You are not the exception. You are the rule, with better skin.",
    type: "standalone",
    planetaryTags: ["plutonian"],
    elementTags: ["water"],
    functionTags: ["clarifying"],
    voiceRegister: "pop",
    trendRisk: "low",
  },
  {
    id: "D04",
    phrase: "The pattern is the plot.",
    type: "standalone",
    planetaryTags: ["plutonian"],
    elementTags: ["water"],
    functionTags: ["clarifying"],
    voiceRegister: "pop",
    trendRisk: "low",
  },
  {
    id: "D05",
    phrase: "Your Saturn return is not a typo.",
    type: "standalone",
    planetaryTags: ["plutonian"],
    elementTags: ["water"],
    functionTags: ["clarifying"],
    voiceRegister: "pop",
    trendRisk: "low",
  },
  {
    id: "D06",
    phrase: "The group chat cannot save you.",
    type: "standalone",
    planetaryTags: ["plutonian"],
    elementTags: ["water"],
    functionTags: ["clarifying"],
    voiceRegister: "pop",
    trendRisk: "low",
  },
  {
    id: "D07",
    phrase: "He's not complicated, he's a Gemini moon.",
    type: "standalone",
    planetaryTags: ["plutonian"],
    elementTags: ["water"],
    functionTags: ["clarifying"],
    voiceRegister: "pop",
    trendRisk: "low",
  },
  {
    id: "D08",
    phrase: "Your mother is in the room with us right now.",
    type: "standalone",
    planetaryTags: ["plutonian"],
    elementTags: ["water"],
    functionTags: ["clarifying"],
    voiceRegister: "pop",
    trendRisk: "low",
  },
  {
    id: "D09",
    phrase: "The journal is a witness, not a fix.",
    type: "standalone",
    planetaryTags: ["plutonian"],
    elementTags: ["water"],
    functionTags: ["clarifying"],
    voiceRegister: "pop",
    trendRisk: "low",
  },
  {
    id: "D10",
    phrase: "You are not behind. You are exactly on time, which is to say, late.",
    type: "standalone",
    planetaryTags: ["plutonian"],
    elementTags: ["water"],
    functionTags: ["clarifying"],
    voiceRegister: "pop",
    trendRisk: "low",
  },

  // --- Pure diagnostic (D11-D20) ---
  {
    id: "D11",
    phrase: "The bath is not the ritual. The willingness to sit in the bath is.",
    type: "standalone",
    planetaryTags: ["neptunian"],
    elementTags: ["water"],
    functionTags: ["calming", "clarifying"],
    voiceRegister: "core",
    trendRisk: "low",
  },
  {
    id: "D12",
    phrase: "You are mistaking productivity for safety.",
    type: "standalone",
    planetaryTags: ["saturnian"],
    elementTags: ["earth"],
    functionTags: ["clarifying", "grounding"],
    voiceRegister: "core",
    trendRisk: "low",
  },
  {
    id: "D13",
    phrase: "You are doing the thing you said you would never do, again.",
    type: "standalone",
    planetaryTags: ["plutonian"],
    elementTags: ["water"],
    functionTags: ["clarifying", "releasing"],
    voiceRegister: "core",
    trendRisk: "low",
  },
  {
    id: "D14",
    phrase: "The grief is not in the way. The grief is the way.",
    type: "standalone",
    planetaryTags: ["plutonian"],
    elementTags: ["water"],
    functionTags: ["calming", "transforming"],
    voiceRegister: "core",
    trendRisk: "low",
  },
  {
    id: "D15",
    phrase: 'Saying "I\'m fine" is not the same as being fine. They rhyme.',
    type: "standalone",
    planetaryTags: ["mercurial"],
    elementTags: ["air"],
    functionTags: ["clarifying"],
    voiceRegister: "core",
    trendRisk: "low",
  },
  {
    id: "D16",
    phrase: "You don't need a sign. You need to act on the seven you've already had.",
    type: "standalone",
    planetaryTags: ["martian"],
    elementTags: ["fire"],
    functionTags: ["energizing", "clarifying"],
    voiceRegister: "core",
    trendRisk: "low",
  },
  {
    id: "D17",
    phrase: "The anxiety is not your intuition. The intuition is quieter.",
    type: "standalone",
    planetaryTags: ["neptunian"],
    elementTags: ["water"],
    functionTags: ["calming", "clarifying"],
    voiceRegister: "core",
    trendRisk: "low",
  },
  {
    id: "D18",
    phrase: "You are not too much. You are too much for some people — that's a setting, not a flaw.",
    type: "standalone",
    planetaryTags: ["solar"],
    elementTags: ["fire"],
    functionTags: ["empowering", "clarifying"],
    voiceRegister: "core",
    trendRisk: "low",
  },
  {
    id: "D19",
    phrase: "The shame is older than you are.",
    type: "standalone",
    planetaryTags: ["plutonian"],
    elementTags: ["water"],
    functionTags: ["releasing", "clarifying"],
    voiceRegister: "core",
    trendRisk: "low",
  },
  {
    id: "D20",
    phrase: "The depression is well-organized this season.",
    type: "standalone",
    planetaryTags: ["neptunian"],
    elementTags: ["water"],
    functionTags: ["clarifying"],
    voiceRegister: "core",
    trendRisk: "low",
  },

  // --- Internet-native (IN01-IN15) ---
  {
    id: "IN01",
    phrase: "Touch grass, but make it a ritual.",
    type: "standalone",
    planetaryTags: ["uranian"],
    elementTags: ["earth"],
    functionTags: ["energizing", "grounding"],
    voiceRegister: "pop",
    trendRisk: "high",
  },
  {
    id: "IN02",
    phrase: "The girls that get it, get it.",
    type: "standalone",
    planetaryTags: ["lunar"],
    elementTags: ["water"],
    functionTags: ["calming"],
    voiceRegister: "pop",
    trendRisk: "high",
  },
  {
    id: "IN03",
    phrase: "He's a 6 but he texts back.",
    type: "standalone",
    planetaryTags: ["venusian"],
    elementTags: ["water"],
    functionTags: ["clarifying"],
    voiceRegister: "pop",
    trendRisk: "high",
  },
  {
    id: "IN04",
    phrase: "Main character energy, but you actually have to do the thing.",
    type: "standalone",
    planetaryTags: ["solar"],
    elementTags: ["fire"],
    functionTags: ["energizing", "empowering"],
    voiceRegister: "pop",
    trendRisk: "high",
  },
  {
    id: "IN05",
    phrase: "Soft launching your healing.",
    type: "standalone",
    planetaryTags: ["neptunian"],
    elementTags: ["water"],
    functionTags: ["calming", "surrendering"],
    voiceRegister: "pop",
    trendRisk: "high",
  },
  {
    id: "IN06",
    phrase: "Your therapist could not have written this transit better.",
    type: "standalone",
    planetaryTags: ["plutonian"],
    elementTags: ["water"],
    functionTags: ["clarifying"],
    voiceRegister: "pop",
    trendRisk: "high",
  },
  {
    id: "IN07",
    phrase: "The ick is a teacher.",
    type: "standalone",
    planetaryTags: ["plutonian"],
    elementTags: ["water"],
    functionTags: ["clarifying", "transforming"],
    voiceRegister: "pop",
    trendRisk: "high",
  },
  {
    id: "IN08",
    phrase: "Boy math says he's tall. Astrology says he's avoidant.",
    type: "standalone",
    planetaryTags: ["mercurial"],
    elementTags: ["air"],
    functionTags: ["clarifying"],
    voiceRegister: "pop",
    trendRisk: "high",
  },
  {
    id: "IN09",
    phrase: "Cancel the plans. Take the bath. You know.",
    type: "standalone",
    planetaryTags: ["neptunian"],
    elementTags: ["water"],
    functionTags: ["calming", "surrendering"],
    voiceRegister: "pop",
    trendRisk: "high",
  },
  {
    id: "IN10",
    phrase: "Block him. The chart said so.",
    type: "standalone",
    planetaryTags: ["martian"],
    elementTags: ["fire"],
    functionTags: ["energizing", "releasing"],
    voiceRegister: "pop",
    trendRisk: "high",
  },
  {
    id: "IN11",
    phrase: 'We don\'t do "almost relationships" in this transit.',
    type: "standalone",
    planetaryTags: ["plutonian"],
    elementTags: ["water"],
    functionTags: ["releasing", "transforming"],
    voiceRegister: "pop",
    trendRisk: "high",
  },
  {
    id: "IN12",
    phrase: "Romanticizing your life only works if you actually live it.",
    type: "standalone",
    planetaryTags: ["solar"],
    elementTags: ["fire"],
    functionTags: ["energizing", "empowering"],
    voiceRegister: "pop",
    trendRisk: "high",
  },
  {
    id: "IN13",
    phrase: "The era is yours but you have to clock in.",
    type: "standalone",
    planetaryTags: ["solar"],
    elementTags: ["fire"],
    functionTags: ["energizing", "empowering"],
    voiceRegister: "pop",
    trendRisk: "high",
  },
  {
    id: "IN14",
    phrase: 'You are not "going through it." You are in it.',
    type: "standalone",
    planetaryTags: ["plutonian"],
    elementTags: ["water"],
    functionTags: ["clarifying"],
    voiceRegister: "pop",
    trendRisk: "high",
  },
  {
    id: "IN15",
    phrase: "This is your Roman Empire and you have to stop letting it sack you.",
    type: "standalone",
    planetaryTags: ["martian"],
    elementTags: ["fire"],
    functionTags: ["energizing", "releasing"],
    voiceRegister: "pop",
    trendRisk: "high",
  },

  // --- Cultural-shorthand cool (CS01-CS06) ---
  {
    id: "CS01",
    phrase: "Pop the champagne. Cancel the situationship.",
    type: "standalone",
    planetaryTags: ["martian"],
    elementTags: ["fire"],
    functionTags: ["energizing", "releasing"],
    voiceRegister: "pop",
    trendRisk: "medium",
  },
  {
    id: "CS02",
    phrase: "We accept the love we think we deserve. We can update the deserving.",
    type: "standalone",
    planetaryTags: ["venusian"],
    elementTags: ["water"],
    functionTags: ["calming", "transforming"],
    voiceRegister: "pop",
    trendRisk: "medium",
  },
  {
    id: "CS03",
    phrase: "Knives out for the version of you that says yes when you mean no.",
    type: "standalone",
    planetaryTags: ["martian"],
    elementTags: ["fire"],
    functionTags: ["energizing", "releasing"],
    voiceRegister: "pop",
    trendRisk: "medium",
  },
  {
    id: "CS04",
    phrase: 'It\'s giving avoidant. It\'s giving "I need space." It\'s giving you the answer.',
    type: "standalone",
    planetaryTags: ["plutonian"],
    elementTags: ["water"],
    functionTags: ["clarifying", "releasing"],
    voiceRegister: "pop",
    trendRisk: "medium",
  },
  {
    id: "CS05",
    phrase: 'He had you at "I\'m working on myself." He lost you at "but not right now."',
    type: "standalone",
    planetaryTags: ["venusian"],
    elementTags: ["water"],
    functionTags: ["clarifying"],
    voiceRegister: "pop",
    trendRisk: "medium",
  },
  {
    id: "CS06",
    phrase: "You are not the one who got away. You are the one who left.",
    type: "standalone",
    planetaryTags: ["martian"],
    elementTags: ["fire"],
    functionTags: ["energizing", "empowering"],
    voiceRegister: "pop",
    trendRisk: "medium",
  },

  // --- Text-fragment register (TF01-TF15) ---
  {
    id: "TF01",
    phrase: "babe. babe.",
    type: "standalone",
    planetaryTags: ["lunar"],
    elementTags: ["water"],
    functionTags: ["calming"],
    voiceRegister: "text_fragment",
    trendRisk: "medium",
  },
  {
    id: "TF02",
    phrase: "Not the same situationship. Not again.",
    type: "standalone",
    planetaryTags: ["plutonian"],
    elementTags: ["water"],
    functionTags: ["releasing"],
    voiceRegister: "text_fragment",
    trendRisk: "medium",
  },
  {
    id: "TF03",
    phrase: "Girl. The chart.",
    type: "standalone",
    planetaryTags: ["plutonian"],
    elementTags: ["water"],
    functionTags: ["clarifying"],
    voiceRegister: "text_fragment",
    trendRisk: "medium",
  },
  {
    id: "TF04",
    phrase: "We are not doing this in 2026.",
    type: "standalone",
    planetaryTags: ["saturnian"],
    elementTags: ["earth"],
    functionTags: ["grounding", "discipline"],
    voiceRegister: "text_fragment",
    trendRisk: "medium",
  },
  {
    id: "TF05",
    phrase: 'He\'s not "complicated." Pull up the chart.',
    type: "standalone",
    planetaryTags: ["mercurial"],
    elementTags: ["air"],
    functionTags: ["clarifying"],
    voiceRegister: "text_fragment",
    trendRisk: "medium",
  },
  {
    id: "TF06",
    phrase: "Send the text or don't. Stop drafting.",
    type: "standalone",
    planetaryTags: ["martian"],
    elementTags: ["fire"],
    functionTags: ["energizing"],
    voiceRegister: "text_fragment",
    trendRisk: "medium",
  },
  {
    id: "TF07",
    phrase: "The bath. Now. Go.",
    type: "standalone",
    planetaryTags: ["neptunian"],
    elementTags: ["water"],
    functionTags: ["calming"],
    voiceRegister: "text_fragment",
    trendRisk: "medium",
  },
  {
    id: "TF08",
    phrase: "No, you don't need closure. You need the block button.",
    type: "standalone",
    planetaryTags: ["martian"],
    elementTags: ["fire"],
    functionTags: ["energizing", "releasing"],
    voiceRegister: "text_fragment",
    trendRisk: "medium",
  },
  {
    id: "TF09",
    phrase: "Therapy on Tuesday. Bath on Friday. Both.",
    type: "standalone",
    planetaryTags: ["saturnian"],
    elementTags: ["earth"],
    functionTags: ["grounding"],
    voiceRegister: "text_fragment",
    trendRisk: "medium",
  },
  {
    id: "TF10",
    phrase: "He texted. So what.",
    type: "standalone",
    planetaryTags: ["martian"],
    elementTags: ["fire"],
    functionTags: ["energizing"],
    voiceRegister: "text_fragment",
    trendRisk: "medium",
  },
  {
    id: "TF11",
    phrase: "Read your own chart and weep.",
    type: "standalone",
    planetaryTags: ["plutonian"],
    elementTags: ["water"],
    functionTags: ["clarifying"],
    voiceRegister: "text_fragment",
    trendRisk: "medium",
  },
  {
    id: "TF12",
    phrase: "You are not a problem to be solved. He is.",
    type: "standalone",
    planetaryTags: ["venusian"],
    elementTags: ["water"],
    functionTags: ["clarifying", "empowering"],
    voiceRegister: "text_fragment",
    trendRisk: "medium",
  },
  {
    id: "TF13",
    phrase: "The audacity of him. The patience of you. Fix one of them.",
    type: "standalone",
    planetaryTags: ["martian"],
    elementTags: ["fire"],
    functionTags: ["energizing", "releasing"],
    voiceRegister: "text_fragment",
    trendRisk: "medium",
  },
  {
    id: "TF14",
    phrase: "Stop. Reading. His. Substack.",
    type: "standalone",
    planetaryTags: ["martian"],
    elementTags: ["fire"],
    functionTags: ["energizing"],
    voiceRegister: "text_fragment",
    trendRisk: "medium",
  },
  {
    id: "TF15",
    phrase: "Touch the grass. Drink the water. Block the boy.",
    type: "standalone",
    planetaryTags: ["martian"],
    elementTags: ["earth"],
    functionTags: ["grounding", "energizing"],
    voiceRegister: "text_fragment",
    trendRisk: "medium",
  },

  // --- Diagnostic with cultural bite (DC01-DC14) ---
  {
    id: "DC01",
    phrase: 'Your aesthetic is "girl who\'s about to make a bad decision and then journal about it."',
    type: "standalone",
    planetaryTags: ["plutonian"],
    elementTags: ["water"],
    functionTags: ["clarifying"],
    voiceRegister: "pop",
    trendRisk: "medium",
  },
  {
    id: "DC02",
    phrase: "The Pinterest board is not the personality.",
    type: "standalone",
    planetaryTags: ["plutonian"],
    elementTags: ["water"],
    functionTags: ["clarifying"],
    voiceRegister: "pop",
    trendRisk: "medium",
  },
  {
    id: "DC03",
    phrase: "You are healing in the same outfit you broke down in. We see it.",
    type: "standalone",
    planetaryTags: ["plutonian"],
    elementTags: ["water"],
    functionTags: ["clarifying", "transforming"],
    voiceRegister: "pop",
    trendRisk: "medium",
  },
  {
    id: "DC04",
    phrase: "Manifesting only works when you also do the dishes.",
    type: "standalone",
    planetaryTags: ["saturnian"],
    elementTags: ["earth"],
    functionTags: ["grounding", "clarifying"],
    voiceRegister: "pop",
    trendRisk: "medium",
  },
  {
    id: "DC05",
    phrase: "The vision board is for him. Make a new one.",
    type: "standalone",
    planetaryTags: ["venusian"],
    elementTags: ["water"],
    functionTags: ["releasing", "clarifying"],
    voiceRegister: "pop",
    trendRisk: "medium",
  },
  {
    id: "DC06",
    phrase: 'Your toxic trait is calling things "toxic traits."',
    type: "standalone",
    planetaryTags: ["mercurial"],
    elementTags: ["air"],
    functionTags: ["clarifying"],
    voiceRegister: "pop",
    trendRisk: "medium",
  },
  {
    id: "DC07",
    phrase: "You are not lazy. You are processing. There's a difference.",
    type: "standalone",
    planetaryTags: ["neptunian"],
    elementTags: ["water"],
    functionTags: ["calming", "clarifying"],
    voiceRegister: "pop",
    trendRisk: "medium",
  },
  {
    id: "DC08",
    phrase: "The astrology is just describing what your therapist already told you.",
    type: "standalone",
    planetaryTags: ["mercurial"],
    elementTags: ["air"],
    functionTags: ["clarifying"],
    voiceRegister: "pop",
    trendRisk: "medium",
  },
  {
    id: "DC09",
    phrase: "You're not a hopeless romantic. You're a Venus in Pisces with no boundaries.",
    type: "standalone",
    planetaryTags: ["venusian"],
    elementTags: ["water"],
    functionTags: ["clarifying"],
    voiceRegister: "pop",
    trendRisk: "medium",
  },
  {
    id: "DC10",
    phrase: 'The "soft girl era" is just rest with better marketing.',
    type: "standalone",
    planetaryTags: ["neptunian"],
    elementTags: ["water"],
    functionTags: ["calming", "clarifying"],
    voiceRegister: "pop",
    trendRisk: "medium",
  },
  {
    id: "DC11",
    phrase: "You don't have a type. You have a wound.",
    type: "standalone",
    planetaryTags: ["plutonian"],
    elementTags: ["water"],
    functionTags: ["clarifying", "transforming"],
    voiceRegister: "pop",
    trendRisk: "medium",
  },
  {
    id: "DC12",
    phrase: "Self-awareness without action is just a really expensive hobby.",
    type: "standalone",
    planetaryTags: ["martian"],
    elementTags: ["fire"],
    functionTags: ["energizing", "clarifying"],
    voiceRegister: "pop",
    trendRisk: "medium",
  },
  {
    id: "DC13",
    phrase: "The Pisces moon will not save him. You also will not save him.",
    type: "standalone",
    planetaryTags: ["neptunian"],
    elementTags: ["water"],
    functionTags: ["clarifying", "releasing"],
    voiceRegister: "pop",
    trendRisk: "medium",
  },
  {
    id: "DC14",
    phrase: 'You are not "an empath." You are anxious and observant.',
    type: "standalone",
    planetaryTags: ["mercurial"],
    elementTags: ["air"],
    functionTags: ["clarifying"],
    voiceRegister: "pop",
    trendRisk: "medium",
  },

  // --- Fashion / lifestyle coded (FL01-FL08) ---
  {
    id: "FL01",
    phrase: "Quiet luxury, loud feelings.",
    type: "standalone",
    planetaryTags: ["venusian"],
    elementTags: ["water"],
    functionTags: ["calming", "pleasure"],
    voiceRegister: "pop",
    trendRisk: "high",
  },
  {
    id: "FL02",
    phrase: "Clean girl morning, demonic afternoon.",
    type: "standalone",
    planetaryTags: ["plutonian"],
    elementTags: ["water"],
    functionTags: ["clarifying"],
    voiceRegister: "pop",
    trendRisk: "high",
  },
  {
    id: "FL03",
    phrase: "Coastal grandmother in the streets, Scorpio in the sheets.",
    type: "standalone",
    planetaryTags: ["plutonian"],
    elementTags: ["water"],
    functionTags: ["clarifying"],
    voiceRegister: "pop",
    trendRisk: "high",
  },
  {
    id: "FL04",
    phrase: "You can wear the silk slip and answer the email.",
    type: "standalone",
    planetaryTags: ["venusian"],
    elementTags: ["earth"],
    functionTags: ["empowering", "pleasure"],
    voiceRegister: "pop",
    trendRisk: "high",
  },
  {
    id: "FL05",
    phrase: "Slick back ponytail energy, but for your boundaries.",
    type: "standalone",
    planetaryTags: ["martian"],
    elementTags: ["fire"],
    functionTags: ["energizing", "empowering"],
    voiceRegister: "pop",
    trendRisk: "high",
  },
  {
    id: "FL06",
    phrase: 'The "it bag" is your nervous system. Fix the bag.',
    type: "standalone",
    planetaryTags: ["saturnian"],
    elementTags: ["earth"],
    functionTags: ["grounding", "clarifying"],
    voiceRegister: "pop",
    trendRisk: "high",
  },
  {
    id: "FL07",
    phrase: "Pilates body, journalism mind, Pisces feelings.",
    type: "standalone",
    planetaryTags: ["neptunian"],
    elementTags: ["water"],
    functionTags: ["clarifying"],
    voiceRegister: "pop",
    trendRisk: "high",
  },
  {
    id: "FL08",
    phrase: 'You are not "dressing for the job you want." You are dressing for the woman you are.',
    type: "standalone",
    planetaryTags: ["solar"],
    elementTags: ["fire"],
    functionTags: ["empowering"],
    voiceRegister: "pop",
    trendRisk: "high",
  },

  // --- Pop diagnostics, deeper bench (PD01-PD20) ---
  {
    id: "PD01",
    phrase: 'You are not "going through a phase." You are going through the phase.',
    type: "standalone",
    planetaryTags: ["plutonian"],
    elementTags: ["water"],
    functionTags: ["clarifying", "transforming"],
    voiceRegister: "pop",
    trendRisk: "medium",
  },
  {
    id: "PD02",
    phrase: "Your situationship has a Pinterest board.",
    type: "standalone",
    planetaryTags: ["venusian"],
    elementTags: ["water"],
    functionTags: ["clarifying"],
    voiceRegister: "pop",
    trendRisk: "medium",
  },
  {
    id: "PD03",
    phrase: "The therapy-speak girlies need to log off.",
    type: "standalone",
    planetaryTags: ["mercurial"],
    elementTags: ["air"],
    functionTags: ["clarifying"],
    voiceRegister: "pop",
    trendRisk: "medium",
  },
  {
    id: "PD04",
    phrase: "He's an avoidant. The chart said. The behavior said. Your friends said. Believe them.",
    type: "standalone",
    planetaryTags: ["plutonian"],
    elementTags: ["water"],
    functionTags: ["clarifying", "releasing"],
    voiceRegister: "pop",
    trendRisk: "medium",
  },
  {
    id: "PD05",
    phrase: "Mercury is not retrograde. You are.",
    type: "standalone",
    planetaryTags: ["mercurial"],
    elementTags: ["air"],
    functionTags: ["clarifying"],
    voiceRegister: "pop",
    trendRisk: "medium",
  },
  {
    id: "PD06",
    phrase: "The transit is real, and you're being dramatic.",
    type: "standalone",
    planetaryTags: ["solar"],
    elementTags: ["fire"],
    functionTags: ["clarifying"],
    voiceRegister: "pop",
    trendRisk: "medium",
  },
  {
    id: "PD07",
    phrase: "Your moon sign is showing.",
    type: "standalone",
    planetaryTags: ["lunar"],
    elementTags: ["water"],
    functionTags: ["clarifying"],
    voiceRegister: "pop",
    trendRisk: "medium",
  },
  {
    id: "PD08",
    phrase: "Pluto in your seventh house is not a vibe, it's a court order.",
    type: "standalone",
    planetaryTags: ["plutonian"],
    elementTags: ["water"],
    functionTags: ["clarifying", "transforming"],
    voiceRegister: "pop",
    trendRisk: "medium",
  },
  {
    id: "PD09",
    phrase: "The audacity. The patience. The Pisces moon.",
    type: "standalone",
    planetaryTags: ["neptunian"],
    elementTags: ["water"],
    functionTags: ["clarifying"],
    voiceRegister: "pop",
    trendRisk: "medium",
  },
  {
    id: "PD10",
    phrase: "Stop. Just. Stop.",
    type: "standalone",
    planetaryTags: ["martian"],
    elementTags: ["fire"],
    functionTags: ["energizing"],
    voiceRegister: "pop",
    trendRisk: "medium",
  },
  {
    id: "PD11",
    phrase: "The chart is the chart, babe.",
    type: "standalone",
    planetaryTags: ["plutonian"],
    elementTags: ["water"],
    functionTags: ["clarifying"],
    voiceRegister: "pop",
    trendRisk: "medium",
  },
  {
    id: "PD12",
    phrase: "Yes you can. No you shouldn't.",
    type: "standalone",
    planetaryTags: ["saturnian"],
    elementTags: ["earth"],
    functionTags: ["grounding", "clarifying"],
    voiceRegister: "pop",
    trendRisk: "medium",
  },
  {
    id: "PD13",
    phrase: "The girl dinner is the depression. We can name it.",
    type: "standalone",
    planetaryTags: ["plutonian"],
    elementTags: ["water"],
    functionTags: ["clarifying", "releasing"],
    voiceRegister: "pop",
    trendRisk: "medium",
  },
  {
    id: "PD14",
    phrase: 'You are in your "main character" era and your friends are tired of it.',
    type: "standalone",
    planetaryTags: ["solar"],
    elementTags: ["fire"],
    functionTags: ["clarifying"],
    voiceRegister: "pop",
    trendRisk: "medium",
  },
  {
    id: "PD15",
    phrase: 'The aesthetic is "trying" and you\'re nailing it.',
    type: "standalone",
    planetaryTags: ["solar"],
    elementTags: ["fire"],
    functionTags: ["empowering", "clarifying"],
    voiceRegister: "pop",
    trendRisk: "medium",
  },
  {
    id: "PD16",
    phrase: "You are dating men your therapist could write a paper on.",
    type: "standalone",
    planetaryTags: ["plutonian"],
    elementTags: ["water"],
    functionTags: ["clarifying"],
    voiceRegister: "pop",
    trendRisk: "medium",
  },
  {
    id: "PD17",
    phrase: 'The men you keep meeting are not "all the same." You keep choosing.',
    type: "standalone",
    planetaryTags: ["plutonian"],
    elementTags: ["water"],
    functionTags: ["clarifying", "releasing"],
    voiceRegister: "pop",
    trendRisk: "medium",
  },
  {
    id: "PD18",
    phrase: "Your standards are not high. Your patterns are.",
    type: "standalone",
    planetaryTags: ["plutonian"],
    elementTags: ["water"],
    functionTags: ["clarifying", "transforming"],
    voiceRegister: "pop",
    trendRisk: "medium",
  },
  {
    id: "PD19",
    phrase: "Hot people have problems too. Yours are just better lit.",
    type: "standalone",
    planetaryTags: ["solar"],
    elementTags: ["fire"],
    functionTags: ["clarifying"],
    voiceRegister: "pop",
    trendRisk: "medium",
  },
  {
    id: "PD20",
    phrase: "You are not closed off. You are appropriately calibrated.",
    type: "standalone",
    planetaryTags: ["saturnian"],
    elementTags: ["earth"],
    functionTags: ["grounding", "clarifying"],
    voiceRegister: "pop",
    trendRisk: "medium",
  },

  // --- Parent-coded standalone (PaD01-PaD02) ---
  {
    id: "PaD01",
    phrase: "The mom guilt is on a loop. The loop is the problem, not the mothering.",
    type: "standalone",
    planetaryTags: ["lunar"],
    elementTags: ["water"],
    functionTags: ["calming", "clarifying"],
    voiceRegister: "core",
    trendRisk: "low",
    audienceLifeStage: ["parent"],
  },
  {
    id: "PaD02",
    phrase: "Your kid does not need you to be calm. Your kid needs you to be honest about not being calm.",
    type: "standalone",
    planetaryTags: ["lunar"],
    elementTags: ["water"],
    functionTags: ["calming", "clarifying"],
    voiceRegister: "core",
    trendRisk: "low",
    audienceLifeStage: ["parent"],
  },

  // --- Masc-coded standalone (MaD01-MaD03) ---
  {
    id: "MaD01",
    phrase: "The thing you can't talk to your guy friends about is the thing.",
    type: "standalone",
    planetaryTags: ["plutonian"],
    elementTags: ["water"],
    functionTags: ["clarifying", "releasing"],
    voiceRegister: "core",
    trendRisk: "low",
    audienceGender: ["masc"],
  },
  {
    id: "MaD02",
    phrase: "The anger is real. The anger is also asking you a question.",
    type: "standalone",
    planetaryTags: ["martian"],
    elementTags: ["fire"],
    functionTags: ["energizing", "clarifying"],
    voiceRegister: "core",
    trendRisk: "low",
    audienceGender: ["masc"],
  },
  {
    id: "MaD03",
    phrase: "The provider role is not the whole role.",
    type: "standalone",
    planetaryTags: ["saturnian"],
    elementTags: ["earth"],
    functionTags: ["grounding", "clarifying"],
    voiceRegister: "core",
    trendRisk: "low",
    audienceGender: ["masc"],
  },

  // --- 45+ standalone (OD01-OD03) ---
  {
    id: "OD01",
    phrase: "The body is not a problem to solve. The body is the report.",
    type: "standalone",
    planetaryTags: ["saturnian"],
    elementTags: ["earth"],
    functionTags: ["grounding", "clarifying"],
    voiceRegister: "core",
    trendRisk: "low",
    audienceLifeStage: ["45+"],
  },
  {
    id: "OD02",
    phrase: "The menopause is not a vibe. It is a re-org.",
    type: "standalone",
    planetaryTags: ["plutonian"],
    elementTags: ["water"],
    functionTags: ["transforming", "clarifying"],
    voiceRegister: "core",
    trendRisk: "low",
    audienceLifeStage: ["45+"],
  },
  {
    id: "OD03",
    phrase: "The aging parents are not a future event.",
    type: "standalone",
    planetaryTags: ["saturnian"],
    elementTags: ["earth"],
    functionTags: ["grounding", "clarifying"],
    voiceRegister: "core",
    trendRisk: "low",
    audienceLifeStage: ["45+"],
  },

  // --- Literary register (LR01-LR14) ---
  {
    id: "LR01",
    phrase: "We tell ourselves stories in order to live. We tell ourselves the same story in order to stay stuck.",
    type: "standalone",
    planetaryTags: ["plutonian"],
    elementTags: ["water"],
    functionTags: ["clarifying", "transforming"],
    voiceRegister: "literary",
    trendRisk: "low",
  },
  {
    id: "LR02",
    phrase: "The center will not hold, but the bath will.",
    type: "standalone",
    planetaryTags: ["neptunian"],
    elementTags: ["water"],
    functionTags: ["calming", "surrendering"],
    voiceRegister: "literary",
    trendRisk: "low",
  },
  {
    id: "LR03",
    phrase: "You were not abandoned. You stopped showing up for yourself first.",
    type: "standalone",
    planetaryTags: ["plutonian"],
    elementTags: ["water"],
    functionTags: ["clarifying", "transforming"],
    voiceRegister: "literary",
    trendRisk: "low",
  },
  {
    id: "LR04",
    phrase: "Self-respect is what you do at 4pm on a Tuesday when no one is watching.",
    type: "standalone",
    planetaryTags: ["saturnian"],
    elementTags: ["earth"],
    functionTags: ["grounding", "discipline"],
    voiceRegister: "literary",
    trendRisk: "low",
  },
  {
    id: "LR05",
    phrase: "The phone call you've been avoiding is the only call worth making.",
    type: "standalone",
    planetaryTags: ["martian"],
    elementTags: ["fire"],
    functionTags: ["energizing", "clarifying"],
    voiceRegister: "literary",
    trendRisk: "low",
  },
  {
    id: "LR06",
    phrase: "The thing about marriage, the thing about all of it, is that you have to keep choosing.",
    type: "standalone",
    planetaryTags: ["venusian"],
    elementTags: ["water"],
    functionTags: ["calming", "clarifying"],
    voiceRegister: "literary",
    trendRisk: "low",
  },
  {
    id: "LR07",
    phrase: "You are someone who has been hurt and not yet someone who has been changed by it.",
    type: "standalone",
    planetaryTags: ["plutonian"],
    elementTags: ["water"],
    functionTags: ["clarifying", "transforming"],
    voiceRegister: "literary",
    trendRisk: "low",
  },
  {
    id: "LR08",
    phrase: "He was a person you could not stop almost-loving.",
    type: "standalone",
    planetaryTags: ["venusian"],
    elementTags: ["water"],
    functionTags: ["calming", "releasing"],
    voiceRegister: "literary",
    trendRisk: "low",
  },
  {
    id: "LR09",
    phrase: "You are not falling apart. You are just unmedicated for the version of yourself you've outgrown.",
    type: "standalone",
    planetaryTags: ["plutonian"],
    elementTags: ["water"],
    functionTags: ["clarifying", "transforming"],
    voiceRegister: "literary",
    trendRisk: "low",
  },
  {
    id: "LR10",
    phrase: "You wanted to be a person who has dinner parties. You are a person who orders Postmates.",
    type: "standalone",
    planetaryTags: ["solar"],
    elementTags: ["fire"],
    functionTags: ["clarifying"],
    voiceRegister: "literary",
    trendRisk: "low",
  },
  {
    id: "LR11",
    phrase: "You are doing fine, in the technical sense.",
    type: "standalone",
    planetaryTags: ["mercurial"],
    elementTags: ["air"],
    functionTags: ["clarifying"],
    voiceRegister: "literary",
    trendRisk: "low",
  },
  {
    id: "LR12",
    phrase: "The class consciousness of leaving a man who texts in fragments.",
    type: "standalone",
    planetaryTags: ["mercurial"],
    elementTags: ["air"],
    functionTags: ["clarifying"],
    voiceRegister: "literary",
    trendRisk: "low",
  },
  {
    id: "LR13",
    phrase: "To love someone is, at minimum, to be inconvenienced by them.",
    type: "standalone",
    planetaryTags: ["venusian"],
    elementTags: ["water"],
    functionTags: ["calming", "clarifying"],
    voiceRegister: "literary",
    trendRisk: "low",
  },
  {
    id: "LR14",
    phrase: "The relationship is not a problem. The relationship is a project. There's a difference.",
    type: "standalone",
    planetaryTags: ["venusian"],
    elementTags: ["water"],
    functionTags: ["calming", "clarifying"],
    voiceRegister: "literary",
    trendRisk: "low",
  },
];

/**
 * Select a vibe phrase based on planetary/element tags and optional filters.
 */
export function getVibeRecommendation(
  planetaryTag?: string,
  elementTag?: string,
  voiceRegisters?: VoiceRegister[],
  excludeIds?: string[],
): VibePhrase {
  let pool = [...VIBE_LIBRARY];

  // Filter by voice register
  if (voiceRegisters?.length) {
    pool = pool.filter((p) => voiceRegisters.includes(p.voiceRegister));
  }

  // Exclude recently shown
  if (excludeIds?.length) {
    const filtered = pool.filter((p) => !excludeIds.includes(p.id));
    if (filtered.length > 0) pool = filtered;
  }

  // Score by tag match
  const scored = pool.map((p) => {
    let score = 0;
    if (planetaryTag && p.planetaryTags.includes(planetaryTag)) score += 2;
    if (elementTag && p.elementTags.includes(elementTag)) score += 1;
    return { phrase: p, score };
  });

  // Sort by score, pick from top candidates deterministically
  scored.sort((a, b) => b.score - a.score);
  const topScore = scored[0]?.score || 0;
  const candidates = scored.filter((s) => s.score >= topScore - 1);

  // Deterministic daily pick
  const seed = Date.now();
  const pick = candidates[seed % candidates.length];
  return pick.phrase;
}
