INSERT INTO kb_signs (name, abbreviation, symbol, element, modality, ruling_planet, date_range, summary, strengths, challenges, life_theme, relationships, career, growth_edge, book_references) VALUES
(
  'Aries',
  'Ari',
  '♈',
  'Fire',
  'Cardinal',
  'Mars',
  'March 21 - April 19',
  $$You move fast and trust your instincts. You're the type who sees something that needs doing and just does it—no endless deliberation. Your energy is contagious, and people feel your aliveness.$$,
  'Initiative, courage, passion, directness, enthusiasm',
  'Impatience, recklessness, selfishness, aggression, tactlessness',
  $$You show up as the pioneer—the one willing to try first. You live in the present moment intensely, which makes you unreliable at follow-through but irresistible in the moment. Your life is about breaking new ground, but the real lesson is learning when to hold steady.$$,
  $$You love the chase more than the catch. You're direct about desire and commitment comes naturally when you feel genuinely ignited. The work is staying interested after the initial spark, and valuing partners as people, not just conquests.$$,
  $$You need work that feels alive and urgent. You're drawn to competition, leadership, or anything pioneering. Routine kills your spirit, but without structure you scatter. Your best work happens when you're fighting for something you believe in.$$,
  $$You need to develop patience and follow-through. Learning that lasting impact requires sustained effort, not just brilliant starts. The growth edge is understanding that other people's timelines matter, and that real power includes the ability to wait.$$,
  'ARRAY[$$Woolfolk - The Only Astrology Book You'\''ll Ever Need$$, $$Hand - Planets in Transit$$, $$Spiller - Astrology for the Soul$$]'
),
(
  'Taurus',
  'Tau',
  '♉',
  'Earth',
  'Fixed',
  'Venus',
  'April 20 - May 20',
  $$You build things that last. You have real appetites—for beauty, comfort, loyalty—and you're willing to work to create stability around them. People trust you because your word means something.$$,
  'Reliability, sensuality, loyalty, patience, practicality',
  'Stubbornness, possessiveness, resistance to change, indulgence, inertia',
  $$You show up as the builder and the anchor. Your life is about creating solid ground—in your home, your finances, your relationships. You're the person who turns vague dreams into real things. The pattern is knowing when stability becomes stagnation, and when holding on prevents growth.$$,
  $$You love deeply and stay put. You want partnership that\'s tangible and real—someone to build a life with, not just feelings. Your loyalty is a gift, but the work is knowing when a situation won\'t change, and when staying is just fear dressed as devotion.$$,
  $$You excel at work requiring patience, craftsmanship, and long-term vision. You\'re the one who builds systems that function for years. Your challenge is flexibility—the world changes, and rigid approaches eventually fail. You\'re strongest when you adapt without losing your core values.$$,
  $$You need to develop flexibility and comfort with change. Learning that letting go isn\'t the same as loss. Your growth edge is discovering that you\'re resourceful enough to rebuild, and that clinging prevents the abundance you actually want.$$,
  'ARRAY[$$Woolfolk - The Only Astrology Book You'\''ll Ever Need$$, $$Hand - Planets in Transit$$, $$Spiller - Astrology for the Soul$$]'
),
(
  'Gemini',
  'Gem',
  '♊',
  'Air',
  'Mutable',
  'Mercury',
  'May 21 - June 20',
  $$You think in connections and see multiple angles instantly. Boredom is your real enemy—you need novelty, conversation, ideas moving. You\'re quick, curious, and restless in the best way.$$,
  'Adaptability, communication, curiosity, wit, versatility',
  'Inconsistency, superficiality, scatteredness, manipulation, nervousness',
  $$You show up as the connector and the translator. Your life is about understanding how things link together, moving between worlds, translating between different people. You collect ideas and stories. The pattern is depth versus breadth—knowing when to go deeper, when your scattered energy actually prevents real understanding.$$,
  $$You love the conversation part of relationship—the mental sparring, the jokes, the shared discoveries. You need intellectual matching, and routine bores you. The work is commitment to one person, and realizing that real intimacy requires consistency, not just novelty.$$,
  $$You need work involving communication, learning, variety, or connecting people. You wilt in singular focus. Sales, writing, consulting, teaching—anything that uses your pattern-seeing. Your challenge is depth: going past the surface, finishing projects, becoming expert at something.$$,
  $$You need to develop depth and follow-through. Learning that real mastery requires sustained focus, not just dabbling. Your growth edge is discovering that consistency deepens pleasure, and that real connection requires showing up repeatedly.$$,
  'ARRAY[$$Woolfolk - The Only Astrology Book You'\''ll Ever Need$$, $$Hand - Planets in Transit$$, $$Spiller - Astrology for the Soul$$]'
),
(
  'Cancer',
  'Can',
  '♋',
  'Water',
  'Cardinal',
  'Moon',
  'June 21 - July 22',
  $$You feel everything and remember everything. Home and family aren\'t just concepts to you—they\'re survival. You\'re protective, intuitive, and you move people by genuinely caring about their wellbeing.$$,
  'Nurturing, intuition, loyalty, protectiveness, emotional awareness',
  'Defensiveness, clinginess, moodiness, self-pity, withdrawal',
  $$You show up as the protector and the nurturer. Your life is about creating safe spaces and belonging—whether that\'s home, family, or an intimate circle. You sense what people need before they say it. The pattern is learning to protect without controlling, to care without drowning.$$,
  $$You love with your whole being once you trust. You need security and commitment—not for show, but for real. The work is realizing that your moodiness affects others, that not everyone needs rescuing, and that being emotionally available doesn\'t mean taking on everyone\'s pain.$$,
  $$You thrive in work involving care, creativity, or emotional intelligence. You\'re good at reading situations and people. Your challenge is emotional overwhelm—you absorb the room\'s energy and lose yourself. Strong boundaries protect your actual capacity to help.$$,
  $$You need to develop emotional resilience and healthy boundaries. Learning that protecting yourself isn\'t selfish, and that others are responsible for their own emotions. Your growth edge is confidence that you\'re allowed to have your own separate life.$$,
  'ARRAY[$$Woolfolk - The Only Astrology Book You'\''ll Ever Need$$, $$Hand - Planets in Transit$$, $$Spiller - Astrology for the Soul$$]'
),
(
  'Leo',
  'Leo',
  '♌',
  'Fire',
  'Fixed',
  'Sun',
  'July 23 - August 22',
  $$You light up rooms because you actually believe in yourself. You\'re generous with attention and resources—you want to celebrate the people you love. Your presence is unmistakable, and people feel more alive around you.$$,
  'Confidence, generosity, creativity, warmth, courage',
  'Arrogance, vanity, pride, need for validation, drama',
  $$You show up as the creator and the performer. Your life is about self-expression, creating something uniquely yours, and being seen for it. You want to matter, to leave a mark. The pattern is separating real accomplishment from needing approval, and learning that true confidence doesn\'t require an audience.$$,
  $$You love grandly and want to be adored. You\'re generous and loyal to people you claim as yours. The work is not making the relationship about you, not needing constant reassurance, and recognizing when your partner\'s needs matter as much as being celebrated.$$,
  $$You excel at creative work, leadership, entertainment, and anything requiring self-promotion. You need recognition—not from insecurity, but because you\'re genuinely proud of your work. Your challenge is handling criticism and recognizing when ego gets in the way of real collaboration.$$,
  $$You need to develop humility and genuine self-worth separate from recognition. Learning that your value doesn\'t depend on applause. Your growth edge is discovering real power in supporting others\' brilliance, not always being center stage.$$,
  'ARRAY[$$Woolfolk - The Only Astrology Book You'\''ll Ever Need$$, $$Hand - Planets in Transit$$, $$Spiller - Astrology for the Soul$$]'
),
(
  'Virgo',
  'Vir',
  '♍',
  'Earth',
  'Mutable',
  'Mercury',
  'August 23 - September 22',
  $$You see what\'s wrong and you know how to fix it. You\'re exacting with yourself and others because you believe in doing things well. Your attention to detail makes you irreplaceable, and people rely on you.$$,
  'Discernment, precision, helpfulness, humility, reliability',
  'Perfectionism, criticism, self-doubt, anxiety, cold detachment',
  $$You show up as the improver and the analyst. Your life is about refining things, solving problems, making incremental progress. You\'re drawn to mastery and doing work that matters. The pattern is knowing when good enough is good enough, when your criticism becomes cruelty, and that perfection is impossible.$$,
  $$You approach relationships practically and want a partner you can genuinely improve life with. You\'re helpful and attentive but can be distant. The work is emotional warmth, accepting human imperfection in your partner, and knowing that love isn\'t about optimizing someone.$$,
  $$You thrive in detailed work, problem-solving, health, and service fields. You\'re happiest improving things or fixing broken systems. Your challenge is overthinking and self-doubt—you can talk yourself out of everything. Your best work happens when you trust your expertise and act.$$,
  $$You need to develop self-compassion and acceptance of imperfection. Learning that mistakes are information, not personal failure. Your growth edge is trusting that your worth doesn\'t depend on productivity, and that rest is necessary, not laziness.$$,
  'ARRAY[$$Woolfolk - The Only Astrology Book You'\''ll Ever Need$$, $$Hand - Planets in Transit$$, $$Spiller - Astrology for the Soul$$]'
),
(
  'Libra',
  'Lib',
  '♎',
  'Air',
  'Cardinal',
  'Venus',
  'September 23 - October 22',
  $$You see all sides and want to find the elegant solution. You\'re drawn to beauty and fairness, and you\'re genuinely interested in other people\'s perspectives. You\'re the diplomat who can make anyone feel like they matter.$$,
  'Diplomacy, fairness, charm, aesthetic sense, social ease',
  'Indecisiveness, people-pleasing, superficiality, codependency, passivity',
  $$You show up as the balancer and the bridge-builder. Your life is about creating harmony, seeing multiple perspectives, building relationships. You\'re alive in partnerships and dialogue. The pattern is that avoiding conflict sometimes creates worse ones, and that true balance includes a strong stance.$$,
  $$You\'re romantic and genuinely interested in your partner. You want partnership that feels elegant and fair. The work is knowing your own needs, not disappearing into what your partner wants, and realizing that healthy relationship includes some roughness and disagreement.$$,
  $$You thrive in work involving people, aesthetics, diplomacy, or justice. You\'re excellent at seeing multiple angles and finding middle ground. Your challenge is decision-making and sometimes just picking a side. Your best work happens when you commit to a vision, not just considering all options.$$,
  $$You need to develop decisiveness and self-definition. Learning that being yourself isn\'t the same as being selfish, and that strong opinions aren\'t unloving. Your growth edge is discovering that clarity and boundaries actually strengthen relationships.$$,
  'ARRAY[$$Woolfolk - The Only Astrology Book You'\''ll Ever Need$$, $$Hand - Planets in Transit$$, $$Spiller - Astrology for the Soul$$]'
),
(
  'Scorpio',
  'Sco',
  '♏',
  'Water',
  'Fixed',
  'Pluto',
  'October 23 - November 21',
  $$You see beneath the surface and you don\'t forget. You\'re intensely loyal to people you trust, and you\'re willing to do deep work others avoid. Your power lies in your ability to transform yourself and situations.$$,
  'Intensity, loyalty, perceptiveness, resilience, resourcefulness',
  'Obsession, secretiveness, vindictiveness, jealousy, control',
  $$You show up as the transformer and the detective. Your life is about going deep, uncovering truth, and becoming more powerful through self-examination. You\'re drawn to intensity and authenticity. The pattern is knowing when depth becomes obsession, when trust is broken and can\'t be repaired, and that not everyone\'s ready for your level of honesty.$$,
  $$You love intensely and expect the same. You\'re all in or all out—there\'s no casual for you. The work is trusting enough to be vulnerable, managing jealousy and control, and recognizing that your partner\'s independence doesn\'t threaten your bond.$$,
  $$You thrive in work involving research, psychology, finance, healing, or anything requiring trust and discretion. You\'re comfortable with complexity and darkness others avoid. Your challenge is letting go—of grudges, of control, of needing to know everything. Your best work transforms not just situations but you.$$,
  $$You need to develop trust and the ability to let go. Learning that forgiveness is for you, not the person who hurt you, and that control is an illusion. Your growth edge is discovering that vulnerability isn\'t weakness, and that healing requires releasing your grip.$$,
  'ARRAY[$$Woolfolk - The Only Astrology Book You'\''ll Ever Need$$, $$Hand - Planets in Transit$$, $$Spiller - Astrology for the Soul$$]'
),
(
  'Sagittarius',
  'Sag',
  '♐',
  'Fire',
  'Mutable',
  'Jupiter',
  'November 22 - December 21',
  $$You see possibility everywhere and you\'re genuinely optimistic. You\'re curious about everything—other cultures, ideas, experiences—and you want to expand beyond what you already know. Your enthusiasm is contagious.$$,
  'Optimism, honesty, enthusiasm, generosity, independence',
  'Tactlessness, recklessness, overconfidence, impatience, escapism',
  $$You show up as the explorer and the truth-teller. Your life is about expanding your understanding, going further, discovering more. You\'re restless and need growth to feel alive. The pattern is that running toward new things is sometimes running from the hard work of real depth, and that your brutal honesty isn\'t always a gift.$$,
  $$You love freedom and authenticity in relationship. You\'re generous and genuinely interested in your partner\'s growth. The work is staying put and doing the unglamorous daily work of partnership, managing your wanderlust, and realizing that commitment isn\'t a cage.$$,
  $$You thrive in work involving travel, learning, philosophy, or expansion. You\'re bored by routine and need purpose that feels bigger than daily tasks. Your challenge is focus and follow-through. Your best work happens when you aim at a genuine target, not just run from boredom.$$,
  $$You need to develop focus and the ability to sit with difficulty. Learning that mastery requires staying with something long enough to get past the initial learning phase. Your growth edge is discovering that depth and commitment deepen freedom, not restrict it.$$,
  'ARRAY[$$Woolfolk - The Only Astrology Book You'\''ll Ever Need$$, $$Hand - Planets in Transit$$, $$Spiller - Astrology for the Soul$$]'
),
(
  'Capricorn',
  'Cap',
  '♑',
  'Earth',
  'Cardinal',
  'Saturn',
  'December 22 - January 19',
  $$You\'re serious about your ambitions and you have the patience to build toward them. You respect competence and hard work, and you\'re willing to do what it takes. People trust your judgment because you\'ve earned it.$$,
  'Discipline, responsibility, ambition, integrity, patience',
  'Coldness, rigidity, pessimism, workaholism, harshness',
  $$You show up as the builder with a long-term vision. Your life is about creating real achievement and status that means something to you. You\'re strategic and willing to do the unglamorous work. The pattern is knowing when discipline becomes joylessness, when fear drives your choices, and that the pinnacle feels empty without genuine values.$$,
  $$You\'re slow to commit but deeply loyal once you do. You need someone with ambition and integrity who respects your goals. The work is warmth, let people actually know you, and realizing that success without love is a hollow victory.$$,
  $$You thrive in work requiring leadership, strategy, and long-term vision. You\'re excellent at managing resources and building systems. Your challenge is flexibility and allowing enjoyment along the path. Your best work happens when ambition serves something you actually care about.$$,
  $$You need to develop warmth and the ability to enjoy the present. Learning that rest is productive, that fun matters, and that you\'re allowed to be imperfect. Your growth edge is discovering that the people you love care about you, not your accomplishments.$$,
  'ARRAY[$$Woolfolk - The Only Astrology Book You'\''ll Ever Need$$, $$Hand - Planets in Transit$$, $$Spiller - Astrology for the Soul$$]'
),
(
  'Aquarius',
  'Aqu',
  '♒',
  'Air',
  'Fixed',
  'Uranus',
  'January 20 - February 18',
  $$You see the future and you\'re already there thinking about it. You\'re idealistic about how things could be better, and you genuinely don\'t care what people think. Your independence is real, and you\'re loyal to people who share your vision.$$,
  'Innovation, idealism, independence, logic, humanitarian vision',
  'Detachment, rebellion for its own sake, emotional coldness, rigidity',
  $$You show up as the visionary and the revolutionary. Your life is about progress, changing systems, aligning with your authentic values. You\'re future-focused and sometimes impatient with people stuck in old ways. The pattern is that disconnection isn\'t the same as enlightenment, and that real change requires understanding current conditions, not just ideals.$$,
  $$You value intellectual matching and freedom. You\'re loyal to people who respect your independence and challenge you. The work is emotional presence, not just intellectual agreement, and recognizing that relationships require showing up, not just believing in the same future.$$,
  $$You thrive in work involving innovation, technology, social change, or anything breaking new ground. You\'re comfortable with unconventional approaches and systems-level thinking. Your challenge is not dismissing people who move slower than you. Your best work happens when you bridge visionary thinking with practical execution.$$,
  $$You need to develop emotional connection and the ability to meet people where they are. Learning that belonging doesn\'t mean conforming, and that vulnerability is strength. Your growth edge is discovering that real revolution happens through connection, not isolation.$$,
  'ARRAY[$$Woolfolk - The Only Astrology Book You'\''ll Ever Need$$, $$Hand - Planets in Transit$$, $$Spiller - Astrology for the Soul$$]'
),
(
  'Pisces',
  'Pis',
  '♓',
  'Water',
  'Mutable',
  'Neptune',
  'February 19 - March 20',
  $$You feel the world\'s emotional undercurrent and you move with it. You\'re intuitive and imaginative, and you\'re genuinely compassionate without judgment. You\'re the person people confide in because they sense you actually understand.$$,
  'Compassion, intuition, creativity, imagination, sensitivity',
  'Escapism, victim mentality, codependency, confusion, lack of boundaries',
  $$You show up as the mystic and the healer. Your life is about navigating invisible currents, creating meaning through art or spirituality, merging with something larger than yourself. You\'re porous to others\' emotions and energy. The pattern is knowing when empathy becomes enablement, when escapism prevents real living, and that you\'re a separate person with your own needs.$$,
  $$You love romantically and idealize your partner. You\'re deeply empathetic and willing to go the distance. The work is maintaining your own identity, not drowning in your partner\'s needs, and recognizing when someone is actually good for you versus just needing rescue.$$,
  $$You thrive in creative, spiritual, or helping work that uses your intuition. You\'re drawn to meaning and beauty. Your challenge is boundaries and follow-through—you can get lost in your own inner world. Your best work happens when you ground your visions in reality and protect your energy.$$,
  $$You need to develop strong boundaries and healthy skepticism. Learning that not every feeling is truth, and that protecting yourself isn\'t coldness. Your growth edge is discovering that you\'re a whole person separate from others, and that real help requires you to stay grounded.$$,
  'ARRAY[$$Woolfolk - The Only Astrology Book You'\''ll Ever Need$$, $$Hand - Planets in Transit$$, $$Spiller - Astrology for the Soul$$]'
);
