-- Taurus entries — planet-specific domains
DELETE FROM kb_planet_in_sign WHERE sign = 'Taurus';

INSERT INTO kb_planet_in_sign (planet, sign, summary, life_patterns, relationships, challenges, growth, book_references) VALUES

('Sun', 'Taurus',
 'Your core identity is built on stability, sensuality, and unwavering presence. You''re the solid ground others build on—reliable, grounded, and fundamentally self-assured.',
 'You move through life deliberately and steadily, building lasting foundations in everything you touch. Security isn''t optional; it''s the bedrock of who you are. You tend to stick with what works, refining rather than abandoning, and you have a natural magnetism that comes from genuine comfort in your own skin.',
 'You''re the loyal, steady partner who creates safety through consistency. In relationships, you''re sensual, affectionate, and fully present—you don''t do anything halfway. People feel genuinely valued by you, even if you express love through simple, physical presence rather than grand gestures.',
 'Your stubbornness can calcify into refusal to change, even when change serves you. Complacency can sneak in when you''re too content. You may resist growth because the new feels uncomfortable, losing sight of what you''re working toward.',
 'Practice flexibility within structure—learn that adaptation isn''t betrayal. Cultivate awareness of when you''re holding on for security versus genuine alignment. Your true power emerges when you ground change itself, becoming the steady force through transitions, not just the resistant one.',
 ARRAY['Woolfolk, The Only Astrology Book You''ll Ever Need', 'Hand, Planets in Transit']),

('Moon', 'Taurus',
 'Your emotional needs are simple and profound: safety, comfort, and physical reassurance. You process feelings through the body and the senses; you need to feel secure before you can feel content.',
 'You''re most emotionally stable when surrounded by tangible security—good food, cozy spaces, reliable people, and sensory beauty. You don''t swing rapidly through emotional states; instead, you settle into feelings and stay there until they naturally shift. Financial and physical stability directly impact your emotional well-being.',
 'You nurture through presence and touch—a meal, a shoulder to lean on, your steady calm when others are chaotic. You''re the emotional anchor in your relationships, offering genuine comfort precisely because you''ve grounded yourself first. You show love through reliability and sensory attentiveness.',
 'Your need for security can become overattachment to possessions, people, or habits. You may resist acknowledging uncomfortable emotions because acknowledging them disrupts your carefully crafted peace. Inflexibility in how you need to feel safe can trap you in situations that no longer serve.',
 'Learn that emotional growth sometimes requires loosening your grip on how things "should be." Building security through inner resources—self-soothing practices, self-trust—gives you freedom to adapt externally. Your steadiness becomes gift, not cage.',
 ARRAY['Woolfolk, The Only Astrology Book You''ll Ever Need', 'Hand, Planets in Transit']),

('Mercury', 'Taurus',
 'Your thinking style is deliberate, practical, and grounded in real-world utility. You speak slowly and with purpose; every word earned its place. You''re not interested in abstract theory without application.',
 'You gather information methodically, testing ideas against experience before accepting them. Your mind works at a steady pace—you''re not the quickest thinker, but you''re thorough and hard to rattle. You trust what you''ve learned through repetition and direct experience; hunches don''t move you without evidence.',
 'You communicate with calm directness; people trust your words because you don''t waste them. You''re patient with people''s questions and you explain things practically, grounding them in concrete examples. However, you can frustrate faster thinkers who interpret your pace as stubbornness rather than thoroughness.',
 'Your resistance to abstract thought limits you when you need to work with theoretical frameworks or rapid-fire idea exchanges. You can mistake your steady pace for competence and resist learning faster methods. Inflexibility in how you approach problems can lock you into outdated strategies.',
 'Intentionally stretch into conceptual thinking and let yourself explore ideas without immediate utility. Practice intellectual flexibility—rapid brainstorming without judgment. Your gift is translating ideas into workable systems; use that gift without gatekeeping what ideas deserve translation.',
 ARRAY['Woolfolk, The Only Astrology Book You''ll Ever Need', 'Hand, Planets in Transit']),

('Venus', 'Taurus',
 'Venus is HOME in Taurus—here she''s most powerful and natural. Your love style is sensual, devoted, and grounded in genuine feeling. You seek beauty in the real, the touchable, the lasting. This is domicile—you''re Venus at her most authentic.',
 'You attract through serene confidence and authentic presence rather than effort or performance. In love, you''re steady and loyal, building intimacy through consistency, touch, and shared comfort. You appreciate beauty but real beauty—a good meal, genuine warmth, natural grace. You''re drawn to stability in partnership and you build it through daily attentiveness.',
 'You''re the devoted partner who creates safe harbor through sensory care—good cooking, physical affection, genuine interest in your person''s comfort. You''re not flashy in love, but you''re dependable in a way that slowly becomes irreplaceable. People feel deeply valued in your presence because you''re fully there.',
 'You can become possessive, mistaking loyalty for ownership. Your resistance to change in relationships can trap both you and your person. Sensuality without connection becomes mere consumption; you must balance your appreciation for the physical with genuine emotional intimacy.',
 'Use your natural gifts to create not possession but genuine sanctuary. Let love evolve while you remain steady. Your greatest strength is showing people they''re worthy of consistent care—practice this without demand for return. Your Venus is richest when giving freely, not keeping score.',
 ARRAY['Woolfolk, The Only Astrology Book You''ll Ever Need', 'Hand, Planets in Transit']),

('Mars', 'Taurus',
 'Your drive is powerful but patient—like a bull, you''re slow to anger but devastating when provoked. You have tremendous stamina and determination, but you move at your own deliberate pace. Energy, sexuality, and ambition flow steadily, not explosively.',
 'You''re not impulsive; you build toward goals methodically, compounding effort into tangible results. Your sexuality is earthy and genuine, appreciating direct physical intimacy without games. In work and life, you''re reliable and consistent, showing up day after day—your persistence wears down obstacles. You don''t rush; you arrive.',
 'You approach conflict with surprising calm until you reach your limit, then you''re formidable. Sexually, you''re straightforward and sensual, comfortable in your body. In partnership, you''re physically affectionate and grounded, showing desire through presence and touch. You expect loyalty in return for your steady devotion.',
 'Your stubbornness can entrench you in situations you''re trying to change—inertia becomes immobilization. You can be sexually possessive or struggle with someone who needs more spontaneity. Slowness to anger means you hold resentment for a very long time before it explodes destructively.',
 'Learn to channel impatience into productive action; sometimes faster movement serves your goals. Practice expressing small frustrations before they calcify. Your stamina is legendary—use it to adapt and evolve, not just to endure. Sexuality deepens when you remain vulnerable, not just present.',
 ARRAY['Woolfolk, The Only Astrology Book You''ll Ever Need', 'Hand, Planets in Transit']),

('Jupiter', 'Taurus',
 'Your luck comes through patience, persistence, and trusting the slow accumulation of resources. You have an intuitive understanding of value and what endures. Expansion for you isn''t rapid growth; it''s deep roots and compound returns.',
 'You''re blessed by reliable growth when you tend to what you''ve planted. Financial abundance often comes through steady work rather than risk or luck; you''re naturally drawn to building security methodically. Your philosophy is grounded and pragmatic—you trust what works and what you can verify. Long-term thinking is your superpower.',
 'You bring stability to groups and enterprises through calm, reliable presence. People trust your judgment because you''re not reckless. In sharing knowledge, you''re generous but grounded, teaching through real-world example rather than ideology. Your optimism is quiet and steady, never naive.',
 'Your conservatism can limit your upside—you may miss growth opportunities because they feel risky. Over-caution can be disguised fear; you may conflate security with stagnation. Your faith in slow accumulation can blind you to moments when bolder action would serve better.',
 'Consciously stretch into calculated risks that align with your long-term vision. Trust that abundance has many forms—growth doesn''t require recklessness. Your true gift is seeing what endures; use that sight to navigate bigger opportunities with confidence, not paralysis.',
 ARRAY['Woolfolk, The Only Astrology Book You''ll Ever Need', 'Hand, Planets in Transit']),

('Saturn', 'Taurus',
 'Your life lessons revolve around building real security through discipline, responsibility, and genuine mastery. Saturn here teaches through solid testing; what you build lasts because you''ve done it right. You learn that true comfort comes from doing the work.',
 'You encounter challenges that demand you build something real—relationships, skills, finances—with no shortcuts. Progress feels glacially slow; you may work for years before seeing results, then suddenly a structure solidifies. Your tests arrive through responsibility: maintaining security, keeping promises, disciplining yourself when it''s easier not to.',
 'You''re the person people lean on because you''ve proven yourself worthy of trust. Relationships deepen through demonstrated consistency over time. You show your love through reliability, follow-through, and willingness to weather difficulties. However, others may resent your slowness or perceived coldness.',
 'Your deepest fear is losing security or being unable to provide it. This fear can drive over-work, hoarding, or relationship stagnation if you''re clinging to stability that''s calcified into dead weight. You may have been taught that love = obligation, trapping you in situations that don''t serve.',
 'Practice distinguishing between healthy responsibility and self-punishment. True security comes from competence, not control. Your greatest growth emerges when you can release old structures that no longer serve—this requires trust that you''ve built something solid enough to weather change.',
 ARRAY['Woolfolk, The Only Astrology Book You''ll Ever Need', 'Hand, Planets in Transit']),

('Uranus', 'Taurus',
 'Your generational rebellion is quiet but unmovable—you''re the fixed revolutionary who changes the world through stubborn insistence on a better way. While your peers resist fiercely, you calmly redirect toward new values. Change for you is about redefining security itself.',
 'Your generation rewires what "stability" means, often through circumstance that forces obsolescence. You''re immune to peer pressure because you''ve already decided what matters; sudden upheaval in your world—financial, relational, structural—often becomes the catalyst for genuine liberation. You''re surprisingly unbothered by disruption when it aligns with your values.',
 'You bring steady innovation to relationships and community, redefining tradition without rejecting it. Your rebellions are quiet and proven: "Here''s a better way." You''re loyal to people but not to outdated systems, and this clarity is deeply attractive. You inspire others through example, not preaching.',
 'Your resistance to change can mask as progressive belief while you cling to comfort. You may be paralyzed when sudden shifts arrive—your groundedness can become rigidity when the ground itself shifts. Stubbornness about "how things should work" can prevent you from adapting quickly enough.',
 'Cultivate flexibility within your values; staying true to yourself doesn''t require staying still. Embrace the sudden shifts your generation experiences as invitations to redefine, not destroy. Your power emerges when you ground change itself, becoming the steady force that stabilizes the new.',
 ARRAY['Woolfolk, The Only Astrology Book You''ll Ever Need', 'Hand, Planets in Transit']),

('Neptune', 'Taurus',
 'Your generational dreams are grounded and material—you envision a world where resources are shared, beauty is accessible, and the sensual needs of all people are honored. Neptune in Taurus dreams practically, but the dream is vast.',
 'Your generation''s spirituality is embodied and earth-based, less interested in abstract transcendence and more in the sacred within the material. You may encounter collective illusions about money, possessions, and security; your job is seeing through them. Escapism through consumption or substance is a real shadow for your generation.',
 'You inspire others by grounding spiritual ideals in practical reality—showing how the sacred lives in the everyday, the sensual, the simple. Your vision of a better world includes good food, accessible beauty, and genuine comfort for all. You''re the bridge between materialism and spirituality.',
 'Your generation can become collectively confused about values—what''s real versus imagined, what creates genuine security versus false comfort. You may struggle to distinguish spiritual practice from escapism, or use materialism to avoid spiritual growth. Addiction and illusion around abundance can affect your generation profoundly.',
 'Ground your spiritual vision in real action and real systems change. Your idealism is your gift; protect it by staying grounded in material reality. Help your generation distinguish between nourishing sensuality and numbing escapism. The sacred and the sensual are not in opposition—this is your teaching.',
 ARRAY['Woolfolk, The Only Astrology Book You''ll Ever Need', 'Hand, Planets in Transit']),

('Pluto', 'Taurus',
 'Your generational transformation is about the redefinition of value itself. Pluto in Taurus is reshaping how humanity relates to money, possessions, resources, security, and the body. What you rebuild will endure; what you deconstruct was already dying.',
 'Your generation encounters total upheaval in systems of resource distribution, property, and material security. What feels permanent—land, money, currency, economic systems—is revealed as fragile and malleable. You''re witnessing and facilitating the death of old resource models and the birth of new ones. This is generational trauma and generational medicine simultaneously.',
 'You bring quiet power to conversations about justice, resource equity, and true value. You''re part of a generation learning to hold the paradox: you need security, yet all forms of security are being revealed as impermanent. Your resilience comes from redefining security inwardly, not externally.',
 'Your generation faces collective fear about survival and security; this can activate scarcity consciousness, hoarding, or desperation. You may swing between fatalism about material collapse and denial that change is coming. The temptation to cling to old systems (or reject all systems) is powerful.',
 'Your role is helping rebuild security on new foundations—not economic, but spiritual and relational. Trust that destruction precedes recreation; what emerges from Pluto''s passage will be genuine and rooted. Your generation is learning that true wealth is resilience, community, and connection—not accumulation.',
 ARRAY['Woolfolk, The Only Astrology Book You''ll Ever Need', 'Hand, Planets in Transit']);
