-- Updated Sagittarius entries — planet-specific
DELETE FROM kb_planet_in_sign WHERE sign = 'Sagittarius';

INSERT INTO kb_planet_in_sign (planet, sign, summary, life_patterns, relationships, challenges, growth, book_references) VALUES

('Sun', 'Sagittarius',
 'Your core identity is built on expansion and meaning. You need to believe in something — a philosophy, a vision, a purpose. You''re not just living; you''re on a quest. Your sense of self comes alive when you''re learning, exploring, or sharing what you know.',
 'You''re the person with a plan, a trip, or a theory about everything. You make big moves and figure out the details later. You speak with conviction and inspire people by simply being enthusiastic. You change directions often because new horizons keep calling. People either love your energy or find it exhausting.',
 'You need a partner who grows with you. Stagnation in a relationship is your dealbreaker. You''re honest — sometimes painfully so — because you respect your partners enough to tell them the truth. You need intellectual stimulation as much as physical attraction.',
 'Your optimism can become denial. You over-promise and under-deliver because you genuinely believe you can do everything. Your directness crosses into cruelty when you''re not paying attention to how your words land. You avoid emotional depth by staying busy with the next thing.',
 'Slow down long enough to let wisdom catch up with experience. Your vision is powerful — pair it with follow-through. Honesty without compassion isn''t honesty, it''s just pain. The deepest adventure is staying present with what''s already in front of you.',
 ARRAY['Woolfolk, The Only Astrology Book You''ll Ever Need', 'Hand, Planets in Transit']),

('Moon', 'Sagittarius',
 'Your emotional needs are tied to freedom, meaning, and forward motion. You process feelings by moving — physically, mentally, or both. You don''t wallow; you reframe, find the lesson, and keep going. Emotional safety for you means knowing you''re not trapped.',
 'You bounce back from setbacks faster than anyone. Your first response to bad news is "okay, what''s next?" You need variety in your emotional life — same routine, same conversations, same dynamics make you feel suffocated. You laugh easily and use humor to process heavy emotions.',
 'You''re warm and generous with partners but need space to breathe. You don''t want to be someone''s whole world, and you don''t want them to be yours. You show love through shared adventures, honest conversation, and believing in your partner''s potential.',
 'Your emotional optimism can be avoidance in disguise. You skip past grief, anger, and pain because sitting in them feels like being stuck. Partners may feel emotionally neglected because you move on before they''ve finished processing. Your need for freedom can look like emotional unavailability.',
 'Not every feeling needs a lesson or a silver lining. Sometimes things just hurt, and the growth is in letting yourself feel that fully before you move on. Your emotional resilience is a genuine gift — just make sure it''s resilience and not avoidance.',
 ARRAY['Woolfolk, The Only Astrology Book You''ll Ever Need', 'Hand, Planets in Transit']),

('Mercury', 'Sagittarius',
 'Your mind thinks in big pictures, philosophies, and connections between ideas. You''re not interested in what happened — you''re interested in what it means. Your thinking is visionary and expansive, but precision isn''t your thing.',
 'You learn through conversation and debate, not quiet study. You have opinions about everything and share them freely. You connect ideas across fields — history to psychology to spirituality to pop culture — in ways that make people say "I never thought of it that way." You read widely but rarely finish books because the main idea was on page 30.',
 'You need a partner who can keep up intellectually. You communicate with enthusiasm and directness. You say what you mean and expect the same back. Passive aggression baffles and irritates you.',
 'You can be preachy and talk over people. Your big-picture thinking misses crucial details that derail your plans. You confuse having an opinion with being right. Your bluntness can be cruel when aimed at someone''s vulnerability.',
 'Listen as enthusiastically as you speak. Details matter — they''re not beneath you. Having a strong opinion and being willing to change it isn''t weakness, it''s intelligence. Your mind is built for connecting dots — make sure some of those connections include other people''s perspectives.',
 ARRAY['Woolfolk, The Only Astrology Book You''ll Ever Need', 'Hand, Planets in Transit']),

('Venus', 'Sagittarius',
 'You love with your whole spirit but you need room to roam. Your idea of romance is a philosophical conversation at midnight, a spontaneous road trip, or someone who makes you see the world differently. You fall for minds and adventurous spirits, not just faces.',
 'You''re attracted to people from different backgrounds, cultures, or belief systems. You flirt through ideas and humor. You''re generous with affection but not possessive about it. Your aesthetic sense is eclectic and globally influenced. You value experiences over things.',
 'You need a partner who has their own life, interests, and ambitions. You''re loving but you need to be able to miss someone to appreciate them. You show love by expanding your partner''s world — introducing them to new ideas, places, and people.',
 'Your need for variety can look like inability to commit. You may leave relationships when they get routine rather than doing the work to deepen them. You can be careless with people''s hearts because you assume everyone bounces back as fast as you do.',
 'The deepest love isn''t always the most exciting — sometimes it''s the most steady. Real freedom is choosing to stay and build something, not always leaving to find something new. Your capacity for joy in love is extraordinary when you add patience to it.',
 ARRAY['Woolfolk, The Only Astrology Book You''ll Ever Need', 'Hand, Planets in Transit']),

('Mars', 'Sagittarius',
 'Your drive is expansive, enthusiastic, and aimed at whatever''s over the next hill. You take action through optimism — you move toward things, not against them. Your energy is physical, restless, and needs an outlet that involves exploration or challenge.',
 'You''re always training for something, planning a trip, or starting a project that excites you. Your energy comes in bursts of enthusiasm. You''re competitive but in a fun way — you want to play, not destroy. You take physical risks that would terrify more cautious signs. You say yes before you think about logistics.',
 'You''re playful, direct, and sexually adventurous. You don''t play games — you''d rather be honest about what you want. You''re not naturally possessive and you give partners a lot of freedom because you need the same. Your anger is hot but burns out fast — you don''t hold grudges.',
 'Your enthusiasm for new things means you often don''t finish what you started. Your physical risk-taking can be reckless. You may avoid the hard, boring middle of projects and relationships because it doesn''t match the excitement of the beginning. Your directness in conflict can be tactless.',
 'Your energy is magnetic and inspiring — channel it into goals that matter enough to see through to the end. The middle of things is where the real adventure happens, not just the beginning. Your honesty in relationships is refreshing; just remember to pair it with timing and compassion.',
 ARRAY['Woolfolk, The Only Astrology Book You''ll Ever Need', 'Hand, Planets in Transit']),

('Jupiter', 'Sagittarius',
 'Jupiter rules Sagittarius, so this is expansion at its most natural. You grow through faith, adventure, and the pursuit of meaning. Lucky breaks come to you more often than average — not because of magic, but because your optimism puts you in the right place at the right time.',
 'Opportunities seem to find you. You''re the person who gets the job through a random conversation, meets someone life-changing on a plane, or stumbles into exactly the right situation. You believe things will work out, and they usually do. Travel, education, and philosophy all feed your growth.',
 'You bring abundance and joy to relationships. Partners grow around you because your optimism is contagious. You believe in people''s potential — sometimes more than they believe in themselves.',
 'Your luck can make you complacent. You don''t always prepare because you assume things will work out. Your optimism can deny real problems. You over-commit because saying yes feels natural and saying no feels limiting.',
 'Your natural abundance is real — honor it by being a good steward of your luck. Help others expand. Believe in people but don''t carry them. Your faith in life is your greatest asset when paired with discipline.',
 ARRAY['Woolfolk, The Only Astrology Book You''ll Ever Need', 'Hand, Planets in Transit']),

('Saturn', 'Sagittarius',
 'Your biggest life lessons come through belief, meaning, and truth. You may have struggled with faith — either too much rigidity or too much skepticism. Your discipline is applied to your worldview: you need a philosophy that actually holds up under pressure.',
 'You take education, travel, and philosophy seriously. You don''t just collect experiences — you integrate them into a coherent understanding of life. You may have felt restricted around religion or ideology growing up. Your sense of meaning was earned, not given.',
 'You''re serious about shared values in relationships. You need a partner whose worldview you respect. Intellectual compatibility isn''t optional — it''s foundational.',
 'Your need for meaningful structures can become dogmatic. You may judge others'' beliefs as shallow. Your seriousness can dampen the very adventure and spontaneity that Sagittarius craves.',
 'The lesson is building a belief system that''s both structured and flexible. Wisdom isn''t certainty — it''s the ability to hold questions. Your disciplined approach to meaning is powerful when it stays curious.',
 ARRAY['Woolfolk, The Only Astrology Book You''ll Ever Need', 'Hand, Planets in Transit']),

('Uranus', 'Sagittarius',
 'Your generation revolutionizes belief systems, education, and how the world shares ideas. You came of age during the expansion of global connectivity. Individually, your rebellion is philosophical — you reject inherited beliefs in favor of your own discovered truth.',
 'You''re drawn to unconventional wisdom traditions, alternative education, or technology that connects cultures. You question dogma instinctively. Your sense of freedom is tied to ideological independence.',
 'You need partners who respect your philosophical independence. You''re attracted to people who think differently than you.',
 'Your rejection of tradition can become its own dogma. Not every institution is corrupt and not every convention is wrong.',
 'Use your visionary thinking to build bridges between old wisdom and new understanding.',
 ARRAY['Woolfolk, The Only Astrology Book You''ll Ever Need', 'Hand, Planets in Transit']),

('Neptune', 'Sagittarius',
 'Your generation dreams in big, universal terms — world peace, spiritual unity, dissolving borders between belief systems. Individually, your spiritual life is expansive and syncretistic. You pull from many traditions without loyalty to any single one.',
 'You''re drawn to visionary art, world music, and spiritual practices from diverse traditions. Your imagination is epic in scope. You may idealize other cultures or spiritual paths.',
 'You bring a sense of spiritual adventure to relationships. You''re attracted to partners who expand your vision of what''s possible.',
 'Your idealism about the world can become naive. You may avoid the practical work of change in favor of dreaming about it.',
 'Ground your vision in action. Your dreams for humanity are beautiful — pair them with concrete steps.',
 ARRAY['Woolfolk, The Only Astrology Book You''ll Ever Need', 'Hand, Planets in Transit']),

('Pluto', 'Sagittarius',
 'Your generation transforms belief systems, institutions of higher learning, and global truth-telling. You grew up watching the internet democratize information. Individually, your power comes from your conviction and your willingness to challenge what''s accepted as true.',
 'You''re drawn to exposing hypocrisy in religion, politics, and education. You take truth personally. You may have experienced a crisis of faith that fundamentally changed your worldview.',
 'You bring transformative honesty to relationships. You push partners to examine their beliefs and grow.',
 'Your intensity around truth can become self-righteous. You may use "honesty" as a weapon.',
 'Your generation''s gift is demanding authenticity from the world''s institutions. Use that power to build better systems, not just to tear down the old ones.',
 ARRAY['Woolfolk, The Only Astrology Book You''ll Ever Need', 'Hand, Planets in Transit']);
