-- Seed data for kb_houses table
-- Inserts all 12 astrological houses

INSERT INTO kb_houses (number, name, traditional_name, summary, life_area, keywords, question, sign_association, planet_association) VALUES
(1, 'First House', 'House of Self',
$$You are the lens through which you see the world. This house governs your appearance, your first impression, and the core identity you project outward. It's your personal brand—how people know you before they know anything else about you.$$,
'Identity, appearance, personality, self-perception, first impressions',
'self, identity, appearance, personality, presence, beginnings, how you are perceived, personal brand',
'Who am I and how do I show up in the world?',
'Aries',
'Mars'),

(2, 'Second House', 'House of Value',
$$Your relationship with resources—money, possessions, and what you value—lives here. This house isn't just about financial gain; it's about what makes you feel secure, what you're willing to invest in, and how you exchange energy with the world.$$,
'Money, possessions, income, self-worth, resources, values, security',
'wealth, money, income, possessions, resources, self-worth, earning potential, material security, values',
'What do I value, and how do I build security in my life?',
'Taurus',
'Venus'),

(3, 'Third House', 'House of Communication',
$$Words are your tools here—how you think, speak, learn, and connect with your immediate world. This house governs your communication style, your curiosity, and your relationships with siblings and neighbors; it's the domain of early learning and how you gather information.$$,
'Communication, learning, siblings, neighbors, short travels, thinking style, writing',
'communication, learning, thinking, speaking, writing, siblings, neighbors, curiosity, short journeys, mental agility',
'How do I learn, communicate, and exchange ideas with others?',
'Gemini',
'Mercury'),

(4, 'Fourth House', 'House of Home',
$$This is your foundation—your family, your home, and your roots. It governs where you come from and where you feel you belong, the emotional security of family bonds, and your relationship with your past. It's the anchor that holds you.$$,
'Family, home, roots, childhood, real estate, endings, private life, parents',
'home, family, roots, childhood, mother, private life, foundation, ancestry, real estate, security',
'Where do I come from, and what serves as my foundation?',
'Cancer',
'Moon'),

(5, 'Fifth House', 'House of Pleasure',
$$Your joy, your creativity, and your self-expression shine here. This house governs romance, creative pursuits, children, and the things you do simply because they bring you alive. It's where you play, create, and fall in love.$$,
'Creativity, romance, children, pleasure, self-expression, hobbies, joy, play',
'creativity, romance, children, joy, pleasure, self-expression, hobbies, talent, entertainment, love affairs',
'What brings me joy, and how do I express my creative self?',
'Leo',
'Sun'),

(6, 'Sixth House', 'House of Health',
$$Daily life and how you serve—your work, your health habits, and your service to others. This house is about the routines that sustain you, your body's signals, and how you show up consistently in your everyday responsibilities.$$,
'Work, health, daily routines, service, habits, practical skills, employees, healing',
'work, health, routines, habits, service, practical skills, employment, healing, daily life, wellness',
'How do I cultivate health and contribute meaningful service?',
'Virgo',
'Mercury'),

(7, 'Seventh House', 'House of Partnership',
$$Relationships are central here—marriage, business partnerships, and all one-on-one connections. This house shows you what you seek in others and reveals the partnerships that shape your life. It's about meeting your mirror.$$,
'Relationships, marriage, partnerships, contracts, open enemies, commitment, others',
'partnerships, marriage, relationships, contracts, commitment, others, marriage partners, balance, enemies',
'Who am I in relationship, and what partnerships reflect my growth?',
'Libra',
'Venus'),

(8, 'Eighth House', 'House of Transformation',
$$Depth, power, and the invisible exchanges between people live here. This house governs shared resources, intimacy, inheritance, and transformation. It's about what you merge with, what you inherit from others, and the profound changes that remake you.$$,
'Transformation, intimacy, shared resources, death, inheritance, psychology, power, sexuality',
'transformation, intimacy, shared resources, inheritance, power dynamics, sexuality, psychology, deep change, taboos',
'What must I transform, and how do I access my deepest power?',
'Scorpio',
'Mars/Pluto'),

(9, 'Ninth House', 'House of Philosophy',
$$Expansion, higher learning, and your search for meaning unfold here. This house governs higher education, travel, philosophy, spirituality, and your worldview. It's about seeing the bigger picture and growing beyond your current boundaries.$$,
'Philosophy, higher learning, travel, spirituality, publishing, law, meaning, expansion',
'philosophy, spirituality, higher learning, travel, meaning, beliefs, publishing, law, expansion, wisdom',
'What is my philosophy, and how do I expand my understanding?',
'Sagittarius',
'Jupiter'),

(10, 'Tenth House', 'House of Career',
$$Your place in the world—career, reputation, and long-term achievement. This house shows what you're called to do and how you're perceived in your public life. It's your legacy and the mark you leave.$$,
'Career, public image, ambition, reputation, authority, long-term goals, achievement, status',
'career, ambition, public image, reputation, authority, achievement, status, legacy, long-term goals, calling',
'What is my calling, and what legacy do I build?',
'Capricorn',
'Saturn'),

(11, 'Eleventh House', 'House of Community',
$$Your people and your purpose within a larger community. This house governs friendships, groups, hopes, and aspirations. It shows how you contribute to something bigger than yourself and the community that sustains you.$$,
'Friendships, groups, community, hopes, dreams, humanitarian causes, technology, networks',
'friendships, groups, community, hopes, aspirations, networks, humanitarian causes, technology, social movements',
'How do I contribute to my community and connect with my people?',
'Aquarius',
'Saturn/Uranus'),

(12, 'Twelfth House', 'House of the Unconscious',
$$The hidden depths of your psyche—the dreams, the fears, the gifts waiting to be discovered. This house governs the unconscious mind, spirituality, retreats, and the dissolution of boundaries. It's where you process and transcend.$$,
'Unconscious mind, spirituality, retreat, solitude, karmic lessons, hidden enemies, surrender, healing',
'unconscious, spirituality, dreams, karmic patterns, hidden truth, retreat, solitude, transcendence, healing, surrender',
'What lies beneath, and how do I access my deepest wisdom?',
'Pisces',
'Jupiter/Neptune');
