-- Updated Cancer entries — planet-specific
DELETE FROM kb_planet_in_sign WHERE sign = 'Cancer';

INSERT INTO kb_planet_in_sign (planet, sign, summary, life_patterns, relationships, challenges, growth, book_references) VALUES

('Sun', 'Cancer',
 'Your core identity is rooted in belonging, protection, and emotional authenticity. You''re here to lead through feeling, not force—a guardian of trust and intimacy.',
 'You build your sense of self through family bonds, emotional security, and creating safe spaces for others. Your ego thrives when you''re needed, protected in return, and emotionally validated by your inner circle. Home—whether physical, emotional, or spiritual—is your anchor.',
 'You connect deeply with people who honor your sensitivity and reciprocate loyalty. You''re the one people turn to when they need comfort, but you risk overgiving if you don''t set boundaries. Your relationships thrive when both parties feel genuinely safe.',
 'Your identity can become too enmeshed with family or past hurts, making it hard to step into independent self-expression. You may retreat inward when vulnerable, or become defensive when your loyalty isn''t returned. Learning to separate self-worth from how much you''re needed is key.',
 'Embrace your emotional depth as a strength, not a weakness. Let your identity evolve beyond caretaking into authentic self-nurturing. Lead others through genuine presence and emotional wisdom, not obligation.',
 ARRAY['Woolfolk, The Only Astrology Book You''ll Ever Need', 'Hand, Planets in Transit', 'Parker, The Inner Sky']),

('Moon', 'Cancer',
 'This is the Moon''s domicile—your emotional core is at home here. You feel everything deeply, respond instinctively, and lead with heart. This is the most naturally emotionally fluent placement in the zodiac.',
 'Your emotional needs are straightforward: safety, belonging, and unconditional presence. You process feelings through nurturing, reminiscing, and creating emotional intimacy. Your moods shift like tides, but your loyalty is unwavering. You trust your gut and intuition implicitly.',
 'You need partners who understand that emotional closeness is not clingy—it''s essential. You offer profound emotional attunement and rarely judge others'' feelings. In family and close bonds, you''re the one holding the emotional thread.',
 'Your sensitivity can become overwhelm or anxiety if you''re absorbing others'' emotions without protection. You may struggle to voice needs directly, instead withdrawing or using guilt. Mood fluctuations can feel confusing to those around you if you don''t explain your inner weather.',
 'Your emotional intelligence is a gift—trust it fully. Learn to distinguish between your feelings and others''. Create rituals that honor your emotional nature without drowning in it. Your gut never lies; your overthinking mind sometimes does.',
 ARRAY['Woolfolk, The Only Astrology Book You''ll Ever Need', 'Hand, Planets in Transit', 'Forrest, The Twelve Houses']),

('Mercury', 'Cancer',
 'Your mind operates through feeling, memory, and emotional association. You think in metaphors, stories, and personal connections—logic filtered through the heart.',
 'You communicate best in intimate settings where you can be heard and understood, not debated. Your thinking style is nonlinear; you hop between past, present, and intuition. You''re brilliant at reading subtext and sensing what people don''t say aloud. Writing, storytelling, and teaching through emotional examples are your gifts.',
 'You listen deeply and remember everything people tell you—especially their feelings and needs. You''re protective of others'' vulnerabilities and rarely weaponize private information. Conversations with you are safe spaces. Your mind is a library of emotional wisdom.',
 'You may struggle with abstract thinking or pure logic divorced from feeling. Public speaking and high-stakes presentations can feel exposing. You''re prone to overthinking, replaying conversations, and spiraling into worry. Others may dismiss your thinking as too emotional.',
 'Strengthen your thinking by balancing heart and head; emotional intelligence IS valid logic. Practice sharing your thoughts in group settings without fear of rejection. Your ability to weave feeling into communication makes you a powerful writer and counselor—lean into it.',
 ARRAY['Woolfolk, The Only Astrology Book You''ll Ever Need', 'Hand, Planets in Transit', 'Carter, An Encyclopedia of Psychological Astrology']),

('Venus', 'Cancer',
 'You love to bond, commit, and create emotional sanctuary. Your attraction runs deep through trust and shared history. Beauty, to you, is intimacy and belonging—not superficial polish.',
 'You take time to warm to people romantically, but once committed, you''re devoted and protective. You show love through caregiving, remembering details, and creating cozy shared spaces. You''re loyal to a fault and expect reciprocal investment. Your aesthetic is personal, sentimental, and home-centered.',
 'You need reassurance that you''re valued and that the bond is safe. You''re affectionate, tender, and generous with those you trust. You build intimacy through vulnerability and shared history. A partner who feels like family—or becomes one—is your ideal.',
 'You can cling to relationships past their expiration date, fearing loss more than toxicity. Jealousy and possessiveness may arise if you feel insecure. You might confuse caretaking with love, or expect others to need you the way you need emotional connection. Codependency is your shadow.',
 'Love is not about keeping someone; it''s about allowing them autonomy while staying close. Cultivate self-love through nourishing yourself, not just others. Seek partners who choose you freely, not ones you''ve convinced to stay. Your worth isn''t measured by how much you''re needed.',
 ARRAY['Woolfolk, The Only Astrology Book You''ll Ever Need', 'Hand, Planets in Transit', 'Forrest, The Inner Sky']),

('Mars', 'Cancer',
 'Mars in its fall in Cancer: your drive is protective, not aggressive. You fight for family, security, and emotional safety—not dominance. Your anger is slow-burning and devastating when finally unleashed.',
 'You''re uncomfortable with direct confrontation or raw competition. Your energy deploys to defend loved ones, establish boundaries, or pursue security. You''re capable of fierce action, but only when emotionally invested. Your sexuality is tender and intimate, needing emotional connection first.',
 'You''re a protective partner who stands beside people in crisis. You''re not interested in casual conquest or shallow victories. You prefer slow-burn passion to instant chemistry. Your loyalty in battle or hardship is unshakeable.',
 'Mars in Cancer struggles with assertiveness; you may suppress anger until you''re resentful. Passive-aggression and guilt-tripping can become your weapons. Your drive can be too focused on security, leading to stagnation. Others may not see you as powerful or bold.',
 'Reclaim your Mars by learning that protecting yourself is as valid as protecting others. Channel anger into standing your ground firmly but kindly. Your capacity to fight for what matters—when you access it—is formidable. Aggression without empathy isn''t strength; what you offer is rare.',
 ARRAY['Woolfolk, The Only Astrology Book You''ll Ever Need', 'Hand, Planets in Transit', 'Carter, An Encyclopedia of Psychological Astrology']),

('Jupiter', 'Cancer',
 'Jupiter exalted in Cancer: you''re blessed with emotional wisdom, inner abundance, and the ability to heal. Your luck flows through generosity, family loyalty, and trusting your intuition.',
 'You naturally attract opportunities through warmth and genuine care. Your growth happens through deepening roots, creating family (blood or chosen), and opening your heart. You''re gifted at sensing others'' needs before they voice them. Expansion for you means emotional maturity, not empire-building.',
 'People feel safer, more whole, and more nurtured in your presence. You''re a natural counselor, healer, or spiritual guide. Your abundance mindset is grounded in trust that you''re cared for. Others'' generosity flows back to you because you model it first.',
 'Your optimism can mask real pain or needs—yours or others''. Jupiter in Cancer can lead to overgiving until you''re depleted. You may struggle to say no or set limits, believing abundance means unlimited availability. Overindulgence in comfort (food, rest, retreat) is possible.',
 'Your emotional generosity is genuine wealth—guard it. Learn to receive as openly as you give. Let yourself ask for help and believe people will show up. Your faith in others'' goodness is right, but it doesn''t obligate you to sacrifice yourself. Expand through self-care, not just caretaking.',
 ARRAY['Woolfolk, The Only Astrology Book You''ll Ever Need', 'Hand, Planets in Transit', 'Forrest, The Only Astrology Book You''ll Ever Need']),

('Saturn', 'Cancer',
 'Saturn in detriment in Cancer: your life lessons involve learning to hold boundaries while staying open, and managing fear without building walls. Responsibility feels heavy when emotional.',
 'You carry anxiety about security—financial, emotional, familial. Your growth unfolds through facing abandonment fears and building solid foundations. You''re deeply responsible for family, sometimes to the point of burden. Time teaches you that you can''t protect everyone, and that''s okay.',
 'You''re a loyal, consistent presence—slow to trust but eternally dependable once you do. Others rely on your stability and quiet strength. You honor commitments and follow through, especially to family. Your restraint and caution are assets in crisis.',
 'Saturn in Cancer crystallizes around fear: fear of loss, rejection, poverty, or emotional pain. You may become overly cautious, withholding love to avoid hurt. Guilt and self-criticism run deep. Your responsibility can become a prison, and you may resent the weight you''ve taken on.',
 'Face your fears directly; they''re usually less catastrophic than you imagine. Let others carry their own emotional weight. Build security through real assets and emotional resilience, not control. Saturn''s gift here is teaching you that you''re stronger than you think and more worthy of care than you believe.',
 ARRAY['Woolfolk, The Only Astrology Book You''ll Ever Need', 'Hand, Planets in Transit', 'Forrest, The Inner Sky']),

('Uranus', 'Cancer',
 'Your generation rebels against rigid family structures and outdated notions of home, belonging, and emotional expression. You''re here to revolutionize what safety and nurturing look like.',
 'Your generation pioneered new family models, emotional honesty, and breaking silence around trauma. You felt called to question ''how things are done'' in households and relationships. Your generation values authenticity in emotional expression over social propriety. Innovation in caregiving, therapy, and community support bears your fingerprint.',
 'Your generation creates chosen families and reimagines belonging. You''re more likely to form bonds based on shared values than bloodline alone. You challenge others to be more emotionally honest and less guarded. Your generational impact is helping people feel safe being their true selves.',
 'Your generation sometimes over-corrected, rejecting tradition without wisdom. Emotional instability can mask as enlightenment. You may resist commitment or intimacy, fearing entrapment. Alienation from biological family can leave you without grounding.',
 'Blend innovation with the wisdom of tradition. Not all old ways are wrong; some are grounded and trustworthy. Let yourself need people and places while staying true to your vision. Your generation''s gift is showing the world that real safety allows freedom, not control.',
 ARRAY['Woolfolk, The Only Astrology Book You''ll Ever Need', 'Hand, Planets in Transit', 'Forrest, The Twelve Houses']),

('Neptune', 'Cancer',
 'Your generation dreams of compassion, healing, and spiritual home. You''re dissolving boundaries between self and other, seeking unconditional love and mystical belonging.',
 'Your generation is haunted by longing—for safety that feels absolute, for a place to truly belong, for love without fear. You''re sensitive to collective suffering and drawn to healing work. Your spiritual path is often rooted in feeling, intuition, and ancestral wisdom. Escapism through comfort or substances is a shadow risk.',
 'Your generation is empathetic to a degree that can blur self-boundaries. You feel the collective emotional pain acutely. Your spiritual practices emphasize connection, vulnerability, and the sacred in everyday life. You''re drawn to healing modalities—therapy, energy work, shamanic practice.',
 'Your generation can be overly idealistic about family and love, setting up disappointment. Escapism through food, sleep, or substances can be a real issue. You may struggle to discern your feelings from others'' or the collective. Victimhood and spiritual bypassing are shadows to watch.',
 'Ground your spirituality in real practice and real boundaries. Your intuition is valuable, but verify it with reality. Healing work is noble, but not if it erases your own needs. Your generation''s longing points to something real—find it through grounded presence, not fantasy. Ancestor work and family healing are your natural medicine.',
 ARRAY['Woolfolk, The Only Astrology Book You''ll Ever Need', 'Hand, Planets in Transit', 'Forrest, The Twelve Houses']),

('Pluto', 'Cancer',
 'Your generation is transforming the deepest structures of family, belonging, trauma, and emotional honesty. You''re dissolving what was hidden, reclaiming power in vulnerability.',
 'Your generation inherited family secrets, ancestral trauma, and unspoken pain. You''re compelled to excavate, expose, and transform these patterns. Power dynamics in family are your obsession—you''re here to transform them. Your generation values psychological depth and ancestral healing as sacred work.',
 'Your generation''s relationships are deep and transformative, sometimes intensely so. You attract people with real darkness and real depth; you''re not afraid of the shadow. You understand that true intimacy requires facing the darkest truths together. Betrayal cuts you because trust, for you, is everything.',
 'Your generation can be obsessive about family wounds or ancestral patterns, getting stuck in the past. Power struggles in relationships can be intense and mutually destructive. You may unconsciously recreate family trauma with partners. Control, especially emotional control, can mask as love or protection.',
 'Transform family patterns by facing them with compassion, not blame. Your power lies in breaking cycles, not perpetuating them. Forgive your ancestors and yourself. Let relationships deepen through honesty about power dynamics, not secrecy. Your generation''s gift is showing the world that transformation begins with truth.',
 ARRAY['Woolfolk, The Only Astrology Book You''ll Ever Need', 'Hand, Planets in Transit', 'Forrest, The Inner Sky']);
