import { NextRequest, NextResponse } from "next/server";
import Anthropic from "@anthropic-ai/sdk";
import { CLAUDE_MODEL, FALLBACK_MODEL } from "@/lib/aiModel";
import {
  PALMISTRY_SYSTEM_PROMPT,
  buildPalmistryUserText,
  type Hand,
  type PalmReading,
} from "@/lib/palmistry";

// Node runtime: more reliable than edge for the Anthropic SDK and for the
// larger (image) request bodies this route receives.
export const runtime = "nodejs";
export const maxDuration = 60;

/**
 * POST /api/palmistry
 *
 * Accepts a photo of the user's palm and returns a structured palm reading
 * generated by Claude's vision model, grounded in traditional palmistry.
 *
 * The image is processed in-memory only and is NEVER persisted or logged here.
 * (Saving is opt-in and handled client-side; see the palmistry page.)
 */

interface PalmistryRequest {
  /** Data URL or bare base64 of a JPEG/PNG/WebP image of the palm. */
  image: string;
  hand: Hand;
  userName?: string;
}

const ALLOWED_MEDIA = new Set(["image/jpeg", "image/png", "image/webp"]);
// ~6MB cap on the decoded base64 string length (well above a 1024px JPEG).
const MAX_BASE64_LEN = 8_000_000;

/** Splits a data URL (or bare base64) into a media type + base64 payload. */
function parseImage(input: string): { mediaType: string; data: string } | null {
  if (!input || typeof input !== "string") return null;
  const dataUrl = input.match(/^data:(image\/[a-zA-Z+]+);base64,(.+)$/);
  if (dataUrl) return { mediaType: dataUrl[1].toLowerCase(), data: dataUrl[2] };
  // Bare base64 — assume JPEG.
  if (/^[A-Za-z0-9+/=\s]+$/.test(input)) return { mediaType: "image/jpeg", data: input.trim() };
  return null;
}

/** Pulls the first JSON object out of Claude's text response. */
function extractJson(text: string): unknown {
  const trimmed = text.trim().replace(/^```(?:json)?/i, "").replace(/```$/, "").trim();
  try {
    return JSON.parse(trimmed);
  } catch {
    const start = trimmed.indexOf("{");
    const end = trimmed.lastIndexOf("}");
    if (start !== -1 && end !== -1 && end > start) {
      try {
        return JSON.parse(trimmed.slice(start, end + 1));
      } catch {
        return null;
      }
    }
    return null;
  }
}

export async function POST(req: NextRequest) {
  try {
    const { getAuthedUserId } = await import("@/lib/apiAuth");
    const uid = await getAuthedUserId(req);
    if (!uid) {
      return NextResponse.json({ error: "Sign in required." }, { status: 401 });
    }

    // Rate limit: vision calls are paid. 10 readings/hr per user.
    const { checkRateLimitDurable } = await import("@/lib/rateLimit");
    const { allowed } = await checkRateLimitDurable(`palmistry:${uid}`, 10, 60 * 60 * 1000);
    if (!allowed) {
      return NextResponse.json(
        { error: "You've done a lot of readings — try again a little later." },
        { status: 429 },
      );
    }

    const body: PalmistryRequest = await req.json();
    const hand: Hand = body.hand === "left" ? "left" : "right";

    const parsed = parseImage(body.image);
    if (!parsed) {
      return NextResponse.json({ error: "No valid image provided." }, { status: 400 });
    }
    if (!ALLOWED_MEDIA.has(parsed.mediaType)) {
      return NextResponse.json({ error: "Unsupported image format." }, { status: 400 });
    }
    if (parsed.data.length > MAX_BASE64_LEN) {
      return NextResponse.json({ error: "Image is too large." }, { status: 413 });
    }

    if (!process.env.ANTHROPIC_API_KEY) {
      return NextResponse.json(
        { error: "Reading service isn't configured (missing API key)." },
        { status: 500 },
      );
    }

    // Instantiate inside the handler so any construction error is caught here
    // and returned as JSON, rather than crashing module load.
    const anthropic = new Anthropic();

    const params = {
      max_tokens: 1200,
      system: PALMISTRY_SYSTEM_PROMPT,
      messages: [
        {
          role: "user" as const,
          content: [
            {
              type: "image" as const,
              source: {
                type: "base64" as const,
                media_type: parsed.mediaType as "image/jpeg" | "image/png" | "image/webp",
                data: parsed.data,
              },
            },
            { type: "text" as const, text: buildPalmistryUserText(hand, body.userName) },
          ],
        },
      ],
    };

    // Prefer the fast model (Haiku) for snappy readings; fall back to Sonnet.
    let message;
    try {
      message = await anthropic.messages.create({ ...params, model: FALLBACK_MODEL });
    } catch {
      message = await anthropic.messages.create({ ...params, model: CLAUDE_MODEL });
    }

    const text = message.content[0]?.type === "text" ? message.content[0].text : "";
    const result = extractJson(text) as
      | { ok: true; reading: PalmReading }
      | { ok: false; reason: string }
      | null;

    if (!result || typeof result !== "object") {
      return NextResponse.json(
        { error: "Couldn't interpret the reading. Please try again." },
        { status: 502 },
      );
    }

    if (result.ok === false) {
      return NextResponse.json({
        ok: false,
        reason:
          result.reason ||
          "Couldn't read that one clearly. Try better lighting and fill the frame with your palm.",
      });
    }

    if (!result.reading?.sections?.length) {
      return NextResponse.json(
        { error: "Couldn't interpret the reading. Please try again." },
        { status: 502 },
      );
    }

    return NextResponse.json({ ok: true, hand, reading: result.reading });
  } catch (error) {
    console.error("Palmistry reading error:", error);
    const detail = error instanceof Error ? error.message : String(error);
    let msg = "Failed to read your palm. Please try again.";
    if (/credit|billing|quota/i.test(detail)) {
      msg = "The reading service is temporarily unavailable. Please try again later.";
    } else if (/401|api key|authentication/i.test(detail)) {
      msg = "Reading service authentication failed. Check the API key.";
    }
    return NextResponse.json({ error: msg, detail }, { status: 500 });
  }
}
