import type { Course } from "../types";

/** FLAGSHIP #6 — Herbalism, taught evidence-first and safety-first. */
export const herbalismFoundations: Course = {
  id: "herbalism-foundations",
  domain: "herbalism",
  title: "Herbalism: Tradition, Evidence & Safety",
  subtitle: "Folk wisdom meets the evidence",
  level: "foundations",
  icon: "🌿",
  summary:
    "Learn common herbs and their traditional and evidence-based uses — and, above all, how to use them safely alongside modern medicine.",
  estMinutes: 45,
  status: "published",
  passThreshold: 0.8,
  finalTestSize: 10,
  safetyNote:
    "Herbs can interact dangerously with medications (e.g. St John's wort with birth control and antidepressants) and some are unsafe in pregnancy. This course leads with safety, and is not a substitute for professional medical care.",

  outline: [
    { module: "Foundations", lessons: ["What herbalism is — and the regulatory reality", "Preparations: teas, tinctures & more", "Herbal actions vocabulary"] },
    { module: "Common Herbs (Tradition vs Evidence)", lessons: ["Calming herbs", "Digestive herbs", "Immune & inflammatory herbs", "St John's wort & its interactions", "Reading the evidence tiers"] },
    { module: "Safety First", lessons: ["Herb–drug interactions", "Pregnancy & breastfeeding", "Sourcing, quality & adulteration", "When to see a clinician, not a herb"] },
  ],

  modules: [
    {
      id: "m1",
      title: "Foundations",
      lessons: [
        {
          id: "l1-what-herbalism-is",
          title: "What herbalism is — and the regulatory reality",
          objective: "Explain what herbalism is and how herbal products are (and aren't) regulated.",
          estMinutes: 5,
          blocks: [
            { kind: "text", text: "Herbalism is the use of plants for wellbeing — a practice found in nearly every culture, with a mix of genuine pharmacology and folk tradition. It is one of the oldest healing systems on Earth: written records of medicinal plant use go back thousands of years, from Egyptian papyri to Chinese, Ayurvedic, Greek, and Indigenous traditions on every continent." },
            { kind: "text", text: "Crucially, herbalism is not the opposite of 'real' medicine — much of modern pharmacology grew directly out of it. The challenge for a thoughtful student is to hold two truths at once: plants contain real, active chemistry (which is exactly why they can both help AND harm), and tradition alone is not proof that a remedy works or is safe." },
            { kind: "callout", tone: "history", title: "From plant to pharmacy", text: "Many cornerstone drugs began as plant medicines: aspirin from willow bark and meadowsweet (salicylates), digoxin from foxglove, morphine from the opium poppy, quinine from cinchona bark, the cancer drug paclitaxel (Taxol) from the Pacific yew, and the antimalarial artemisinin from sweet wormwood — a discovery that won a Nobel Prize in 2015." },
            { kind: "callout", tone: "safety", title: "The regulatory reality", text: "In the US, herbal supplements are regulated as foods under the 1994 DSHEA law, not as drugs. They are NOT FDA-approved for safety or effectiveness before sale. Manufacturers — not the FDA — are responsible for safety, and the FDA generally acts only AFTER a product on the market is shown to be harmful. Products are not standardized, so the actual dose and purity can vary a lot between brands and even bottles. 'Natural' does not mean safe, regulated, or effective." },
            { kind: "table", headers: ["", "Prescription drug", "Herbal supplement (US)"], rows: [
              ["Pre-market approval", "Yes — proven safe & effective first", "No"],
              ["Dose standardized", "Yes, to the milligram", "Often not; varies by brand/batch"],
              ["Manufacturing checks", "Strict (cGMP, inspected)", "Lighter; quality varies widely"],
              ["Claims allowed", "Specific disease claims if proven", "Only vague 'structure/function' claims"],
            ] },
            { kind: "callout", tone: "tip", title: "Reading a label", text: "Supplement labels can legally say things like 'supports immune health' but NOT 'treats colds' or 'cures' anything. A disease claim on a supplement is a red flag, not a green light — by law that claim has not been vetted." },
            { kind: "keyfacts", items: [
              "Herbalism is ancient and worldwide; modern drugs often descend from it.",
              "US herbal supplements are regulated as foods, not pre-approved like drugs.",
              "Dose and purity are NOT standardized — they vary by brand and batch.",
              "'Natural' ≠ safe, regulated, or effective.",
            ] },
          ],
          quiz: [
            { id: "q1", type: "mcq", prompt: "In the US, herbal supplements are…", options: [
              { id: "a", text: "Regulated as foods, not FDA-approved like drugs", correct: true, explanation: "Correct — under DSHEA they aren't pre-approved for safety/efficacy." },
              { id: "b", text: "Approved by the FDA before sale", correct: false, explanation: "They are not pre-approved like drugs." },
              { id: "c", text: "Banned", correct: false, explanation: "They're legal but lightly regulated." },
              { id: "d", text: "Held to the same standards as prescription drugs", correct: false, explanation: "The standards are much lighter than for drugs." },
            ] },
            { id: "q2", type: "true-false", prompt: "'Natural' reliably means safe and standardized.", options: [
              { id: "t", text: "True", correct: false, explanation: "No — natural products can be potent, variable, and risky." },
              { id: "f", text: "False", correct: true, explanation: "Correct — natural ≠ safe or standardized." },
            ] },
            { id: "q3", type: "mcq", prompt: "Which is true of herbal product strength?", options: [
              { id: "a", text: "It can vary between brands and batches", correct: true, explanation: "Right — they aren't standardized like drugs." },
              { id: "b", text: "It is identical everywhere", correct: false, explanation: "No — potency varies." },
              { id: "c", text: "It is set by the FDA", correct: false, explanation: "The FDA doesn't pre-set supplement doses." },
              { id: "d", text: "It is always weaker than any drug", correct: false, explanation: "Concentrated herbal extracts can be quite potent." },
            ] },
            { id: "q4", type: "mcq", prompt: "On a US supplement label, which claim is a red flag that something is being marketed illegally?", options: [
              { id: "a", text: "'Cures cold and flu'", correct: true, explanation: "Correct — disease 'cure/treat' claims are not allowed on supplements and signal an unvetted claim." },
              { id: "b", text: "'Supports immune health'", correct: false, explanation: "That's a legal, vague structure/function claim." },
              { id: "c", text: "'Traditionally used to promote calm'", correct: false, explanation: "Vague traditional-use wording is permitted." },
              { id: "d", text: "Listing the amount per serving", correct: false, explanation: "That's normal and helpful." },
            ] },
            { id: "q5", type: "recall", prompt: "Name the antimalarial drug derived from sweet wormwood whose discovery won a 2015 Nobel Prize.", options: [], answer: "artemisinin", accept: ["artemesinin", "qinghaosu"], explanation: "Artemisinin (qinghaosu), from Artemisia annua — a striking example of a modern drug rooted in traditional herbalism." },
            { id: "q6", type: "true-false", prompt: "Because the same chemistry that lets a plant help can also let it harm, potency is a reason for caution, not reassurance.", options: [
              { id: "t", text: "True", correct: true, explanation: "Correct — active chemistry cuts both ways." },
              { id: "f", text: "False", correct: false, explanation: "Active compounds can both help and harm; that's why dose and interactions matter." },
            ] },
          ],
        },
        {
          id: "l2-preparations",
          title: "Preparations: teas, tinctures & more",
          objective: "Distinguish the main ways herbs are prepared and how preparation changes the dose.",
          estMinutes: 5,
          blocks: [
            { kind: "text", text: "The same plant can be a gentle food or a potent medicine depending on how it's prepared. Preparation determines which compounds you extract, how concentrated they are, and therefore the effective dose. Understanding this is the single most practical safety skill in herbalism." },
            { kind: "table", headers: ["Preparation", "What it is", "Best for"], rows: [
              ["Infusion (tea)", "Steeping soft parts (leaves, flowers) in hot water, covered, ~5–15 min", "Delicate aromatic herbs — chamomile, peppermint, lemon balm"],
              ["Decoction", "Simmering tough parts (roots, bark, seeds) in water 15–30+ min", "Hard material — ginger root, cinnamon bark, dandelion root"],
              ["Cold infusion", "Steeping in cool water for hours", "Mucilage/demulcent herbs like marshmallow root"],
              ["Tincture", "Extracting a herb in alcohol; concentrated, shelf-stable for years", "Potent or non-water-soluble constituents; precise dosing by drops"],
              ["Glycerite", "Alcohol-free extract in vegetable glycerin", "Children or alcohol-avoiders (often weaker than tinctures)"],
              ["Infused oil / salve", "Steeping a herb in oil for topical use", "External use — calendula salve, arnica (external only)"],
              ["Capsule / powder", "Dried, ground herb in a measured dose", "Bitter or bulky herbs; easier consistent dosing"],
              ["Standardized extract", "Concentrated to a set % of a marker compound", "Reproducible dose (e.g. milk thistle standardized to silymarin)"],
            ] },
            { kind: "callout", tone: "tip", title: "Concentration is everything", text: "A cup of chamomile tea and a concentrated tincture or standardized extract are very different doses of the same plant. Most safety problems and interactions come with concentrated forms (tinctures, extracts, high-dose capsules), not with culinary or light-tea amounts." },
            { kind: "callout", tone: "evidence", title: "Tea vs extract isn't interchangeable", text: "Clinical studies often use a SPECIFIC preparation and dose — for example enteric-coated peppermint OIL for IBS, not peppermint tea. Evidence for one form does not automatically transfer to another. Match the form to the form that was actually studied." },
            { kind: "callout", tone: "tradition", title: "Why roots get simmered and flowers get steeped", text: "Folk practice arrived at a real chemical logic: tough, woody material needs sustained heat (decoction) to release its constituents, while delicate flowers and aromatic leaves lose their volatile oils if boiled — so they're steeped, covered, to trap the aromatics." },
            { kind: "keyfacts", items: [
              "Infusion = steep soft parts; decoction = simmer tough parts.",
              "Tincture = alcohol extract — concentrated, long-lasting, dosed in drops.",
              "Standardized extracts give a reproducible amount of a marker compound.",
              "Evidence is form-specific: don't assume tea equals the studied extract.",
            ] },
          ],
          quiz: [
            { id: "q1", type: "mcq", prompt: "A decoction is made by…", options: [
              { id: "a", text: "Simmering tough parts like roots and bark in water", correct: true, explanation: "Correct — sustained heat extracts the tougher material." },
              { id: "b", text: "Steeping leaves briefly in cool water", correct: false, explanation: "That's closer to a cold infusion." },
              { id: "c", text: "Extracting in alcohol", correct: false, explanation: "That's a tincture." },
              { id: "d", text: "Pressing oil from seeds", correct: false, explanation: "That's not a decoction." },
            ] },
            { id: "q2", type: "mcq", prompt: "A tincture extracts a herb in…", options: [
              { id: "a", text: "Alcohol", correct: true, explanation: "Yes — concentrated and shelf-stable, dosed in drops." },
              { id: "b", text: "Hot water only", correct: false, explanation: "That's a tea/infusion." },
              { id: "c", text: "Sunlight", correct: false, explanation: "Not a preparation method." },
              { id: "d", text: "Vinegar exclusively", correct: false, explanation: "Tinctures are typically alcohol-based." },
            ] },
            { id: "q3", type: "true-false", prompt: "A concentrated extract and a cup of tea are roughly the same dose.", options: [
              { id: "t", text: "True", correct: false, explanation: "No — concentrates are far stronger." },
              { id: "f", text: "False", correct: true, explanation: "Correct — concentration changes the dose a lot." },
            ] },
            { id: "q4", type: "mcq", prompt: "Delicate aromatic flowers and leaves are usually steeped (infused) rather than boiled because…", options: [
              { id: "a", text: "Boiling drives off their volatile aromatic oils", correct: true, explanation: "Correct — covered steeping preserves the aromatics." },
              { id: "b", text: "They contain no useful compounds", correct: false, explanation: "They do — which is why you want to preserve them." },
              { id: "c", text: "Water can't extract them at all", correct: false, explanation: "Hot water does extract them; prolonged boiling just loses the volatiles." },
              { id: "d", text: "It is illegal to boil them", correct: false, explanation: "Not a real reason." },
            ] },
            { id: "q5", type: "mcq", prompt: "A study found enteric-coated peppermint OIL helps IBS. What does this tell you about peppermint TEA for IBS?", options: [
              { id: "a", text: "The evidence is form-specific; tea wasn't what was tested", correct: true, explanation: "Correct — match the form studied; don't assume the tea is equivalent." },
              { id: "b", text: "Tea is automatically proven for IBS too", correct: false, explanation: "Evidence doesn't transfer freely between forms." },
              { id: "c", text: "Tea must be stronger than the oil", correct: false, explanation: "The oil is the concentrated, studied form here." },
              { id: "d", text: "Peppermint has no evidence at all", correct: false, explanation: "The oil does have good evidence; the point is form-specificity." },
            ] },
            { id: "q6", type: "recall", prompt: "What is the name for an alcohol-free herbal extract made in vegetable glycerin, sometimes used for children?", options: [], answer: "glycerite", accept: ["glycerite", "glycerin extract", "glycerine extract"], explanation: "A glycerite — alcohol-free but often weaker than an alcohol tincture." },
          ],
        },
        {
          id: "l10-herbal-actions",
          title: "Herbal actions vocabulary",
          objective: "Define the core 'herbal action' terms and read them critically.",
          estMinutes: 5,
          blocks: [
            { kind: "text", text: "Traditional herbalism describes herbs by their 'actions' — broad categories of how a plant is said to affect the body. This vocabulary is genuinely useful for reading herbal sources and understanding tradition. But treat these as descriptive folk categories, not proven clinical effects: an herb labelled a 'tonic' has not necessarily been shown to do anything in a trial." },
            { kind: "table", headers: ["Action", "Meaning", "Classic example"], rows: [
              ["Adaptogen", "Said to help the body resist/adapt to stress, broadly", "Ashwagandha, rhodiola, ginseng"],
              ["Nervine", "Affects the nervous system (relaxing or stimulating)", "Lemon balm, valerian (relaxing)"],
              ["Carminative", "Relieves gas, bloating, digestive spasm", "Fennel, peppermint, ginger"],
              ["Demulcent", "Soothing, mucilaginous; coats irritated tissue", "Marshmallow root, slippery elm"],
              ["Bitter", "Stimulates digestion via bitter taste", "Gentian, dandelion, artichoke"],
              ["Expectorant", "Helps move mucus from the airways", "Thyme, mullein"],
              ["Diaphoretic", "Promotes sweating", "Yarrow, elderflower"],
              ["Anti-inflammatory", "Said to reduce inflammation", "Turmeric, ginger"],
              ["Astringent", "Tightens/tones tissue (tannins)", "Witch hazel, raspberry leaf"],
            ] },
            { kind: "callout", tone: "evidence", title: "'Adaptogen' is a tradition/marketing term, not a regulatory one", text: "'Adaptogen' was coined by Soviet researchers in the mid-1900s and is widely used in marketing. Some adaptogens (e.g. ashwagandha for stress/sleep) have early, modest human trials; many claims rest on tradition or lab studies. It is not a recognized pharmacological category with a guaranteed effect — read it as a hypothesis, not a proven mechanism." },
            { kind: "callout", tone: "tradition", title: "Energetics: warm/cool, dry/moist", text: "Many traditions (Western folk, Ayurveda, Traditional Chinese Medicine) also describe herbs by 'energetics' — e.g. ginger as warming, peppermint as cooling. This is a traditional matching framework, not a measured property, but it's how a lot of herbal source material is organized, so it helps to recognize the language." },
            { kind: "callout", tone: "safety", title: "An 'action' is not a free pass", text: "A soothing or 'gentle' action label says nothing about interactions or contraindications. Demulcents like marshmallow can theoretically slow absorption of medications taken at the same time; bitters and others have their own cautions. Always check the specific herb, not just its category." },
            { kind: "keyfacts", items: [
              "Adaptogen = resist stress; nervine = nervous system; carminative = anti-gas.",
              "Demulcent = soothing/mucilaginous; bitter = stimulates digestion.",
              "These are traditional descriptive categories, not proven clinical effects.",
              "Category labels never replace checking a specific herb's safety and interactions.",
            ] },
          ],
          quiz: [
            { id: "q1", type: "mcq", prompt: "A 'carminative' herb is one traditionally used to…", options: [
              { id: "a", text: "Relieve gas, bloating, and digestive spasm", correct: true, explanation: "Correct — fennel and peppermint are classic carminatives." },
              { id: "b", text: "Promote sweating", correct: false, explanation: "That's a diaphoretic." },
              { id: "c", text: "Soothe irritated tissue with mucilage", correct: false, explanation: "That's a demulcent." },
              { id: "d", text: "Tighten and tone tissue", correct: false, explanation: "That's an astringent." },
            ] },
            { id: "q2", type: "mcq", prompt: "A 'demulcent' such as marshmallow root works by…", options: [
              { id: "a", text: "Coating and soothing irritated tissue with mucilage", correct: true, explanation: "Correct — slimy, mucilaginous herbs soothe surfaces." },
              { id: "b", text: "Stimulating strong sweating", correct: false, explanation: "That's a diaphoretic." },
              { id: "c", text: "Stimulating digestion via bitter taste", correct: false, explanation: "That's a bitter." },
              { id: "d", text: "Thinning the blood", correct: false, explanation: "Not the demulcent action." },
            ] },
            { id: "q3", type: "true-false", prompt: "'Adaptogen' is an officially recognized pharmacological category with a guaranteed proven effect.", options: [
              { id: "t", text: "True", correct: false, explanation: "No — it's a traditional/marketing term; evidence is mixed and mostly early." },
              { id: "f", text: "False", correct: true, explanation: "Correct — treat 'adaptogen' as a hypothesis, not a proven mechanism." },
            ] },
            { id: "q4", type: "recall", prompt: "What single word describes an herb that affects the nervous system — for example calming, relaxing valerian?", options: [], answer: "nervine", accept: ["nervine"], explanation: "A nervine acts on the nervous system; it can be relaxing or stimulating." },
            { id: "q5", type: "mcq", prompt: "Why shouldn't you rely on an action label like 'gentle demulcent' to judge safety?", options: [
              { id: "a", text: "The category says nothing about that herb's interactions or contraindications", correct: true, explanation: "Correct — e.g. demulcents may slow absorption of meds taken together; always check the specific herb." },
              { id: "b", text: "Action labels are always wrong", correct: false, explanation: "They're useful descriptors, just not safety guarantees." },
              { id: "c", text: "Gentle herbs are the most dangerous", correct: false, explanation: "Overstated; the point is the label alone isn't enough." },
              { id: "d", text: "Only doctors can read them", correct: false, explanation: "Anyone can learn them; they just aren't safety verdicts." },
            ] },
          ],
        },
      ],
    },
    {
      id: "m2",
      title: "Common Herbs (Tradition vs Evidence)",
      lessons: [
        {
          id: "l3-calming",
          title: "Calming herbs",
          objective: "Summarize the evidence for common calming herbs and their sedation risks.",
          estMinutes: 5,
          blocks: [
            { kind: "text", text: "Calming or 'nervine' herbs are among the most popular for everyday stress and sleep. The evidence ranges from modest-but-real to thin, and the main safety theme is shared: sedation that can stack with other depressants." },
            { kind: "table", headers: ["Herb", "Traditional use", "What the evidence shows"], rows: [
              ["Chamomile", "Calm, sleep, digestion", "Modest evidence for mild anxiety/sleep; generally gentle"],
              ["Valerian", "Sleep, anxiety", "Mixed/inconsistent for sleep; can cause drowsiness, occasional 'hangover'"],
              ["Lemon balm", "Calm, mood", "Limited but promising for stress/sleep, often combined with valerian"],
              ["Lavender", "Anxiety, sleep", "Oral standardized prep (Silexan) has some anxiety evidence; aromatherapy weaker"],
              ["Passionflower", "Anxiety, restlessness", "Limited; some small trials for anxiety/sleep"],
            ] },
            { kind: "callout", tone: "safety", title: "Watch the sedation stack", text: "Calming/sedating herbs — especially valerian — can ADD to the effect of alcohol, benzodiazepines, opioids, prescription sleep aids, and anti-anxiety medication, causing excessive drowsiness or impaired breathing. Don't combine without medical advice, don't drive or operate machinery if drowsy, and tell your anesthetist before surgery (valerian may interact with anesthesia)." },
            { kind: "callout", tone: "safety", title: "Allergy note", text: "Chamomile is in the daisy (Asteraceae) family. People allergic to ragweed, daisies, marigolds, or chrysanthemums can react to it, occasionally severely." },
            { kind: "callout", tone: "evidence", title: "Honest read on valerian", text: "Despite its popularity, systematic reviews find valerian's sleep evidence inconsistent and often from low-quality studies. It may help some people; it's not a reliable sleep cure, and the variable potency of products makes results hard to predict." },
            { kind: "keyfacts", items: [
              "Chamomile: modest, gentle evidence — but a daisy-family allergen.",
              "Valerian: mixed evidence; clear sedation/anesthesia caution.",
              "Sedating herbs stack with alcohol and CNS-depressant medications.",
              "Lavender (oral Silexan) has more anxiety evidence than aromatherapy.",
            ] },
          ],
          quiz: [
            { id: "q1", type: "mcq", prompt: "Valerian is mainly used traditionally for…", options: [
              { id: "a", text: "Sleep and anxiety", correct: true, explanation: "Correct — a sedating herb." },
              { id: "b", text: "Boosting energy", correct: false, explanation: "It's calming, not stimulating." },
              { id: "c", text: "Healing wounds", correct: false, explanation: "That's not its traditional use." },
              { id: "d", text: "Lowering cholesterol", correct: false, explanation: "Not a recognized use." },
            ] },
            { id: "q2", type: "mcq", prompt: "A key safety concern with sedating herbs is…", options: [
              { id: "a", text: "Added drowsiness with alcohol or sleep/anxiety meds", correct: true, explanation: "Right — CNS-depressant effects can stack dangerously." },
              { id: "b", text: "They make you radioactive", correct: false, explanation: "Not a real concern." },
              { id: "c", text: "They cure infections", correct: false, explanation: "Unrelated and unproven." },
              { id: "d", text: "They raise blood pressure sharply", correct: false, explanation: "The main concern is additive sedation, not hypertension." },
            ] },
            { id: "q3", type: "true-false", prompt: "Chamomile has modest evidence for mild anxiety and sleep.", options: [
              { id: "t", text: "True", correct: true, explanation: "Correct — modest but real, and it's gentle." },
              { id: "f", text: "False", correct: false, explanation: "There is modest supporting evidence." },
            ] },
            { id: "q4", type: "mcq", prompt: "Why should someone allergic to ragweed or daisies be cautious with chamomile?", options: [
              { id: "a", text: "Chamomile is in the same daisy (Asteraceae) family and can cross-react", correct: true, explanation: "Correct — cross-reactivity can occasionally be severe." },
              { id: "b", text: "Chamomile contains gluten", correct: false, explanation: "Not the issue here." },
              { id: "c", text: "Chamomile is a stimulant", correct: false, explanation: "It's calming; the concern is allergy." },
              { id: "d", text: "It interacts with sunlight", correct: false, explanation: "Not the relevant risk." },
            ] },
            { id: "q5", type: "true-false", prompt: "You should tell your anesthetist before surgery if you take valerian.", options: [
              { id: "t", text: "True", correct: true, explanation: "Correct — valerian may interact with anesthesia and other sedatives." },
              { id: "f", text: "False", correct: false, explanation: "Always disclose sedating herbs before surgery." },
            ] },
            { id: "q6", type: "mcq", prompt: "The honest summary of valerian's sleep evidence is…", options: [
              { id: "a", text: "Mixed and inconsistent — it may help some, but isn't a reliable cure", correct: true, explanation: "Correct — reviews find low-quality, inconsistent results." },
              { id: "b", text: "Strong, conclusive proof it cures insomnia", correct: false, explanation: "The evidence does not support that." },
              { id: "c", text: "Proof it is more effective than any sleep drug", correct: false, explanation: "No such evidence." },
              { id: "d", text: "Nonexistent — no studies have ever looked", correct: false, explanation: "There are studies; they're just inconsistent." },
            ] },
          ],
        },
        {
          id: "l4-digestive",
          title: "Digestive herbs",
          objective: "Summarize the evidence for ginger and peppermint and their limits.",
          estMinutes: 5,
          blocks: [
            { kind: "text", text: "Ginger and peppermint are two of the better-evidenced herbs in everyday use — a useful reminder that 'herbal' is not a synonym for 'unproven.' Both also illustrate that even well-supported herbs have real cautions." },
            { kind: "table", headers: ["Herb", "Use", "What the evidence shows"], rows: [
              ["Ginger", "Nausea (motion, pregnancy, post-op, chemo)", "Good evidence it reduces nausea, including in pregnancy"],
              ["Peppermint", "IBS, indigestion", "Good evidence for enteric-coated oil in IBS; eases cramping"],
              ["Fennel", "Bloating, infant colic (traditional)", "Limited evidence; carminative tradition"],
              ["Artichoke / bitters", "Indigestion, appetite", "Some evidence for functional dyspepsia"],
            ] },
            { kind: "callout", tone: "evidence", title: "Two of the better-evidenced herbs", text: "Multiple trials and reviews support ginger for several kinds of nausea, and enteric-coated peppermint oil for IBS symptoms. These are genuine bright spots — but note the evidence attaches to specific forms and doses, not to 'ginger in general' or 'peppermint anything.'" },
            { kind: "callout", tone: "safety", title: "Real cautions even for 'safe' herbs", text: "Peppermint can RELAX the esophageal sphincter and worsen acid reflux/GERD in some people. Very high-dose ginger may mildly affect blood clotting and blood sugar, so use caution with blood thinners or before surgery. In pregnancy, ginger is generally considered acceptable in moderate amounts, but discuss dose with your clinician." },
            { kind: "callout", tone: "tip", title: "Food vs medicine dose", text: "Ginger in cooking or a cup of peppermint tea is a world away from concentrated capsules or oil. The cautions above apply mainly to concentrated, medicinal doses." },
            { kind: "keyfacts", items: [
              "Ginger: good evidence for nausea, including pregnancy nausea (discuss dose).",
              "Enteric-coated peppermint OIL: good evidence for IBS symptoms.",
              "Peppermint can worsen reflux; high-dose ginger may affect clotting/sugar.",
              "Evidence is form- and dose-specific — not 'the herb in general.'",
            ] },
          ],
          quiz: [
            { id: "q1", type: "mcq", prompt: "Ginger has good evidence for…", options: [
              { id: "a", text: "Reducing nausea", correct: true, explanation: "Correct — including motion and pregnancy nausea." },
              { id: "b", text: "Curing infections", correct: false, explanation: "Not its evidence base." },
              { id: "c", text: "Improving eyesight", correct: false, explanation: "No evidence for that." },
              { id: "d", text: "Lowering cholesterol dramatically", correct: false, explanation: "Not an established use." },
            ] },
            { id: "q2", type: "mcq", prompt: "Enteric-coated peppermint oil has evidence for…", options: [
              { id: "a", text: "Irritable bowel syndrome (IBS) symptoms", correct: true, explanation: "Yes — a well-studied use." },
              { id: "b", text: "Healing broken bones", correct: false, explanation: "No evidence for that." },
              { id: "c", text: "Lowering cholesterol", correct: false, explanation: "Not an established use." },
              { id: "d", text: "Curing the flu", correct: false, explanation: "No such evidence." },
            ] },
            { id: "q3", type: "true-false", prompt: "All herbal remedies are unproven by definition.", options: [
              { id: "t", text: "True", correct: false, explanation: "No — some, like ginger and peppermint, have solid evidence." },
              { id: "f", text: "False", correct: true, explanation: "Correct — evidence varies by herb." },
            ] },
            { id: "q4", type: "mcq", prompt: "Peppermint can be a problem for some people because it may…", options: [
              { id: "a", text: "Relax the esophageal sphincter and worsen acid reflux", correct: true, explanation: "Correct — it can aggravate GERD in susceptible people." },
              { id: "b", text: "Cause radioactivity", correct: false, explanation: "Not real." },
              { id: "c", text: "Always cure reflux instantly", correct: false, explanation: "It can worsen, not cure, reflux." },
              { id: "d", text: "Raise blood pressure sharply", correct: false, explanation: "Not the typical concern." },
            ] },
            { id: "q5", type: "mcq", prompt: "Why might someone on blood thinners or facing surgery use caution with very high-dose ginger?", options: [
              { id: "a", text: "It may mildly affect blood clotting", correct: true, explanation: "Correct — high doses can have a mild antiplatelet effect." },
              { id: "b", text: "It causes immediate liver failure", correct: false, explanation: "That's not ginger's profile." },
              { id: "c", text: "It is a controlled substance", correct: false, explanation: "It's a common food." },
              { id: "d", text: "It blocks all medications", correct: false, explanation: "Overstated." },
            ] },
            { id: "q6", type: "recall", prompt: "Which kitchen herb has good evidence for reducing nausea, including nausea in pregnancy?", options: [], answer: "ginger", accept: ["ginger root", "zingiber"], explanation: "Ginger — discuss dose with a clinician during pregnancy, but it's one of the better-evidenced herbs for nausea." },
          ],
        },
        {
          id: "l5-immune",
          title: "Immune & inflammatory herbs",
          objective: "Summarize the (mixed) evidence for echinacea, elderberry, and turmeric.",
          estMinutes: 5,
          blocks: [
            { kind: "sort", prompt: "Sort herbs by traditional use", instructions: "Tap a herb, then tap its category", groups: [
              { name: "Calming", accent: "#8e6bb5", items: ["Chamomile", "Lemon balm", "Lavender"] },
              { name: "Digestive", accent: "#6a9a4a", items: ["Peppermint", "Ginger", "Fennel"] },
              { name: "Immune", accent: "#c9881f", items: ["Echinacea", "Elderberry", "Astragalus"] },
            ] },
            { kind: "text", text: "Immune and anti-inflammatory herbs are among the most heavily marketed — and among the most oversold. Reading them critically is a core skill: promising lab results and strong tradition frequently outrun the human evidence." },
            { kind: "table", headers: ["Herb", "Use", "What the evidence shows"], rows: [
              ["Echinacea", "Preventing/shortening colds", "Mixed/weak — may modestly shorten a cold at best; prevention unproven"],
              ["Elderberry", "Colds, flu symptoms", "Limited; some small trials suggest milder/shorter symptoms — not a cure"],
              ["Turmeric (curcumin)", "Inflammation, joint pain", "Some evidence for osteoarthritis pain; poorly absorbed on its own"],
              ["Astragalus", "Immune 'tonic' (TCM)", "Mostly traditional/lab data; little strong human evidence"],
            ] },
            { kind: "callout", tone: "evidence", title: "Read claims critically", text: "Echinacea's cold benefit is weak and inconsistent, and it does not reliably prevent colds. Elderberry may slightly ease symptoms in small studies but is not a proven flu treatment. Turmeric shows the most promise (especially for osteoarthritis), but curcumin is poorly absorbed on its own and results vary by formulation." },
            { kind: "callout", tone: "safety", title: "Cautions that get overlooked", text: "High-dose turmeric/curcumin can upset the stomach and may interact with blood thinners; rare liver injury has been reported with some concentrated supplements. Echinacea is a daisy-family plant (allergy cross-reactivity). 'Immune-boosting' herbs may be inadvisable for people on immunosuppressants or with autoimmune conditions — check with a clinician." },
            { kind: "callout", tone: "safety", title: "Never a substitute for vaccines or urgent care", text: "No immune herb replaces vaccination, antibiotics for a bacterial infection, or care for serious illness. A high fever, trouble breathing, or a worsening infection needs medical attention, not echinacea." },
            { kind: "keyfacts", items: [
              "Echinacea: weak/inconsistent; doesn't reliably prevent colds.",
              "Elderberry: limited; may ease symptoms, not a flu cure.",
              "Turmeric: best evidence (osteoarthritis) but poorly absorbed; blood-thinner caution.",
              "Immune herbs don't replace vaccines, antibiotics, or urgent care.",
            ] },
          ],
          quiz: [
            { id: "q1", type: "mcq", prompt: "The evidence for echinacea preventing colds is…", options: [
              { id: "a", text: "Weak and inconsistent", correct: true, explanation: "Correct — at best it may slightly shorten a cold; prevention is unproven." },
              { id: "b", text: "Strong and conclusive", correct: false, explanation: "No — the evidence is mixed/weak." },
              { id: "c", text: "Proof it cures the flu", correct: false, explanation: "There's no such proof." },
              { id: "d", text: "Proof it replaces a flu vaccine", correct: false, explanation: "No herb replaces vaccination." },
            ] },
            { id: "q2", type: "mcq", prompt: "A practical issue with turmeric/curcumin is…", options: [
              { id: "a", text: "It's poorly absorbed on its own", correct: true, explanation: "Right — bioavailability is low without special formulation." },
              { id: "b", text: "It's radioactive", correct: false, explanation: "Not a real concern." },
              { id: "c", text: "It's illegal", correct: false, explanation: "It's a common spice/supplement." },
              { id: "d", text: "It only works as an injection", correct: false, explanation: "Not true." },
            ] },
            { id: "q3", type: "true-false", prompt: "Popular herbs are sometimes oversold relative to the evidence.", options: [
              { id: "t", text: "True", correct: true, explanation: "Correct — read claims critically." },
              { id: "f", text: "False", correct: false, explanation: "Marketing often outpaces the evidence." },
            ] },
            { id: "q4", type: "mcq", prompt: "Who should be especially cautious with 'immune-boosting' herbs without medical advice?", options: [
              { id: "a", text: "People on immunosuppressants or with autoimmune conditions", correct: true, explanation: "Correct — stimulating the immune system can be counterproductive or risky for them." },
              { id: "b", text: "Everyone who has ever had a cold", correct: false, explanation: "Overbroad; the specific concern is immune-modulating situations." },
              { id: "c", text: "Only athletes", correct: false, explanation: "Not the relevant group." },
              { id: "d", text: "Nobody — they're universally safe", correct: false, explanation: "They are not universally safe." },
            ] },
            { id: "q5", type: "true-false", prompt: "A high fever with trouble breathing can be safely managed with echinacea instead of seeing a clinician.", options: [
              { id: "t", text: "True", correct: false, explanation: "No — those are warning signs that need medical care." },
              { id: "f", text: "False", correct: true, explanation: "Correct — serious symptoms need a clinician, not an immune herb." },
            ] },
            { id: "q6", type: "mcq", prompt: "The fairest summary of elderberry for colds and flu is…", options: [
              { id: "a", text: "Limited evidence it may ease symptoms; not a proven cure", correct: true, explanation: "Correct — small trials, modest effect, not a treatment for the flu." },
              { id: "b", text: "Conclusively proven to cure influenza", correct: false, explanation: "The evidence doesn't support a cure." },
              { id: "c", text: "Equivalent to antiviral medication", correct: false, explanation: "It is not." },
              { id: "d", text: "Completely without any supporting studies", correct: false, explanation: "There are some small supportive trials." },
            ] },
          ],
        },
        {
          id: "l6-st-johns-wort",
          title: "St John's wort & its interactions",
          objective: "Explain why St John's wort is the single most important herb–drug interaction to know.",
          estMinutes: 6,
          blocks: [
            { kind: "text", text: "St John's wort (Hypericum perforatum) has some genuine evidence for mild-to-moderate depression — in several trials it performed better than placebo and comparably to some standard antidepressants for mild-to-moderate cases. But it is also the most important herb–drug interaction in all of herbalism, and that is what every student must remember first." },
            { kind: "callout", tone: "safety", title: "Why it's risky — the mechanism", text: "St John's wort strongly INDUCES (speeds up) liver enzymes — especially CYP3A4 — and activates a drug transporter called P-glycoprotein. This makes the body clear many medications faster, REDUCING their effectiveness, sometimes to the point of failure." },
            { kind: "table", headers: ["Drug affected", "Consequence of taking St John's wort"], rows: [
              ["Hormonal birth control (the pill, etc.)", "Reduced effectiveness — breakthrough bleeding and risk of unintended pregnancy"],
              ["Warfarin & some blood thinners", "Reduced anticoagulation — clot risk"],
              ["Transplant anti-rejection drugs (ciclosporin, tacrolimus)", "Reduced levels — risk of organ rejection"],
              ["Many HIV and cancer medicines", "Reduced levels — treatment failure"],
              ["SSRIs / other antidepressants", "ADDED serotonin effect — risk of serotonin syndrome"],
              ["Some heart, seizure & immunosuppressant drugs", "Altered levels — loss of control of the condition"],
            ] },
            { kind: "callout", tone: "safety", title: "Serotonin syndrome", text: "Combined with SSRIs, SNRIs, triptans, tramadol, or other serotonergic drugs, St John's wort can cause serotonin syndrome — agitation, rapid heart rate, high temperature, tremor, and in severe cases a medical emergency. This is the opposite risk from the 'reduced effectiveness' interactions: here, effects stack." },
            { kind: "callout", tone: "tip", title: "The takeaway", text: "Never start St John's wort without checking with a pharmacist or doctor about EVERYTHING else you take — including the pill, and including other supplements. And don't stop it abruptly while on interacting medication without guidance, because drug levels can swing the other way when you do." },
            { kind: "keyfacts", items: [
              "St John's wort speeds up CYP3A4 and P-glycoprotein, clearing drugs faster.",
              "It REDUCES the effectiveness of hormonal birth control and many other drugs.",
              "With SSRIs and other serotonergic drugs it risks serotonin syndrome.",
              "Always check with a pharmacist/doctor before starting — and before stopping.",
            ] },
          ],
          quiz: [
            { id: "q1", type: "mcq", prompt: "St John's wort can dangerously REDUCE the effect of…", options: [
              { id: "a", text: "Hormonal birth control and many other drugs", correct: true, explanation: "Correct — it speeds their breakdown via CYP3A4/P-gp." },
              { id: "b", text: "Nothing — it has no interactions", correct: false, explanation: "It's a major interaction risk." },
              { id: "c", text: "Only vitamins", correct: false, explanation: "It affects many prescription drugs." },
              { id: "d", text: "Only over-the-counter painkillers", correct: false, explanation: "Its interactions are far broader." },
            ] },
            { id: "q2", type: "mcq", prompt: "Combining St John's wort with SSRIs risks…", options: [
              { id: "a", text: "Serotonin syndrome", correct: true, explanation: "Right — a potentially dangerous reaction." },
              { id: "b", text: "Improved sleep only", correct: false, explanation: "The real concern is serotonin syndrome." },
              { id: "c", text: "No effect", correct: false, explanation: "It can be dangerous." },
              { id: "d", text: "Instant cure of depression", correct: false, explanation: "Not how it works, and it's a risk, not a benefit." },
            ] },
            { id: "q3", type: "true-false", prompt: "It's fine to start St John's wort without telling your doctor or pharmacist.", options: [
              { id: "t", text: "True", correct: false, explanation: "No — always check for interactions first." },
              { id: "f", text: "False", correct: true, explanation: "Correct — check first, especially re: the pill." },
            ] },
            { id: "q4", type: "recall", prompt: "Which herb is famous for REDUCING the effectiveness of birth control and interacting with many medications, including SSRIs?", options: [], answer: "St John's wort", accept: ["st johns wort", "st. john's wort", "saint john's wort", "hypericum", "hypericum perforatum"], explanation: "St John's wort — the single most important herb–drug interaction to memorize." },
            { id: "q5", type: "mcq", prompt: "St John's wort reduces other drugs' levels mainly because it…", options: [
              { id: "a", text: "Induces liver enzymes (CYP3A4) and P-glycoprotein, clearing drugs faster", correct: true, explanation: "Correct — faster clearance means lower drug levels." },
              { id: "b", text: "Blocks the stomach from absorbing anything", correct: false, explanation: "That's not the mechanism." },
              { id: "c", text: "Neutralizes drugs chemically in the bottle", correct: false, explanation: "It acts in the body via enzyme induction." },
              { id: "d", text: "Has no real mechanism", correct: false, explanation: "It has a well-characterized one." },
            ] },
            { id: "q6", type: "mcq", prompt: "Someone stabilized on a transplant anti-rejection drug starts St John's wort. The danger is…", options: [
              { id: "a", text: "Lower drug levels and risk of organ rejection", correct: true, explanation: "Correct — reduced ciclosporin/tacrolimus levels can trigger rejection." },
              { id: "b", text: "The drug becoming far too strong", correct: false, explanation: "St John's wort lowers, not raises, these levels." },
              { id: "c", text: "No change at all", correct: false, explanation: "This is a clinically serious interaction." },
              { id: "d", text: "Improved transplant success", correct: false, explanation: "The opposite — it endangers the transplant." },
            ] },
          ],
        },
        {
          id: "l11-evidence-tiers",
          title: "Reading the evidence tiers",
          objective: "Place popular herbs on a rough evidence scale and weigh tradition against trials.",
          estMinutes: 5,
          blocks: [
            { kind: "text", text: "Not all herbal claims are equal. A useful habit is to mentally sort any claim into an evidence tier — from solid human trials down to tradition and testimonial alone. The amount of evidence should set how confident (and how cautious) you are." },
            { kind: "table", headers: ["Tier", "What it means", "Example herbs (for their best-studied use)"], rows: [
              ["Better-supported", "Multiple human trials / reviews show a real, if modest, effect", "Ginger (nausea), peppermint oil (IBS), St John's wort (mild–moderate depression)"],
              ["Promising but mixed", "Some positive trials, inconsistent or limited", "Turmeric (osteoarthritis), lavender (anxiety), valerian (sleep)"],
              ["Weak / inconsistent", "Trials are small, conflicting, or mostly negative", "Echinacea (colds), elderberry (flu)"],
              ["Mostly traditional", "Tradition and lab data, little strong human evidence", "Astragalus, many 'adaptogens', many tonics"],
            ] },
            { kind: "callout", tone: "evidence", title: "Tradition is a hypothesis, not a verdict", text: "Long traditional use is genuinely valuable — it's how many real medicines were first noticed, and it can flag plausible candidates. But tradition can also preserve remedies that don't work or that are unsafe (bloodletting was 'traditional' too). Use tradition to generate questions; use evidence to answer them." },
            { kind: "callout", tone: "evidence", title: "Watch for these red flags", text: "Be skeptical of: 'cures' of serious diseases; results only from test tubes or animals (not people); single testimonials; 'detox' and cure-all language; before/after marketing; and claims that a supplement is 'suppressed' by mainstream medicine. Strong claims need strong, human, replicated evidence." },
            { kind: "callout", tone: "tip", title: "Where to look it up", text: "For a quick, reasonably balanced read on a specific herb, neutral sources include the NIH's National Center for Complementary and Integrative Health (NCCIH), MedlinePlus, the NIH LiverTox database (for liver-safety), and a pharmacist who can check interactions." },
            { kind: "callout", tone: "safety", title: "Absence of evidence ≠ proof of safety", text: "An herb landing in 'mostly traditional' is not automatically safe just because trials are scarce — it may simply be understudied. When evidence is thin, the honest stance is uncertainty, and caution (especially around concentrated doses, pregnancy, and other medications) is the default." },
            { kind: "keyfacts", items: [
              "Sort each claim into a tier: better-supported → promising → weak → traditional.",
              "Tradition generates good hypotheses; trials test them.",
              "Red flags: disease 'cures', test-tube-only data, testimonials, 'detox' language.",
              "Thin evidence means uncertainty — default to caution, not confidence.",
            ] },
          ],
          quiz: [
            { id: "q1", type: "mcq", prompt: "Which group of herbs sits in the 'better-supported' tier for their best-studied use?", options: [
              { id: "a", text: "Ginger (nausea) and enteric-coated peppermint oil (IBS)", correct: true, explanation: "Correct — both have multiple supportive human trials." },
              { id: "b", text: "Echinacea (cold prevention) and astragalus (immune tonic)", correct: false, explanation: "Those are weaker/mostly traditional." },
              { id: "c", text: "Any herb sold in a pharmacy", correct: false, explanation: "Being sold says nothing about evidence." },
              { id: "d", text: "Whatever has the most reviews online", correct: false, explanation: "Popularity isn't evidence." },
            ] },
            { id: "q2", type: "true-false", prompt: "Long traditional use, by itself, proves an herb is effective and safe.", options: [
              { id: "t", text: "True", correct: false, explanation: "No — tradition is a hypothesis; bloodletting was traditional too." },
              { id: "f", text: "False", correct: true, explanation: "Correct — tradition flags candidates; evidence tests them." },
            ] },
            { id: "q3", type: "mcq", prompt: "Which is a RED FLAG that an herbal claim is overblown?", options: [
              { id: "a", text: "It promises to 'cure' a serious disease and cites only testimonials", correct: true, explanation: "Correct — disease cures plus testimonials are classic warning signs." },
              { id: "b", text: "It cites several human randomized trials", correct: false, explanation: "That's a sign of stronger evidence, not a red flag." },
              { id: "c", text: "It says evidence is limited and more study is needed", correct: false, explanation: "That's honest framing, not a red flag." },
              { id: "d", text: "It lists known interactions", correct: false, explanation: "Disclosing interactions is responsible." },
            ] },
            { id: "q4", type: "true-false", prompt: "If an herb has little research, that absence proves it is safe.", options: [
              { id: "t", text: "True", correct: false, explanation: "No — understudied is not the same as proven safe." },
              { id: "f", text: "False", correct: true, explanation: "Correct — thin evidence means uncertainty; default to caution." },
            ] },
            { id: "q5", type: "mcq", prompt: "A neutral place to check a specific herb's safety and interactions is…", options: [
              { id: "a", text: "NIH's NCCIH/MedlinePlus, or a pharmacist", correct: true, explanation: "Correct — balanced, non-commercial sources and a pharmacist for interactions." },
              { id: "b", text: "The brand's own advertising", correct: false, explanation: "Marketing isn't a neutral source." },
              { id: "c", text: "A single five-star product review", correct: false, explanation: "A testimonial isn't evidence." },
              { id: "d", text: "A social-media 'cure' thread", correct: false, explanation: "Not reliable." },
            ] },
          ],
        },
      ],
    },
    {
      id: "m3",
      title: "Safety First",
      lessons: [
        {
          id: "l7-interactions",
          title: "Herb–drug interactions",
          objective: "Recognize common herb–drug interaction patterns and the safe habit around them.",
          estMinutes: 6,
          blocks: [
            { kind: "text", text: "Herb–drug interactions are the most common way herbs cause real harm. They fall into a few recognizable patterns. You don't need to memorize every pair — you need the patterns, plus the habit of checking." },
            { kind: "callout", tone: "safety", title: "Pattern 1 — increased BLEEDING risk", text: "Several herbs can add to the effect of blood thinners (warfarin, apixaban, aspirin, etc.) or affect platelets: ginkgo, garlic (high dose), high-dose ginger, ginseng, and fish oil. Combined with anticoagulants, or before surgery, this raises bleeding risk." },
            { kind: "callout", tone: "safety", title: "Pattern 2 — changing how drugs are cleared", text: "St John's wort SPEEDS UP drug metabolism (CYP3A4/P-gp), reducing the effectiveness of many medications — including birth control. Grapefruit (not a herb, but worth knowing) does the OPPOSITE: it blocks the same enzyme, raising drug levels and the risk of toxicity for statins, some blood-pressure drugs, and others." },
            { kind: "callout", tone: "safety", title: "Pattern 3 — additive effects", text: "Sedating herbs (valerian, kava) add to alcohol and CNS depressants. Licorice (glycyrrhizin) can raise blood pressure and lower potassium, opposing blood-pressure and heart medications and worsening effects of some diuretics. Herbs that affect blood sugar can stack with diabetes medication, risking lows." },
            { kind: "table", headers: ["Herb", "Watch out with", "Why"], rows: [
              ["St John's wort", "Birth control, SSRIs, many drugs", "Speeds clearance / serotonin effects"],
              ["Ginkgo, garlic, high-dose ginger", "Blood thinners; surgery", "Added bleeding risk"],
              ["Licorice (glycyrrhizin)", "BP & heart meds, diuretics", "Raises BP, lowers potassium"],
              ["Valerian, kava", "Alcohol, sedatives", "Additive sedation"],
              ["Grapefruit (fruit, not herb)", "Statins, some BP/heart drugs", "Blocks CYP3A4 — raises drug levels"],
            ] },
            { kind: "callout", tone: "tip", title: "The safe habit", text: "Before combining any herb with a prescription medication, ask a pharmacist — they can check interactions in seconds, for free. Always tell ALL your doctors which supplements you take, and mention herbs before any surgery or procedure." },
            { kind: "keyfacts", items: [
              "Bleeding-risk herbs: ginkgo, garlic, high-dose ginger, ginseng, fish oil.",
              "St John's wort lowers drug levels; grapefruit raises them.",
              "Licorice raises blood pressure and lowers potassium.",
              "Check with a pharmacist before combining; disclose herbs before surgery.",
            ] },
          ],
          quiz: [
            { id: "q1", type: "mcq", prompt: "Which herbs can increase bleeding risk with blood thinners?", options: [
              { id: "a", text: "Ginkgo, garlic, and high-dose ginger", correct: true, explanation: "Correct — they can add to anticoagulant effects." },
              { id: "b", text: "Only chamomile", correct: false, explanation: "The bleeding-risk group is ginkgo/garlic/ginger/ginseng/fish oil." },
              { id: "c", text: "No herbs affect bleeding", correct: false, explanation: "Several do." },
              { id: "d", text: "Only peppermint", correct: false, explanation: "Peppermint isn't the bleeding-risk concern." },
            ] },
            { id: "q2", type: "mcq", prompt: "The safest habit before combining a herb with medication is to…", options: [
              { id: "a", text: "Ask a pharmacist to check for interactions", correct: true, explanation: "Yes — quick, free, and reliable." },
              { id: "b", text: "Guess based on a blog", correct: false, explanation: "Not safe or reliable." },
              { id: "c", text: "Take double the dose", correct: false, explanation: "Never — that increases risk." },
              { id: "d", text: "Stop the medication and use only the herb", correct: false, explanation: "Dangerous — never swap a prescribed drug for an herb on your own." },
            ] },
            { id: "q3", type: "true-false", prompt: "You should tell your doctors which supplements you take.", options: [
              { id: "t", text: "True", correct: true, explanation: "Correct — it helps them keep you safe." },
              { id: "f", text: "False", correct: false, explanation: "Always disclose supplements." },
            ] },
            { id: "q4", type: "mcq", prompt: "Grapefruit differs from St John's wort because grapefruit…", options: [
              { id: "a", text: "Blocks CYP3A4, RAISING drug levels (toxicity risk)", correct: true, explanation: "Correct — the opposite direction from St John's wort, which speeds clearance." },
              { id: "b", text: "Speeds up drug clearance like St John's wort", correct: false, explanation: "No — grapefruit blocks the enzyme, raising levels." },
              { id: "c", text: "Has no effect on any drug", correct: false, explanation: "Grapefruit has well-known interactions." },
              { id: "d", text: "Is the same as St John's wort", correct: false, explanation: "Their effects are opposite." },
            ] },
            { id: "q5", type: "recall", prompt: "Which sweet root herb can raise blood pressure and lower potassium (via glycyrrhizin), interacting with heart and BP medications?", options: [], answer: "licorice", accept: ["liquorice", "licorice root", "glycyrrhiza"], explanation: "Licorice (glycyrrhizin) — a reason people with hypertension or heart conditions should be cautious." },
            { id: "q6", type: "true-false", prompt: "It's fine to replace a prescribed medication with an herb on your own as long as the herb is 'natural.'", options: [
              { id: "t", text: "True", correct: false, explanation: "No — never substitute an herb for a prescribed drug without your prescriber's guidance." },
              { id: "f", text: "False", correct: true, explanation: "Correct — swapping a prescribed drug for an herb can be dangerous." },
            ] },
          ],
        },
        {
          id: "l8-pregnancy",
          title: "Pregnancy & breastfeeding",
          objective: "Apply extra caution with herbs during pregnancy, breastfeeding, and in children.",
          estMinutes: 5,
          blocks: [
            { kind: "text", text: "Pregnancy, breastfeeding, infancy, and early childhood are the highest-caution windows in herbalism. A developing baby is exposed to whatever crosses the placenta or passes into breast milk, and most herbs simply have not been studied in these groups — so 'we don't know' is common, and caution is the default." },
            { kind: "callout", tone: "safety", title: "Pregnancy — herbs to avoid in medicinal amounts", text: "Some herbs can stimulate the uterus, affect hormones, or harm a developing baby and should be avoided in medicinal/concentrated amounts — for example blue cohosh, black cohosh, pennyroyal (dangerous; has caused poisoning and deaths), mugwort, rue, tansy, wormwood, and high-dose licorice. Never use an herb to try to end or 'bring on' a pregnancy — so-called abortifacient herbs like pennyroyal are toxic and potentially fatal." },
            { kind: "callout", tone: "safety", title: "Breastfeeding & infants", text: "Herbs can pass into breast milk, and infants are especially vulnerable — for example, plants containing pyrrolizidine alkaloids (comfrey, coltsfoot) can damage an infant's liver. Avoid giving herbal products to babies and young children except on professional advice, and be cautious with herbal teas while nursing." },
            { kind: "callout", tone: "tip", title: "Dose and food vs medicine", text: "Culinary amounts of common herbs and spices in food are generally fine in pregnancy. The concern is concentrated medicinal doses, supplements, strong teas, and tinctures. Ginger in moderate amounts is generally considered acceptable for pregnancy nausea — but confirm the dose with your clinician." },
            { kind: "callout", tone: "safety", title: "The default rule", text: "When pregnant, trying to conceive, breastfeeding, or treating a child, clear ANY herbal remedy with your doctor, midwife, or pharmacist first. 'Untested' should be read as 'avoid unless cleared,' not 'probably fine.'" },
            { kind: "keyfacts", items: [
              "Avoid uterine-stimulant/abortifacient herbs (pennyroyal, blue/black cohosh, rue, tansy).",
              "Pennyroyal is genuinely toxic — never used to 'bring on' a period or end pregnancy.",
              "Comfrey/coltsfoot (pyrrolizidine alkaloids) can harm an infant's liver.",
              "Culinary amounts are usually fine; concentrated doses are the concern — clear them first.",
            ] },
          ],
          quiz: [
            { id: "q1", type: "mcq", prompt: "Which class of herbs is a particular concern in pregnancy?", options: [
              { id: "a", text: "Uterine stimulants like pennyroyal and blue cohosh", correct: true, explanation: "Correct — avoid these in medicinal amounts." },
              { id: "b", text: "All culinary spices in food", correct: false, explanation: "Food amounts are generally fine; concentrates are the concern." },
              { id: "c", text: "None — anything goes", correct: false, explanation: "Several herbs are unsafe in pregnancy." },
              { id: "d", text: "Only herbs that taste bitter", correct: false, explanation: "Taste isn't the criterion." },
            ] },
            { id: "q2", type: "mcq", prompt: "During pregnancy, the safest approach to herbal remedies is to…", options: [
              { id: "a", text: "Clear them with a doctor or midwife first", correct: true, explanation: "Yes — caution is the default." },
              { id: "b", text: "Assume all are safe", correct: false, explanation: "Many are untested or unsafe." },
              { id: "c", text: "Take the strongest dose", correct: false, explanation: "Never — that raises risk." },
              { id: "d", text: "Use only what's marketed as 'natural'", correct: false, explanation: "'Natural' doesn't mean safe in pregnancy." },
            ] },
            { id: "q3", type: "true-false", prompt: "Concentrated medicinal doses carry more risk in pregnancy than culinary amounts.", options: [
              { id: "t", text: "True", correct: true, explanation: "Correct — dose matters." },
              { id: "f", text: "False", correct: false, explanation: "Concentrated doses are the concern." },
            ] },
            { id: "q4", type: "recall", prompt: "Name one herb that is dangerously toxic and must never be used to try to end or 'bring on' a pregnancy.", options: [], answer: "pennyroyal", accept: ["pennyroyal", "blue cohosh", "tansy", "rue"], explanation: "Pennyroyal (also blue cohosh, tansy, rue) — these so-called abortifacient herbs are toxic and have caused poisonings and deaths." },
            { id: "q5", type: "mcq", prompt: "Why are comfrey and coltsfoot especially unsafe around infants and in pregnancy/breastfeeding?", options: [
              { id: "a", text: "They contain pyrrolizidine alkaloids that can damage the liver", correct: true, explanation: "Correct — infants are particularly susceptible to this liver toxicity." },
              { id: "b", text: "They are stimulants that prevent sleep", correct: false, explanation: "The concern is liver toxicity, not stimulation." },
              { id: "c", text: "They have no active compounds", correct: false, explanation: "They have toxic ones." },
              { id: "d", text: "They only affect adults", correct: false, explanation: "Infants are especially vulnerable." },
            ] },
            { id: "q6", type: "true-false", prompt: "It is safe to give any herbal product to a baby as long as it's labeled 'gentle' or 'for children.'", options: [
              { id: "t", text: "True", correct: false, explanation: "No — avoid herbal products in infants/young children except on professional advice." },
              { id: "f", text: "False", correct: true, explanation: "Correct — children's herbal products still need professional guidance." },
            ] },
          ],
        },
        {
          id: "l12-sourcing-quality",
          title: "Sourcing, quality & adulteration",
          objective: "Judge herbal product quality and recognize the risks of contamination and adulteration.",
          estMinutes: 5,
          blocks: [
            { kind: "text", text: "Because herbal supplements are lightly regulated, what's in the bottle doesn't always match the label. Independent testing has repeatedly found products that are mislabeled, contaminated, or substituted with cheaper plants. Knowing how to source well is a core safety skill, not a nicety." },
            { kind: "callout", tone: "safety", title: "What can go wrong in a bottle", text: "Documented problems include: the wrong species (substitution with a cheaper or different plant), 'fillers' instead of the listed herb, contamination with heavy metals (lead, arsenic, mercury) — a known issue in some imported and traditional products — pesticides or microbes, and the most dangerous: deliberate adulteration with hidden PRESCRIPTION DRUGS (e.g. sildenafil in 'sexual enhancement' products, steroids or stimulants in 'weight-loss' or 'workout' products)." },
            { kind: "callout", tone: "evidence", title: "How quality is actually verified", text: "Reputable manufacturers test raw material identity (including DNA/chemical methods) and finished products for potency and contaminants. The strongest independent signals for a buyer are third-party seals: USP Verified, NSF, or ConsumerLab — these confirm the product contains what the label says and is free of unacceptable contaminants. They are voluntary, so their absence isn't proof of a bad product, but their presence is a meaningful plus." },
            { kind: "table", headers: ["Good sign", "Warning sign"], rows: [
              ["Third-party seal (USP, NSF, ConsumerLab)", "Miracle 'cure-all' or rapid weight-loss claims"],
              ["Clear Latin (botanical) name & plant part", "Only a vague common name; no plant part listed"],
              ["Lot number, expiry, contact info", "No lot/expiry; no way to reach the company"],
              ["Standardized/known amount per dose", "Vague 'proprietary blend' hiding amounts"],
              ["Established maker, transparent sourcing", "Imported 'traditional' remedy with unknown contents"],
            ] },
            { kind: "callout", tone: "safety", title: "Highest-risk categories", text: "Products marketed for weight loss, 'sexual enhancement', bodybuilding, and 'detox' are the categories most often found spiked with hidden pharmaceuticals or banned stimulants. Treat dramatic promises in these areas as a danger signal, not a selling point." },
            { kind: "callout", tone: "tip", title: "Practical buying habits", text: "Prefer products with a third-party seal; look for the botanical name and plant part; avoid 'proprietary blends' that hide amounts; be wary of unusually cheap or unusually hyped products; and when in doubt, ask a pharmacist." },
            { kind: "keyfacts", items: [
              "Lightly regulated = label may not match contents; testing has found mislabeling.",
              "Risks: wrong species, heavy metals, pesticides, and hidden prescription drugs.",
              "Third-party seals (USP, NSF, ConsumerLab) are the strongest buyer signal.",
              "Weight-loss, 'enhancement', and 'detox' products are highest-risk for adulteration.",
            ] },
          ],
          quiz: [
            { id: "q1", type: "mcq", prompt: "Which is the STRONGEST independent signal that a supplement contains what its label says?", options: [
              { id: "a", text: "A third-party seal such as USP Verified, NSF, or ConsumerLab", correct: true, explanation: "Correct — these voluntary certifications verify identity, potency, and purity." },
              { id: "b", text: "A 'cures everything' claim on the box", correct: false, explanation: "That's a red flag, not a quality signal." },
              { id: "c", text: "The lowest price available", correct: false, explanation: "Cheapness isn't a quality signal." },
              { id: "d", text: "A 'proprietary blend' label", correct: false, explanation: "Proprietary blends hide amounts — a warning sign." },
            ] },
            { id: "q2", type: "mcq", prompt: "Which product category is MOST often found adulterated with hidden prescription drugs?", options: [
              { id: "a", text: "Weight-loss, 'sexual enhancement', and bodybuilding products", correct: true, explanation: "Correct — these are repeatedly found spiked with hidden pharmaceuticals." },
              { id: "b", text: "Plain culinary spices", correct: false, explanation: "Not the high-risk category here." },
              { id: "c", text: "A single-herb tea with a botanical name", correct: false, explanation: "Lower risk than the hyped categories." },
              { id: "d", text: "USP-verified products", correct: false, explanation: "Verification lowers this risk." },
            ] },
            { id: "q3", type: "true-false", prompt: "Independent testing has found herbal products that are mislabeled, contaminated, or substituted with other plants.", options: [
              { id: "t", text: "True", correct: true, explanation: "Correct — this is a well-documented problem in a lightly regulated market." },
              { id: "f", text: "False", correct: false, explanation: "It's well documented; quality genuinely varies." },
            ] },
            { id: "q4", type: "mcq", prompt: "On a label, which is a WARNING sign rather than a good sign?", options: [
              { id: "a", text: "A 'proprietary blend' that hides how much of each herb is included", correct: true, explanation: "Correct — hidden amounts make dosing and safety opaque." },
              { id: "b", text: "The botanical (Latin) name and plant part", correct: false, explanation: "That's a good sign of a careful product." },
              { id: "c", text: "A lot number and expiry date", correct: false, explanation: "Those are good signs." },
              { id: "d", text: "A third-party verification seal", correct: false, explanation: "That's a good sign." },
            ] },
            { id: "q5", type: "true-false", prompt: "Because they're 'natural,' herbal products can't be contaminated with heavy metals like lead.", options: [
              { id: "t", text: "True", correct: false, explanation: "No — heavy-metal contamination is a documented problem, especially in some imported products." },
              { id: "f", text: "False", correct: true, explanation: "Correct — natural products can carry lead, arsenic, mercury, pesticides, and more." },
            ] },
          ],
        },
        {
          id: "l9-clinician",
          title: "When to see a clinician, not a herb",
          objective: "Recognize when to seek medical care rather than self-treat.",
          estMinutes: 5,
          blocks: [
            { kind: "text", text: "Herbalism can support everyday wellbeing — easing mild, self-limiting complaints, adding ritual and comfort, and complementing a healthy lifestyle. But it has firm limits. Some situations need a professional, not a tea, and recognizing them is the most important safety judgment of all." },
            { kind: "callout", tone: "safety", title: "Seek urgent care for", text: "Chest pain or pressure; trouble breathing; sudden weakness, facial droop, or slurred speech (stroke signs); severe or worsening pain; a high or persistent fever; severe allergic reaction (swelling, hives, throat tightness); confusion or fainting; uncontrolled bleeding; or thoughts of self-harm. These are emergencies — call emergency services, don't reach for a herb." },
            { kind: "callout", tone: "safety", title: "See a clinician (not just a herb) for", text: "Symptoms that are severe, persistent, or worsening; a suspected infection; anything affecting a baby or young child; any serious or chronic condition (diabetes, heart disease, cancer, mental-health conditions); a new or unexplained symptom; or before stopping/changing any prescribed medication. Herbs are not a substitute for diagnosis and treatment." },
            { kind: "callout", tone: "tip", title: "Use both wisely", text: "The healthiest approach treats herbs as a COMPLEMENT to — not a replacement for — professional care, and keeps your medical team in the loop about everything you take. 'Integrative' done well means more information shared, not less." },
            { kind: "callout", tone: "evidence", title: "This course is education, not medical advice", text: "Everything here is for learning. It is not a diagnosis or a treatment plan, and it can't account for your personal health, medications, or circumstances. For anything affecting your health, consult a qualified professional — and a pharmacist is an excellent, accessible first stop for interaction questions." },
            { kind: "keyfacts", items: [
              "Emergencies (chest pain, breathing trouble, stroke signs) → call emergency services.",
              "Severe, persistent, worsening, or serious/chronic conditions → see a clinician.",
              "Herbs complement professional care; they don't replace it.",
              "This is education, not medical advice — consult a professional/pharmacist.",
            ] },
          ],
          quiz: [
            { id: "q1", type: "mcq", prompt: "Which situation calls for a clinician rather than self-treating with herbs?", options: [
              { id: "a", text: "Chest pain or trouble breathing", correct: true, explanation: "Correct — that needs urgent medical care." },
              { id: "b", text: "Wanting a calming evening tea", correct: false, explanation: "That's a fine everyday use." },
              { id: "c", text: "Mild seasonal sniffles you're managing", correct: false, explanation: "Not necessarily urgent." },
              { id: "d", text: "Curiosity about how an herb tastes", correct: false, explanation: "Not a medical situation." },
            ] },
            { id: "q2", type: "mcq", prompt: "The healthiest role for herbalism is as…", options: [
              { id: "a", text: "A complement to professional care, not a replacement", correct: true, explanation: "Yes — use both, and keep your team informed." },
              { id: "b", text: "A full replacement for doctors", correct: false, explanation: "Herbs can't replace medical care." },
              { id: "c", text: "A cure for everything", correct: false, explanation: "No remedy cures everything." },
              { id: "d", text: "A reason to stop prescribed medication", correct: false, explanation: "Never stop prescribed meds on your own." },
            ] },
            { id: "q3", type: "true-false", prompt: "Herbs are an appropriate substitute for diagnosing a serious condition.", options: [
              { id: "t", text: "True", correct: false, explanation: "No — serious symptoms need a professional." },
              { id: "f", text: "False", correct: true, explanation: "Correct — see a clinician for those." },
            ] },
            { id: "q4", type: "mcq", prompt: "Which set of symptoms is a medical EMERGENCY (call emergency services)?", options: [
              { id: "a", text: "Sudden facial droop, slurred speech, and one-sided weakness", correct: true, explanation: "Correct — these are stroke warning signs; act fast." },
              { id: "b", text: "Mild after-dinner bloating", correct: false, explanation: "Not an emergency." },
              { id: "c", text: "Wanting better sleep this week", correct: false, explanation: "Not an emergency." },
              { id: "d", text: "A slightly bitter taste from a tea", correct: false, explanation: "Not an emergency." },
            ] },
            { id: "q5", type: "true-false", prompt: "This course can serve as personalized medical advice for your specific health situation.", options: [
              { id: "t", text: "True", correct: false, explanation: "No — it's education, not a diagnosis or treatment plan; consult a professional." },
              { id: "f", text: "False", correct: true, explanation: "Correct — for your health, consult a qualified professional or pharmacist." },
            ] },
          ],
        },
      ],
    },
  ],

  finalTest: [
    { id: "f1", type: "mcq", prompt: "In the US, herbal supplements are…", options: [
      { id: "a", text: "Regulated as foods, not FDA-approved like drugs", correct: true },
      { id: "b", text: "Pre-approved by the FDA for safety", correct: false },
      { id: "c", text: "Illegal", correct: false },
      { id: "d", text: "Standardized to exact doses by law", correct: false },
    ] },
    { id: "f2", type: "mcq", prompt: "'Natural' means…", options: [
      { id: "a", text: "Not necessarily safe, standardized, or effective", correct: true },
      { id: "b", text: "Always safe", correct: false },
      { id: "c", text: "Always effective", correct: false },
      { id: "d", text: "FDA-approved", correct: false },
    ] },
    { id: "f3", type: "mcq", prompt: "A tincture extracts a herb in…", options: [
      { id: "a", text: "Alcohol", correct: true },
      { id: "b", text: "Hot water", correct: false },
      { id: "c", text: "Oil", correct: false },
      { id: "d", text: "Vinegar only", correct: false },
    ] },
    { id: "f4", type: "mcq", prompt: "A decoction is best for extracting…", options: [
      { id: "a", text: "Tough roots, bark, and seeds (by simmering)", correct: true },
      { id: "b", text: "Delicate flowers (which lose aromatics if boiled)", correct: false },
      { id: "c", text: "Nothing — it's not a real method", correct: false },
      { id: "d", text: "Only essential oils", correct: false },
    ] },
    { id: "f5", type: "mcq", prompt: "Ginger has good evidence for…", options: [
      { id: "a", text: "Reducing nausea", correct: true },
      { id: "b", text: "Curing infections", correct: false },
      { id: "c", text: "Improving vision", correct: false },
      { id: "d", text: "Healing bones", correct: false },
    ] },
    { id: "f6", type: "mcq", prompt: "Enteric-coated peppermint oil is evidenced for…", options: [
      { id: "a", text: "IBS symptoms", correct: true },
      { id: "b", text: "Lowering cholesterol", correct: false },
      { id: "c", text: "Curing colds", correct: false },
      { id: "d", text: "Bone healing", correct: false },
    ] },
    { id: "f7", type: "mcq", prompt: "Peppermint can be a problem for some people because it may…", options: [
      { id: "a", text: "Relax the esophageal sphincter and worsen acid reflux", correct: true },
      { id: "b", text: "Cause radioactivity", correct: false },
      { id: "c", text: "Always cure reflux", correct: false },
      { id: "d", text: "Make herbs illegal", correct: false },
    ] },
    { id: "f8", type: "mcq", prompt: "The evidence for echinacea against colds is…", options: [
      { id: "a", text: "Weak and inconsistent", correct: true },
      { id: "b", text: "Strong and conclusive", correct: false },
      { id: "c", text: "Proof it cures flu", correct: false },
      { id: "d", text: "Proof it replaces a vaccine", correct: false },
    ] },
    { id: "f9", type: "mcq", prompt: "A practical limitation of turmeric/curcumin is that it…", options: [
      { id: "a", text: "Is poorly absorbed on its own", correct: true },
      { id: "b", text: "Is radioactive", correct: false },
      { id: "c", text: "Is illegal to buy", correct: false },
      { id: "d", text: "Works only by injection", correct: false },
    ] },
    { id: "f10", type: "mcq", prompt: "St John's wort can REDUCE the effectiveness of…", options: [
      { id: "a", text: "Hormonal birth control and many drugs", correct: true },
      { id: "b", text: "Nothing", correct: false },
      { id: "c", text: "Only food", correct: false },
      { id: "d", text: "Water", correct: false },
    ] },
    { id: "f11", type: "mcq", prompt: "St John's wort + SSRIs risks…", options: [
      { id: "a", text: "Serotonin syndrome", correct: true },
      { id: "b", text: "Better sleep only", correct: false },
      { id: "c", text: "No effect", correct: false },
      { id: "d", text: "Improved vision", correct: false },
    ] },
    { id: "f12", type: "mcq", prompt: "St John's wort lowers other drug levels mainly by…", options: [
      { id: "a", text: "Inducing liver enzymes (CYP3A4) and P-glycoprotein", correct: true },
      { id: "b", text: "Blocking the stomach entirely", correct: false },
      { id: "c", text: "Neutralizing drugs in the bottle", correct: false },
      { id: "d", text: "Having no real mechanism", correct: false },
    ] },
    { id: "f13", type: "mcq", prompt: "Which herbs increase bleeding risk with blood thinners?", options: [
      { id: "a", text: "Ginkgo, garlic, high-dose ginger", correct: true },
      { id: "b", text: "Only chamomile", correct: false },
      { id: "c", text: "None", correct: false },
      { id: "d", text: "Only peppermint", correct: false },
    ] },
    { id: "f14", type: "mcq", prompt: "Grapefruit (vs St John's wort) tends to…", options: [
      { id: "a", text: "Block CYP3A4 and RAISE drug levels", correct: true },
      { id: "b", text: "Speed drug clearance like St John's wort", correct: false },
      { id: "c", text: "Have no drug interactions", correct: false },
      { id: "d", text: "Cure all infections", correct: false },
    ] },
    { id: "f15", type: "mcq", prompt: "Licorice (glycyrrhizin) can…", options: [
      { id: "a", text: "Raise blood pressure and lower potassium", correct: true },
      { id: "b", text: "Lower blood pressure to zero risk", correct: false },
      { id: "c", text: "Cure heart disease", correct: false },
      { id: "d", text: "Have no effect on the body", correct: false },
    ] },
    { id: "f16", type: "mcq", prompt: "Which is a uterine-stimulant herb to avoid in pregnancy?", options: [
      { id: "a", text: "Pennyroyal", correct: true },
      { id: "b", text: "Culinary basil in food", correct: false },
      { id: "c", text: "Chamomile tea", correct: false },
      { id: "d", text: "Peppermint", correct: false },
    ] },
    { id: "f17", type: "mcq", prompt: "Why are comfrey and coltsfoot unsafe taken internally, especially for infants?", options: [
      { id: "a", text: "Their pyrrolizidine alkaloids can damage the liver", correct: true },
      { id: "b", text: "They are stimulants only", correct: false },
      { id: "c", text: "They contain no active compounds", correct: false },
      { id: "d", text: "They only affect plants", correct: false },
    ] },
    { id: "f18", type: "mcq", prompt: "Before combining a herb with medication, you should…", options: [
      { id: "a", text: "Ask a pharmacist to check interactions", correct: true },
      { id: "b", text: "Double the dose", correct: false },
      { id: "c", text: "Guess", correct: false },
      { id: "d", text: "Stop all your medications", correct: false },
    ] },
    { id: "f19", type: "mcq", prompt: "The strongest independent signal of supplement quality is…", options: [
      { id: "a", text: "A third-party seal (USP, NSF, or ConsumerLab)", correct: true },
      { id: "b", text: "A 'cures everything' claim", correct: false },
      { id: "c", text: "The lowest price", correct: false },
      { id: "d", text: "A 'proprietary blend' label", correct: false },
    ] },
    { id: "f20", type: "mcq", prompt: "Which product category is most often adulterated with hidden prescription drugs?", options: [
      { id: "a", text: "Weight-loss and 'sexual enhancement' products", correct: true },
      { id: "b", text: "Plain culinary spices", correct: false },
      { id: "c", text: "USP-verified single herbs", correct: false },
      { id: "d", text: "Tap water", correct: false },
    ] },
    { id: "f21", type: "mcq", prompt: "A 'carminative' herb is traditionally used to…", options: [
      { id: "a", text: "Relieve gas and bloating", correct: true },
      { id: "b", text: "Promote sweating", correct: false },
      { id: "c", text: "Soothe with mucilage", correct: false },
      { id: "d", text: "Thin the blood", correct: false },
    ] },
    { id: "f22", type: "mcq", prompt: "How should you treat long traditional use as evidence?", options: [
      { id: "a", text: "As a useful hypothesis to be tested, not proof of safety/effect", correct: true },
      { id: "b", text: "As conclusive proof it works", correct: false },
      { id: "c", text: "As proof it is safe in pregnancy", correct: false },
      { id: "d", text: "As irrelevant and worthless", correct: false },
    ] },
    { id: "f23", type: "mcq", prompt: "Which calls for a clinician, not herbs?", options: [
      { id: "a", text: "Chest pain or trouble breathing", correct: true },
      { id: "b", text: "Wanting a calming tea", correct: false },
      { id: "c", text: "Mild sniffles", correct: false },
      { id: "d", text: "Curiosity about herbs", correct: false },
    ] },
    { id: "f24", type: "true-false", prompt: "Sedating herbs like valerian can add to the effect of alcohol and sleep meds.", options: [
      { id: "t", text: "True", correct: true },
      { id: "f", text: "False", correct: false },
    ] },
    { id: "f25", type: "true-false", prompt: "Culinary amounts of herbs in food carry the same risk as concentrated extracts.", options: [
      { id: "t", text: "True", correct: false },
      { id: "f", text: "False", correct: true },
    ] },
    { id: "f26", type: "true-false", prompt: "Herbs can substitute for diagnosing and treating a serious condition.", options: [
      { id: "t", text: "True", correct: false },
      { id: "f", text: "False", correct: true },
    ] },
    { id: "f27", type: "true-false", prompt: "You should tell your doctors which supplements you take.", options: [
      { id: "t", text: "True", correct: true },
      { id: "f", text: "False", correct: false },
    ] },
    { id: "f28", type: "true-false", prompt: "It's safe to swap a prescribed medication for an herb on your own because the herb is 'natural.'", options: [
      { id: "t", text: "True", correct: false },
      { id: "f", text: "False", correct: true },
    ] },
    { id: "f29", type: "true-false", prompt: "Because herbal supplements are lightly regulated, what's in the bottle doesn't always match the label.", options: [
      { id: "t", text: "True", correct: true },
      { id: "f", text: "False", correct: false },
    ] },
  ],
};
