// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}


// Validate ../../src/app/(tabs)/dolly/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dolly">> = Specific
  const handler = {} as typeof import("../../src/app/(tabs)/dolly/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(tabs)/home/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/home">> = Specific
  const handler = {} as typeof import("../../src/app/(tabs)/home/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(tabs)/learn/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/learn">> = Specific
  const handler = {} as typeof import("../../src/app/(tabs)/learn/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(tabs)/maps/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/maps">> = Specific
  const handler = {} as typeof import("../../src/app/(tabs)/maps/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(tabs)/practice/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/practice">> = Specific
  const handler = {} as typeof import("../../src/app/(tabs)/practice/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(tabs)/tarot/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/tarot">> = Specific
  const handler = {} as typeof import("../../src/app/(tabs)/tarot/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(tabs)/you/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/you">> = Specific
  const handler = {} as typeof import("../../src/app/(tabs)/you/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/account/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/account">> = Specific
  const handler = {} as typeof import("../../src/app/account/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/almanac/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/almanac">> = Specific
  const handler = {} as typeof import("../../src/app/almanac/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/auth/verify/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/auth/verify">> = Specific
  const handler = {} as typeof import("../../src/app/auth/verify/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/chart/new/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/chart/new">> = Specific
  const handler = {} as typeof import("../../src/app/chart/new/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/chart/result/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/chart/result">> = Specific
  const handler = {} as typeof import("../../src/app/chart/result/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/journal/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/journal">> = Specific
  const handler = {} as typeof import("../../src/app/journal/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/onboarding/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/onboarding">> = Specific
  const handler = {} as typeof import("../../src/app/onboarding/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/account/delete/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/account/delete">> = Specific
  const handler = {} as typeof import("../../src/app/api/account/delete/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/astrocartography/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/astrocartography">> = Specific
  const handler = {} as typeof import("../../src/app/api/astrocartography/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/chart/calculate/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/chart/calculate">> = Specific
  const handler = {} as typeof import("../../src/app/api/chart/calculate/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/chart/interpret/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/chart/interpret">> = Specific
  const handler = {} as typeof import("../../src/app/api/chart/interpret/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/chart/solar-return/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/chart/solar-return">> = Specific
  const handler = {} as typeof import("../../src/app/api/chart/solar-return/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/composite/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/composite">> = Specific
  const handler = {} as typeof import("../../src/app/api/composite/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/dolly/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/dolly">> = Specific
  const handler = {} as typeof import("../../src/app/api/dolly/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/dolly/test/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/dolly/test">> = Specific
  const handler = {} as typeof import("../../src/app/api/dolly/test/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/horoscope/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/horoscope">> = Specific
  const handler = {} as typeof import("../../src/app/api/horoscope/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/journal/prompt/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/journal/prompt">> = Specific
  const handler = {} as typeof import("../../src/app/api/journal/prompt/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/journal/reflect/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/journal/reflect">> = Specific
  const handler = {} as typeof import("../../src/app/api/journal/reflect/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/seed-special-points/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/seed-special-points">> = Specific
  const handler = {} as typeof import("../../src/app/api/seed-special-points/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/synastry/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/synastry">> = Specific
  const handler = {} as typeof import("../../src/app/api/synastry/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/transits/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/transits">> = Specific
  const handler = {} as typeof import("../../src/app/api/transits/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/wizard/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/wizard">> = Specific
  const handler = {} as typeof import("../../src/app/api/wizard/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/auth/callback/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/auth/callback">> = Specific
  const handler = {} as typeof import("../../src/app/auth/callback/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}





// Validate ../../src/app/(tabs)/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/(tabs)/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
