var R=require("../../../chunks/ssr/[turbopack]_runtime.js")("server/app/(tabs)/learn/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__0ib~1g2._.js")
R.c("server/chunks/ssr/node_modules_0vtdjw7._.js")
R.c("server/chunks/ssr/node_modules_next_dist_esm_build_templates_app-page_0tez5fk.js")
R.c("server/chunks/ssr/[root-of-the-server]__0k9p-1d._.js")
R.c("server/chunks/ssr/node_modules_next_dist_03nkrli._.js")
R.c("server/chunks/ssr/src_app_layout_tsx_0fhx__n._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_0inhx6q._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_0ghu-f7.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_0cjv-23.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_0lgvd_..js")
R.c("server/chunks/ssr/src_app_(tabs)_layout_tsx_0q.j9wb._.js")
R.c("server/chunks/ssr/_next-internal_server_app_(tabs)_learn_page_actions_0s-5sf5.js")
R.m(58227)
module.exports=R.m(58227).exports
