var R=require("../../../chunks/ssr/[turbopack]_runtime.js")("server/app/(tabs)/practice/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__0~1q1li._.js")
R.c("server/chunks/ssr/node_modules_0vtdjw7._.js")
R.c("server/chunks/ssr/node_modules_next_dist_esm_build_templates_app-page_0ybawtd.js")
R.c("server/chunks/ssr/[root-of-the-server]__0fidn8g._.js")
R.c("server/chunks/ssr/[root-of-the-server]__09z7o2x._.js")
R.c("server/chunks/ssr/src_0fdke_p._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_0inhx6q._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_0ghu-f7.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_0cjv-23.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_0lgvd_..js")
R.c("server/chunks/ssr/src_app_(tabs)_layout_tsx_0q.j9wb._.js")
R.c("server/chunks/ssr/_next-internal_server_app_(tabs)_practice_page_actions_0j1.7qc.js")
R.m(71412)
module.exports=R.m(71412).exports
