import type { ReferenceEntry } from "../types";

/**
 * Quick-reference crystal lookup. Accurate mineralogy + the traditional
 * associations clearly labelled as tradition, with safety flags on toxic stones.
 * Sourced from docs/learning-library-research.md.
 */

function crystal(e: Omit<ReferenceEntry, "domain">): ReferenceEntry {
  return { domain: "crystals", ...e };
}

export const crystalReference: ReferenceEntry[] = [
  crystal({
    id: "clear-quartz",
    name: "Clear Quartz",
    aka: ["rock crystal"],
    category: "Quartz family",
    summary: "Pure silicon dioxide (SiO₂), the colourless, transparent member of the quartz family that crystallises in hexagonal prisms. Traditionally used as the all-purpose 'master healer' for clarity, focus, and amplifying intention.",
    fields: [
      { label: "What it is", value: "Pure quartz (silicon dioxide, SiO₂) — colorless and transparent." },
      { label: "Hardness", value: "Mohs 7 — hard and durable" },
      { label: "Traditionally for", value: "Clarity, focus, amplifying intention; the 'all-rounder' stone." },
      { label: "Care", value: "Tough and water-safe. Can be cleaned with water or a soft cloth." },
    ],
    tags: ["white", "clear", "amplify", "all purpose"],
  }),
  crystal({
    id: "amethyst",
    name: "Amethyst",
    category: "Quartz family",
    summary: "A violet variety of quartz (SiO₂) whose colour comes from iron impurities activated by natural irradiation. Traditionally used for calm, restful sleep, and clear intuition, its name tracing to a Greek word for not being intoxicated.",
    fields: [
      { label: "What it is", value: "Quartz (SiO₂) — the violet color comes from iron impurities and natural irradiation." },
      { label: "Hardness", value: "Mohs 7" },
      { label: "Traditionally for", value: "Calm, sleep, sobriety, intuition. Its name comes from a Greek word linked to not being intoxicated." },
      { label: "Care", value: "Water-safe, but its color fades in prolonged sunlight — store out of direct sun." },
    ],
    tags: ["purple", "violet", "calm", "sleep"],
  }),
  crystal({
    id: "citrine",
    name: "Citrine",
    category: "Quartz family",
    summary: "A yellow-to-golden variety of quartz (SiO₂); natural citrine is rare, so most on the market is heat-treated amethyst. Traditionally used as the 'success stone' for abundance, confidence, and optimism.",
    fields: [
      { label: "What it is", value: "Quartz (SiO₂). Natural citrine is rare; the vast majority sold (~95%) is heat-treated amethyst." },
      { label: "Hardness", value: "Mohs 7" },
      { label: "Traditionally for", value: "Abundance, confidence, optimism — the 'success stone.'" },
      { label: "Care", value: "Water-safe; color can fade in strong sun." },
    ],
    tags: ["yellow", "gold", "abundance", "heat treated", "amethyst"],
  }),
  crystal({
    id: "rose-quartz",
    name: "Rose Quartz",
    category: "Quartz family",
    summary: "A pink variety of quartz (SiO₂) whose soft hue comes from trace mineral inclusions, often massive rather than well-formed crystals. Traditionally used as the stone of love, compassion, and emotional healing, linked in legend to Aphrodite.",
    fields: [
      { label: "What it is", value: "Quartz (SiO₂) with a pink hue from trace minerals." },
      { label: "Hardness", value: "Mohs 7" },
      { label: "Traditionally for", value: "Love (self-love and relationships), compassion, emotional healing." },
      { label: "Care", value: "Water-safe; the pink fades in prolonged sunlight." },
    ],
    tags: ["pink", "love", "heart", "compassion"],
  }),
  crystal({
    id: "smoky-quartz",
    name: "Smoky Quartz",
    category: "Quartz family",
    summary: "A brown-to-grey variety of quartz (SiO₂) whose smoky colour arises from natural irradiation acting on traces of aluminium. Traditionally used for grounding, protection, and releasing stress.",
    fields: [
      { label: "What it is", value: "Quartz (SiO₂); the smoky color comes from natural irradiation of the crystal." },
      { label: "Hardness", value: "Mohs 7" },
      { label: "Traditionally for", value: "Grounding, protection, releasing stress." },
      { label: "Care", value: "Water-safe and durable." },
    ],
    tags: ["brown", "grey", "grounding", "protection"],
  }),
  crystal({
    id: "selenite",
    name: "Selenite",
    category: "Gypsum",
    summary: "A soft, glassy crystalline form of gypsum (hydrated calcium sulfate, CaSO₄·2H₂O) that is very soft and water-soluble. Traditionally used as a high-vibration stone for cleansing and clearing energy.",
    fields: [
      { label: "What it is", value: "A crystalline form of gypsum (calcium sulfate, CaSO₄·2H₂O)." },
      { label: "Hardness", value: "Mohs 2 — very soft" },
      { label: "Traditionally for", value: "Cleansing, clearing 'energy,' a 'high-vibration' stone." },
      { label: "Care", value: "Keep it DRY — selenite is water-soluble and will be damaged or dissolved by water." },
    ],
    safety: "Never soak selenite in water — it dissolves. Dust it or wipe with a dry cloth only.",
    tags: ["white", "cleansing", "soft", "water soluble"],
  }),
  crystal({
    id: "obsidian",
    name: "Obsidian",
    category: "Volcanic glass",
    summary: "A natural volcanic glass that cooled too fast to form a lattice, making it amorphous rather than a true crystal. Traditionally used for protection, grounding, and facing the 'shadow' self.",
    fields: [
      { label: "What it is", value: "Natural volcanic glass — it cooled too fast to form a lattice, so it's amorphous (no crystal structure)." },
      { label: "Hardness", value: "Mohs ~5–5.5" },
      { label: "Traditionally for", value: "Protection, grounding, facing the 'shadow' self." },
      { label: "Care", value: "Water-safe; edges can be sharp (it was used for blades)." },
    ],
    tags: ["black", "glass", "protection", "shadow"],
  }),
  crystal({
    id: "black-tourmaline",
    name: "Black Tourmaline",
    aka: ["schorl"],
    category: "Tourmaline",
    summary: "Schorl, the black, iron-rich variety of the tourmaline group of complex boron silicate minerals. Traditionally used as the classic stone for protection, grounding, and shielding from negativity.",
    fields: [
      { label: "What it is", value: "Schorl, the black, iron-rich variety of the tourmaline mineral group." },
      { label: "Hardness", value: "Mohs 7–7.5" },
      { label: "Traditionally for", value: "Protection, grounding, shielding from negativity." },
      { label: "Care", value: "Durable and water-safe." },
    ],
    tags: ["black", "protection", "grounding", "schorl"],
  }),
  crystal({
    id: "lapis-lazuli",
    name: "Lapis Lazuli",
    category: "Rock (not a single mineral)",
    summary: "A deep-blue metamorphic rock rather than a single mineral, made mainly of lazurite with flecks of golden pyrite and white calcite. Traditionally used for truth, wisdom, communication, and inner vision.",
    fields: [
      { label: "What it is", value: "A rock — a mix of lazurite (blue), pyrite (gold flecks), and calcite (white)." },
      { label: "Hardness", value: "Mohs ~5–5.5" },
      { label: "Traditionally for", value: "Truth, wisdom, communication, inner vision." },
      { label: "Care", value: "Porous — avoid prolonged water and harsh cleaners." },
    ],
    tags: ["blue", "gold", "truth", "wisdom", "pyrite"],
  }),
  crystal({
    id: "malachite",
    name: "Malachite",
    category: "Copper carbonate",
    summary: "A vivid green copper carbonate hydroxide whose colour comes from its copper content, often banded in concentric layers. Traditionally used for transformation, change, and protection, though its dust is toxic if inhaled or ingested.",
    fields: [
      { label: "What it is", value: "Copper carbonate hydroxide — the green comes from copper." },
      { label: "Hardness", value: "Mohs 3.5–4 — fairly soft" },
      { label: "Traditionally for", value: "Transformation, change, protection." },
      { label: "Care", value: "Never wet raw malachite or breathe its dust; handle polished pieces only and wash hands." },
    ],
    safety: "Toxic. Raw malachite dust and soluble copper are hazardous — never make elixirs, never grind or lick it, and keep it away from water you'll drink.",
    tags: ["green", "copper", "transformation", "toxic"],
  }),
  crystal({
    id: "tigers-eye",
    name: "Tiger's Eye",
    category: "Quartz family",
    summary: "A golden-brown variety of quartz (SiO₂) whose silky, shifting shimmer (chatoyancy) comes from parallel fibrous inclusions. Traditionally used for courage, confidence, willpower, and focus.",
    fields: [
      { label: "What it is", value: "Quartz with fibrous inclusions that create 'chatoyancy' (a shifting band of light)." },
      { label: "Hardness", value: "Mohs 7" },
      { label: "Traditionally for", value: "Courage, confidence, willpower, focus." },
      { label: "Care", value: "Durable and water-safe." },
    ],
    tags: ["gold", "brown", "courage", "confidence"],
  }),
  crystal({
    id: "fluorite",
    name: "Fluorite",
    category: "Halide",
    summary: "Calcium fluoride (CaF₂), a glassy halide mineral that occurs in purple, green, blue, and rainbow-banded crystals. Traditionally used for focus, study, mental clarity, and bringing order from chaos.",
    fields: [
      { label: "What it is", value: "Calcium fluoride (CaF₂); comes in purple, green, blue, and rainbow bands." },
      { label: "Hardness", value: "Mohs 4 — soft, scratches easily" },
      { label: "Traditionally for", value: "Focus, study, mental clarity, order from chaos." },
      { label: "Care", value: "Soft and color fades in sunlight; avoid scratches and prolonged sun." },
    ],
    tags: ["purple", "green", "rainbow", "focus", "study"],
  }),
  crystal({
    id: "carnelian",
    name: "Carnelian",
    category: "Chalcedony (quartz)",
    summary: "A warm orange-to-red variety of chalcedony (microcrystalline quartz) coloured by iron oxides. Traditionally used for vitality, creativity, courage, and motivation.",
    fields: [
      { label: "What it is", value: "A reddish-orange variety of chalcedony (microcrystalline quartz)." },
      { label: "Hardness", value: "Mohs 6.5–7" },
      { label: "Traditionally for", value: "Vitality, creativity, courage, motivation." },
      { label: "Care", value: "Durable and water-safe; color can fade in strong sun." },
    ],
    tags: ["orange", "red", "creativity", "vitality"],
  }),
  crystal({
    id: "moonstone",
    name: "Moonstone",
    category: "Feldspar",
    summary: "A feldspar mineral whose floating blue-white sheen (adularescence) comes from light scattering between thin internal layers. Traditionally used for intuition, new beginnings, and emotional cycles.",
    fields: [
      { label: "What it is", value: "A feldspar mineral; the glow ('adularescence') comes from light scattering between internal layers." },
      { label: "Hardness", value: "Mohs ~6–6.5" },
      { label: "Traditionally for", value: "Intuition, new beginnings, emotional cycles, the feminine." },
      { label: "Care", value: "Somewhat fragile; avoid knocks and long water exposure." },
    ],
    tags: ["white", "blue", "intuition", "moon", "feminine"],
  }),
  crystal({
    id: "labradorite",
    name: "Labradorite",
    category: "Feldspar",
    summary: "A grey plagioclase feldspar that flashes iridescent blue-green (labradorescence) from light interference within its layered structure. Traditionally used for intuition, magic, transformation, and psychic protection.",
    fields: [
      { label: "What it is", value: "A feldspar; the iridescent flash comes from light interference within its structure." },
      { label: "Hardness", value: "Mohs ~6–6.5" },
      { label: "Traditionally for", value: "Intuition, 'magic,' transformation, psychic protection." },
      { label: "Care", value: "Reasonably durable; avoid harsh knocks." },
    ],
    tags: ["grey", "blue", "flash", "magic", "intuition"],
  }),
  crystal({
    id: "turquoise",
    name: "Turquoise",
    category: "Phosphate",
    summary: "A blue-green hydrated copper-aluminium phosphate whose colour comes from copper; much cheap 'turquoise' is actually dyed howlite or magnesite. Traditionally used for protection, communication, healing, and good fortune.",
    fields: [
      { label: "What it is", value: "A copper-aluminium phosphate. Much cheap 'turquoise' is actually dyed howlite or magnesite." },
      { label: "Hardness", value: "Mohs ~5–6" },
      { label: "Traditionally for", value: "Protection, communication, healing, good fortune." },
      { label: "Care", value: "Porous — keep away from water, oils, and cosmetics, which stain it." },
    ],
    tags: ["blue", "green", "protection", "howlite", "dyed"],
  }),
  crystal({
    id: "hematite",
    name: "Hematite",
    category: "Iron oxide",
    summary: "Iron oxide (Fe₂O₃), a dense mineral with a metallic shine, though 'magnetic hematite' on the market is usually a synthetic ferrite. Traditionally used for grounding, focus, stability, and absorbing stress.",
    fields: [
      { label: "What it is", value: "Iron oxide (Fe₂O₃) — heavy with a metallic shine. ('Magnetic hematite' is usually a synthetic.)" },
      { label: "Hardness", value: "Mohs 5–6" },
      { label: "Traditionally for", value: "Grounding, focus, stability, absorbing stress." },
      { label: "Care", value: "Can rust — keep dry; avoid prolonged water." },
    ],
    tags: ["grey", "metallic", "iron", "grounding"],
  }),
  crystal({
    id: "jade",
    name: "Jade",
    category: "Jadeite / Nephrite",
    summary: "A name covering two distinct tough green minerals, jadeite (a pyroxene) and nephrite (an amphibole), both extremely durable. Traditionally used for luck, harmony, prosperity, and protection, and deeply valued in Chinese and Mesoamerican cultures.",
    fields: [
      { label: "What it is", value: "Two different minerals are sold as jade: jadeite and nephrite, both very tough." },
      { label: "Hardness", value: "Mohs ~6–7" },
      { label: "Traditionally for", value: "Luck, harmony, prosperity, protection — deeply valued in Chinese and Mesoamerican cultures." },
      { label: "Care", value: "Durable and water-safe." },
    ],
    tags: ["green", "luck", "harmony", "prosperity"],
  }),
  crystal({
    id: "garnet",
    name: "Garnet",
    category: "Silicate group",
    summary: "A group of related silicate minerals; the familiar deep-red gem is almandine, coloured by iron. Traditionally used for passion, vitality, commitment, and courage.",
    fields: [
      { label: "What it is", value: "A group of silicate minerals; the familiar deep-red is almandine garnet." },
      { label: "Hardness", value: "Mohs ~6.5–7.5" },
      { label: "Traditionally for", value: "Passion, vitality, commitment, courage." },
      { label: "Care", value: "Durable and water-safe." },
    ],
    tags: ["red", "passion", "energy", "January"],
  }),
  crystal({
    id: "aventurine",
    name: "Green Aventurine",
    category: "Quartz family",
    summary: "A green variety of quartz (SiO₂) speckled with tiny mineral inclusions, often green fuchsite, that create a shimmer called aventurescence. Traditionally used as the 'stone of opportunity' for luck, growth, and soothing the heart.",
    fields: [
      { label: "What it is", value: "Quartz with tiny mineral inclusions (often fuchsite) giving a green shimmer ('aventurescence')." },
      { label: "Hardness", value: "Mohs 7" },
      { label: "Traditionally for", value: "Luck, opportunity, growth, soothing the heart." },
      { label: "Care", value: "Durable and water-safe." },
    ],
    tags: ["green", "luck", "opportunity", "growth"],
  }),
  crystal({
    id: "sodalite",
    name: "Sodalite",
    category: "Silicate",
    summary: "A royal-blue silicate mineral of the feldspathoid family, often veined with white and easily mistaken for lapis but lacking its gold pyrite flecks. Traditionally used for rational thought, calm communication, and self-expression.",
    fields: [
      { label: "What it is", value: "A blue silicate mineral, often mistaken for lapis (but without the gold pyrite flecks)." },
      { label: "Hardness", value: "Mohs ~5.5–6" },
      { label: "Traditionally for", value: "Rational thought, calm communication, self-expression." },
      { label: "Care", value: "Somewhat porous; avoid prolonged water." },
    ],
    tags: ["blue", "logic", "calm", "communication"],
  }),
  crystal({
    id: "pyrite",
    name: "Pyrite",
    aka: ["fool's gold"],
    category: "Iron sulfide",
    summary: "Iron sulfide (FeS₂), a brassy, gold-coloured mineral nicknamed 'fool's gold' for its metallic luster. Traditionally used for abundance, confidence, willpower, and protection.",
    fields: [
      { label: "What it is", value: "Iron sulfide (FeS₂) with a brassy, gold-like metallic luster." },
      { label: "Hardness", value: "Mohs 6–6.5" },
      { label: "Traditionally for", value: "Abundance, confidence, willpower, protection." },
      { label: "Care", value: "Keep dry — pyrite can react with moisture and tarnish or crumble over time." },
    ],
    safety: "Keep dry and wash hands after handling — pyrite can release small amounts of sulfur/iron, and weathered pyrite can be irritating. Never make elixirs from it.",
    tags: ["gold", "metallic", "abundance", "fools gold"],
  }),
  crystal({
    id: "amazonite",
    name: "Amazonite",
    category: "Feldspar",
    summary: "A soothing blue-green variety of microcline feldspar, coloured by traces of lead and water in its structure. Traditionally used for calm, emotional balance, truthful communication, and boundaries.",
    fields: [
      { label: "What it is", value: "A green-blue variety of microcline feldspar." },
      { label: "Hardness", value: "Mohs ~6–6.5" },
      { label: "Traditionally for", value: "Calm, emotional balance, truthful communication, boundaries." },
      { label: "Care", value: "Reasonably durable; avoid harsh knocks and prolonged water." },
    ],
    tags: ["blue", "green", "calm", "balance", "communication"],
  }),
  crystal({
    id: "celestite",
    name: "Celestite",
    aka: ["celestine"],
    category: "Strontium sulfate",
    summary: "Strontium sulfate (SrSO₄), a soft, fragile mineral that forms delicate pale sky-blue crystal clusters. Traditionally used for peace, calm, gentleness, and spiritual connection.",
    fields: [
      { label: "What it is", value: "Strontium sulfate (SrSO₄), typically in pale-blue clusters." },
      { label: "Hardness", value: "Mohs 3–3.5 — soft and fragile" },
      { label: "Traditionally for", value: "Peace, calm, gentleness, spiritual connection." },
      { label: "Care", value: "Fragile and its color fades in sunlight; handle gently and keep out of direct sun." },
    ],
    tags: ["blue", "peace", "calm", "fragile"],
  }),
];
