import type { ReferenceEntry } from "../types";

/**
 * Quick-reference essential-oil lookup — what each oil is, its uses, the
 * evidence, and (critically) safety: dilution, phototoxicity, and pet risk.
 * Verified against Tisserand and ASPCA guidance. Not medical advice; dilute,
 * patch test, keep away from pets, and never ingest without expert guidance.
 */

function oil(e: {
  id: string; name: string; aka?: string[]; category: string; summary: string;
  is: string; uses: string; evidence: string; safety: string; tags?: string[];
}): ReferenceEntry {
  return {
    domain: "essential-oils",
    id: `oil-${e.id}`, // namespaced so it never collides with a same-named herb
    name: e.name,
    aka: e.aka,
    category: e.category,
    summary: e.summary,
    fields: [
      { label: "What it is", value: e.is },
      { label: "Used for", value: e.uses },
      { label: "Evidence", value: e.evidence },
    ],
    safety: e.safety,
    tags: e.tags,
  };
}

export const essentialOilReference: ReferenceEntry[] = [
  oil({ id: "lavender", name: "Lavender", category: "Calming", summary: "A gentle floral oil steam-distilled from lavender flowers, used mainly for relaxation, sleep support, and easing everyday tension. Modest clinical evidence supports inhaled lavender and a standardized oral preparation for anxiety and sleep, though it is not a substitute for medical care.", is: "Steam-distilled oil of lavender flowers.", uses: "Relaxation, sleep, anxiety, minor skin care.", evidence: "Modest evidence (inhaled and a standardized oral form) for anxiety and sleep.", safety: "One of the gentler oils, but still dilute before skin use and don't ingest the essential oil. Keep away from cats.", tags: ["calm", "sleep", "relax", "floral"] }),
  oil({ id: "peppermint", name: "Peppermint", category: "Invigorating", summary: "A cooling, menthol-rich oil steam-distilled from the peppermint plant, used for alertness, tension headaches, nausea, and a sense of clear breathing. Some evidence supports its use for tension headache and short-term alertness, but effects are modest and it is not a medical treatment.", is: "Steam-distilled oil of the peppermint plant, high in menthol.", uses: "Alertness, tension headache, nausea, congestion.", evidence: "Some evidence for tension headache and alertness.", safety: "Keep away from the faces of infants and young children (menthol can affect breathing). Toxic to cats. Dilute well.", tags: ["mint", "headache", "alert", "menthol"] }),
  oil({ id: "tea-tree", name: "Tea Tree", aka: ["melaleuca"], category: "Topical antimicrobial", summary: "A medicinal-smelling oil steam-distilled from the Australian Melaleuca alternifolia tree, used in diluted topical form for acne and minor skin care and never swallowed. Some evidence supports its topical antimicrobial use, such as for acne, though results vary and it can sensitize skin.", is: "Steam-distilled oil of the Melaleuca alternifolia tree.", uses: "Acne and minor skin care (diluted, topical).", evidence: "Some evidence for topical antimicrobial use (e.g. acne).", safety: "NEVER ingest — it is toxic if swallowed. Toxic to cats and dogs. Always dilute; can sensitize skin, especially if oxidized.", tags: ["skin", "acne", "antimicrobial", "toxic if ingested"] }),
  oil({ id: "eucalyptus", name: "Eucalyptus", category: "Respiratory", summary: "A sharp, fresh oil steam-distilled from eucalyptus leaves and rich in 1,8-cineole, traditionally used for congestion and a clearing scent. Evidence is limited, and it is valued mostly for the subjective feeling of clearer breathing rather than as a proven respiratory remedy.", is: "Steam-distilled oil of eucalyptus leaves, high in 1,8-cineole.", uses: "Congestion, a fresh/clearing scent.", evidence: "Limited evidence; popular for a feeling of clear breathing.", safety: "Strong — keep away from the faces of babies and young children, and toxic to pets. Dilute; don't ingest.", tags: ["congestion", "fresh", "cineole", "respiratory"] }),
  oil({ id: "lemon", name: "Lemon", category: "Citrus / uplifting", summary: "A bright, zesty oil cold-pressed from lemon peel, used to lift mood, freshen a space, and add a clean scent to cleaning blends. Effects on mood and freshness are modest rather than therapeutic, and because it is phototoxic, treated skin should stay out of the sun.", is: "Cold-pressed oil from lemon peel.", uses: "Uplifting mood, fresh scent, cleaning.", evidence: "Modest mood/freshness effects; not a treatment.", safety: "Phototoxic: keep skin diluted to about 2% max and out of the sun for ~12–18 hours after topical use. Toxic to pets (citrus/d-limonene).", tags: ["citrus", "phototoxic", "uplift", "fresh"] }),
  oil({ id: "sweet-orange", name: "Sweet Orange", category: "Citrus / uplifting", summary: "A cheerful, warm citrus oil cold-pressed from sweet orange peel, used to lift mood and add a sweet, friendly scent to blends. Evidence for its mood effects is modest, but it is gentle and popular, and unusually for an expressed citrus it is essentially non-phototoxic.", is: "Cold-pressed oil from sweet orange peel.", uses: "Uplifting mood, a warm, sweet scent.", evidence: "Modest mood effects; gentle and popular.", safety: "Unusually, expressed sweet orange is essentially non-phototoxic. Still dilute, and citrus oils are toxic to pets.", tags: ["citrus", "uplift", "sweet", "mood"] }),
  oil({ id: "bergamot", name: "Bergamot", category: "Citrus / calming", summary: "A complex citrus oil cold-pressed from the bergamot orange peel, the scent behind Earl Grey tea, used in aromatherapy for calming and uplifting effects. Some aromatherapy evidence points to mood and anxiety benefits, but the standard oil is strongly phototoxic and must be kept off sun-exposed skin.", is: "Cold-pressed oil from the bergamot orange peel.", uses: "Calming, uplifting, complex scent (used in Earl Grey tea).", evidence: "Some aromatherapy evidence for mood/anxiety.", safety: "Strongly phototoxic — max about 0.4% on skin before sun exposure; otherwise keep that skin out of the sun. Toxic to pets. (A 'bergapten-free' version is non-phototoxic.)", tags: ["citrus", "phototoxic", "calm", "earl grey"] }),
  oil({ id: "frankincense", name: "Frankincense", category: "Grounding", summary: "A warm, resinous oil steam-distilled from the hardened resin of the Boswellia tree, long used in meditation, grounding rituals, and skin care. Evidence is limited, and it is valued chiefly for its calming, contemplative aroma rather than any proven therapeutic effect.", is: "Steam-distilled oil from Boswellia tree resin.", uses: "Meditation, grounding, skin care.", evidence: "Limited evidence; valued for its calming, ritual scent.", safety: "Generally gentle — dilute before skin use and don't ingest. Keep away from cats.", tags: ["resin", "meditation", "grounding", "ritual"] }),
  oil({ id: "roman-chamomile", name: "Roman Chamomile", category: "Calming", summary: "A soft, apple-scented oil steam-distilled from Roman chamomile flowers, used to encourage calm and to soothe sensitive skin in gentle dilution. Evidence is limited, and it is appreciated mainly as a mild, relaxing aroma rather than a clinically proven remedy.", is: "Steam-distilled oil of Roman chamomile flowers.", uses: "Calm, soothing, sensitive skin.", evidence: "Limited evidence; gentle and relaxing.", safety: "Generally gentle; dilute. People allergic to ragweed/daisies may react. Keep away from pets.", tags: ["calm", "soothing", "gentle", "apple"] }),
  oil({ id: "rosemary", name: "Rosemary", category: "Invigorating", summary: "A sharp, herbaceous oil steam-distilled from the rosemary herb and often rich in camphor, used for focus, alertness, scalp and hair care, and a sense of stimulated circulation. Work on its aroma and alertness is preliminary, and most of its reputation rests on tradition rather than firm clinical evidence.", is: "Steam-distilled oil of the rosemary herb (often camphor-rich).", uses: "Focus, alertness, scalp/hair care, circulation.", evidence: "Preliminary aroma/alertness work; mostly traditional.", safety: "Avoid in pregnancy and with epilepsy (camphor content). Dilute; don't ingest; toxic to pets.", tags: ["focus", "hair", "herbaceous", "camphor"] }),
  oil({ id: "ylang-ylang", name: "Ylang-Ylang", category: "Calming / floral", summary: "A heady, sweet tropical floral oil steam-distilled from Cananga odorata flowers, used for relaxation, mood, and a sensual scent in low dilution. Evidence is limited, and it is popular mainly for its relaxing aroma rather than any established therapeutic benefit.", is: "Steam-distilled oil of Cananga odorata flowers.", uses: "Relaxation, mood, sensual/floral scent.", evidence: "Limited evidence; popular for relaxation.", safety: "Can cause headaches or skin sensitization in some people — keep the dilution low. Toxic to pets.", tags: ["floral", "relax", "tropical", "mood"] }),
  oil({ id: "cedarwood", name: "Cedarwood", category: "Grounding / woody", summary: "A warm, woody oil steam-distilled from cedar wood, used for grounding, sleep support, and a comforting forest-like scent. Evidence is limited, and it is enjoyed chiefly for its calming, woody aroma rather than as a proven treatment.", is: "Steam-distilled oil from cedar wood.", uses: "Grounding, sleep, a woody/forest scent.", evidence: "Limited evidence; calming, woody aroma.", safety: "Generally gentle; dilute before skin use. Keep away from pets; don't ingest.", tags: ["woody", "grounding", "sleep", "forest"] }),
  oil({ id: "lemongrass", name: "Lemongrass", category: "Fresh / citrusy", summary: "A bright, grassy-citrus oil steam-distilled from the lemongrass plant, used for a fresh scent, as an insect deterrent, and for an energizing lift. Evidence is limited and it is valued mostly for its aroma, while being a notable skin sensitizer that calls for low dilution and a patch test.", is: "Steam-distilled oil of the lemongrass plant.", uses: "Fresh scent, insect deterrent, energizing.", evidence: "Limited evidence; valued for its fresh aroma.", safety: "A notable skin sensitizer — use a low dilution and patch test. Toxic to pets; don't ingest.", tags: ["citrus", "grass", "fresh", "sensitizer"] }),
  oil({ id: "clary-sage", name: "Clary Sage", category: "Calming", summary: "A soft, herbaceous oil steam-distilled from the clary sage plant, used for relaxation and traditionally for menstrual and hormonal comfort. Evidence is limited, and it is valued mainly for its relaxing aroma rather than any proven hormonal effect; it should be avoided during pregnancy.", is: "Steam-distilled oil of the clary sage plant.", uses: "Relaxation, traditionally for menstrual/hormonal comfort.", evidence: "Limited evidence; relaxing aroma.", safety: "Avoid during pregnancy. Dilute; can be sedating, so don't combine with alcohol; keep away from pets.", tags: ["calm", "hormonal", "herbaceous", "sage"] }),
];
