import type { ReferenceEntry } from "../types";

/**
 * Quick-reference essential-oil lookup — what each oil is, its uses, the
 * evidence, and (critically) safety: dilution, phototoxicity, and pet risk.
 * Verified against Tisserand and ASPCA guidance. Not medical advice; dilute,
 * patch test, keep away from pets, and never ingest without expert guidance.
 */

function oil(e: {
  id: string; name: string; aka?: string[]; category: string; summary: string;
  is: string; uses: string; evidence: string; safety: string; tags?: string[];
}): ReferenceEntry {
  return {
    domain: "essential-oils",
    id: `oil-${e.id}`, // namespaced so it never collides with a same-named herb
    name: e.name,
    aka: e.aka,
    category: e.category,
    summary: e.summary,
    fields: [
      { label: "What it is", value: e.is },
      { label: "Used for", value: e.uses },
      { label: "Evidence", value: e.evidence },
    ],
    safety: e.safety,
    tags: e.tags,
  };
}

export const essentialOilReference: ReferenceEntry[] = [
  oil({ id: "lavender", name: "Lavender", category: "Calming", summary: "A gentle floral oil steam-distilled from lavender flowers, used mainly for relaxation, sleep support, and easing everyday tension. Modest clinical evidence supports inhaled lavender and a standardized oral preparation for anxiety and sleep, though it is not a substitute for medical care.", is: "Steam-distilled oil of lavender flowers.", uses: "Relaxation, sleep, anxiety, minor skin care.", evidence: "Modest evidence (inhaled and a standardized oral form) for anxiety and sleep.", safety: "One of the gentler oils, but still dilute before skin use and don't ingest the essential oil. Keep away from cats.", tags: ["calm", "sleep", "relax", "floral"] }),
  oil({ id: "peppermint", name: "Peppermint", category: "Invigorating", summary: "A cooling, menthol-rich oil steam-distilled from the peppermint plant, used for alertness, tension headaches, nausea, and a sense of clear breathing. Some evidence supports its use for tension headache and short-term alertness, but effects are modest and it is not a medical treatment.", is: "Steam-distilled oil of the peppermint plant, high in menthol.", uses: "Alertness, tension headache, nausea, congestion.", evidence: "Some evidence for tension headache and alertness.", safety: "Keep away from the faces of infants and young children (menthol can affect breathing). Toxic to cats. Dilute well.", tags: ["mint", "headache", "alert", "menthol"] }),
  oil({ id: "tea-tree", name: "Tea Tree", aka: ["melaleuca"], category: "Topical antimicrobial", summary: "A medicinal-smelling oil steam-distilled from the Australian Melaleuca alternifolia tree, used in diluted topical form for acne and minor skin care and never swallowed. Some evidence supports its topical antimicrobial use, such as for acne, though results vary and it can sensitize skin.", is: "Steam-distilled oil of the Melaleuca alternifolia tree.", uses: "Acne and minor skin care (diluted, topical).", evidence: "Some evidence for topical antimicrobial use (e.g. acne).", safety: "NEVER ingest — it is toxic if swallowed. Toxic to cats and dogs. Always dilute; can sensitize skin, especially if oxidized.", tags: ["skin", "acne", "antimicrobial", "toxic if ingested"] }),
  oil({ id: "eucalyptus", name: "Eucalyptus", category: "Respiratory", summary: "A sharp, fresh oil steam-distilled from eucalyptus leaves and rich in 1,8-cineole, traditionally used for congestion and a clearing scent. Evidence is limited, and it is valued mostly for the subjective feeling of clearer breathing rather than as a proven respiratory remedy.", is: "Steam-distilled oil of eucalyptus leaves, high in 1,8-cineole.", uses: "Congestion, a fresh/clearing scent.", evidence: "Limited evidence; popular for a feeling of clear breathing.", safety: "Strong — keep away from the faces of babies and young children, and toxic to pets. Dilute; don't ingest.", tags: ["congestion", "fresh", "cineole", "respiratory"] }),
  oil({ id: "lemon", name: "Lemon", category: "Citrus / uplifting", summary: "A bright, zesty oil cold-pressed from lemon peel, used to lift mood, freshen a space, and add a clean scent to cleaning blends. Effects on mood and freshness are modest rather than therapeutic, and because it is phototoxic, treated skin should stay out of the sun.", is: "Cold-pressed oil from lemon peel.", uses: "Uplifting mood, fresh scent, cleaning.", evidence: "Modest mood/freshness effects; not a treatment.", safety: "Phototoxic: keep skin diluted to about 2% max and out of the sun for ~12–18 hours after topical use. Toxic to pets (citrus/d-limonene).", tags: ["citrus", "phototoxic", "uplift", "fresh"] }),
  oil({ id: "sweet-orange", name: "Sweet Orange", category: "Citrus / uplifting", summary: "A cheerful, warm citrus oil cold-pressed from sweet orange peel, used to lift mood and add a sweet, friendly scent to blends. Evidence for its mood effects is modest, but it is gentle and popular, and unusually for an expressed citrus it is essentially non-phototoxic.", is: "Cold-pressed oil from sweet orange peel.", uses: "Uplifting mood, a warm, sweet scent.", evidence: "Modest mood effects; gentle and popular.", safety: "Unusually, expressed sweet orange is essentially non-phototoxic. Still dilute, and citrus oils are toxic to pets.", tags: ["citrus", "uplift", "sweet", "mood"] }),
  oil({ id: "bergamot", name: "Bergamot", category: "Citrus / calming", summary: "A complex citrus oil cold-pressed from the bergamot orange peel, the scent behind Earl Grey tea, used in aromatherapy for calming and uplifting effects. Some aromatherapy evidence points to mood and anxiety benefits, but the standard oil is strongly phototoxic and must be kept off sun-exposed skin.", is: "Cold-pressed oil from the bergamot orange peel.", uses: "Calming, uplifting, complex scent (used in Earl Grey tea).", evidence: "Some aromatherapy evidence for mood/anxiety.", safety: "Strongly phototoxic — max about 0.4% on skin before sun exposure; otherwise keep that skin out of the sun. Toxic to pets. (A 'bergapten-free' version is non-phototoxic.)", tags: ["citrus", "phototoxic", "calm", "earl grey"] }),
  oil({ id: "frankincense", name: "Frankincense", category: "Grounding", summary: "A warm, resinous oil steam-distilled from the hardened resin of the Boswellia tree, long used in meditation, grounding rituals, and skin care. Evidence is limited, and it is valued chiefly for its calming, contemplative aroma rather than any proven therapeutic effect.", is: "Steam-distilled oil from Boswellia tree resin.", uses: "Meditation, grounding, skin care.", evidence: "Limited evidence; valued for its calming, ritual scent.", safety: "Generally gentle — dilute before skin use and don't ingest. Keep away from cats.", tags: ["resin", "meditation", "grounding", "ritual"] }),
  oil({ id: "roman-chamomile", name: "Roman Chamomile", category: "Calming", summary: "A soft, apple-scented oil steam-distilled from Roman chamomile flowers, used to encourage calm and to soothe sensitive skin in gentle dilution. Evidence is limited, and it is appreciated mainly as a mild, relaxing aroma rather than a clinically proven remedy.", is: "Steam-distilled oil of Roman chamomile flowers.", uses: "Calm, soothing, sensitive skin.", evidence: "Limited evidence; gentle and relaxing.", safety: "Generally gentle; dilute. People allergic to ragweed/daisies may react. Keep away from pets.", tags: ["calm", "soothing", "gentle", "apple"] }),
  oil({ id: "rosemary", name: "Rosemary", category: "Invigorating", summary: "A sharp, herbaceous oil steam-distilled from the rosemary herb and often rich in camphor, used for focus, alertness, scalp and hair care, and a sense of stimulated circulation. Work on its aroma and alertness is preliminary, and most of its reputation rests on tradition rather than firm clinical evidence.", is: "Steam-distilled oil of the rosemary herb (often camphor-rich).", uses: "Focus, alertness, scalp/hair care, circulation.", evidence: "Preliminary aroma/alertness work; mostly traditional.", safety: "Avoid in pregnancy and with epilepsy (camphor content). Dilute; don't ingest; toxic to pets.", tags: ["focus", "hair", "herbaceous", "camphor"] }),
  oil({ id: "ylang-ylang", name: "Ylang-Ylang", category: "Calming / floral", summary: "A heady, sweet tropical floral oil steam-distilled from Cananga odorata flowers, used for relaxation, mood, and a sensual scent in low dilution. Evidence is limited, and it is popular mainly for its relaxing aroma rather than any established therapeutic benefit.", is: "Steam-distilled oil of Cananga odorata flowers.", uses: "Relaxation, mood, sensual/floral scent.", evidence: "Limited evidence; popular for relaxation.", safety: "Can cause headaches or skin sensitization in some people — keep the dilution low. Toxic to pets.", tags: ["floral", "relax", "tropical", "mood"] }),
  oil({ id: "cedarwood", name: "Cedarwood", category: "Grounding / woody", summary: "A warm, woody oil steam-distilled from cedar wood, used for grounding, sleep support, and a comforting forest-like scent. Evidence is limited, and it is enjoyed chiefly for its calming, woody aroma rather than as a proven treatment.", is: "Steam-distilled oil from cedar wood.", uses: "Grounding, sleep, a woody/forest scent.", evidence: "Limited evidence; calming, woody aroma.", safety: "Generally gentle; dilute before skin use. Keep away from pets; don't ingest.", tags: ["woody", "grounding", "sleep", "forest"] }),
  oil({ id: "lemongrass", name: "Lemongrass", category: "Fresh / citrusy", summary: "A bright, grassy-citrus oil steam-distilled from the lemongrass plant, used for a fresh scent, as an insect deterrent, and for an energizing lift. Evidence is limited and it is valued mostly for its aroma, while being a notable skin sensitizer that calls for low dilution and a patch test.", is: "Steam-distilled oil of the lemongrass plant.", uses: "Fresh scent, insect deterrent, energizing.", evidence: "Limited evidence; valued for its fresh aroma.", safety: "A notable skin sensitizer — use a low dilution and patch test. Toxic to pets; don't ingest.", tags: ["citrus", "grass", "fresh", "sensitizer"] }),
  oil({ id: "clary-sage", name: "Clary Sage", category: "Calming", summary: "A soft, herbaceous oil steam-distilled from the clary sage plant, used for relaxation and traditionally for menstrual and hormonal comfort. Evidence is limited, and it is valued mainly for its relaxing aroma rather than any proven hormonal effect; it should be avoided during pregnancy.", is: "Steam-distilled oil of the clary sage plant.", uses: "Relaxation, traditionally for menstrual/hormonal comfort.", evidence: "Limited evidence; relaxing aroma.", safety: "Avoid during pregnancy. Dilute; can be sedating, so don't combine with alcohol; keep away from pets.", tags: ["calm", "hormonal", "herbaceous", "sage"] }),

  // ---------------------------------------------------------------------------
  // Additional common oils. Safety notes verified against Tisserand & Young
  // ("Essential Oil Safety," 2nd ed.), IFRA restrictions, and ASPCA pet
  // guidance. Universal rules: never ingest; always dilute in a carrier oil
  // (typ. 1–3%) for skin; keep away from eyes and mucous membranes; patch test.
  // ---------------------------------------------------------------------------

  oil({ id: "eucalyptus-radiata", name: "Eucalyptus Radiata", aka: ["narrow-leaved peppermint eucalyptus"], category: "Respiratory", summary: "A softer, gentler cousin of standard eucalyptus, steam-distilled from Eucalyptus radiata leaves and rich in 1,8-cineole, often preferred for its milder profile while still giving a fresh, clearing scent. Evidence is limited; it is valued chiefly for the subjective feeling of easier breathing.", is: "Steam-distilled oil of Eucalyptus radiata leaves; cineole-rich but gentler than E. globulus.", uses: "Congestion, a fresh clearing scent, everyday diffusing.", evidence: "Limited evidence; popular for a feeling of clear breathing.", safety: "Like all cineole-rich oils, keep away from the faces of babies and young children (apnea risk). Dilute; never ingest; toxic to cats and dogs.", tags: ["congestion", "fresh", "cineole", "respiratory"] }),
  oil({ id: "lime", name: "Lime", category: "Citrus / uplifting", summary: "A sharp, zesty oil most often cold-pressed from lime peel, used to lift mood, energize, and add a crisp scent to cleaning and perfume blends. Effects are modest rather than therapeutic, and cold-pressed lime is strongly phototoxic, so treated skin must stay out of the sun.", is: "Cold-pressed (expressed) oil from lime peel; a steam-distilled, non-phototoxic version also exists.", uses: "Uplifting, energizing, fresh/crisp scent, cleaning.", evidence: "Modest mood/freshness effects; not a treatment.", safety: "Cold-pressed lime is strongly phototoxic — keep to about 0.7% on skin and out of the sun/UV for ~12–18 hours after topical use (steam-distilled lime is non-phototoxic). Never ingest; toxic to pets (d-limonene).", tags: ["citrus", "phototoxic", "uplift", "fresh"] }),
  oil({ id: "grapefruit", name: "Grapefruit", category: "Citrus / uplifting", summary: "A bright, slightly bitter citrus oil cold-pressed from grapefruit peel, used to uplift, freshen, and energize. Mood effects are modest, and while it is less phototoxic than bergamot or lime, treated skin should still be kept out of the sun.", is: "Cold-pressed oil from grapefruit peel.", uses: "Uplifting, energizing, fresh scent.", evidence: "Modest mood/freshness effects; not a treatment.", safety: "Phototoxic — keep to about 4% on skin and out of strong sun/UV for ~12–18 hours after topical use. Never ingest; toxic to pets (d-limonene).", tags: ["citrus", "phototoxic", "uplift", "fresh"] }),
  oil({ id: "mandarin", name: "Mandarin", aka: ["tangerine"], category: "Citrus / calming", summary: "A sweet, gentle citrus oil cold-pressed from mandarin peel, prized as one of the calmer, more soothing citruses and often used to settle and uplift. Mood effects are modest; mandarin is unusually low in phototoxic compounds but still warrants care.", is: "Cold-pressed oil from mandarin (or tangerine) peel.", uses: "Calming, gently uplifting, a sweet soft scent.", evidence: "Modest mood effects; gentle and popular.", safety: "Generally considered non-phototoxic or very low risk, but keep treated skin out of strong sun to be safe. Never ingest; dilute; toxic to pets (d-limonene).", tags: ["citrus", "calm", "sweet", "gentle"] }),
  oil({ id: "myrrh", name: "Myrrh", category: "Grounding / resinous", summary: "A deep, warm, balsamic oil steam-distilled from the hardened resin of the Commiphora tree, long used in ritual, meditation, and skin and oral care. Evidence is limited; it is valued chiefly for its rich, grounding aroma.", is: "Steam-distilled oil from Commiphora myrrha tree resin.", uses: "Meditation, grounding, skin care, a warm resinous scent.", evidence: "Limited evidence; valued for its grounding scent.", safety: "Avoid during pregnancy. Dilute before skin use; never ingest; keep away from pets.", tags: ["resin", "meditation", "grounding", "ritual"] }),
  oil({ id: "sandalwood", name: "Sandalwood", category: "Grounding / woody", summary: "A soft, creamy, woody oil steam-distilled from sandalwood heartwood, used for meditation, grounding, and skin care, with a long, lingering base-note scent. Evidence is limited; it is treasured mainly for its calming, woody aroma.", is: "Steam-distilled oil of sandalwood (Santalum) heartwood.", uses: "Meditation, grounding, skin care, a creamy woody scent.", evidence: "Limited evidence; calming, woody aroma.", safety: "Generally gentle; dilute before skin use. Never ingest; keep away from pets.", tags: ["woody", "grounding", "meditation", "skin"] }),
  oil({ id: "basil", name: "Basil", aka: ["sweet basil"], category: "Invigorating / herbaceous", summary: "A bright, herbaceous oil steam-distilled from basil leaves, used for focus, mental clarity, and an uplifting green scent. Choose linalool-type basil; evidence is limited and it is valued mostly for its fresh aroma.", is: "Steam-distilled oil of basil leaves (prefer the gentler linalool chemotype).", uses: "Focus, mental clarity, an uplifting herbaceous scent.", evidence: "Limited evidence; valued for its fresh aroma.", safety: "Avoid the estragole-rich (methyl chavicol) chemotype, which is a concern in higher amounts; avoid in pregnancy. Dilute well; never ingest; toxic to pets.", tags: ["herbaceous", "focus", "fresh", "green"] }),
  oil({ id: "sage", name: "Sage", aka: ["common sage", "dalmatian sage"], category: "Herbaceous", summary: "A strong, camphoraceous oil steam-distilled from common sage, traditionally used in small amounts but treated with real caution due to its thujone content. It is one of the more hazardous common oils and is best avoided by most home users in favor of clary sage.", is: "Steam-distilled oil of common sage (Salvia officinalis), high in thujone.", uses: "Traditionally herbaceous/clearing; generally better replaced by gentler clary sage.", evidence: "Limited evidence; used cautiously and sparingly.", safety: "High thujone content — avoid in pregnancy and with epilepsy or seizure disorders. Use only at very low dilution if at all; never ingest; toxic to pets.", tags: ["herbaceous", "thujone", "caution", "sage"] }),
  oil({ id: "thyme", name: "Thyme", category: "Hot / antimicrobial", summary: "A potent, herbaceous oil steam-distilled from thyme, often rich in thymol, traditionally used in heavily diluted topical blends for its antimicrobial reputation. It is a 'hot,' irritating oil that demands strong dilution and care.", is: "Steam-distilled oil of thyme (prefer the gentler linalool or thymol chemotypes, used diluted).", uses: "Traditionally antimicrobial topical and cleaning blends.", evidence: "Some lab antimicrobial data; limited clinical evidence.", safety: "A 'HOT,' strongly irritating oil — use very low dilution (around 0.5–1%) and patch test; avoid in pregnancy. Never ingest; keep off mucous membranes; toxic to pets.", tags: ["hot", "antimicrobial", "irritant", "herbaceous"] }),
  oil({ id: "oregano", name: "Oregano", category: "Hot / antimicrobial", summary: "A very potent, carvacrol-rich oil steam-distilled from oregano, popular for its antimicrobial reputation but among the harshest, hottest oils on skin. It requires heavy dilution and is never used neat.", is: "Steam-distilled oil of oregano, high in carvacrol.", uses: "Traditionally antimicrobial blends (heavily diluted).", evidence: "Lab antimicrobial data; limited human clinical evidence.", safety: "One of the 'HOTTEST' oils — a strong skin and mucous-membrane irritant. Use only at very low dilution (about 0.5–1%); avoid in pregnancy; never ingest; toxic to pets.", tags: ["hot", "antimicrobial", "irritant", "carvacrol"] }),
  oil({ id: "cinnamon-bark", name: "Cinnamon Bark", category: "Hot / warming", summary: "A rich, spicy, sweet oil steam-distilled from cinnamon bark and high in cinnamaldehyde, used in tiny amounts for a warming festive aroma. It is one of the harshest skin irritants and sensitizers, so it is mostly diffused rather than applied.", is: "Steam-distilled oil of cinnamon bark, rich in cinnamaldehyde.", uses: "Warming, spicy, festive scent (mostly diffused).", evidence: "Limited evidence; valued for its warm aroma.", safety: "A 'HOT' oil and strong skin sensitizer/irritant — best diffused, not applied; if used on skin keep well below 0.1%. Never ingest; keep off mucous membranes; avoid in pregnancy; toxic to pets.", tags: ["hot", "spice", "warming", "sensitizer"] }),
  oil({ id: "cinnamon-leaf", name: "Cinnamon Leaf", category: "Hot / warming", summary: "A warm, spicy, slightly clove-like oil steam-distilled from cinnamon leaves and rich in eugenol, milder than cinnamon bark but still a potent, warming oil used mostly in diffusion. Evidence is limited; it is valued for its cozy aroma.", is: "Steam-distilled oil of cinnamon leaves, rich in eugenol.", uses: "Warming, spicy scent (mostly diffused).", evidence: "Limited evidence; valued for its warm aroma.", safety: "A 'HOT' oil and skin irritant/sensitizer (eugenol) — keep dilution very low (around 0.5%) and patch test; never ingest; avoid in pregnancy; toxic to pets.", tags: ["hot", "spice", "warming", "eugenol"] }),
  oil({ id: "clove", name: "Clove", aka: ["clove bud"], category: "Hot / warming", summary: "A powerful, warm, spicy oil steam-distilled from clove buds and very high in eugenol, traditionally used in dental folk remedies and for a festive scent. It is a potent irritant best used sparingly and well diluted.", is: "Steam-distilled oil of clove buds, very high in eugenol.", uses: "Warming festive scent; traditional dental/oral folk use.", evidence: "Some traditional dental use (eugenol); limited clinical evidence.", safety: "A 'HOT' oil and strong skin/mucous-membrane irritant and sensitizer — keep dilution very low (around 0.5%); may interact with blood thinners; never ingest; avoid in pregnancy; toxic to pets.", tags: ["hot", "spice", "eugenol", "dental"] }),
  oil({ id: "ginger", name: "Ginger", category: "Warming / digestive", summary: "A warm, spicy, slightly sweet oil steam-distilled from ginger root, used for a comforting warming scent and traditionally associated with easing nausea and supporting digestion. Some evidence links ginger aroma to nausea relief, though it is not a medical treatment.", is: "Steam-distilled oil of ginger root.", uses: "Warming scent, traditionally for nausea and digestive comfort.", evidence: "Some evidence that ginger aroma may ease nausea.", safety: "Generally gentle but can mildly irritate or (when oxidized) sensitize skin — dilute and patch test. Never ingest; keep away from pets.", tags: ["warming", "spice", "nausea", "digestive"] }),
  oil({ id: "black-pepper", name: "Black Pepper", category: "Warming / invigorating", summary: "A dry, warm, peppery oil steam-distilled from black peppercorns, used for a warming, stimulating scent and traditionally to support a feeling of circulation and warmth. Evidence is limited; it is valued mainly for its energizing aroma.", is: "Steam-distilled oil of black peppercorns.", uses: "Warming, stimulating scent, a feeling of circulation.", evidence: "Limited evidence; valued for its warming aroma.", safety: "Generally gentle in low dilution but can be warming/irritating on sensitive skin — dilute. Never ingest; keep away from pets.", tags: ["warming", "spice", "stimulating", "peppery"] }),
  oil({ id: "cardamom", name: "Cardamom", category: "Warming / digestive", summary: "A sweet, spicy, slightly cooling oil steam-distilled from cardamom seeds, used for a comforting, uplifting scent and traditionally linked to digestive ease. Evidence is limited; it is enjoyed mostly for its rich, spicy aroma.", is: "Steam-distilled oil of cardamom seeds.", uses: "Warming uplifting scent, traditionally for digestive comfort.", evidence: "Limited evidence; valued for its spicy aroma.", safety: "Generally gentle; dilute before skin use. Never ingest; keep away from pets.", tags: ["warming", "spice", "digestive", "sweet"] }),
  oil({ id: "fennel", name: "Fennel", aka: ["sweet fennel"], category: "Herbaceous / digestive", summary: "A sweet, anise-like oil steam-distilled from fennel seeds, traditionally associated with digestive comfort and a soothing herbaceous scent. It is rich in trans-anethole, which brings real cautions for some groups.", is: "Steam-distilled oil of fennel seeds, rich in trans-anethole.", uses: "Soothing anise-like scent, traditionally for digestive comfort.", evidence: "Limited evidence; valued for its sweet aroma.", safety: "Avoid in pregnancy, with epilepsy, and with estrogen-sensitive conditions; can be a mild skin sensitizer. Use low dilution; never ingest; toxic to pets.", tags: ["anise", "digestive", "herbaceous", "caution"] }),
  oil({ id: "geranium", name: "Geranium", aka: ["rose geranium"], category: "Floral / balancing", summary: "A sweet, rosy-green floral oil steam-distilled from geranium leaves and stems, used for a balancing, uplifting scent and in gentle skin-care blends. Evidence is limited; it is popular for its pleasant, rose-like aroma.", is: "Steam-distilled oil of geranium (Pelargonium) leaves and stems.", uses: "Balancing, uplifting floral scent, gentle skin care.", evidence: "Limited evidence; popular for its rosy aroma.", safety: "Generally gentle but can sensitize some skin — dilute and patch test. Never ingest; keep away from pets.", tags: ["floral", "balancing", "rosy", "skin"] }),
  oil({ id: "rose-otto", name: "Rose Otto", aka: ["rose", "rose attar"], category: "Floral / luxury", summary: "A precious, deeply floral oil steam-distilled from rose petals, used in tiny amounts for emotional comfort, romance, and luxurious skin care. Evidence is limited; it is treasured chiefly for its exquisite aroma and is one of the gentler florals.", is: "Steam-distilled oil of rose petals (Rosa damascena); very precious.", uses: "Emotional comfort, romance, luxurious skin care.", evidence: "Limited evidence; valued for its exquisite aroma.", safety: "One of the gentler oils, but still dilute and never ingest. Keep away from pets.", tags: ["floral", "luxury", "comfort", "skin"] }),
  oil({ id: "jasmine", name: "Jasmine", aka: ["jasmine absolute"], category: "Floral / luxury", summary: "A rich, heady, sweet floral typically produced as an absolute by solvent extraction from jasmine flowers, used in minute amounts for romance, mood, and perfume. Evidence is limited; it is prized for its intense, exotic aroma.", is: "Solvent-extracted absolute from jasmine flowers (not steam-distilled).", uses: "Romance, mood, perfume, a heady floral scent.", evidence: "Limited evidence; valued for its exotic aroma.", safety: "As an absolute it may carry trace solvent and can sensitize — use very low dilution and patch test; avoid in pregnancy. Never ingest; keep away from pets.", tags: ["floral", "luxury", "absolute", "perfume"] }),
  oil({ id: "neroli", name: "Neroli", aka: ["orange blossom"], category: "Floral / calming", summary: "A delicate, sweet floral oil steam-distilled from bitter orange blossoms, used for calm, emotional comfort, and gentle skin care. Some aromatherapy work suggests a calming effect; it is one of the gentler, non-phototoxic citrus-family oils.", is: "Steam-distilled oil of bitter orange (Citrus aurantium) blossoms.", uses: "Calming, emotional comfort, gentle skin care.", evidence: "Some aromatherapy evidence for calming/relaxation.", safety: "Steam-distilled, so non-phototoxic, and generally gentle — still dilute and never ingest. Keep away from pets.", tags: ["floral", "calm", "citrus", "comfort"] }),
  oil({ id: "petitgrain", name: "Petitgrain", category: "Fresh / calming", summary: "A fresh, green, slightly floral oil steam-distilled from the leaves and twigs of the bitter orange tree, used for calming and an uplifting, clean scent. Evidence is limited; it is valued as an affordable, gentle relative of neroli.", is: "Steam-distilled oil from bitter orange leaves and twigs.", uses: "Calming, a fresh green uplifting scent.", evidence: "Limited evidence; popular for relaxation.", safety: "Distilled from leaves, so non-phototoxic and generally gentle — still dilute and never ingest. Keep away from pets.", tags: ["fresh", "calm", "green", "citrus-leaf"] }),
  oil({ id: "german-chamomile", name: "German Chamomile", aka: ["blue chamomile"], category: "Calming / skin", summary: "A deep blue, herbaceous oil steam-distilled from German chamomile flowers, its color from soothing chamazulene, used in gentle dilution for sensitive, irritated skin and for calm. Evidence is limited; it is valued for its soothing reputation and rich aroma.", is: "Steam-distilled oil of German chamomile flowers; blue from chamazulene.", uses: "Soothing irritated/sensitive skin, calm.", evidence: "Limited evidence; gentle and soothing.", safety: "Generally gentle; dilute. Those allergic to ragweed/daisies may react. Never ingest; keep away from pets.", tags: ["calm", "skin", "soothing", "blue"] }),
  oil({ id: "helichrysum", name: "Helichrysum", aka: ["immortelle", "everlasting"], category: "Skin / restorative", summary: "A warm, slightly honey-curry-scented oil steam-distilled from helichrysum flowers, prized in skin care for bruises, scars, and aging skin. Evidence is limited; it is a sought-after, premium oil valued for its restorative skin reputation.", is: "Steam-distilled oil of Helichrysum italicum flowers.", uses: "Skin care — bruises, scars, mature skin.", evidence: "Limited evidence; popular in premium skin care.", safety: "Generally gentle; dilute before skin use. Never ingest; keep away from pets.", tags: ["skin", "restorative", "premium", "soothing"] }),
  oil({ id: "vetiver", name: "Vetiver", category: "Grounding / earthy", summary: "A deep, smoky, earthy oil steam-distilled from vetiver roots, used as a grounding base note for relaxation, sleep, and focus. Evidence is limited; it is valued chiefly for its rich, calming, earthy aroma.", is: "Steam-distilled oil of vetiver (Chrysopogon zizanioides) roots.", uses: "Grounding, relaxation, sleep, focus.", evidence: "Limited evidence; calming, earthy aroma.", safety: "Generally gentle; dilute before skin use. Never ingest; keep away from pets.", tags: ["earthy", "grounding", "sleep", "base-note"] }),
  oil({ id: "patchouli", name: "Patchouli", category: "Grounding / earthy", summary: "A rich, musky, earthy oil steam-distilled from patchouli leaves, used as a grounding base note in perfume, for relaxation, and in skin care. Evidence is limited; it is valued for its distinctive, lingering aroma that improves with age.", is: "Steam-distilled oil of patchouli leaves.", uses: "Grounding, perfume base, relaxation, skin care.", evidence: "Limited evidence; valued for its earthy aroma.", safety: "Generally gentle; dilute before skin use. Never ingest; keep away from pets.", tags: ["earthy", "grounding", "perfume", "musky"] }),
  oil({ id: "citronella", name: "Citronella", category: "Fresh / insect deterrent", summary: "A bright, grassy-lemony oil steam-distilled from citronella grass, best known as a natural insect deterrent and for a fresh, energizing scent. Some evidence supports short-lived mosquito-repelling effects; it is a notable skin sensitizer.", is: "Steam-distilled oil of citronella grass (Cymbopogon).", uses: "Insect deterrent, fresh energizing scent.", evidence: "Some evidence as a short-acting insect repellent.", safety: "A skin sensitizer — use low dilution and patch test; avoid in pregnancy. Never ingest; toxic to cats and dogs.", tags: ["citrus", "insect", "fresh", "sensitizer"] }),
  oil({ id: "palmarosa", name: "Palmarosa", category: "Floral / skin", summary: "A sweet, rosy-grassy oil steam-distilled from palmarosa grass and rich in geraniol, used in skin care and for a gentle, uplifting floral scent. Evidence is limited; it is popular as an affordable, soothing rose-like oil.", is: "Steam-distilled oil of palmarosa grass (Cymbopogon martinii), rich in geraniol.", uses: "Skin care, a soft rosy uplifting scent.", evidence: "Limited evidence; popular in skin care.", safety: "Generally gentle but can sensitize some skin — dilute and patch test. Never ingest; keep away from pets.", tags: ["floral", "skin", "rosy", "grass"] }),
  oil({ id: "may-chang", name: "May Chang", aka: ["litsea cubeba", "litsea"], category: "Citrus / uplifting", summary: "A bright, sweet, lemony oil steam-distilled from the fruit of the litsea (may chang) tree, used for an uplifting citrus scent without the phototoxicity of pressed citrus oils. Evidence is limited; it is valued for its cheerful aroma, but it is a notable sensitizer.", is: "Steam-distilled oil from the fruit of Litsea cubeba.", uses: "Uplifting lemony scent, mood, freshening.", evidence: "Limited evidence; valued for its bright aroma.", safety: "A skin sensitizer (citral-rich) — use low dilution (around 0.8%) and patch test. Not phototoxic. Never ingest; keep away from pets.", tags: ["citrus", "uplift", "sensitizer", "fresh"] }),
  oil({ id: "juniper-berry", name: "Juniper Berry", category: "Fresh / cleansing", summary: "A crisp, fresh, woody-balsamic oil steam-distilled from juniper berries, used for a clearing, grounding scent and a feeling of cleansing or detox. Evidence is limited; it is valued mainly for its fresh, forest-like aroma.", is: "Steam-distilled oil of juniper berries.", uses: "Fresh cleansing scent, grounding, freshening.", evidence: "Limited evidence; valued for its crisp aroma.", safety: "Avoid in pregnancy; use oxidation-fresh oil to reduce skin irritation. Dilute; never ingest; keep away from pets.", tags: ["fresh", "woody", "cleansing", "forest"] }),
  oil({ id: "cypress", name: "Cypress", category: "Fresh / grounding", summary: "A clean, fresh, woody oil steam-distilled from cypress needles and twigs, used for a grounding, clearing scent and a feeling of circulation and tone. Evidence is limited; it is valued for its crisp, evergreen aroma.", is: "Steam-distilled oil of cypress (Cupressus sempervirens) needles and twigs.", uses: "Grounding, fresh evergreen scent, a feeling of tone.", evidence: "Limited evidence; valued for its fresh aroma.", safety: "Generally gentle; dilute before skin use. Never ingest; keep away from pets.", tags: ["fresh", "woody", "grounding", "evergreen"] }),
  oil({ id: "pine", name: "Pine", aka: ["scots pine"], category: "Fresh / respiratory", summary: "A sharp, fresh, resinous oil steam-distilled from pine needles, used for an invigorating, clearing evergreen scent and a feeling of easier breathing. Evidence is limited; it is valued chiefly for its bracing forest aroma.", is: "Steam-distilled oil of pine needles (often Pinus sylvestris).", uses: "Invigorating fresh scent, a feeling of clear breathing.", evidence: "Limited evidence; valued for its fresh aroma.", safety: "Use oxidation-fresh oil; old or oxidized pine can irritate or sensitize skin — dilute and patch test. Never ingest; keep away from pets.", tags: ["fresh", "respiratory", "evergreen", "resinous"] }),
  oil({ id: "fir", name: "Fir Needle", aka: ["silver fir", "balsam fir"], category: "Fresh / grounding", summary: "A clean, soft, evergreen oil steam-distilled from fir needles, used for an uplifting, grounding forest scent and a sense of fresh air. Evidence is limited; it is valued mainly for its cheerful, woodland aroma.", is: "Steam-distilled oil of fir needles (Abies species).", uses: "Uplifting grounding forest scent, fresh air feeling.", evidence: "Limited evidence; valued for its fresh aroma.", safety: "Use oxidation-fresh oil; can irritate or sensitize skin if oxidized — dilute and patch test. Never ingest; keep away from pets.", tags: ["fresh", "evergreen", "grounding", "forest"] }),
  oil({ id: "spruce", name: "Spruce", aka: ["black spruce"], category: "Fresh / grounding", summary: "A soft, sweet, evergreen oil steam-distilled from spruce needles, used for a grounding, balancing forest scent often favored in meditation and yoga blends. Evidence is limited; it is valued for its calming woodland aroma.", is: "Steam-distilled oil of spruce needles (often Picea mariana).", uses: "Grounding, balancing, a soft evergreen scent.", evidence: "Limited evidence; valued for its calming aroma.", safety: "Use oxidation-fresh oil; can irritate or sensitize if oxidized — dilute and patch test. Never ingest; keep away from pets.", tags: ["fresh", "evergreen", "grounding", "meditation"] }),
  oil({ id: "marjoram", name: "Marjoram", aka: ["sweet marjoram"], category: "Calming / soothing", summary: "A warm, soft, herbaceous oil steam-distilled from sweet marjoram, used for relaxation, a feeling of muscular ease, and restful evenings. Evidence is limited; it is valued for its comforting, calming aroma.", is: "Steam-distilled oil of sweet marjoram (Origanum majorana).", uses: "Relaxation, a feeling of muscular ease, restful sleep.", evidence: "Limited evidence; valued for its calming aroma.", safety: "Generally gentle; dilute before skin use. Never ingest; keep away from pets.", tags: ["calm", "soothing", "herbaceous", "sleep"] }),
  oil({ id: "melissa", name: "Melissa", aka: ["lemon balm"], category: "Calming / uplifting", summary: "A delicate, sweet, lemony-herbaceous oil steam-distilled from melissa (lemon balm) leaves, used for calm and uplift; it is precious, costly, and often adulterated. Evidence is limited; genuine melissa is treasured for its gentle, brightening aroma.", is: "Steam-distilled oil of melissa (lemon balm) leaves; rare and expensive.", uses: "Calming, uplifting, a soft lemony scent.", evidence: "Limited evidence; valued for its gentle aroma.", safety: "A skin sensitizer (citral/citronellal) — use low dilution (around 0.9%) and patch test; avoid in pregnancy. Never ingest; keep away from pets.", tags: ["calm", "uplift", "lemony", "sensitizer"] }),
  oil({ id: "spearmint", name: "Spearmint", category: "Fresh / invigorating", summary: "A sweet, soft, minty oil steam-distilled from spearmint and rich in carvone rather than menthol, giving a gentler lift than peppermint, used for alertness, a fresh scent, and digestive comfort. Evidence is limited; it is valued as a milder mint.", is: "Steam-distilled oil of spearmint, high in carvone (low menthol).", uses: "Alertness, fresh scent, digestive comfort.", evidence: "Limited evidence; a gentler alternative to peppermint.", safety: "Gentler than peppermint but still keep away from the faces of infants and young children. Dilute; never ingest; toxic to pets.", tags: ["mint", "fresh", "alert", "gentle"] }),
  oil({ id: "wintergreen", name: "Wintergreen", category: "Warming / caution", summary: "An intense, sharp, sweet-medicinal oil steam-distilled from wintergreen and made up almost entirely of methyl salicylate — an aspirin-like compound — traditionally used in tiny amounts in muscle rubs. It is one of the most dangerous common oils and is best avoided by home users.", is: "Steam-distilled oil of wintergreen, roughly 96–99% methyl salicylate (aspirin-like).", uses: "Traditionally in warming muscle/joint rubs (heavily diluted, by experts).", evidence: "Limited evidence; methyl salicylate is a known counterirritant.", safety: "DANGEROUS — methyl salicylate is toxic and aspirin-like; a single teaspoon can be lethal to a child. NEVER ingest; avoid with blood thinners, aspirin sensitivity, in pregnancy, and around children and pets (potentially fatal). Keep tightly capped and out of reach.", tags: ["caution", "methyl-salicylate", "toxic", "warming"] }),
  oil({ id: "birch", name: "Birch", aka: ["sweet birch"], category: "Warming / caution", summary: "A sharp, wintergreen-like oil steam-distilled from sweet birch bark and, like wintergreen, almost entirely methyl salicylate, traditionally used in muscle rubs. It carries the same serious aspirin-like toxicity and is best avoided by home users.", is: "Steam-distilled oil of sweet birch bark, around 90%+ methyl salicylate (aspirin-like).", uses: "Traditionally in warming muscle/joint rubs (heavily diluted, by experts).", evidence: "Limited evidence; methyl salicylate is a known counterirritant.", safety: "DANGEROUS — methyl salicylate is toxic and aspirin-like; small amounts can be lethal to children. NEVER ingest; avoid with blood thinners, aspirin sensitivity, in pregnancy, and around children and pets (potentially fatal). Keep tightly capped and out of reach.", tags: ["caution", "methyl-salicylate", "toxic", "warming"] }),
  oil({ id: "camphor", name: "Camphor", aka: ["white camphor"], category: "Warming / caution", summary: "A penetrating, medicinal oil steam-distilled from the camphor tree, traditionally used in tiny amounts in warming rubs and for a clearing scent. It is potent and neurotoxic in excess, so it must be used sparingly and kept away from children.", is: "Steam-distilled oil of the camphor tree (use the safer 'white' fraction only).", uses: "Traditionally warming rubs, a clearing medicinal scent.", evidence: "Limited evidence; valued as a counterirritant.", safety: "Potentially neurotoxic and seizure-inducing if overused or ingested — avoid in pregnancy and with epilepsy. Keep away from the faces of babies and children (apnea risk). NEVER ingest; use only at very low dilution; toxic to pets. Avoid brown/yellow camphor (high safrole).", tags: ["caution", "warming", "neurotoxic", "medicinal"] }),
  oil({ id: "aniseed", name: "Aniseed", aka: ["anise"], category: "Sweet / herbaceous", summary: "A sweet, licorice-like oil steam-distilled from anise seeds and rich in trans-anethole, traditionally associated with digestive comfort and a comforting scent. It carries real cautions and is best used sparingly.", is: "Steam-distilled oil of anise (Pimpinella anisum) seeds, rich in trans-anethole.", uses: "Sweet licorice-like scent, traditionally for digestive comfort.", evidence: "Limited evidence; valued for its sweet aroma.", safety: "Avoid in pregnancy, with epilepsy, and with estrogen-sensitive conditions; can sensitize skin. Use very low dilution; never ingest; toxic to pets.", tags: ["anise", "sweet", "digestive", "caution"] }),
  oil({ id: "star-anise", name: "Star Anise", category: "Sweet / herbaceous", summary: "A sweet, warm, licorice-like oil steam-distilled from star anise fruit and high in trans-anethole, similar in scent and cautions to aniseed and used for a comforting spicy-sweet aroma. Evidence is limited; it is best used sparingly.", is: "Steam-distilled oil of star anise (Illicium verum) fruit, rich in trans-anethole.", uses: "Sweet spicy licorice-like scent, festive blends.", evidence: "Limited evidence; valued for its sweet aroma.", safety: "Avoid in pregnancy, with epilepsy, and with estrogen-sensitive conditions; can sensitize skin. Use very low dilution; never ingest; toxic to pets.", tags: ["anise", "sweet", "spice", "caution"] }),
  oil({ id: "nutmeg", name: "Nutmeg", category: "Warming / spice", summary: "A warm, sweet, spicy oil steam-distilled from nutmeg seeds, used for a cozy, comforting scent in festive and warming blends. It contains myristicin, which calls for moderate dilution and sensible limits.", is: "Steam-distilled oil of nutmeg seeds (contains myristicin).", uses: "Warming, cozy, spicy scent for festive blends.", evidence: "Limited evidence; valued for its warm aroma.", safety: "Use in moderation and low dilution (myristicin can be problematic in excess); avoid in pregnancy. Never ingest; keep away from pets.", tags: ["warming", "spice", "cozy", "caution"] }),
  oil({ id: "hyssop", name: "Hyssop", category: "Herbaceous / caution", summary: "A sharp, herbaceous, slightly sweet oil steam-distilled from hyssop, traditionally used for a clearing, uplifting scent but treated with caution due to its pinocamphone content. The standard chemotype is one of the riskier common oils.", is: "Steam-distilled oil of hyssop (Hyssopus officinalis); standard type is high in pinocamphones.", uses: "Traditionally a clearing herbaceous scent (used sparingly).", evidence: "Limited evidence; used cautiously.", safety: "The common (pinocamphone) chemotype can trigger seizures — avoid with epilepsy and in pregnancy, and use only the gentler decumbens chemotype if at all. Use very low dilution; never ingest; toxic to pets.", tags: ["herbaceous", "caution", "neurotoxic", "clearing"] }),
  oil({ id: "rosewood", name: "Rosewood", aka: ["bois de rose"], category: "Floral / woody", summary: "A soft, sweet, woody-floral oil steam-distilled from rosewood and rich in linalool, used for a gentle, soothing scent and in skin care. Evidence is limited; choose sustainably sourced oil, as wild rosewood has been over-harvested.", is: "Steam-distilled oil of rosewood, rich in linalool (seek sustainable sources).", uses: "Soothing woody-floral scent, gentle skin care.", evidence: "Limited evidence; valued for its gentle aroma.", safety: "Generally gentle; dilute before skin use. Never ingest; keep away from pets. Prefer responsibly sourced oil.", tags: ["woody", "floral", "linalool", "skin"] }),
  oil({ id: "copaiba", name: "Copaiba", category: "Grounding / soothing", summary: "A soft, mild, woody-balsamic oil steam-distilled from copaiba tree oleoresin and rich in beta-caryophyllene, used for a grounding scent and in soothing skin and relaxation blends. Evidence is limited; it is valued as one of the gentler base oils.", is: "Steam-distilled oil from copaiba (Copaifera) tree oleoresin, rich in beta-caryophyllene.", uses: "Grounding scent, soothing skin and relaxation blends.", evidence: "Limited evidence; valued for its mild aroma.", safety: "One of the gentler oils; still dilute before skin use and never ingest. Keep away from pets.", tags: ["woody", "grounding", "soothing", "balsamic"] }),
  oil({ id: "blue-tansy", name: "Blue Tansy", aka: ["Moroccan tansy"], category: "Calming / skin", summary: "A deep blue, sweet-herbaceous oil steam-distilled from blue tansy flowers, its color from soothing chamazulene, prized in skin care for calming irritated skin and for a relaxing aroma. Evidence is limited; it is a premium, sought-after oil.", is: "Steam-distilled oil of blue tansy (Tanacetum annuum); blue from chamazulene.", uses: "Soothing irritated skin, calming, a rich aroma.", evidence: "Limited evidence; popular in premium skin care.", safety: "Generally gentle but premium and easily adulterated — dilute. Never ingest; keep away from pets. (Distinct from toxic common tansy.)", tags: ["calm", "skin", "soothing", "blue"] }),
  oil({ id: "carrot-seed", name: "Carrot Seed", category: "Skin / restorative", summary: "An earthy, sweet, slightly woody oil steam-distilled from wild carrot seeds, prized in skin care for mature and dry skin and for a grounding, restorative reputation. Evidence is limited; it is valued chiefly for its skin-care tradition.", is: "Steam-distilled oil of wild carrot (Daucus carota) seeds.", uses: "Skin care — mature, dry skin; a grounding earthy scent.", evidence: "Limited evidence; popular in skin care.", safety: "Generally gentle; avoid in pregnancy as a precaution. Dilute; never ingest; keep away from pets.", tags: ["skin", "restorative", "earthy", "grounding"] }),
  oil({ id: "vanilla", name: "Vanilla", aka: ["vanilla oleoresin", "vanilla absolute"], category: "Sweet / comforting", summary: "A warm, sweet, comforting aroma produced as an absolute or oleoresin from cured vanilla pods (not a true steam-distilled essential oil), used to add cozy sweetness and a calming scent to blends. Evidence is limited; it is loved for its familiar, comforting aroma.", is: "Solvent-extracted absolute/oleoresin from cured vanilla pods (not a true essential oil).", uses: "Cozy sweet scent, comforting and calming blends.", evidence: "Limited evidence; valued for its comforting aroma.", safety: "Generally gentle but thick and best diluted; as an absolute it may carry trace solvent. Never ingest the concentrate; keep away from pets.", tags: ["sweet", "comforting", "absolute", "cozy"] }),
  oil({ id: "lavandin", name: "Lavandin", category: "Calming / fresh", summary: "A fresh, camphoraceous lavender-family oil steam-distilled from a hybrid of true lavender and spike lavender, more abundant and sharper than true lavender, used for relaxation, fresh scenting, and cleaning. Evidence is limited; it is a popular, affordable lavender alternative.", is: "Steam-distilled oil of lavandin (a lavender × spike lavender hybrid); higher in camphor than true lavender.", uses: "Relaxation, fresh scenting, cleaning blends.", evidence: "Limited evidence; a fresher, sharper lavender alternative.", safety: "Generally gentle but higher in camphor than true lavender — keep away from the faces of young children and avoid in pregnancy. Dilute; never ingest; keep away from pets.", tags: ["calm", "fresh", "lavender", "camphor"] }),
  oil({ id: "spike-lavender", name: "Spike Lavender", category: "Fresh / respiratory", summary: "A sharper, more camphoraceous member of the lavender family steam-distilled from Lavandula latifolia and higher in camphor and cineole, used for a clearing, fresh scent and a feeling of easier breathing. Evidence is limited; it is a more stimulating cousin of true lavender.", is: "Steam-distilled oil of spike lavender (Lavandula latifolia); high in camphor and cineole.", uses: "Clearing fresh scent, a feeling of clear breathing.", evidence: "Limited evidence; a more invigorating lavender relative.", safety: "Higher in camphor/cineole than true lavender — keep away from the faces of babies and young children and avoid in pregnancy. Dilute; never ingest; keep away from pets.", tags: ["fresh", "respiratory", "lavender", "camphor"] }),
  oil({ id: "lemon-eucalyptus", name: "Lemon Eucalyptus", aka: ["eucalyptus citriodora"], category: "Fresh / insect deterrent", summary: "A bright, lemony oil steam-distilled from Corymbia citriodora leaves, best known as an insect deterrent and for a fresh citrus-eucalyptus scent. Note this raw oil differs from the refined PMD repellent product; evidence for the raw oil is limited.", is: "Steam-distilled oil of lemon eucalyptus (Corymbia citriodora) leaves; citronellal-rich.", uses: "Insect deterrent, a fresh lemony scent.", evidence: "Limited evidence for the raw oil (the refined PMD derivative is a registered repellent).", safety: "Citronellal-rich, so a skin sensitizer — use low dilution and patch test. Never ingest; toxic to pets; keep away from young children's faces.", tags: ["citrus", "insect", "fresh", "sensitizer"] }),
  oil({ id: "manuka", name: "Manuka", category: "Skin / antimicrobial", summary: "A warm, herbaceous, slightly sweet oil steam-distilled from the New Zealand manuka shrub, used in diluted topical skin-care blends and valued, like tea tree, for an antimicrobial reputation. Evidence is limited but promising for topical skin use.", is: "Steam-distilled oil of manuka (Leptospermum scoparium).", uses: "Diluted topical skin care; a warm herbaceous scent.", evidence: "Limited but promising evidence for topical antimicrobial use.", safety: "Generally gentle; dilute and patch test. Never ingest; keep away from pets.", tags: ["skin", "antimicrobial", "herbaceous", "topical"] }),
  oil({ id: "niaouli", name: "Niaouli", category: "Respiratory", summary: "A fresh, slightly sweet, cineole-rich oil steam-distilled from the niaouli tree (a Melaleuca relative), used for a clearing respiratory scent and in topical blends. Evidence is limited; it is valued for a feeling of easier breathing.", is: "Steam-distilled oil of niaouli (Melaleuca quinquenervia), rich in 1,8-cineole.", uses: "Clearing respiratory scent, topical blends.", evidence: "Limited evidence; valued for a feeling of clear breathing.", safety: "Cineole-rich — keep away from the faces of babies and young children (apnea risk). Dilute; never ingest; toxic to pets.", tags: ["respiratory", "cineole", "fresh", "clearing"] }),
  oil({ id: "cajeput", name: "Cajeput", category: "Respiratory", summary: "A sharp, fresh, medicinal oil steam-distilled from the cajeput tree (a Melaleuca relative) and rich in 1,8-cineole, used for a clearing respiratory scent and warming topical blends. Evidence is limited; it is valued for a feeling of clearer breathing.", is: "Steam-distilled oil of cajeput (Melaleuca cajuputi), rich in 1,8-cineole.", uses: "Clearing respiratory scent, warming topical blends.", evidence: "Limited evidence; valued for a feeling of clear breathing.", safety: "Cineole-rich — keep away from the faces of babies and young children (apnea risk). Dilute; can irritate sensitive skin; never ingest; toxic to pets.", tags: ["respiratory", "cineole", "fresh", "clearing"] }),
  oil({ id: "ravintsara", name: "Ravintsara", category: "Respiratory / immune", summary: "A fresh, soft, cineole-rich oil steam-distilled from the leaves of the Madagascar camphor tree (the cineole, not camphor, chemotype), popular for a clearing, supportive respiratory scent. Evidence is limited; it is valued as a gentler cineole oil.", is: "Steam-distilled leaf oil of Cinnamomum camphora ct. cineole from Madagascar.", uses: "Clearing respiratory scent, a supportive feeling.", evidence: "Limited evidence; valued for a feeling of clear breathing.", safety: "Cineole-rich — keep away from the faces of babies and young children (apnea risk). Dilute; never ingest; toxic to pets. (Distinct from camphor-rich ravensara/camphor oils.)", tags: ["respiratory", "cineole", "immune", "fresh"] }),
  oil({ id: "tangelo-yuzu", name: "Yuzu", category: "Citrus / uplifting", summary: "A complex, bright, tart-sweet Japanese citrus oil, available cold-pressed or steam-distilled, used for an uplifting, refreshing scent in mood and perfume blends. Evidence is limited; it is prized for its distinctive aroma.", is: "Cold-pressed or steam-distilled oil from yuzu (Citrus junos) peel.", uses: "Uplifting, refreshing scent, mood and perfume blends.", evidence: "Limited evidence; valued for its bright aroma.", safety: "Cold-pressed yuzu may be mildly phototoxic — keep treated skin out of strong sun (steam-distilled is non-phototoxic). Dilute; never ingest; toxic to pets (d-limonene).", tags: ["citrus", "uplift", "fresh", "phototoxic"] }),
  oil({ id: "bay-laurel", name: "Bay Laurel", aka: ["laurel leaf", "sweet bay"], category: "Herbaceous / warming", summary: "A warm, spicy, herbaceous oil steam-distilled from bay laurel leaves and rich in 1,8-cineole, used for a clearing, invigorating scent and warming blends. Evidence is limited; it is valued for its spicy, fresh aroma.", is: "Steam-distilled oil of bay laurel (Laurus nobilis) leaves; cineole-rich.", uses: "Clearing invigorating scent, warming blends.", evidence: "Limited evidence; valued for its spicy aroma.", safety: "Can sensitize skin (contains costunolide); use low dilution and patch test; avoid in pregnancy. Cineole-rich, so keep off young children's faces. Never ingest; toxic to pets.", tags: ["herbaceous", "warming", "cineole", "sensitizer"] }),
  oil({ id: "tarragon", name: "Tarragon", aka: ["estragon"], category: "Herbaceous / digestive", summary: "A sweet, anise-like, herbaceous oil steam-distilled from tarragon and high in estragole (methyl chavicol), traditionally linked to digestive comfort. Its estragole content brings real cautions, so it is used sparingly.", is: "Steam-distilled oil of tarragon (Artemisia dracunculus), high in estragole.", uses: "Sweet herbaceous anise-like scent, traditionally digestive.", evidence: "Limited evidence; used sparingly.", safety: "High in estragole, a compound of concern in excess — use very low dilution and sparingly; avoid in pregnancy. Never ingest; toxic to pets.", tags: ["herbaceous", "anise", "estragole", "caution"] }),
  oil({ id: "davana", name: "Davana", category: "Floral / sweet", summary: "A rich, sweet, fruity-floral oil steam-distilled from the davana plant, prized in perfumery for a complex, honeyed aroma that smells slightly different on each person. Evidence is limited; it is valued chiefly as a perfume note.", is: "Steam-distilled oil of davana (Artemisia pallens).", uses: "Perfumery, a sweet fruity-floral scent, mood blends.", evidence: "Limited evidence; valued for its unique aroma.", safety: "Avoid in pregnancy (an Artemisia species). Dilute; never ingest; keep away from pets.", tags: ["floral", "sweet", "perfume", "fruity"] }),
  oil({ id: "elemi", name: "Elemi", category: "Grounding / resinous", summary: "A fresh, lemony-resinous oil steam-distilled from elemi tree resin, a relative of frankincense used for a grounding, clarifying scent and in meditation and skin blends. Evidence is limited; it is valued for its bright, balsamic aroma.", is: "Steam-distilled oil of elemi (Canarium luzonicum) resin.", uses: "Grounding clarifying scent, meditation, skin blends.", evidence: "Limited evidence; valued for its fresh resinous aroma.", safety: "Generally gentle; dilute before skin use. Never ingest; keep away from pets.", tags: ["resin", "grounding", "fresh", "meditation"] }),
  oil({ id: "galbanum", name: "Galbanum", category: "Green / grounding", summary: "An intense, green, earthy oil steam-distilled from galbanum resin, used in tiny amounts in perfumery for a sharp green top note and a grounding effect. Evidence is limited; it is valued chiefly as a distinctive perfume material.", is: "Steam-distilled oil of galbanum (Ferula) resin.", uses: "Perfumery green note, grounding blends (used sparingly).", evidence: "Limited evidence; valued for its green aroma.", safety: "Avoid in pregnancy. Dilute and use sparingly; never ingest; keep away from pets.", tags: ["green", "resin", "perfume", "grounding"] }),
];
