import type { ReferenceEntry } from "../types";

/**
 * Quick-reference herb lookup — what each herb is, its traditional use, the
 * evidence, and (critically) safety. Sourced from docs/learning-library-research.md.
 * Not medical advice; always check with a clinician/pharmacist before combining
 * herbs with medication, in pregnancy, or for a medical condition.
 */

function herb(e: {
  id: string; name: string; aka?: string[]; category: string; summary: string;
  is: string; tradition: string; evidence: string; safety?: string; tags?: string[];
}): ReferenceEntry {
  const fields = [
    { label: "What it is", value: e.is },
    { label: "Traditionally for", value: e.tradition },
    { label: "Evidence", value: e.evidence },
  ];
  return {
    domain: "herbalism",
    id: e.id,
    name: e.name,
    aka: e.aka,
    category: e.category,
    summary: e.summary,
    fields,
    safety: e.safety,
    tags: e.tags,
  };
}

export const herbReference: ReferenceEntry[] = [
  herb({ id: "chamomile", name: "Chamomile", category: "Calming", summary: "A gentle daisy-family flower, usually taken as a tea, traditionally used to calm the mind, ease sleep, and settle mild digestive upset. There is modest evidence for mild anxiety and sleep, and it is generally very gentle.", is: "A daisy-family flower, taken mostly as a tea.", tradition: "Calm, sleep, mild digestive upset.", evidence: "Modest evidence for mild anxiety and sleep; generally very gentle.", safety: "Usually safe. People allergic to ragweed/daisies may react; very high doses may add to blood thinners.", tags: ["calm", "sleep", "tea", "gentle"] }),
  herb({ id: "valerian", name: "Valerian", category: "Calming", summary: "A sedating root taken as tea, tincture, or capsule, traditionally used for sleep, anxiety, and restlessness. The evidence for sleep is mixed and any effects are modest.", is: "A root taken as tea, tincture, or capsule.", tradition: "Sleep, anxiety, restlessness.", evidence: "Mixed evidence for sleep; effects are modest.", safety: "Causes drowsiness — do not combine with alcohol, sleep aids, or anti-anxiety meds, and don't drive if drowsy.", tags: ["sleep", "sedative", "anxiety"] }),
  herb({ id: "lemon-balm", name: "Lemon Balm", aka: ["melissa"], category: "Calming", summary: "A lemon-scented mint-family leaf, often taken as a tea, traditionally used for calm, mood, sleep, and digestion. Evidence for stress and sleep is limited but promising.", is: "A mint-family leaf, often as tea.", tradition: "Calm, mood, sleep, digestion.", evidence: "Limited but promising evidence for stress and sleep.", tags: ["calm", "mood", "mint"] }),
  herb({ id: "ginger", name: "Ginger", category: "Digestive", summary: "A pungent root used fresh, dried, or as capsules, traditionally valued for nausea, digestion, and its warming quality. There is good evidence that it reduces nausea, including motion, pregnancy, and chemo-related forms.", is: "A pungent root used fresh, dried, or as capsules.", tradition: "Nausea, digestion, warming.", evidence: "Good evidence it reduces nausea (motion, pregnancy, chemo-related).", safety: "Very high doses may slightly thin the blood — use caution with blood thinners.", tags: ["nausea", "digestion", "root"] }),
  herb({ id: "peppermint", name: "Peppermint", category: "Digestive", summary: "A mint leaf whose oil is used in capsules, traditionally taken for indigestion, IBS, headaches, and congestion. There is good evidence that enteric-coated oil eases IBS symptoms.", is: "A mint leaf; the oil is used in capsules.", tradition: "Indigestion, IBS, headaches, congestion.", evidence: "Good evidence (enteric-coated oil) for IBS symptoms.", safety: "Can worsen acid reflux/heartburn in some people. Keep concentrated oil away from infants' faces.", tags: ["ibs", "digestion", "mint", "headache"] }),
  herb({ id: "echinacea", name: "Echinacea", category: "Immune", summary: "A coneflower taken as tincture, tea, or capsule, traditionally used to prevent or shorten colds. The evidence is weak and inconsistent, and at best it may slightly shorten a cold.", is: "A coneflower, taken as tincture, tea, or capsule.", tradition: "Preventing or shortening colds.", evidence: "Weak and inconsistent — at best it may slightly shorten a cold.", safety: "People allergic to daisies/ragweed may react; caution with autoimmune conditions.", tags: ["cold", "immune", "coneflower"] }),
  herb({ id: "turmeric", name: "Turmeric (Curcumin)", category: "Anti-inflammatory", summary: "A golden root and spice whose active compound is curcumin, traditionally used for inflammation, joint pain, and digestion. There is some evidence for inflammation and joints, but curcumin is poorly absorbed on its own.", is: "A root/spice; curcumin is its active compound.", tradition: "Inflammation, joint pain, digestion.", evidence: "Some evidence for inflammation/joints, but curcumin is poorly absorbed on its own.", safety: "High-dose supplements can upset the stomach and may add to blood thinners; rare liver issues reported.", tags: ["inflammation", "joints", "spice", "curcumin"] }),
  herb({ id: "ginkgo", name: "Ginkgo Biloba", category: "Circulation / cognition", summary: "An extract of ginkgo tree leaves, traditionally used for memory, circulation, and focus. It is not supported for preventing dementia or boosting memory in healthy people.", is: "An extract of ginkgo tree leaves.", tradition: "Memory, circulation, focus.", evidence: "Not supported for preventing dementia or boosting memory in healthy people.", safety: "Increases bleeding risk — avoid with blood thinners (warfarin, aspirin) and stop before surgery.", tags: ["memory", "circulation", "bleeding"] }),
  herb({ id: "st-johns-wort", name: "St John's Wort", category: "Mood", summary: "A yellow-flowered herb usually taken as capsules or tincture, traditionally used for low mood and mild depression. There is some evidence for mild-to-moderate depression, but it has major drug interactions.", is: "A yellow-flowered herb, usually as capsules/tincture.", tradition: "Low mood, mild depression.", evidence: "Some evidence for mild-to-moderate depression.", safety: "MAJOR interactions: reduces the effect of birth control, blood thinners, transplant and HIV/cancer drugs, and more; with SSRIs can cause serotonin syndrome. Never start without checking with a doctor/pharmacist.", tags: ["depression", "mood", "interactions", "birth control"] }),
  herb({ id: "lavender", name: "Lavender", category: "Calming", summary: "A fragrant flower used as oil, tea, or capsule, traditionally taken for relaxation, sleep, and anxiety. There is modest evidence, from aromatherapy and a standardized oral oil, for anxiety and sleep.", is: "A fragrant flower; used as oil, tea, or capsule.", tradition: "Relaxation, sleep, anxiety.", evidence: "Modest evidence (aromatherapy and a standardized oral oil) for anxiety and sleep.", safety: "Essential oil is for inhalation/diluted topical use — don't swallow essential oil. See the essential-oils course for dilution and pet safety.", tags: ["relax", "sleep", "anxiety", "aroma"] }),
  herb({ id: "ashwagandha", name: "Ashwagandha", category: "Adaptogen", summary: "A root used in Ayurveda, taken as powder or capsule, traditionally valued for stress, energy, sleep, and vitality. There is some evidence it modestly reduces stress and improves sleep.", is: "A root used in Ayurveda, taken as powder or capsule.", tradition: "Stress, energy, sleep, vitality.", evidence: "Some evidence it modestly reduces stress and improves sleep.", safety: "Avoid in pregnancy; caution with thyroid conditions, autoimmune disease, and sedatives. Rare liver injury reported.", tags: ["stress", "adaptogen", "ayurveda", "sleep"] }),
  herb({ id: "garlic", name: "Garlic", category: "Cardiovascular", summary: "A culinary bulb, also sold as concentrated supplements, traditionally used for heart health, immunity, and circulation. There is modest evidence for small reductions in blood pressure and cholesterol.", is: "A culinary bulb; also concentrated supplements.", tradition: "Heart health, immunity, circulation.", evidence: "Modest evidence for small reductions in blood pressure and cholesterol.", safety: "High-dose supplements increase bleeding risk with blood thinners and before surgery.", tags: ["heart", "blood pressure", "bleeding", "cholesterol"] }),
  herb({ id: "ginseng", name: "Ginseng (Panax)", category: "Adaptogen", summary: "A root from the Asian or American Panax species, traditionally used for energy, stamina, cognition, and immunity. The evidence for fatigue and cognition is mixed.", is: "A root (Asian/American Panax species).", tradition: "Energy, stamina, cognition, immunity.", evidence: "Mixed evidence for fatigue and cognition.", safety: "Can affect blood sugar and blood pressure and interacts with blood thinners, diabetes, and other meds; may cause insomnia. Not for pregnancy.", tags: ["energy", "focus", "adaptogen", "blood sugar"] }),
  herb({ id: "milk-thistle", name: "Milk Thistle", category: "Liver", summary: "A thistle seed extract known as silymarin, traditionally used for liver support and detox. The evidence is limited and mixed, though it is generally well tolerated.", is: "A thistle seed extract (silymarin).", tradition: "Liver support, detox.", evidence: "Limited and mixed evidence; generally well tolerated.", safety: "Usually safe; may cause mild GI upset; people allergic to daisies/ragweed may react.", tags: ["liver", "detox", "silymarin"] }),
  herb({ id: "elderberry", name: "Elderberry", category: "Immune", summary: "The dark berry of the elder shrub, taken as syrup or lozenge, traditionally used for colds, flu, and immune support. There is some evidence that syrups may modestly ease cold and flu symptoms.", is: "The berry of the elder shrub, as syrup or lozenge.", tradition: "Colds and flu, immune support.", evidence: "Some evidence (syrups) may modestly ease cold/flu symptoms.", safety: "RAW elderberries, leaves, bark, and seeds are toxic and cause nausea/vomiting — only use properly cooked/prepared products.", tags: ["cold", "flu", "immune", "toxic raw"] }),
  herb({ id: "passionflower", name: "Passionflower", category: "Calming", summary: "A flowering climbing vine taken as tea or tincture, traditionally used for anxiety, restlessness, and sleep. The evidence for anxiety and sleep is limited.", is: "A flowering vine, as tea or tincture.", tradition: "Anxiety, restlessness, sleep.", evidence: "Limited evidence for anxiety and sleep.", safety: "Can cause drowsiness — don't combine with sedatives or alcohol; avoid in pregnancy.", tags: ["anxiety", "sleep", "sedative"] }),
  herb({ id: "nettle", name: "Nettle", aka: ["stinging nettle"], category: "General", summary: "A nutritive leafy green that is cooked or dried to remove the sting, traditionally used for seasonal allergies, joint aches, and nutrition. The evidence is limited and, while popular, it is not well proven.", is: "A leafy green (cooked/dried removes the sting).", tradition: "Seasonal allergies, joint aches, nutrition.", evidence: "Limited evidence; popular but not well proven.", safety: "Generally safe cooked/dried; may interact with blood pressure, diuretic, or diabetes medication.", tags: ["allergies", "joints", "green"] }),
  herb({ id: "dandelion", name: "Dandelion", category: "Digestive", summary: "A common plant whose leaf and root are used as a digestive bitter, traditionally taken for digestion, as a mild diuretic, and for liver support. The use is mostly traditional, with little clinical evidence.", is: "The leaf and root of the dandelion plant.", tradition: "Digestion, mild diuretic, liver support.", evidence: "Mostly traditional; little clinical evidence.", safety: "May act as a diuretic and interact with some medications; daisy-family allergy possible.", tags: ["digestion", "diuretic", "bitter"] }),
  herb({ id: "fennel", name: "Fennel", category: "Digestive", summary: "A licorice-flavored aromatic seed used as tea or culinary spice, traditionally taken for gas, bloating, colic, and digestion. The evidence is limited, though it has a long history of culinary use.", is: "An aromatic seed, as tea or culinary spice.", tradition: "Gas, bloating, colic, digestion.", evidence: "Limited evidence; long culinary use.", safety: "Culinary amounts are fine; avoid concentrated medicinal doses in pregnancy.", tags: ["digestion", "bloating", "seed"] }),
  herb({ id: "tulsi", name: "Holy Basil (Tulsi)", aka: ["tulsi"], category: "Adaptogen", summary: "A basil relative central to Ayurveda, traditionally used for stress, mood, and immunity. The evidence for stress and mood is limited but growing.", is: "A basil relative central to Ayurveda.", tradition: "Stress, mood, immunity.", evidence: "Limited but growing evidence for stress and mood.", safety: "Generally well tolerated; may affect blood sugar and blood clotting — caution with related meds and around surgery.", tags: ["stress", "adaptogen", "ayurveda", "basil"] }),
  herb({ id: "rosemary", name: "Rosemary", category: "Culinary / cognition", summary: "A woody, fragrant culinary herb, traditionally used for memory, focus, circulation, and the hair and scalp. The use is mostly traditional, with some preliminary work on aroma and cognition.", is: "A woody culinary herb.", tradition: "Memory, focus, circulation, hair/scalp.", evidence: "Mostly traditional; some preliminary aroma/cognition work.", safety: "Culinary amounts are safe; avoid concentrated medicinal doses in pregnancy.", tags: ["memory", "focus", "culinary"] }),
  herb({ id: "sage", name: "Sage", category: "Culinary / wellness", summary: "A culinary herb also taken as tea or extract, traditionally used for sore throat, sweating, menopause symptoms, and memory. There is some evidence for sore throat and menopausal hot flashes.", is: "A culinary herb; also taken as tea/extract.", tradition: "Sore throat, sweating, menopause symptoms, memory.", evidence: "Some evidence for sore throat and menopausal hot flashes.", safety: "Contains thujone — avoid concentrated/medicinal doses in pregnancy and breastfeeding; culinary amounts are fine.", tags: ["throat", "menopause", "culinary", "thujone"] }),

  // — Culinary & aromatic herbs —
  herb({ id: "thyme", name: "Thyme", category: "Culinary / respiratory", summary: "A small aromatic culinary herb, taken as tea or in syrups, traditionally used for coughs, sore throats, and chest congestion. There is some evidence its extracts ease cough, often paired with ivy leaf.", is: "An aromatic culinary herb; tea, syrup, or extract.", tradition: "Cough, sore throat, chest congestion, antimicrobial.", evidence: "Some evidence (often with ivy leaf) for easing cough; good antimicrobial activity in the lab.", safety: "Culinary amounts are safe. Avoid concentrated thyme essential oil internally; medicinal doses are best avoided in pregnancy.", tags: ["cough", "throat", "culinary", "respiratory"] }),
  herb({ id: "oregano", name: "Oregano", category: "Culinary / antimicrobial", summary: "A pungent culinary herb whose concentrated oil is sold as a supplement, traditionally used for infections and digestion. Lab studies show strong antimicrobial activity, but human evidence is limited.", is: "A culinary herb; oil of oregano is the concentrated supplement.", tradition: "Infections, digestion, immune support.", evidence: "Strong antimicrobial activity in the lab; limited human evidence.", safety: "Culinary use is safe. Concentrated oregano oil can irritate the gut/mouth and may thin blood and lower blood sugar; avoid medicinal doses in pregnancy.", tags: ["antimicrobial", "culinary", "oil", "digestion"] }),
  herb({ id: "basil", name: "Basil", category: "Culinary", summary: "The classic sweet culinary herb, used fresh or as tea, traditionally taken for digestion, stress, and as an antimicrobial. Beyond culinary use, clinical evidence is minimal.", is: "A sweet culinary leaf; fresh or as tea.", tradition: "Digestion, stress, mild antimicrobial.", evidence: "Mostly culinary and traditional; minimal clinical evidence (note: holy basil/tulsi is the more medicinal relative).", safety: "Culinary amounts are safe; avoid concentrated medicinal extracts in pregnancy.", tags: ["culinary", "digestion", "stress"] }),
  herb({ id: "dill", name: "Dill", category: "Digestive", summary: "A feathery aromatic herb and seed, used in cooking and as tea, traditionally taken for gas, colic, and digestion. Evidence is largely traditional.", is: "An aromatic herb and seed; culinary or as tea.", tradition: "Gas, colic, digestion, freshening breath.", evidence: "Largely traditional; little clinical evidence.", safety: "Culinary amounts are safe; avoid concentrated medicinal doses in pregnancy.", tags: ["digestion", "colic", "seed", "culinary"] }),
  herb({ id: "caraway", name: "Caraway", category: "Digestive", summary: "A warm aromatic seed, used in cooking and as tea, traditionally taken for bloating, gas, and cramps. Caraway oil with peppermint oil has some evidence for indigestion.", is: "An aromatic seed; culinary or as tea/oil.", tradition: "Bloating, gas, cramps, digestion.", evidence: "Some evidence (caraway-plus-peppermint oil) for functional indigestion.", safety: "Culinary amounts are safe; avoid concentrated medicinal doses in pregnancy.", tags: ["digestion", "bloating", "seed"] }),
  herb({ id: "cardamom", name: "Cardamom", category: "Digestive", summary: "A fragrant pod-spice central to Indian and Middle Eastern cooking, used as tea or spice, traditionally taken for digestion, breath, and nausea. Evidence is mostly traditional.", is: "A fragrant pod-spice; culinary or as tea.", tradition: "Digestion, fresh breath, nausea.", evidence: "Mostly traditional; small studies on blood pressure and metabolism are early.", safety: "Culinary amounts are safe; high medicinal doses best avoided in pregnancy or with gallstones.", tags: ["digestion", "spice", "nausea"] }),
  herb({ id: "cinnamon", name: "Cinnamon", category: "Metabolic / culinary", summary: "A warm bark spice, used in cooking and as supplements, traditionally taken for blood sugar, digestion, and warmth. There is modest, mixed evidence for small reductions in blood sugar.", is: "A bark spice; culinary or as capsules.", tradition: "Blood sugar, digestion, warming, circulation.", evidence: "Modest, mixed evidence for small blood-sugar reductions.", safety: "Cassia cinnamon is high in coumarin, which can stress the liver in large daily doses — choose Ceylon cinnamon for supplements; high doses may interact with diabetes and liver medication.", tags: ["blood sugar", "spice", "coumarin", "liver"] }),
  herb({ id: "clove", name: "Clove", category: "Culinary / dental", summary: "An intensely aromatic flower bud, used as spice and as clove oil, traditionally taken for toothache, digestion, and as an antimicrobial. Clove oil (eugenol) has real local numbing/antiseptic action for dental pain.", is: "An aromatic flower bud; spice or clove oil.", tradition: "Toothache, digestion, antimicrobial.", evidence: "Clove oil (eugenol) has genuine local numbing and antiseptic action; broader claims are traditional.", safety: "Clove oil is potent — dilute for topical use and don't swallow it; it can irritate gums and may thin the blood. Keep away from children.", tags: ["dental", "toothache", "oil", "antimicrobial"] }),
  herb({ id: "nutmeg", name: "Nutmeg", category: "Culinary", summary: "A warm baking spice, used in small culinary amounts, traditionally taken for digestion and sleep. In large doses it is genuinely toxic and hallucinogenic.", is: "A warm seed-spice; small culinary amounts.", tradition: "Digestion, sleep, warming.", evidence: "Mostly traditional in culinary doses.", safety: "TOXIC in large doses — a few teaspoons can cause hallucinations, racing heart, nausea, and serious poisoning. Use only culinary pinches; avoid medicinal doses, especially in pregnancy.", tags: ["culinary", "spice", "toxic in excess"] }),
  herb({ id: "black-pepper", name: "Black Pepper", category: "Culinary / absorption", summary: "The everyday table spice, whose compound piperine is added to supplements, traditionally used for digestion and to enhance absorption. Piperine genuinely boosts curcumin and some drug absorption.", is: "A common spice; piperine is the active compound.", tradition: "Digestion, warming, absorption aid.", evidence: "Piperine reliably boosts absorption of curcumin and some nutrients/drugs.", safety: "Culinary amounts are safe. Because piperine raises drug absorption, high-dose supplements can intensify medications — use caution if you take prescription drugs.", tags: ["absorption", "piperine", "digestion", "spice"] }),
  herb({ id: "cayenne", name: "Cayenne", aka: ["capsicum", "chili"], category: "Circulation / pain", summary: "A hot chili pepper whose compound is capsaicin, used in food and topical creams, traditionally taken for circulation, metabolism, and pain. Topical capsaicin has good evidence for nerve and joint pain.", is: "A hot chili; capsaicin is the active compound.", tradition: "Circulation, metabolism, pain, digestion.", evidence: "Topical capsaicin has good evidence for nerve pain and osteoarthritis.", safety: "Topical cream burns — wash hands and keep away from eyes. Can aggravate reflux/ulcers; high doses may thin blood and interact with blood-pressure or blood-thinning meds.", tags: ["pain", "capsaicin", "circulation", "topical"] }),
  herb({ id: "lemongrass", name: "Lemongrass", category: "Digestive / calming", summary: "A citrusy grass used as tea and in cooking, traditionally taken for digestion, calm, and mild fever. Evidence is largely traditional.", is: "A citrusy grass; tea or culinary.", tradition: "Digestion, calm, mild fever, antimicrobial.", evidence: "Largely traditional; small early studies only.", safety: "Tea amounts are generally safe; avoid concentrated medicinal doses in pregnancy. Essential oil is for diluted external use, not swallowing.", tags: ["digestion", "calm", "tea", "citrus"] }),
  herb({ id: "lemon-verbena", name: "Lemon Verbena", category: "Calming / digestive", summary: "A lemon-scented leaf used as tea, traditionally taken for digestion, calm, and sleep. Evidence is limited and mostly traditional.", is: "A lemon-scented leaf; usually as tea.", tradition: "Digestion, calm, sleep.", evidence: "Limited; mostly traditional with small studies on recovery/antioxidants.", safety: "Generally gentle; avoid concentrated medicinal doses in pregnancy and with kidney disease.", tags: ["calm", "digestion", "tea", "citrus"] }),
  herb({ id: "spearmint", name: "Spearmint", category: "Digestive / hormonal", summary: "A milder mint than peppermint, used as tea, traditionally taken for digestion and freshening breath. Spearmint tea has some evidence for lowering androgens in women with PCOS-related hirsutism.", is: "A mild mint leaf; usually as tea.", tradition: "Digestion, fresh breath, mild calm.", evidence: "Some evidence spearmint tea lowers male hormones (helpful in PCOS-related facial hair); digestive use is traditional.", safety: "Generally gentle and safe; very high intake may affect hormones, so use moderate amounts if pregnant.", tags: ["digestion", "pcos", "hormones", "mint"] }),
  herb({ id: "anise", name: "Anise", aka: ["aniseed"], category: "Digestive", summary: "A licorice-flavored seed, used as tea and in cooking, traditionally taken for gas, cough, and colic. Evidence is mostly traditional.", is: "A licorice-flavored seed; tea or culinary.", tradition: "Gas, bloating, cough, colic.", evidence: "Mostly traditional; small studies on indigestion and menopause.", safety: "Culinary amounts are safe; has mild estrogen-like activity, so avoid concentrated medicinal doses in pregnancy or with hormone-sensitive conditions.", tags: ["digestion", "cough", "seed"] }),
  herb({ id: "star-anise", name: "Star Anise", category: "Digestive / antiviral", summary: "A star-shaped pod-spice, the source of shikimic acid used to make Tamiflu, traditionally taken for digestion and colds. Culinary Chinese star anise is safe; the Japanese species is toxic.", is: "A star-shaped pod-spice; culinary or as tea.", tradition: "Digestion, gas, colds, flu.", evidence: "Source of shikimic acid (Tamiflu precursor); direct herbal evidence is limited.", safety: "Use only Chinese star anise — Japanese star anise is toxic and can cause seizures, and the two are easily confused. Avoid giving to infants; avoid medicinal doses in pregnancy.", tags: ["digestion", "spice", "toxic look-alike", "antiviral"] }),
  herb({ id: "cumin", name: "Cumin", category: "Digestive / culinary", summary: "An earthy seed-spice central to many cuisines, used in food and as tea, traditionally taken for digestion and blood sugar. Evidence is mostly traditional with early metabolic studies.", is: "An earthy seed-spice; culinary or as tea.", tradition: "Digestion, gas, blood sugar.", evidence: "Mostly traditional; early studies on blood sugar and lipids.", safety: "Culinary amounts are safe; high medicinal doses may lower blood sugar and are best avoided in pregnancy.", tags: ["digestion", "blood sugar", "spice"] }),
  herb({ id: "coriander", name: "Coriander", aka: ["cilantro"], category: "Digestive / culinary", summary: "The seed and leaf of the same plant (cilantro), used in cooking and as tea, traditionally taken for digestion and blood sugar. Evidence is mostly traditional.", is: "Seed and leaf of one plant; culinary or as tea.", tradition: "Digestion, gas, blood sugar.", evidence: "Mostly traditional; small studies on blood sugar and lipids.", safety: "Culinary amounts are safe; high medicinal doses may lower blood sugar and are best avoided in pregnancy.", tags: ["digestion", "blood sugar", "spice", "cilantro"] }),
  herb({ id: "fenugreek", name: "Fenugreek", category: "Metabolic / lactation", summary: "A maple-scented seed used in cooking and as supplements, traditionally taken for blood sugar, milk supply, and digestion. There is some evidence for blood sugar and for boosting breast-milk supply.", is: "A maple-scented seed; culinary or as capsules.", tradition: "Blood sugar, milk supply, digestion, appetite.", evidence: "Some evidence for lowering blood sugar and increasing breast-milk supply.", safety: "Can lower blood sugar (caution with diabetes meds) and may thin blood. Avoid medicinal doses in pregnancy (may stimulate the uterus). May cause a maple-syrup body odor.", tags: ["blood sugar", "lactation", "seed", "diabetes"] }),

  // — Bitters, liver & digestive roots —
  herb({ id: "burdock", name: "Burdock", category: "Liver / skin", summary: "A long taproot used as tea, tincture, or food, traditionally taken as a blood and skin tonic and gentle diuretic. Evidence is largely traditional.", is: "A taproot; tea, tincture, or vegetable.", tradition: "Skin conditions, 'blood cleansing', digestion, diuretic.", evidence: "Largely traditional; little clinical evidence.", safety: "Generally well tolerated; may act as a diuretic and lower blood sugar. Daisy-family allergy possible; avoid in pregnancy. Wild-harvested burdock can be confused with toxic belladonna.", tags: ["skin", "liver", "diuretic", "root"] }),
  herb({ id: "gentian", name: "Gentian", category: "Digestive bitter", summary: "An intensely bitter root used in digestive bitters and aperitifs, traditionally taken to stimulate appetite and digestion. Bitters genuinely stimulate digestive secretions.", is: "A very bitter root; tincture or in bitters.", tradition: "Appetite, sluggish digestion, bloating.", evidence: "Bitters reliably stimulate saliva and digestive juices; specific claims are traditional.", safety: "Avoid with active stomach ulcers, severe reflux, or in pregnancy. Can lower blood pressure slightly.", tags: ["bitter", "appetite", "digestion", "root"] }),
  herb({ id: "artichoke", name: "Artichoke Leaf", category: "Liver / digestive", summary: "The leaf of the globe artichoke, taken as extract, traditionally used for digestion, liver support, and cholesterol. There is some evidence for indigestion and modest cholesterol lowering.", is: "The leaf of the globe artichoke; as extract.", tradition: "Indigestion, liver/bile support, cholesterol.", evidence: "Some evidence for functional dyspepsia and modest cholesterol reduction.", safety: "Avoid with bile-duct blockage or gallstones (it stimulates bile flow); daisy-family allergy possible.", tags: ["liver", "digestion", "cholesterol", "bile"] }),
  herb({ id: "yellow-dock", name: "Yellow Dock", category: "Digestive / iron", summary: "A bitter root used as tincture or tea, traditionally taken as a gentle laxative, liver tonic, and iron-rich blood builder. Evidence is largely traditional.", is: "A bitter root; tincture or tea.", tradition: "Constipation, liver support, iron/blood building.", evidence: "Largely traditional; contains laxative anthraquinones.", safety: "High in oxalates — avoid with kidney stones or kidney disease. Don't use as a long-term laxative; avoid in pregnancy.", tags: ["laxative", "liver", "iron", "oxalate"] }),

  // — Mucilage & soothing demulcents —
  herb({ id: "marshmallow-root", name: "Marshmallow Root", category: "Soothing demulcent", summary: "A mucilage-rich root taken as cold infusion or capsule, traditionally used to soothe sore throat, cough, and irritated gut. There is reasonable support for its soothing, coating action.", is: "A mucilage-rich root; cold infusion or capsule.", tradition: "Sore throat, dry cough, irritated stomach/gut lining.", evidence: "Reasonable support for its demulcent (coating, soothing) action on irritated tissue.", safety: "Generally very safe. Its coating action can slow absorption of other medicines — take a couple of hours apart. May lower blood sugar slightly.", tags: ["throat", "cough", "soothing", "gut"] }),
  herb({ id: "slippery-elm", name: "Slippery Elm", category: "Soothing demulcent", summary: "The mucilage-rich inner bark of the elm, taken as powder or lozenge, traditionally used for sore throat, heartburn, and irritated gut. Support is mostly traditional but consistent for soothing.", is: "Mucilage-rich inner bark; powder or lozenge.", tradition: "Sore throat, heartburn, IBS, irritated gut.", evidence: "Mostly traditional but widely used as a gentle soothing demulcent.", safety: "Generally very safe. Its coating action can slow absorption of other medicines — take a couple of hours apart. (Slippery elm is a threatened tree — buy sustainably sourced bark.)", tags: ["throat", "heartburn", "soothing", "gut"] }),
  herb({ id: "plantain-leaf", name: "Plantain (Leaf)", aka: ["plantago", "ribwort"], category: "Soothing / topical", summary: "A common lawn weed (not the banana), used as poultice, tea, or salve, traditionally taken for bites, wounds, and cough. Evidence is largely traditional but it is a gentle soother.", is: "A common weed leaf (Plantago, not the banana); poultice, tea, or salve.", tradition: "Insect bites, minor wounds, cough, irritated skin.", evidence: "Largely traditional; mild soothing and astringent action.", safety: "Generally very safe topically and as tea; avoid concentrated medicinal doses in pregnancy.", tags: ["bites", "wounds", "cough", "topical"] }),
  herb({ id: "mullein", name: "Mullein", category: "Respiratory", summary: "A tall woolly-leaved plant used as tea or tincture, and the flower as ear oil, traditionally taken for cough, congestion, and earache. Evidence is largely traditional.", is: "Woolly leaves (tea/tincture) and flowers (ear oil).", tradition: "Cough, bronchial congestion, earache, sore throat.", evidence: "Largely traditional; flower ear oil is a folk remedy.", safety: "Strain leaf tea well — the fine hairs can irritate the throat. Don't put ear oil in an ear with a ruptured eardrum.", tags: ["cough", "congestion", "earache", "respiratory"] }),
  herb({ id: "oat-straw", name: "Oat Straw", aka: ["milky oats", "avena"], category: "Nervine tonic", summary: "The green stalk and seed of the oat plant, taken as tea or tincture, traditionally used as a gentle nervous-system tonic for stress and fatigue. Evidence is limited and mostly traditional.", is: "The green oat plant; tea or tincture (milky oats).", tradition: "Nervous exhaustion, stress, mild anxiety, vitality.", evidence: "Limited; some early work on cognition and mood, otherwise traditional.", safety: "Generally very safe. Contains gluten-adjacent proteins, so people with celiac disease should choose certified gluten-free oat products.", tags: ["nervine", "stress", "tonic", "gentle"] }),

  // — Nervines, sleep & calming —
  herb({ id: "skullcap", name: "Skullcap", aka: ["scutellaria"], category: "Calming", summary: "A mint-family nervine taken as tea or tincture, traditionally used for anxiety, tension, and sleep. Evidence is limited but it is a popular gentle nervine.", is: "A mint-family nervine; tea or tincture.", tradition: "Anxiety, nervous tension, sleep, restlessness.", evidence: "Limited human evidence; small studies on anxiety/mood.", safety: "Can cause drowsiness — don't mix with sedatives or alcohol. Buy from reputable sources: skullcap has been adulterated with liver-toxic germander. Avoid in pregnancy.", tags: ["anxiety", "sleep", "nervine", "adulteration risk"] }),
  herb({ id: "hops", name: "Hops", category: "Calming", summary: "The flower used in beer, also taken as tea, tincture, or capsule, traditionally used for sleep and restlessness, often with valerian. There is limited evidence, mostly in combination, for sleep.", is: "A bittering flower; tea, tincture, or capsule.", tradition: "Sleep, restlessness, anxiety, appetite.", evidence: "Limited; some evidence (often combined with valerian) for sleep.", safety: "Sedating — don't combine with sleep aids or alcohol. Has estrogen-like activity, so caution with hormone-sensitive conditions; can worsen depression in some people.", tags: ["sleep", "sedative", "estrogenic"] }),
  herb({ id: "kava", name: "Kava", aka: ["kava kava", "piper methysticum"], category: "Calming", summary: "A Pacific Islands root traditionally prepared as a relaxing drink, used for anxiety and stress. There is reasonable evidence it reduces anxiety, but it carries a real risk of liver injury.", is: "A Pacific root, prepared as a drink or taken as extract.", tradition: "Anxiety, stress, social ease, relaxation.", evidence: "Reasonable evidence it reduces anxiety in the short term.", safety: "LIVER RISK: linked to severe, occasionally fatal liver injury, and banned/restricted in several countries. Never combine with alcohol, sedatives, or other liver-stressing drugs; avoid with any liver problem and in pregnancy. Don't use long-term, and stop if you notice jaundice or dark urine.", tags: ["anxiety", "liver risk", "sedative", "caution"] }),
  herb({ id: "california-poppy", name: "California Poppy", category: "Calming", summary: "A mild relative of the opium poppy (without strong opiates), taken as tea or tincture, traditionally used for sleep, anxiety, and mild pain. Evidence is limited and mostly traditional.", is: "A gentle poppy (not opium); tea or tincture.", tradition: "Sleep, anxiety, restlessness, mild pain.", evidence: "Limited; small studies, often combined with other calming herbs.", safety: "Mildly sedating — don't combine with sedatives or alcohol. Avoid in pregnancy; may interact with sedative and blood-pressure medication.", tags: ["sleep", "anxiety", "mild pain", "sedative"] }),
  herb({ id: "catnip", name: "Catnip", category: "Calming / digestive", summary: "A mint-family herb (famous with cats) taken as tea, traditionally used for calm, sleep, and digestion in people. Evidence is largely traditional.", is: "A mint-family herb; usually as tea.", tradition: "Calm, sleep, digestion, colic, mild fever.", evidence: "Largely traditional; little clinical evidence.", safety: "Generally gentle; mildly sedating. Avoid medicinal doses in pregnancy — it can stimulate the uterus.", tags: ["calm", "sleep", "digestion", "mint"] }),
  herb({ id: "motherwort", name: "Motherwort", category: "Calming / cardiac", summary: "A bitter mint-family herb taken as tincture or tea, traditionally used for anxiety, palpitations, and menstrual and menopausal complaints. Evidence is largely traditional.", is: "A bitter mint-family herb; tincture or tea.", tradition: "Anxiety, heart palpitations, menstrual cramps, menopause.", evidence: "Largely traditional; limited clinical evidence.", safety: "Avoid in pregnancy (can stimulate the uterus). May add to heart and blood-thinning medication and to sedatives — check with a clinician if you have a heart condition.", tags: ["anxiety", "palpitations", "menstrual", "heart"] }),

  // — Heart & circulation —
  herb({ id: "hawthorn", name: "Hawthorn", category: "Cardiovascular", summary: "A berry, leaf, and flower of the hawthorn shrub, taken as extract or tea, traditionally used as a heart tonic. There is some evidence it helps mild heart failure symptoms.", is: "Berry, leaf, and flower; extract or tea.", tradition: "Heart tonic, mild heart failure, blood pressure, palpitations.", evidence: "Some evidence as an add-on for mild heart-failure symptoms; otherwise traditional.", safety: "Can interact with heart and blood-pressure medication (digoxin, beta-blockers, nitrates) — only use under medical supervision if you have a heart condition or take cardiac drugs.", tags: ["heart", "blood pressure", "circulation", "interactions"] }),
  herb({ id: "hibiscus", name: "Hibiscus", aka: ["roselle"], category: "Cardiovascular", summary: "A tart red flower used as tea, traditionally taken for blood pressure and cooling. There is some evidence it modestly lowers blood pressure.", is: "A tart red flower; usually as tea.", tradition: "Blood pressure, cooling, refreshment.", evidence: "Some evidence it modestly lowers blood pressure.", safety: "Can lower blood pressure (caution with BP meds) and may interact with some drugs. Avoid medicinal amounts in pregnancy; may affect blood sugar.", tags: ["blood pressure", "tea", "cooling"] }),
  herb({ id: "rosehip", name: "Rosehip", category: "Vitamin C / joints", summary: "The vitamin-C-rich fruit of the rose, taken as tea, powder, or capsule, traditionally used for immunity and joints. There is some evidence rosehip powder eases osteoarthritis pain.", is: "The fruit of the rose; tea, powder, or capsule.", tradition: "Immune support, joint health, vitamin C.", evidence: "Some evidence (standardized powder) for reducing osteoarthritis pain.", safety: "Generally very safe; high doses may cause loose stools. Mild blood-thinning at high doses.", tags: ["vitamin c", "joints", "immune", "fruit"] }),
  herb({ id: "bilberry", name: "Bilberry", category: "Eyes / circulation", summary: "A dark blue relative of the blueberry, taken as extract, traditionally used for eyesight, circulation, and capillary strength. Evidence for vision is weak; antioxidant action is real.", is: "A dark berry (blueberry relative); extract or fruit.", tradition: "Night vision, eye strain, circulation, capillaries.", evidence: "Weak evidence for vision; antioxidant and capillary effects are plausible.", safety: "Generally safe as food/extract; high doses may thin blood and lower blood sugar — caution with blood thinners and diabetes meds.", tags: ["eyes", "circulation", "antioxidant", "berry"] }),

  // — Women's & urinary —
  herb({ id: "raspberry-leaf", name: "Red Raspberry Leaf", category: "Women's health", summary: "The leaf (not the fruit), taken as tea, traditionally used as a uterine tonic in late pregnancy and for menstrual health. Evidence is limited and timing matters.", is: "The leaf of the raspberry plant; usually as tea.", tradition: "Uterine tone, late-pregnancy preparation, menstrual cramps.", evidence: "Limited; traditional birth-preparation tonic with weak supporting data.", safety: "Commonly avoided in early pregnancy and usually started only in the third trimester — talk to your midwife or doctor about timing. May affect blood sugar.", tags: ["pregnancy", "uterine tonic", "menstrual", "tea"] }),
  herb({ id: "chasteberry", name: "Chasteberry", aka: ["vitex", "chaste tree"], category: "Women's health", summary: "The berry of the chaste tree, taken as extract, traditionally used for PMS, irregular cycles, and breast tenderness. There is some evidence for PMS and cyclic breast pain.", is: "The berry of the chaste tree; usually as extract.", tradition: "PMS, irregular cycles, breast tenderness, fertility.", evidence: "Some evidence for PMS and cyclic breast pain.", safety: "Affects hormones — avoid in pregnancy and with hormone-sensitive conditions; can interfere with birth control, fertility drugs, and dopamine-related medication.", tags: ["pms", "hormones", "menstrual", "interactions"] }),
  herb({ id: "black-cohosh", name: "Black Cohosh", category: "Women's health", summary: "A root taken as extract, traditionally used for menopausal hot flashes and menstrual complaints. Evidence for hot flashes is mixed, and there are rare liver-safety concerns.", is: "A root; usually as standardized extract.", tradition: "Menopausal hot flashes, night sweats, menstrual cramps.", evidence: "Mixed evidence for hot flashes.", safety: "Rare reports of liver injury — stop if you notice jaundice or abdominal pain. Avoid in pregnancy (except possibly near term under supervision) and with liver disease or hormone-sensitive cancers.", tags: ["menopause", "hot flashes", "liver", "hormones"] }),
  herb({ id: "dong-quai", name: "Dong Quai", aka: ["angelica sinensis"], category: "Women's health", summary: "A root central to Chinese medicine, taken as decoction or capsule, traditionally used for menstrual and menopausal complaints. Clinical evidence is weak.", is: "A root used in Chinese medicine; decoction or capsule.", tradition: "Menstrual cramps, irregular cycles, menopause, 'blood tonic'.", evidence: "Weak clinical evidence; long traditional use.", safety: "Can thin the blood (avoid with anticoagulants and before surgery) and increases sun sensitivity. Avoid in pregnancy and with hormone-sensitive conditions.", tags: ["menstrual", "menopause", "bleeding", "photosensitivity"] }),
  herb({ id: "cranberry", name: "Cranberry", category: "Urinary", summary: "A tart red berry taken as juice, capsule, or extract, traditionally used to prevent urinary tract infections. There is some evidence it helps prevent recurrent UTIs (not treat active ones).", is: "A tart berry; juice, capsule, or extract.", tradition: "Preventing urinary tract infections.", evidence: "Some evidence for preventing recurrent UTIs; not a treatment for active infection.", safety: "Generally safe. High doses may interact with warfarin and may aggravate kidney stones in prone people. See a doctor for an active UTI.", tags: ["uti", "urinary", "prevention", "berry"] }),
  herb({ id: "uva-ursi", name: "Uva Ursi", aka: ["bearberry"], category: "Urinary", summary: "A leaf taken short-term as tea or extract, traditionally used for urinary tract infections. There is some evidence for short-term UTI use, but it is not for long-term use.", is: "A leaf; short-term tea or extract.", tradition: "Urinary tract infections, urinary antiseptic.", evidence: "Some evidence for short-term UTI relief.", safety: "Contains hydroquinone — use only short-term (a few days, not more than ~1 week) and not repeatedly; can stress the liver. Avoid in pregnancy, breastfeeding, kidney disease, and in children.", tags: ["uti", "urinary", "short-term only", "caution"] }),
  herb({ id: "saw-palmetto", name: "Saw Palmetto", category: "Men's health", summary: "A palm berry extract, traditionally used for enlarged prostate (BPH) symptoms and hair loss. The evidence for prostate symptoms is mixed and largely unconvincing in high-quality trials.", is: "A palm-berry extract; capsule or softgel.", tradition: "Enlarged prostate (BPH), urinary flow, hair loss.", evidence: "Mixed; high-quality trials mostly show little benefit over placebo for BPH.", safety: "Mild and generally well tolerated; may slightly thin the blood and affect hormones. Not for use in pregnancy. Get prostate symptoms properly evaluated rather than self-treating.", tags: ["prostate", "bph", "men", "hair"] }),
  herb({ id: "nettle-root", name: "Nettle Root", category: "Men's health", summary: "The root of stinging nettle (distinct from the leaf), taken as extract, traditionally used for enlarged prostate symptoms. There is some evidence, often in combination with saw palmetto.", is: "The root of nettle (not the leaf); extract.", tradition: "Enlarged prostate (BPH), urinary flow.", evidence: "Some evidence for BPH symptoms, often combined with saw palmetto.", safety: "Generally well tolerated; may affect blood sugar and blood pressure. Get prostate symptoms properly evaluated rather than self-treating.", tags: ["prostate", "bph", "men", "root"] }),
  herb({ id: "damiana", name: "Damiana", category: "Tonic / libido", summary: "A shrub leaf taken as tea or tincture, traditionally used as an aphrodisiac and mood lifter. Clinical evidence is minimal.", is: "A shrub leaf; tea or tincture.", tradition: "Libido, mood, energy, mild relaxation.", evidence: "Minimal clinical evidence; mostly traditional.", safety: "Generally mild. May affect blood sugar (caution with diabetes meds and around surgery); avoid medicinal doses in pregnancy.", tags: ["libido", "mood", "aphrodisiac"] }),
  herb({ id: "muira-puama", name: "Muira Puama", aka: ["potency wood"], category: "Tonic / libido", summary: "An Amazonian wood/root taken as tincture or capsule, traditionally used as an aphrodisiac and nerve tonic. Clinical evidence is minimal.", is: "An Amazonian wood/root; tincture or capsule.", tradition: "Libido, sexual function, fatigue, nerve tonic.", evidence: "Minimal clinical evidence; mostly traditional.", safety: "Limited safety data — avoid in pregnancy and use cautiously with other medication.", tags: ["libido", "tonic", "aphrodisiac"] }),

  // — Adaptogens & tonics —
  herb({ id: "rhodiola", name: "Rhodiola", aka: ["golden root", "arctic root"], category: "Adaptogen", summary: "A cold-climate root taken as extract, traditionally used for fatigue, stress, and stamina. There is some evidence it reduces fatigue and supports stress resilience.", is: "A cold-climate root; standardized extract.", tradition: "Fatigue, stress, stamina, focus.", evidence: "Some evidence it reduces fatigue and improves stress-related performance.", safety: "Generally well tolerated; can be stimulating (avoid late in the day). Caution with bipolar disorder, blood-pressure and diabetes meds, and in pregnancy.", tags: ["fatigue", "stress", "adaptogen", "stamina"] }),
  herb({ id: "schisandra", name: "Schisandra", aka: ["five-flavor berry"], category: "Adaptogen", summary: "A tart berry used in Chinese medicine, taken as extract or tea, traditionally used for energy, stress, and liver support. Evidence is limited but promising for liver and stress.", is: "A five-flavor berry; extract or tea.", tradition: "Energy, stress resilience, liver support, focus.", evidence: "Limited but promising for liver markers and stress.", safety: "May interact with drugs processed by the liver (it affects metabolizing enzymes). Avoid in pregnancy, with peptic ulcers, epilepsy, or high intracranial pressure.", tags: ["adaptogen", "liver", "stress", "interactions"] }),
  herb({ id: "eleuthero", name: "Eleuthero", aka: ["siberian ginseng"], category: "Adaptogen", summary: "A root (not a true ginseng) taken as extract, traditionally used for stamina, stress, and immunity. There is some evidence for stress resilience and fatigue.", is: "A root (not true ginseng); extract or tincture.", tradition: "Stamina, stress, immunity, recovery.", evidence: "Some evidence for stress resilience and fatigue.", safety: "Can be stimulating and raise blood pressure; caution with hypertension, blood thinners, diabetes meds, and in pregnancy.", tags: ["adaptogen", "stamina", "stress", "immune"] }),
  herb({ id: "maca", name: "Maca", category: "Tonic / libido", summary: "A Peruvian root vegetable taken as powder or capsule, traditionally used for energy, libido, and fertility. There is limited evidence for libido and mood.", is: "A Peruvian root; powder or capsule.", tradition: "Energy, libido, fertility, mood, stamina.", evidence: "Limited evidence for libido and possibly mood/menopausal symptoms.", safety: "Generally well tolerated as a food. Caution with hormone-sensitive conditions and thyroid issues (it's a brassica with goitrogens); limited pregnancy data.", tags: ["libido", "energy", "fertility", "root"] }),
  herb({ id: "gotu-kola", name: "Gotu Kola", aka: ["centella asiatica"], category: "Cognition / skin", summary: "A creeping herb central to Ayurveda, taken as tea, capsule, or topical, traditionally used for memory, calm, wound healing, and circulation. There is some evidence for wound healing and circulation.", is: "A creeping herb; tea, capsule, or topical.", tradition: "Memory, calm, wound healing, varicose veins.", evidence: "Some evidence for wound healing and venous circulation; cognitive claims are weaker.", safety: "Rare reports of liver injury with prolonged use — avoid with liver disease and don't take long-term without breaks. Avoid in pregnancy; may add to sedatives.", tags: ["cognition", "skin", "circulation", "liver"] }),
  herb({ id: "bacopa", name: "Bacopa", aka: ["brahmi"], category: "Cognition", summary: "A creeping herb used in Ayurveda, taken as standardized extract, traditionally used for memory and focus. There is some evidence it modestly improves memory over weeks of use.", is: "An Ayurvedic herb; standardized extract.", tradition: "Memory, learning, focus, calm.", evidence: "Some evidence it modestly improves memory with sustained use (weeks).", safety: "Commonly causes GI upset (take with food). May affect thyroid hormones and add to sedatives; limited pregnancy data — best avoided.", tags: ["memory", "focus", "cognition", "ayurveda"] }),
  herb({ id: "gymnema", name: "Gymnema", aka: ["gurmar", "sugar destroyer"], category: "Metabolic", summary: "A leaf used in Ayurveda, taken as extract, traditionally used for blood sugar and sugar cravings — it temporarily blunts sweet taste. There is some evidence for blood-sugar support.", is: "An Ayurvedic leaf; extract or chewable.", tradition: "Blood sugar, sugar cravings, metabolic support.", evidence: "Some evidence it supports blood-sugar control and reduces sweet cravings.", safety: "Can lower blood sugar — risk of hypoglycemia if combined with diabetes medication; monitor levels and coordinate with your doctor. Avoid in pregnancy.", tags: ["blood sugar", "cravings", "diabetes", "ayurveda"] }),

  // — Anti-inflammatory & pain —
  herb({ id: "boswellia", name: "Boswellia", aka: ["frankincense", "indian frankincense"], category: "Anti-inflammatory", summary: "A tree resin taken as standardized extract, traditionally used for joint pain and inflammation. There is some evidence it eases osteoarthritis pain and inflammatory conditions.", is: "A tree resin (frankincense); standardized extract.", tradition: "Joint pain, arthritis, inflammation, gut inflammation.", evidence: "Some evidence for reducing osteoarthritis pain and inflammation.", safety: "Generally well tolerated; can cause mild GI upset. May interact with immune-suppressing and anti-inflammatory drugs; limited pregnancy data.", tags: ["inflammation", "joints", "arthritis", "resin"] }),
  herb({ id: "devils-claw", name: "Devil's Claw", category: "Anti-inflammatory", summary: "An African root taken as extract, traditionally used for joint and back pain. There is some evidence for low back pain and osteoarthritis.", is: "An African root; standardized extract.", tradition: "Joint pain, back pain, arthritis, digestion.", evidence: "Some evidence for low back pain and osteoarthritis.", safety: "Avoid with stomach/duodenal ulcers (it stimulates stomach acid). May interact with blood thinners, blood-pressure, diabetes, and heart medication; avoid in pregnancy.", tags: ["pain", "joints", "back pain", "arthritis"] }),
  herb({ id: "willow-bark", name: "White Willow Bark", category: "Pain / anti-inflammatory", summary: "The bark from which aspirin was originally derived, taken as extract or tea, traditionally used for pain, headache, and fever. There is some evidence for back pain — and it carries aspirin-like cautions.", is: "Aspirin's natural source; salicin-rich bark, as extract or tea.", tradition: "Pain, headache, fever, joint and back pain.", evidence: "Some evidence for low back pain; works like a gentle natural aspirin.", safety: "SALICYLATE: treat like aspirin. Avoid if you're allergic to aspirin/NSAIDs, take blood thinners, have ulcers or asthma, or are pregnant/breastfeeding. Do NOT give to children or teens with a viral illness (Reye's syndrome risk).", tags: ["pain", "salicylate", "aspirin", "reyes"] }),
  herb({ id: "meadowsweet", name: "Meadowsweet", category: "Pain / digestive", summary: "A flowering herb rich in salicylates, taken as tea or tincture, traditionally used for pain, fever, and heartburn. Evidence is largely traditional, with aspirin-like cautions.", is: "A salicylate-rich flowering herb; tea or tincture.", tradition: "Pain, fever, heartburn, acid stomach.", evidence: "Largely traditional; a gentle salicylate-containing herb.", safety: "SALICYLATE: like aspirin, avoid with aspirin/NSAID allergy, blood thinners, asthma, and in pregnancy. Do NOT give to children or teens with a viral illness (Reye's syndrome risk).", tags: ["pain", "salicylate", "heartburn", "reyes"] }),
  herb({ id: "feverfew", name: "Feverfew", category: "Headache / migraine", summary: "A daisy-family herb taken as capsule or dried leaf, traditionally used to prevent migraines. There is some evidence it reduces migraine frequency.", is: "A daisy-family herb; capsule or dried leaf.", tradition: "Migraine prevention, headache, fever, arthritis.", evidence: "Some evidence it reduces the frequency of migraines.", safety: "May thin the blood — caution with anticoagulants and before surgery. Don't stop abruptly (rebound headaches). Avoid in pregnancy (can stimulate the uterus); daisy-family allergy possible.", tags: ["migraine", "headache", "bleeding", "pregnancy"] }),
  herb({ id: "butterbur", name: "Butterbur", category: "Headache / allergy", summary: "A root extract taken for migraine and hay fever. There is some evidence for migraine prevention and allergic rhinitis — but only PA-free products are safe.", is: "A root extract; standardized capsules.", tradition: "Migraine prevention, hay fever, allergies.", evidence: "Some evidence for migraine prevention and allergic rhinitis.", safety: "MUST be a certified PA-free (pyrrolizidine-alkaloid-free) product — raw/unprocessed butterbur contains liver-toxic, cancer-causing alkaloids. Even PA-free products have rare liver reports; avoid with liver disease and in pregnancy. Daisy-family allergy possible.", tags: ["migraine", "allergy", "PA-free only", "liver"] }),

  // — Antimicrobial / berberine —
  herb({ id: "goldenseal", name: "Goldenseal", category: "Antimicrobial", summary: "A berberine-rich root taken as tincture or capsule, traditionally used for infections, sinus, and gut complaints. Evidence is largely traditional, and berberine carries real interactions.", is: "A berberine-rich root; tincture or capsule.", tradition: "Colds, sinus infections, digestive and skin infections.", evidence: "Largely traditional; berberine has antimicrobial action in the lab.", safety: "BERBERINE: avoid in pregnancy and breastfeeding (can harm the newborn — risk of kernicterus) and in infants. Interacts with many drugs by affecting liver enzymes; caution with blood-pressure, blood-sugar, and blood-thinning meds. (Goldenseal is also over-harvested — choose cultivated sources.)", tags: ["berberine", "antimicrobial", "pregnancy", "interactions"] }),
  herb({ id: "oregon-grape", name: "Oregon Grape", category: "Antimicrobial / skin", summary: "A berberine-rich root used as tincture or topical, traditionally used for skin conditions (like psoriasis) and digestion. There is some evidence for topical use in psoriasis.", is: "A berberine-rich root; tincture or topical cream.", tradition: "Psoriasis and skin conditions, digestion, infections.", evidence: "Some evidence for topical use in mild psoriasis.", safety: "BERBERINE: avoid in pregnancy and breastfeeding and in infants (kernicterus risk). Interacts with many medications via liver enzymes; caution with blood-sugar and blood-pressure drugs.", tags: ["berberine", "psoriasis", "skin", "pregnancy"] }),
  herb({ id: "andrographis", name: "Andrographis", aka: ["king of bitters"], category: "Immune", summary: "A bitter herb used in Asian medicine, taken as extract, traditionally used for colds and immune support. There is some evidence it eases cold symptoms and shortens their duration.", is: "A bitter herb; standardized extract.", tradition: "Colds, sore throat, fever, immune support.", evidence: "Some evidence it reduces cold symptom severity and duration.", safety: "May lower blood pressure and blood sugar and stimulate the immune system — caution with autoimmune disease, blood thinners, and related meds. Avoid in pregnancy (may stimulate the uterus).", tags: ["cold", "immune", "bitter", "throat"] }),

  // — Immune & astringent —
  herb({ id: "astragalus", name: "Astragalus", category: "Immune / adaptogen", summary: "A root central to Chinese medicine, taken as decoction, extract, or capsule, traditionally used for immune support and vitality. Evidence is limited but it is a popular immune tonic.", is: "A root used in Chinese medicine; decoction, extract, or capsule.", tradition: "Immune support, energy, recovery, heart and kidney tonic.", evidence: "Limited human evidence; popular as an immune/adaptogenic tonic.", safety: "Stimulates the immune system — caution with autoimmune disease and immune-suppressing drugs (e.g. after transplant). May affect blood sugar and blood pressure; limited pregnancy data.", tags: ["immune", "adaptogen", "energy", "autoimmune caution"] }),
  herb({ id: "yarrow", name: "Yarrow", category: "Astringent / wound", summary: "A feathery flowering herb used as tea, tincture, or poultice, traditionally used to stop bleeding, for fevers/colds, and for digestion. Evidence is largely traditional.", is: "A flowering herb; tea, tincture, or poultice.", tradition: "Stopping minor bleeding, fever, colds, digestion, menstrual flow.", evidence: "Largely traditional; astringent and styptic action on contact.", safety: "Daisy-family allergy possible and can increase sun sensitivity. Avoid medicinal doses in pregnancy (can stimulate the uterus); may add to blood thinners and sedatives.", tags: ["bleeding", "wound", "fever", "astringent"] }),
  herb({ id: "calendula", name: "Calendula", aka: ["pot marigold"], category: "Skin / topical", summary: "A bright marigold flower used as cream, oil, or wash, traditionally used for wounds, rashes, and inflamed skin. There is some evidence for wound healing and skin soothing.", is: "A marigold flower; cream, oil, salve, or wash.", tradition: "Minor wounds, rashes, dry/inflamed skin, mouth and throat rinses.", evidence: "Some evidence for wound healing and soothing inflamed skin.", safety: "Very safe topically. Daisy-family allergy possible; avoid concentrated internal/medicinal doses in pregnancy.", tags: ["skin", "wound", "topical", "soothing"] }),
  herb({ id: "elderflower", name: "Elderflower", category: "Immune / respiratory", summary: "The flower of the elder shrub, used as tea or cordial, traditionally used for colds, fevers, and hay fever. Evidence is largely traditional.", is: "The flower of the elder shrub; tea or cordial.", tradition: "Colds, fevers, sinus congestion, hay fever.", evidence: "Largely traditional; gentle diaphoretic (sweat-promoting) use.", safety: "Generally gentle. Use only flowers and properly prepared products — other parts of the elder (leaves, bark, unripe berries) are toxic.", tags: ["cold", "fever", "respiratory", "tea"] }),
  herb({ id: "red-clover", name: "Red Clover", category: "Women's health", summary: "A flowering legume rich in isoflavones, taken as tea or extract, traditionally used for menopausal symptoms and skin. Evidence for hot flashes is weak and mixed.", is: "A flowering legume (isoflavone source); tea or extract.", tradition: "Menopausal hot flashes, skin conditions, 'blood cleansing'.", evidence: "Weak, mixed evidence for menopausal symptoms.", safety: "Has estrogen-like activity — avoid in pregnancy, breastfeeding, and with hormone-sensitive cancers. May thin blood; caution with anticoagulants and before surgery.", tags: ["menopause", "hormones", "isoflavones", "bleeding"] }),
  herb({ id: "cleavers", name: "Cleavers", aka: ["goosegrass", "clivers"], category: "Lymphatic / urinary", summary: "A sticky spring weed used as tea, tincture, or juice, traditionally used as a lymphatic and urinary tonic and for skin. Evidence is almost entirely traditional.", is: "A sticky spring weed; tea, tincture, or fresh juice.", tradition: "Lymphatic support, mild diuretic, skin conditions, swollen glands.", evidence: "Almost entirely traditional; little clinical evidence.", safety: "Generally gentle; its mild diuretic action means caution with diuretic medication. Avoid medicinal doses in pregnancy.", tags: ["lymphatic", "diuretic", "skin", "tonic"] }),
  herb({ id: "horsetail", name: "Horsetail", aka: ["equisetum"], category: "Mineral / urinary", summary: "An ancient silica-rich plant used as tea or extract, traditionally used for hair, nails, bones, and as a diuretic. Evidence is limited.", is: "A silica-rich plant; tea or extract.", tradition: "Hair, nails, bone support, mild diuretic, urinary health.", evidence: "Limited; mostly traditional with small studies on bone and diuresis.", safety: "Use only Equisetum arvense — the look-alike marsh horsetail is toxic. Contains thiaminase (can deplete vitamin B1) — don't use long-term. Diuretic action; avoid in pregnancy and with kidney disease.", tags: ["hair", "nails", "diuretic", "toxic look-alike"] }),

  // — Medicinal mushrooms —
  herb({ id: "reishi", name: "Reishi", aka: ["ganoderma", "lingzhi"], category: "Medicinal mushroom", summary: "A woody mushroom used in Chinese medicine, taken as extract or tea, traditionally used for immunity, calm, and longevity. Evidence is limited but it is a popular immune/calming tonic.", is: "A woody mushroom; extract, powder, or tea.", tradition: "Immune support, calm, sleep, longevity, vitality.", evidence: "Limited human evidence; popular immune and calming tonic.", safety: "May thin the blood and lower blood pressure/blood sugar — caution with anticoagulants, BP and diabetes meds, and before surgery. Limited pregnancy data; rare liver reports with high doses.", tags: ["immune", "calm", "mushroom", "bleeding"] }),
  herb({ id: "lions-mane", name: "Lion's Mane", category: "Medicinal mushroom", summary: "An edible white mushroom taken as extract or food, traditionally used for cognition and nerve health. There is early, limited evidence for mood and mild cognitive support.", is: "An edible mushroom; extract, powder, or food.", tradition: "Memory, focus, nerve health, mood.", evidence: "Early, limited evidence for mood and mild cognitive support.", safety: "Generally well tolerated; allergic reactions possible (it's a mushroom). Limited pregnancy data; may affect blood sugar and blood clotting at high doses.", tags: ["cognition", "nerve", "mood", "mushroom"] }),
  herb({ id: "cordyceps", name: "Cordyceps", category: "Medicinal mushroom", summary: "A fungus used in Chinese medicine, taken as extract, traditionally used for energy, stamina, and lung/kidney support. Evidence for athletic performance is mixed.", is: "A fungus (mostly cultivated); extract or powder.", tradition: "Energy, stamina, athletic performance, lung and kidney tonic.", evidence: "Mixed evidence for exercise performance; otherwise traditional.", safety: "May affect blood sugar and thin the blood, and stimulates the immune system — caution with diabetes meds, anticoagulants, autoimmune disease, and immune-suppressing drugs. Limited pregnancy data.", tags: ["energy", "stamina", "mushroom", "immune"] }),
  herb({ id: "chaga", name: "Chaga", category: "Medicinal mushroom", summary: "A birch-tree fungus taken as tea or extract, traditionally used for immunity and as an antioxidant tonic. Human evidence is minimal.", is: "A birch fungus; tea or extract.", tradition: "Immune support, antioxidant, general tonic.", evidence: "Minimal human evidence; high antioxidant content in the lab.", safety: "High in oxalates — avoid with kidney stones or kidney disease (kidney-damage reports with heavy use). May thin blood and lower blood sugar; caution with anticoagulants and diabetes meds. Limited pregnancy data.", tags: ["immune", "antioxidant", "mushroom", "oxalate"] }),
  herb({ id: "turkey-tail", name: "Turkey Tail", aka: ["coriolus", "trametes"], category: "Medicinal mushroom", summary: "A common shelf mushroom taken as extract, traditionally used for immune support; its compounds (PSK/PSP) are studied as adjuncts in cancer care. Evidence is mainly as an adjunct, not a standalone treatment.", is: "A shelf mushroom; extract (PSK/PSP).", tradition: "Immune support, recovery, gut health.", evidence: "Studied as an immune adjunct alongside conventional cancer treatment; not a standalone therapy.", safety: "Generally well tolerated. Stimulates the immune system — caution with autoimmune disease and immune-suppressing drugs. If you have cancer, only use alongside (not instead of) medical treatment and tell your oncology team.", tags: ["immune", "mushroom", "adjunct", "cancer care"] }),

  // — Toxic / unsafe-internal cautionary entries —
  herb({ id: "comfrey", name: "Comfrey", aka: ["knitbone"], category: "Topical / CAUTION", summary: "A traditional 'knitbone' herb used topically for bruises and sprains — but its pyrrolizidine alkaloids make internal use genuinely dangerous to the liver.", is: "A leafy root herb; topical salve/poultice (not for swallowing).", tradition: "Bruises, sprains, muscle pain, wound healing (external).", evidence: "Some evidence topical comfrey eases bruises, sprains, and joint pain.", safety: "HEPATOTOXIC: contains pyrrolizidine alkaloids that cause liver veno-occlusive disease and are cancer-causing. Do NOT take internally. Use only PA-free topical products, on unbroken skin, short-term, and not in pregnancy/breastfeeding or on children.", tags: ["topical only", "hepatotoxic", "pyrrolizidine", "do not ingest"] }),
  herb({ id: "coltsfoot", name: "Coltsfoot", category: "CAUTION", summary: "A traditional cough herb that contains liver-toxic pyrrolizidine alkaloids, making internal use unsafe in most forms.", is: "A flowering herb historically used as cough tea/syrup.", tradition: "Cough, sore throat, bronchial congestion.", evidence: "Traditional cough use, but undermined by serious safety concerns.", safety: "HEPATOTOXIC: contains pyrrolizidine alkaloids linked to liver veno-occlusive disease and cancer. Avoid internal use; banned or restricted in several countries. Do not use in pregnancy, breastfeeding, or in children. Only PA-free products (if available) should ever be considered.", tags: ["hepatotoxic", "pyrrolizidine", "cough", "avoid internal"] }),
  herb({ id: "wormwood", name: "Wormwood", aka: ["artemisia absinthium"], category: "Bitter / CAUTION", summary: "A very bitter herb used in absinthe and digestive bitters, traditionally used for digestion and parasites — but its thujone is neurotoxic in excess.", is: "A bitter herb; tincture or in bitters (small amounts).", tradition: "Sluggish digestion, appetite, intestinal parasites.", evidence: "Bitter digestive action is real; broader claims are traditional.", safety: "THUJONE: neurotoxic in higher doses — can cause seizures and kidney damage. Use only brief, low-dose, properly prepared products. Avoid in pregnancy and breastfeeding (can stimulate the uterus), with epilepsy, and with kidney disease.", tags: ["thujone", "bitter", "neurotoxic", "pregnancy"] }),
  herb({ id: "mugwort", name: "Mugwort", aka: ["artemisia vulgaris"], category: "Bitter / CAUTION", summary: "An aromatic herb used in bitters, dream pillows, and moxibustion, traditionally used for digestion and menstruation — but it stimulates the uterus and contains thujone.", is: "An aromatic herb; tea, tincture, bitters, or moxa.", tradition: "Digestion, menstrual regulation, sleep/dreams.", evidence: "Largely traditional; bitter digestive action.", safety: "Avoid in pregnancy — it can stimulate the uterus and has been used to bring on periods. Contains thujone (use modest amounts); daisy/ragweed allergy and birch-pollen cross-reactivity are common.", tags: ["pregnancy", "thujone", "menstrual", "digestion"] }),
  herb({ id: "pennyroyal", name: "Pennyroyal", category: "TOXIC — do not ingest", summary: "A mint historically used as an abortifacient — but it is dangerously toxic. The oil has caused organ failure and death; it should not be ingested.", is: "A mint-family plant; historically a folk abortifacient (DO NOT use).", tradition: "Historically (and dangerously) used to bring on menstruation/abortion, and as an insect repellent.", evidence: "No safe medicinal use; the historical abortifacient use is unreliable and deadly.", safety: "TOXIC: pennyroyal oil contains pulegone, which causes severe liver and kidney failure, seizures, and death — fatalities are documented. NEVER swallow pennyroyal oil. Absolutely contraindicated in pregnancy. There is no safe internal dose.", tags: ["toxic", "fatal", "abortifacient", "do not ingest"] }),
  herb({ id: "yohimbe", name: "Yohimbe", category: "Stimulant / CAUTION", summary: "A West African bark stimulant traditionally used for erectile dysfunction and energy — but unstandardized products are risky to the heart and nervous system.", is: "A bark stimulant; capsules/extract (yohimbine is the active alkaloid).", tradition: "Erectile dysfunction, libido, energy, fat loss.", evidence: "Yohimbine has some evidence for erectile dysfunction, but OTC yohimbe bark products are wildly inconsistent in strength.", safety: "Can cause dangerous spikes in blood pressure and heart rate, anxiety, and arrhythmias. Avoid with heart disease, high/low blood pressure, anxiety, kidney disease, and many medications (MAOIs, stimulants, antidepressants). Not for pregnancy. Use only under medical guidance.", tags: ["stimulant", "blood pressure", "heart", "caution"] }),
  herb({ id: "ephedra", name: "Ephedra", aka: ["ma huang"], category: "Stimulant — banned", summary: "A powerful stimulant herb once sold for weight loss and energy — banned in supplements in many countries after deaths from heart attacks and strokes.", is: "A stimulant herb (ephedrine alkaloids); banned in many supplements.", tradition: "Asthma/congestion, energy, weight loss.", evidence: "Genuinely active as a stimulant and decongestant, but with an unacceptable safety record in supplements.", safety: "DANGEROUS: linked to heart attacks, strokes, seizures, and deaths; banned from dietary supplements in the US and elsewhere. Do not use for weight loss or energy. Absolutely avoid with heart conditions, high blood pressure, and in pregnancy.", tags: ["stimulant", "banned", "heart", "stroke"] }),
  herb({ id: "licorice", name: "Licorice (Root)", aka: ["liquorice", "glycyrrhiza"], category: "Soothing / CAUTION", summary: "A sweet root used for sore throat, cough, and digestion — but its glycyrrhizin raises blood pressure and lowers potassium, which can be dangerous.", is: "A sweet root; tea, lozenge, extract, or DGL (deglycyrrhizinated) form.", tradition: "Sore throat, cough, heartburn, ulcers, adrenal/energy support.", evidence: "Some evidence for soothing the throat and gut; DGL is used for heartburn/ulcers.", safety: "BP/POTASSIUM: regular glycyrrhizin-containing licorice raises blood pressure and lowers potassium, which can cause dangerous heart rhythms and swelling. Avoid with high blood pressure, heart, kidney, or liver disease, and in pregnancy; interacts with BP, diuretic, heart, and steroid meds. DGL licorice lacks this effect.", tags: ["blood pressure", "potassium", "throat", "pregnancy"] }),
];
