import type { ReferenceEntry } from "../types";

/**
 * Quick-reference herb lookup — what each herb is, its traditional use, the
 * evidence, and (critically) safety. Sourced from docs/learning-library-research.md.
 * Not medical advice; always check with a clinician/pharmacist before combining
 * herbs with medication, in pregnancy, or for a medical condition.
 */

function herb(e: {
  id: string; name: string; aka?: string[]; category: string; summary: string;
  is: string; tradition: string; evidence: string; safety?: string; tags?: string[];
}): ReferenceEntry {
  const fields = [
    { label: "What it is", value: e.is },
    { label: "Traditionally for", value: e.tradition },
    { label: "Evidence", value: e.evidence },
  ];
  return {
    domain: "herbalism",
    id: e.id,
    name: e.name,
    aka: e.aka,
    category: e.category,
    summary: e.summary,
    fields,
    safety: e.safety,
    tags: e.tags,
  };
}

export const herbReference: ReferenceEntry[] = [
  herb({ id: "chamomile", name: "Chamomile", category: "Calming", summary: "A gentle daisy-family flower, usually taken as a tea, traditionally used to calm the mind, ease sleep, and settle mild digestive upset. There is modest evidence for mild anxiety and sleep, and it is generally very gentle.", is: "A daisy-family flower, taken mostly as a tea.", tradition: "Calm, sleep, mild digestive upset.", evidence: "Modest evidence for mild anxiety and sleep; generally very gentle.", safety: "Usually safe. People allergic to ragweed/daisies may react; very high doses may add to blood thinners.", tags: ["calm", "sleep", "tea", "gentle"] }),
  herb({ id: "valerian", name: "Valerian", category: "Calming", summary: "A sedating root taken as tea, tincture, or capsule, traditionally used for sleep, anxiety, and restlessness. The evidence for sleep is mixed and any effects are modest.", is: "A root taken as tea, tincture, or capsule.", tradition: "Sleep, anxiety, restlessness.", evidence: "Mixed evidence for sleep; effects are modest.", safety: "Causes drowsiness — do not combine with alcohol, sleep aids, or anti-anxiety meds, and don't drive if drowsy.", tags: ["sleep", "sedative", "anxiety"] }),
  herb({ id: "lemon-balm", name: "Lemon Balm", aka: ["melissa"], category: "Calming", summary: "A lemon-scented mint-family leaf, often taken as a tea, traditionally used for calm, mood, sleep, and digestion. Evidence for stress and sleep is limited but promising.", is: "A mint-family leaf, often as tea.", tradition: "Calm, mood, sleep, digestion.", evidence: "Limited but promising evidence for stress and sleep.", tags: ["calm", "mood", "mint"] }),
  herb({ id: "ginger", name: "Ginger", category: "Digestive", summary: "A pungent root used fresh, dried, or as capsules, traditionally valued for nausea, digestion, and its warming quality. There is good evidence that it reduces nausea, including motion, pregnancy, and chemo-related forms.", is: "A pungent root used fresh, dried, or as capsules.", tradition: "Nausea, digestion, warming.", evidence: "Good evidence it reduces nausea (motion, pregnancy, chemo-related).", safety: "Very high doses may slightly thin the blood — use caution with blood thinners.", tags: ["nausea", "digestion", "root"] }),
  herb({ id: "peppermint", name: "Peppermint", category: "Digestive", summary: "A mint leaf whose oil is used in capsules, traditionally taken for indigestion, IBS, headaches, and congestion. There is good evidence that enteric-coated oil eases IBS symptoms.", is: "A mint leaf; the oil is used in capsules.", tradition: "Indigestion, IBS, headaches, congestion.", evidence: "Good evidence (enteric-coated oil) for IBS symptoms.", safety: "Can worsen acid reflux/heartburn in some people. Keep concentrated oil away from infants' faces.", tags: ["ibs", "digestion", "mint", "headache"] }),
  herb({ id: "echinacea", name: "Echinacea", category: "Immune", summary: "A coneflower taken as tincture, tea, or capsule, traditionally used to prevent or shorten colds. The evidence is weak and inconsistent, and at best it may slightly shorten a cold.", is: "A coneflower, taken as tincture, tea, or capsule.", tradition: "Preventing or shortening colds.", evidence: "Weak and inconsistent — at best it may slightly shorten a cold.", safety: "People allergic to daisies/ragweed may react; caution with autoimmune conditions.", tags: ["cold", "immune", "coneflower"] }),
  herb({ id: "turmeric", name: "Turmeric (Curcumin)", category: "Anti-inflammatory", summary: "A golden root and spice whose active compound is curcumin, traditionally used for inflammation, joint pain, and digestion. There is some evidence for inflammation and joints, but curcumin is poorly absorbed on its own.", is: "A root/spice; curcumin is its active compound.", tradition: "Inflammation, joint pain, digestion.", evidence: "Some evidence for inflammation/joints, but curcumin is poorly absorbed on its own.", safety: "High-dose supplements can upset the stomach and may add to blood thinners; rare liver issues reported.", tags: ["inflammation", "joints", "spice", "curcumin"] }),
  herb({ id: "ginkgo", name: "Ginkgo Biloba", category: "Circulation / cognition", summary: "An extract of ginkgo tree leaves, traditionally used for memory, circulation, and focus. It is not supported for preventing dementia or boosting memory in healthy people.", is: "An extract of ginkgo tree leaves.", tradition: "Memory, circulation, focus.", evidence: "Not supported for preventing dementia or boosting memory in healthy people.", safety: "Increases bleeding risk — avoid with blood thinners (warfarin, aspirin) and stop before surgery.", tags: ["memory", "circulation", "bleeding"] }),
  herb({ id: "st-johns-wort", name: "St John's Wort", category: "Mood", summary: "A yellow-flowered herb usually taken as capsules or tincture, traditionally used for low mood and mild depression. There is some evidence for mild-to-moderate depression, but it has major drug interactions.", is: "A yellow-flowered herb, usually as capsules/tincture.", tradition: "Low mood, mild depression.", evidence: "Some evidence for mild-to-moderate depression.", safety: "MAJOR interactions: reduces the effect of birth control, blood thinners, transplant and HIV/cancer drugs, and more; with SSRIs can cause serotonin syndrome. Never start without checking with a doctor/pharmacist.", tags: ["depression", "mood", "interactions", "birth control"] }),
  herb({ id: "lavender", name: "Lavender", category: "Calming", summary: "A fragrant flower used as oil, tea, or capsule, traditionally taken for relaxation, sleep, and anxiety. There is modest evidence, from aromatherapy and a standardized oral oil, for anxiety and sleep.", is: "A fragrant flower; used as oil, tea, or capsule.", tradition: "Relaxation, sleep, anxiety.", evidence: "Modest evidence (aromatherapy and a standardized oral oil) for anxiety and sleep.", safety: "Essential oil is for inhalation/diluted topical use — don't swallow essential oil. See the essential-oils course for dilution and pet safety.", tags: ["relax", "sleep", "anxiety", "aroma"] }),
  herb({ id: "ashwagandha", name: "Ashwagandha", category: "Adaptogen", summary: "A root used in Ayurveda, taken as powder or capsule, traditionally valued for stress, energy, sleep, and vitality. There is some evidence it modestly reduces stress and improves sleep.", is: "A root used in Ayurveda, taken as powder or capsule.", tradition: "Stress, energy, sleep, vitality.", evidence: "Some evidence it modestly reduces stress and improves sleep.", safety: "Avoid in pregnancy; caution with thyroid conditions, autoimmune disease, and sedatives. Rare liver injury reported.", tags: ["stress", "adaptogen", "ayurveda", "sleep"] }),
  herb({ id: "garlic", name: "Garlic", category: "Cardiovascular", summary: "A culinary bulb, also sold as concentrated supplements, traditionally used for heart health, immunity, and circulation. There is modest evidence for small reductions in blood pressure and cholesterol.", is: "A culinary bulb; also concentrated supplements.", tradition: "Heart health, immunity, circulation.", evidence: "Modest evidence for small reductions in blood pressure and cholesterol.", safety: "High-dose supplements increase bleeding risk with blood thinners and before surgery.", tags: ["heart", "blood pressure", "bleeding", "cholesterol"] }),
  herb({ id: "ginseng", name: "Ginseng (Panax)", category: "Adaptogen", summary: "A root from the Asian or American Panax species, traditionally used for energy, stamina, cognition, and immunity. The evidence for fatigue and cognition is mixed.", is: "A root (Asian/American Panax species).", tradition: "Energy, stamina, cognition, immunity.", evidence: "Mixed evidence for fatigue and cognition.", safety: "Can affect blood sugar and blood pressure and interacts with blood thinners, diabetes, and other meds; may cause insomnia. Not for pregnancy.", tags: ["energy", "focus", "adaptogen", "blood sugar"] }),
  herb({ id: "milk-thistle", name: "Milk Thistle", category: "Liver", summary: "A thistle seed extract known as silymarin, traditionally used for liver support and detox. The evidence is limited and mixed, though it is generally well tolerated.", is: "A thistle seed extract (silymarin).", tradition: "Liver support, detox.", evidence: "Limited and mixed evidence; generally well tolerated.", safety: "Usually safe; may cause mild GI upset; people allergic to daisies/ragweed may react.", tags: ["liver", "detox", "silymarin"] }),
  herb({ id: "elderberry", name: "Elderberry", category: "Immune", summary: "The dark berry of the elder shrub, taken as syrup or lozenge, traditionally used for colds, flu, and immune support. There is some evidence that syrups may modestly ease cold and flu symptoms.", is: "The berry of the elder shrub, as syrup or lozenge.", tradition: "Colds and flu, immune support.", evidence: "Some evidence (syrups) may modestly ease cold/flu symptoms.", safety: "RAW elderberries, leaves, bark, and seeds are toxic and cause nausea/vomiting — only use properly cooked/prepared products.", tags: ["cold", "flu", "immune", "toxic raw"] }),
  herb({ id: "passionflower", name: "Passionflower", category: "Calming", summary: "A flowering climbing vine taken as tea or tincture, traditionally used for anxiety, restlessness, and sleep. The evidence for anxiety and sleep is limited.", is: "A flowering vine, as tea or tincture.", tradition: "Anxiety, restlessness, sleep.", evidence: "Limited evidence for anxiety and sleep.", safety: "Can cause drowsiness — don't combine with sedatives or alcohol; avoid in pregnancy.", tags: ["anxiety", "sleep", "sedative"] }),
  herb({ id: "nettle", name: "Nettle", aka: ["stinging nettle"], category: "General", summary: "A nutritive leafy green that is cooked or dried to remove the sting, traditionally used for seasonal allergies, joint aches, and nutrition. The evidence is limited and, while popular, it is not well proven.", is: "A leafy green (cooked/dried removes the sting).", tradition: "Seasonal allergies, joint aches, nutrition.", evidence: "Limited evidence; popular but not well proven.", safety: "Generally safe cooked/dried; may interact with blood pressure, diuretic, or diabetes medication.", tags: ["allergies", "joints", "green"] }),
  herb({ id: "dandelion", name: "Dandelion", category: "Digestive", summary: "A common plant whose leaf and root are used as a digestive bitter, traditionally taken for digestion, as a mild diuretic, and for liver support. The use is mostly traditional, with little clinical evidence.", is: "The leaf and root of the dandelion plant.", tradition: "Digestion, mild diuretic, liver support.", evidence: "Mostly traditional; little clinical evidence.", safety: "May act as a diuretic and interact with some medications; daisy-family allergy possible.", tags: ["digestion", "diuretic", "bitter"] }),
  herb({ id: "fennel", name: "Fennel", category: "Digestive", summary: "A licorice-flavored aromatic seed used as tea or culinary spice, traditionally taken for gas, bloating, colic, and digestion. The evidence is limited, though it has a long history of culinary use.", is: "An aromatic seed, as tea or culinary spice.", tradition: "Gas, bloating, colic, digestion.", evidence: "Limited evidence; long culinary use.", safety: "Culinary amounts are fine; avoid concentrated medicinal doses in pregnancy.", tags: ["digestion", "bloating", "seed"] }),
  herb({ id: "tulsi", name: "Holy Basil (Tulsi)", aka: ["tulsi"], category: "Adaptogen", summary: "A basil relative central to Ayurveda, traditionally used for stress, mood, and immunity. The evidence for stress and mood is limited but growing.", is: "A basil relative central to Ayurveda.", tradition: "Stress, mood, immunity.", evidence: "Limited but growing evidence for stress and mood.", safety: "Generally well tolerated; may affect blood sugar and blood clotting — caution with related meds and around surgery.", tags: ["stress", "adaptogen", "ayurveda", "basil"] }),
  herb({ id: "rosemary", name: "Rosemary", category: "Culinary / cognition", summary: "A woody, fragrant culinary herb, traditionally used for memory, focus, circulation, and the hair and scalp. The use is mostly traditional, with some preliminary work on aroma and cognition.", is: "A woody culinary herb.", tradition: "Memory, focus, circulation, hair/scalp.", evidence: "Mostly traditional; some preliminary aroma/cognition work.", safety: "Culinary amounts are safe; avoid concentrated medicinal doses in pregnancy.", tags: ["memory", "focus", "culinary"] }),
  herb({ id: "sage", name: "Sage", category: "Culinary / wellness", summary: "A culinary herb also taken as tea or extract, traditionally used for sore throat, sweating, menopause symptoms, and memory. There is some evidence for sore throat and menopausal hot flashes.", is: "A culinary herb; also taken as tea/extract.", tradition: "Sore throat, sweating, menopause symptoms, memory.", evidence: "Some evidence for sore throat and menopausal hot flashes.", safety: "Contains thujone — avoid concentrated/medicinal doses in pregnancy and breastfeeding; culinary amounts are fine.", tags: ["throat", "menopause", "culinary", "thujone"] }),
];
