import type { ReferenceEntry } from "../types";

/**
 * Quick-reference for all 78 tarot cards (Rider–Waite–Smith tradition).
 * Meanings are the conventional upright/reversed readings, taught as a
 * reflective tool — not prediction.
 */

function major(num: number, id: string, name: string, summary: string, upright: string, reversed: string, tags: string[]): ReferenceEntry {
  return {
    domain: "tarot",
    id: `major-${id}`,
    name,
    category: "Major Arcana",
    summary,
    image: `/images/tarot/major-${num}.webp`,
    fields: [
      { label: "Upright", value: upright },
      { label: "Reversed", value: reversed },
      { label: "Card", value: `${num} · Major Arcana` },
    ],
    tags: ["major arcana", ...tags],
  };
}

const RANK_NUM: Record<string, number> = { ace: 1, "2": 2, "3": 3, "4": 4, "5": 5, "6": 6, "7": 7, "8": 8, "9": 9, "10": 10, page: 11, knight: 12, queen: 13, king: 14 };

const SUITS = {
  wands: { name: "Wands", el: "Fire", theme: "energy, passion, action, will" },
  cups: { name: "Cups", el: "Water", theme: "emotion, relationships, intuition" },
  swords: { name: "Swords", el: "Air", theme: "thought, truth, conflict" },
  pentacles: { name: "Pentacles", el: "Earth", theme: "money, work, body, the material" },
} as const;

type SuitKey = keyof typeof SUITS;

function minor(suit: SuitKey, rank: string, rankLabel: string, summary: string, upright: string, reversed: string): ReferenceEntry {
  const s = SUITS[suit];
  return {
    domain: "tarot",
    id: `${suit}-${rank}`,
    name: `${rankLabel} of ${s.name}`,
    category: `Minor Arcana · ${s.name}`,
    summary,
    image: `/images/tarot/${suit}-${RANK_NUM[rank]}.webp`,
    fields: [
      { label: "Upright", value: upright },
      { label: "Reversed", value: reversed },
      { label: "Suit", value: `${s.name} — ${s.el} (${s.theme})` },
    ],
    tags: ["minor arcana", s.name.toLowerCase(), s.el.toLowerCase()],
  };
}

const majors: ReferenceEntry[] = [
  major(0, "fool", "The Fool", "A youth steps toward a cliff edge, white rose and bundle in hand, gazing skyward as a small dog leaps at his heels. The Fool marks a moment of innocent new beginnings, spontaneity, and faith in the unknown journey ahead.", "A fresh start, spontaneity, taking a leap into the unknown with an open heart.", "Recklessness, holding back, naivety, fear of starting.", ["beginnings", "leap", "innocence"]),
  major(1, "magician", "The Magician", "One hand raised to the heavens and one pointing to earth, the Magician stands before the four suit emblems with the infinity sign above him. He channels focused will and resourcefulness, drawing on every tool to manifest intention into reality.", "You have the tools and skill to make it real; focused will and action.", "Manipulation, untapped talent, scattered energy, self-doubt.", ["manifestation", "power", "skill"]),
  major(2, "high-priestess", "The High Priestess", "Seated between the black and white pillars with a veil of pomegranates behind her, the High Priestess guards a hidden scroll of sacred knowledge. She invites you to quiet the noise and listen to intuition, mystery, and the wisdom of the subconscious.", "Trust your intuition; hidden knowledge and the subconscious are speaking.", "Secrets, ignored intuition, surface over depth.", ["intuition", "mystery", "subconscious"]),
  major(3, "empress", "The Empress", "Crowned with stars and reclining amid a field of ripening wheat, the Empress embodies fertile abundance and the nurturing power of nature. She speaks of creativity, sensual richness, and the maternal care that helps things grow.", "Fertility, nurturing, sensual abundance, creative flow.", "Creative block, smothering, neglect of self-care.", ["abundance", "nurture", "creativity", "mother"]),
  major(4, "emperor", "The Emperor", "Enthroned on stone carved with rams' heads, the Emperor holds the ankh and orb of worldly dominion. He represents authority, structure, and the discipline that builds lasting stability and order.", "Leadership, structure, discipline, protective authority.", "Domination, rigidity, loss of control, stubbornness.", ["authority", "structure", "father", "control"]),
  major(5, "hierophant", "The Hierophant", "Seated between two pillars with two initiates kneeling before him, the Hierophant raises his hand in blessing as keeper of sacred tradition. He represents established institutions, mentorship, and the shared beliefs that pass wisdom from one generation to the next.", "Convention, mentorship, spiritual or institutional guidance.", "Rebellion, questioning norms, personal belief over dogma.", ["tradition", "teacher", "religion"]),
  major(6, "lovers", "The Lovers", "A man and woman stand beneath an angel's blessing in a garden recalling Eden, naked and unashamed. The Lovers speaks of deep connection, union, and an important choice that must align with your truest values.", "Connection, partnership, an important choice aligned with your values.", "Disharmony, imbalance, misalignment of values, avoidance.", ["love", "union", "choice", "relationship"]),
  major(7, "chariot", "The Chariot", "An armored figure rides a chariot drawn by two sphinxes pulling in opposite directions, holding them in check by will alone. The Chariot speaks of harnessed drive and disciplined focus that steers conflicting forces toward victory.", "Determination and control move you toward victory; stay the course.", "Lost direction, scattered effort, lack of control.", ["drive", "victory", "willpower"]),
  major(8, "strength", "Strength", "A serene woman gently closes the jaws of a lion, the infinity symbol floating above her head. Strength shows that true power is the quiet courage, patience, and compassion that tame raw instinct without force.", "Calm courage, compassion, mastering impulse through gentleness.", "Self-doubt, raw emotion, low confidence.", ["courage", "strength", "patience"]),
  major(9, "hermit", "The Hermit", "Alone on a snowy peak, the Hermit lifts a lantern containing a single guiding star and leans on his staff. He represents the withdrawal into solitude and introspection through which inner wisdom and guidance are found.", "Withdrawal to seek inner wisdom; soul-searching and reflection.", "Isolation, loneliness, withdrawal taken too far.", ["solitude", "reflection", "wisdom"]),
  major(10, "wheel-of-fortune", "Wheel of Fortune", "A great wheel turns in the sky surrounded by mystical creatures, ever rising and falling. The Wheel of Fortune reminds you that life moves in cycles, and turning points and shifts of fate are part of the natural rhythm.", "A turn of fate, luck, the wheel turning toward a new cycle.", "Bad luck, resistance to change, a downturn in the cycle.", ["fate", "change", "cycles", "luck"]),
  major(11, "justice", "Justice", "Enthroned with an upright sword in one hand and balanced scales in the other, Justice weighs every action with impartial clarity. The card speaks of fairness, truth, and the cause-and-effect by which choices meet their consequences.", "Accountability, fairness, truth and consequences come due.", "Unfairness, avoidance of accountability, dishonesty.", ["justice", "truth", "fairness", "karma"]),
  major(12, "hanged-man", "The Hanged Man", "A man hangs serenely upside down from a living tree, suspended by one foot with a halo of light around his head. The Hanged Man invites willing surrender, a pause from striving, and the fresh perspective that comes from seeing the world differently.", "Letting go, suspension, gaining insight by seeing differently.", "Stalling, resistance, needless martyrdom.", ["surrender", "pause", "perspective"]),
  major(13, "death", "Death", "A skeletal figure in armor rides a white horse beneath a rising sun, as figures from every station fall before him. Death rarely means literal dying; it marks a profound ending and transformation that clears the ground for renewal.", "A necessary ending that clears the way for transformation and renewal.", "Resistance to change, clinging to the past, stagnation.", ["transformation", "ending", "change", "rebirth"]),
  major(14, "temperance", "Temperance", "An angel pours liquid between two cups, one foot on land and one in the water, blending opposites into a single flow. Temperance teaches balance, patience, and the moderation of the middle path that brings inner harmony.", "Blending, balance, patient moderation, the middle path.", "Imbalance, excess, impatience, discord.", ["balance", "moderation", "patience"]),
  major(15, "devil", "The Devil", "A horned figure looms over two chained human figures whose loose shackles they could slip free at any time. The Devil reveals the attachments, fears, and shadow appetites that bind us, often by our own consent.", "Bondage to habits, materialism, or fear — often self-chosen.", "Breaking free, reclaiming power, facing the shadow.", ["addiction", "shadow", "bondage", "materialism"]),
  major(16, "tower", "The Tower", "Lightning strikes a tall tower and sets its crown ablaze, hurling two figures from its heights. The Tower marks a sudden upheaval or revelation that tears down whatever was built on a false foundation.", "A sudden shake-up tears down what was built on a false foundation.", "Fear of change, delaying the inevitable, a softer fall.", ["upheaval", "collapse", "shock", "revelation"]),
  major(17, "star", "The Star", "Beneath a sky of shining stars, a woman kneels by a pool pouring water onto land and into the water, her body bare and open. The Star brings hope, healing, and renewed inspiration that arrive quietly after a time of hardship.", "Healing, hope, renewed faith and inspiration after hardship.", "Despair, lost faith, disconnection from hope.", ["hope", "healing", "renewal", "inspiration"]),
  major(18, "moon", "The Moon", "A pale moon weeps light over a winding path between two towers, while a dog and wolf howl and a crayfish crawls from the water. The Moon speaks of illusion, uncertainty, and the fears and intuitions that surface when the way ahead is unclear.", "Uncertainty, dreams, fears and intuition surfacing; not all is clear.", "Releasing fear, clarity returning, confusion lifting.", ["illusion", "fear", "dreams", "intuition"]),
  major(19, "sun", "The Sun", "A radiant sun shines over a child riding a white horse beneath blooming sunflowers. The Sun radiates joy, vitality, and the clear, uncomplicated success that comes when everything is brought into the light.", "Warmth, success, vitality and clear, simple joy.", "Temporary gloom, dimmed optimism, delays to happiness.", ["joy", "success", "vitality", "clarity"]),
  major(20, "judgement", "Judgement", "An angel sounds a trumpet as figures rise from their tombs with arms lifted in answer. Judgement is a moment of awakening and reckoning, a call to rise above the past and answer a higher purpose.", "Self-evaluation, awakening, answering a higher calling, rebirth.", "Self-doubt, avoiding the lesson, harsh self-judgement.", ["awakening", "rebirth", "reckoning", "calling"]),
  major(21, "world", "The World", "A dancing figure encircled by a victory wreath is framed by the four living creatures of the corners. The World marks completion, fulfilment, and the sense of wholeness that arrives when a long cycle reaches its joyful close.", "Accomplishment, integration, the successful close of a cycle.", "Incompletion, loose ends, delay before the finish.", ["completion", "fulfillment", "wholeness"]),
];

const minors: ReferenceEntry[] = [
  // ── Wands (Fire) ──
  minor("wands", "ace", "Ace", "A hand emerges from a cloud offering a sprouting wand, leaves falling like sparks of life. The Ace of Wands is a spark of fresh inspiration and raw creative energy, an invitation to begin something with passion.", "Inspiration, a new venture, creative potential, raw energy.", "Delays, lack of direction, a false start."),
  minor("wands", "2", "Two", "A figure stands on a castle wall holding a globe, gazing out over the sea toward distant horizons. The Two of Wands is about planning, vision, and weighing whether to leave familiar comfort to pursue something larger.", "Future planning, decisions, leaving comfort to expand.", "Fear of the unknown, playing it too safe, poor planning."),
  minor("wands", "3", "Three", "A figure stands on a cliff watching ships sail out across the sea, plans already in motion. The Three of Wands speaks of expansion, foresight, and the first rewards of a venture beginning to take off.", "Progress, foresight, ventures beginning to take off.", "Delays, obstacles, lack of foresight."),
  minor("wands", "4", "Four", "Four wands form a flowered canopy as figures raise bouquets in celebration before a castle. The Four of Wands is a card of homecoming, harmony, and joyful milestones shared with others.", "Homecoming, celebration, harmony, a happy milestone.", "Transition, lack of support, a muted celebration."),
  minor("wands", "5", "Five", "Five youths brandish their wands at one another in a chaotic, unfocused scuffle. The Five of Wands reflects conflict, rivalry, and the scattered friction of competing energies that have not yet found common direction.", "Tension, rivalry, scattered effort, healthy competition.", "Avoiding conflict, finding agreement, inner tension."),
  minor("wands", "6", "Six", "A rider crowned with laurel parades on horseback through a cheering crowd. The Six of Wands is the card of victory, public recognition, and the confidence that comes from earned success.", "Success, public recognition, confidence, momentum.", "Ego, fall from grace, lack of recognition."),
  minor("wands", "7", "Seven", "A figure on higher ground fends off six wands rising from below, holding the advantage. The Seven of Wands is about standing your ground, defending your convictions, and persevering against challenge.", "Defending your position, perseverance, holding firm.", "Overwhelm, giving up, feeling outnumbered."),
  minor("wands", "8", "Eight", "Eight wands fly through the open air over an open landscape, all racing in the same direction. The Eight of Wands signals swift movement, momentum, and news or events arriving quickly after a period of waiting.", "Speed, action, news, things moving quickly.", "Delays, frustration, scattered energy."),
  minor("wands", "9", "Nine", "A bandaged but watchful figure grips a wand, with eight others fenced behind him, braced for one more challenge. The Nine of Wands speaks of resilience, persistence, and guarding what you have worked hard to build.", "Last stand, resilience, guarding what you've built.", "Exhaustion, defensiveness, paranoia."),
  minor("wands", "10", "Ten", "A man struggles forward under the weight of all ten wands, his view of the town ahead nearly blocked. The Ten of Wands is about burden and overload, the heavy cost of carrying too much responsibility alone.", "Responsibility, carrying too much, hard-won progress.", "Burnout, delegating, releasing the burden."),
  minor("wands", "page", "Page", "A young figure in a vibrant tunic studies a sprouting wand with eager curiosity. The Page of Wands embodies the enthusiastic spark of a new idea, a free spirit ready to explore where inspiration leads.", "Curiosity, enthusiasm, a creative idea, free spirit.", "Hesitation, scattered ideas, immaturity."),
  minor("wands", "knight", "Knight", "A knight in flame-patterned armor charges forward on a rearing horse, wand in hand. The Knight of Wands brings bold, adventurous action, the fiery passion to chase a goal headlong.", "Energy, adventure, passion, charging ahead.", "Impulsiveness, recklessness, frustration."),
  minor("wands", "queen", "Queen", "The Queen sits on a throne adorned with lions and sunflowers, a black cat at her feet and a wand in her hand. The Queen of Wands radiates warm, confident vibrancy, a magnetic and determined presence that draws others in.", "Confidence, warmth, determination, magnetic presence.", "Self-doubt, jealousy, a demanding streak."),
  minor("wands", "king", "King", "The King sits on a throne carved with salamanders and lions, gripping a flowering wand with natural command. The King of Wands embodies visionary, charismatic leadership, the boldness to inspire others toward a shared goal.", "Leadership, vision, boldness, natural authority.", "Impulsiveness, domineering, high expectations."),
  // ── Cups (Water) ──
  minor("cups", "ace", "Ace", "A hand offers an overflowing cup as a dove descends and five streams pour into the water below. The Ace of Cups is a new emotional or creative beginning, an opening of the heart to love, compassion, and intuition.", "New love, compassion, emotional opening, creativity.", "Blocked emotion, emptiness, repressed feelings."),
  minor("cups", "2", "Two", "Two figures exchange cups beneath the winged caduceus of Hermes, pledging themselves to one another. The Two of Cups is the card of mutual connection, attraction, and partnership built on respect.", "Partnership, attraction, mutual respect, union.", "Imbalance, broken connection, tension."),
  minor("cups", "3", "Three", "Three women raise their cups in a joyful toast amid a harvest of fruit and flowers. The Three of Cups celebrates friendship, community, and the shared joy of belonging.", "Community, friendship, joy, celebration together.", "Overindulgence, gossip, a falling-out."),
  minor("cups", "4", "Four", "A figure sits under a tree with arms crossed, ignoring a cup offered by a hand from a cloud. The Four of Cups speaks of apathy, contemplation, and the discontent that can blind us to the opportunities already at hand.", "Contemplation, apathy, missing an offered opportunity.", "Renewed interest, acceptance, awareness."),
  minor("cups", "5", "Five", "A cloaked figure mourns over three spilled cups, not yet turning to see two that still stand behind. The Five of Cups is about grief and disappointment, the pull to dwell on loss while something worthwhile remains.", "Grief, disappointment, focus on what's lost.", "Acceptance, moving on, finding the silver lining."),
  minor("cups", "6", "Six", "A child offers a flower-filled cup to another in a peaceful old courtyard. The Six of Cups stirs nostalgia, innocence, and the sweet comfort of memories and reunion with the past.", "Memories, nostalgia, reunion, childlike comfort.", "Stuck in the past, naivety, moving forward."),
  minor("cups", "7", "Seven", "A figure gazes at seven cups floating in the clouds, each holding a different tempting vision. The Seven of Cups is about choices and illusion, the wishful daydreams that must be sorted from what is truly real.", "Many options, fantasy, wishful thinking, daydreams.", "Clarity, a decisive choice, reality check."),
  minor("cups", "8", "Eight", "A figure turns away beneath a waning moon, leaving eight cups behind to climb toward distant mountains. The Eight of Cups is about walking away from what no longer satisfies in order to seek deeper meaning.", "Leaving something behind to seek deeper fulfillment.", "Fear of change, aimlessness, staying when you shouldn't."),
  minor("cups", "9", "Nine", "A satisfied figure sits with arms folded before a row of nine cups arranged like a display of plenty. Known as the wish card, the Nine of Cups speaks of contentment, gratitude, and emotional wishes fulfilled.", "Satisfaction, gratitude, emotional contentment.", "Smugness, unfulfilled wishes, overindulgence."),
  minor("cups", "10", "Ten", "A couple stands with arms raised as children play, a rainbow of ten cups arcing across the sky above their home. The Ten of Cups is the picture of emotional fulfilment, lasting harmony, and the warmth of loving bonds.", "Happiness, family harmony, lasting emotional joy.", "Broken harmony, misaligned values, strained bonds."),
  minor("cups", "page", "Page", "A whimsical youth gazes at a fish that has surfaced in a cup, charmed by the unexpected. The Page of Cups carries intuitive, creative messages, an openness to imagination and feelings that arrive from unlikely places.", "Creativity, intuition, an emotional message, openness.", "Emotional immaturity, moodiness, creative block."),
  minor("cups", "knight", "Knight", "A graceful knight rides slowly forward offering a cup, winged helmet marking him as a dreamer and messenger. The Knight of Cups follows the heart with charm and idealism, bringing offers of romance and beauty.", "Romance, charm, idealism, an offer of the heart.", "Moodiness, unrealistic ideals, broken promises."),
  minor("cups", "queen", "Queen", "The Queen sits at the water's edge gazing into an ornate covered cup, lost in feeling. The Queen of Cups embodies compassionate emotional depth, intuition, and a nurturing care that holds others tenderly.", "Compassion, emotional security, intuition, nurturing.", "Emotional overwhelm, insecurity, martyrdom."),
  minor("cups", "king", "King", "The King sits calmly on a throne floating amid turbulent seas, holding a cup with steady composure. The King of Cups represents emotional balance and diplomacy, mastery of feeling that stays generous and serene under pressure.", "Emotional mastery, diplomacy, calm, generosity.", "Moodiness, emotional manipulation, volatility."),
  // ── Swords (Air) ──
  minor("swords", "ace", "Ace", "A hand thrusts an upright sword from the clouds, its tip crowned with laurel above a stark mountain range. The Ace of Swords is a breakthrough of clarity and truth, the cutting power of a new idea that pierces confusion.", "Mental clarity, breakthrough, a new idea, sharp truth.", "Confusion, miscommunication, clouded judgement."),
  minor("swords", "2", "Two", "A blindfolded figure sits with two crossed swords held against her chest before a moonlit sea. The Two of Swords is a stalemate or hard choice, a defensive standoff where truth is shut out to avoid a difficult decision.", "Indecision, stalemate, avoiding a difficult choice.", "Indecision breaking, information revealed, overwhelm."),
  minor("swords", "3", "Three", "Three swords pierce a single red heart beneath grey storm clouds and falling rain. The Three of Swords is the image of heartbreak, sorrow, and the sharp pain of a truth that wounds even as it clarifies.", "Sorrow, heartbreak, a painful but clarifying truth.", "Recovery, releasing pain, forgiveness."),
  minor("swords", "4", "Four", "A knight lies in repose like a tomb effigy, three swords on the wall and one beneath him. The Four of Swords calls for rest, recovery, and quiet contemplation, a necessary pause to restore the mind.", "Rest, contemplation, recovery, a needed pause.", "Restlessness, burnout, avoiding rest."),
  minor("swords", "5", "Five", "A smirking figure gathers swords while two defeated others walk away under a ragged sky. The Five of Swords is conflict won at a cost, a hollow victory marked by discord, pride, and damaged trust.", "Conflict, defeat, winning at the expense of others.", "Reconciliation, releasing resentment, making amends."),
  minor("swords", "6", "Six", "A ferryman poles a small boat carrying a cloaked passenger and six swords toward a calmer shore. The Six of Swords is a transition away from turbulence, a sorrowful but necessary passage toward steadier water.", "Moving on, transition, recovery, leaving turbulence.", "Stuck, resisting change, unfinished business."),
  minor("swords", "7", "Seven", "A figure tiptoes away from a camp carrying five swords, leaving two behind, glancing back slyly. The Seven of Swords is about strategy, stealth, and deception, the temptation to act alone or get away with something.", "Cunning, strategy, getting away with something.", "Coming clean, conscience, a plan exposed."),
  minor("swords", "8", "Eight", "A bound and blindfolded figure stands hemmed in by eight swords, though the path out lies open. The Eight of Swords is the sense of being trapped by self-limiting beliefs and fears that bind more than circumstance does.", "Restriction, feeling stuck, self-limiting beliefs.", "Freeing yourself, new perspective, releasing fear."),
  minor("swords", "9", "Nine", "A figure sits up in bed with face in hands, nine swords mounted on the wall in the dark. The Nine of Swords is the card of anxiety and worry, the sleepless dread and mental anguish that loom largest in the night.", "Anxiety, dread, sleepless worry, mental anguish.", "Hope returning, facing fears, releasing anxiety."),
  minor("swords", "10", "Ten", "A figure lies face down with ten swords in his back, yet a golden dawn breaks on the horizon. The Ten of Swords marks a painful, definitive ending or rock bottom, with the quiet promise that the worst is now over.", "A definitive painful ending, betrayal, the worst is over.", "Recovery, survival, refusing to stay down."),
  minor("swords", "page", "Page", "A young figure stands on windswept ground holding a sword aloft, alert and watchful. The Page of Swords is curious, vigilant mental energy, a restless appetite for ideas, truth, and information.", "Curiosity, new ideas, vigilance, mental restlessness.", "Scattered thoughts, gossip, all talk no action."),
  minor("swords", "knight", "Knight", "A knight charges into a stormy wind at full gallop, sword raised and thoughts racing ahead. The Knight of Swords is fast, blunt, ambitious action, driven by logic and urgency to cut straight to the goal.", "Drive, ambition, charging in with logic and speed.", "Recklessness, aggression, burnout."),
  minor("swords", "queen", "Queen", "The Queen sits upright with sword raised and one hand extended, gazing ahead with unclouded eyes. The Queen of Swords offers clear, independent perception, honest judgement tempered by hard-won experience.", "Honest clarity, independence, perceptive judgement.", "Coldness, harsh words, bitterness."),
  minor("swords", "king", "King", "The King sits in judgement holding an upright sword, blue robes and butterflies marking a clear and principled mind. The King of Swords embodies intellectual authority and ethics, the disciplined truth that rules with fairness.", "Intellect, truth, ethical authority, clear judgement.", "Manipulation, cruelty, misuse of power."),
  // ── Pentacles (Earth) ──
  minor("pentacles", "ace", "Ace", "A hand extends a single golden pentacle above a lush garden with a flowered archway leading onward. The Ace of Pentacles is a new material opportunity, a tangible seed of prosperity waiting to be planted and grown.", "Opportunity, prosperity, a new venture, manifestation.", "Missed chance, scarcity mindset, poor planning."),
  minor("pentacles", "2", "Two", "A figure dances while juggling two pentacles linked by an infinity loop as ships ride the waves behind. The Two of Pentacles is about juggling and adaptability, keeping competing priorities in playful balance as circumstances shift.", "Balance, adaptability, managing priorities, flexibility.", "Overwhelm, disorganization, dropping the ball."),
  minor("pentacles", "3", "Three", "A sculptor at work in a cathedral confers with two others reviewing the plans together. The Three of Pentacles honors teamwork and skill, the craftsmanship that grows when talent, planning, and collaboration combine.", "Collaboration, craftsmanship, building together.", "Disharmony, lack of teamwork, poor quality."),
  minor("pentacles", "4", "Four", "A seated figure clutches one pentacle to his chest, stands on two more, and balances a fourth on his head. The Four of Pentacles is about security and holding on, the impulse to grip tightly to money, control, and what feels safe.", "Stability, saving, control — sometimes clinging.", "Possessiveness loosening, generosity, or greed."),
  minor("pentacles", "5", "Five", "Two ragged figures trudge through snow past a lit, stained-glass church window they do not look up to see. The Five of Pentacles speaks of hardship and insecurity, the cold of hard times when help is closer than it appears.", "Insecurity, hard times, but support is closer than it seems.", "Recovery, help accepted, hardship easing."),
  minor("pentacles", "6", "Six", "A merchant weighs coins on a scale while giving alms to two kneeling beggars. The Six of Pentacles is about giving and receiving in balance, the fair exchange and generosity that flow in both directions.", "Generosity, fair exchange, support flowing both ways.", "Strings attached, imbalance, debt."),
  minor("pentacles", "7", "Seven", "A laborer leans on his hoe, pausing to regard the pentacles growing on a flourishing vine. The Seven of Pentacles is about patience and the long view, assessing progress while waiting for steady effort to bear fruit.", "Assessment, patience, waiting for effort to pay off.", "Impatience, poor return, giving up too soon."),
  minor("pentacles", "8", "Eight", "A craftsman sits at his bench carving pentacle after pentacle, fully absorbed in the work. The Eight of Pentacles is about diligence and mastery, the patient dedication that refines a skill through steady repetition.", "Skill-building, dedication, refining your craft.", "Perfectionism, cut corners, lack of focus."),
  minor("pentacles", "9", "Nine", "An elegant woman stands in a lush vineyard with a hooded falcon resting on her gloved hand. The Nine of Pentacles is self-sufficient abundance, the refined independence and comfort earned through one's own disciplined effort.", "Independence, luxury, enjoying the fruits of effort.", "Overwork, financial dependence, hollow success."),
  minor("pentacles", "10", "Ten", "Three generations gather at an archway with dogs at hand and ten pentacles arranged around them. The Ten of Pentacles speaks of lasting wealth and legacy, the deep security of family, tradition, and what endures across generations.", "Long-term security, family, legacy, established wealth.", "Instability, family friction, fleeting wealth."),
  minor("pentacles", "page", "Page", "A young figure stands in a green field studying a single pentacle held up before him with focused care. The Page of Pentacles is ambition and a new opportunity, the studious eagerness to learn a craft and bring a plan to life.", "Study, ambition, manifestation, a promising opening.", "Distraction, procrastination, unrealized plans."),
  minor("pentacles", "knight", "Knight", "A knight sits still on a sturdy workhorse, holding a pentacle over freshly plowed fields. The Knight of Pentacles embodies steady, reliable diligence, the patient persistence and routine that finish a job properly.", "Routine, reliability, hard work, patient persistence.", "Stagnation, boredom, over-caution."),
  minor("pentacles", "queen", "Queen", "The Queen sits in a flowering garden cradling a pentacle, a rabbit hopping by her feet. The Queen of Pentacles offers practical, nurturing abundance, a grounded resourcefulness that cares for both home and the people in it.", "Resourcefulness, nurturing, grounded abundance.", "Self-neglect, smothering, work–life imbalance."),
  minor("pentacles", "king", "King", "The King sits on a throne wreathed in grapevines, one hand resting on a pentacle amid his flourishing estate. The King of Pentacles embodies grounded prosperity and leadership, the disciplined mastery that turns ambition into lasting success.", "Wealth, stability, leadership, disciplined success.", "Greed, materialism, controlling tendencies."),
];

export const tarotReference: ReferenceEntry[] = [...majors, ...minors];
