import { NextResponse } from "next/server";
import { supabase } from "@/lib/supabase";

export const runtime = "edge";

/* One-time seed endpoint: GET /api/seed-special-points
   Seeds Chiron, North Node, and South Node interpretations into kb_planet_in_sign.
   Delete this file after running it once. */

interface Entry {
  planet: string;
  sign: string;
  summary: string;
  life_patterns: string;
  relationships: string;
  challenges: string;
  growth: string;
  book_references: string[];
}

const CHIRON: Entry[] = [
  { planet: "Chiron", sign: "Aries", summary: "Your deepest wound is around your own identity and right to exist as you are. You've learned that being authentically yourself is dangerous, that your natural assertiveness makes you too much. The wound asks: Can I be myself without apology?", life_patterns: "You struggle to initiate. Even when you know what you want, something inside stops you from going after it. You may come across as hesitant when inside you're burning with desire. You start strong then second-guess yourself mid-stride.", relationships: "You attract people who need your courage more than you trust your own. You may find yourself in relationships where you're the passive one, waiting to be chosen. Partners sense your doubt before you do.", challenges: "The hardest part is the constant self-doubt that shadows your impulses. You can't tell if you're being wise or cowardly. There's deep frustration — you see others charge forward and wonder why you can't.", growth: "Your healing comes through reclaiming small acts of courage. Start with what you secretly want and do it, even imperfectly. Your wound becomes your gift when you guide others in trusting their own impulses.", book_references: ["Reinhart, Chiron and the Healing Journey"] },
  { planet: "Chiron", sign: "Taurus", summary: "Your deepest wound is about your fundamental worth — whether you deserve good things, comfort, stability. You learned early that self-worth was conditional, that you had to earn the right to exist safely. The question haunts you: Am I enough just as I am?", life_patterns: "You oscillate between self-deprivation and desperation. Money, your body, and material well-being become battlegrounds. You're either depriving yourself to prove worthiness or overindulging to numb the emptiness.", relationships: "You attract people who either overvalue or devalue you — rarely the healthy middle. You may settle for relationships where you're not truly treasured, or push away partners who genuinely care.", challenges: "The deepest pain is knowing internal poverty despite external abundance. You may have resources but never feel secure. Your body becomes a source of shame and self-judgment.", growth: "Healing happens when you begin offering yourself the tenderness you'd give a beloved. Your wound transforms into the ability to help others reclaim their worth — you become a healer of shame.", book_references: ["Reinhart, Chiron and the Healing Journey"] },
  { planet: "Chiron", sign: "Gemini", summary: "Your deepest wound is around being heard and understood. You learned that your voice doesn't matter, that what you think is less important than what others believe. Your mind is sharp but burdened by the belief that intelligence isn't enough.", life_patterns: "You talk without being listened to, or you stay silent when you have something crucial to say. You may become a chronic explainer, desperate to make yourself clear, or retreat into cold logic to avoid vulnerability.", relationships: "You often feel fundamentally misunderstood, even with people who care. You attract partners who listen superficially or dismiss your perspective. Intimacy requires being known, and you're terrified you never can be.", challenges: "The loneliness of being surrounded by people yet unheard. You question your own intelligence constantly, second-guessing what you know. Deep anxiety about saying the wrong thing or being exposed as a fraud.", growth: "Your healing comes through finding your actual voice — not explaining yourself to be understood, but speaking your truth to those who are listening. Your wound becomes your gift when you truly hear others.", book_references: ["Reinhart, Chiron and the Healing Journey"] },
  { planet: "Chiron", sign: "Cancer", summary: "Your deepest wound is about belonging and safety — having a true home, whether physical or emotional. You needed nurturing and either received it conditionally or not at all. You've spent your life searching for somewhere that feels like home.", life_patterns: "You fluctuate between clinginess and withdrawal. You may struggle to leave unhealthy situations because the familiar feels safer than the unknown. Or you don't stay anywhere long enough to build the safety you crave.", relationships: "You magnetize either caretakers or people who need caretaking — rarely equals. Emotional intimacy triggers your deepest fears about rejection and abandonment. You may mother others while secretly wanting to be mothered.", challenges: "Homesickness that no place can cure. You're caught between deep loyalty to origins that hurt you and desperate longing for something better. There's guilt — you want to care for others but you're exhausted from not being cared for.", growth: "Healing comes through recognizing that home isn't a place, it's a feeling you create inside yourself. Your wound transforms into the ability to provide real emotional safety for others — genuine holding space.", book_references: ["Reinhart, Chiron and the Healing Journey"] },
  { planet: "Chiron", sign: "Leo", summary: "Your deepest wound is about creative self-expression and being truly seen. You learned that shining made you a target, that your light threatens others. Part of you wants desperately to be witnessed; another part hides what makes you unique.", life_patterns: "You either perform constantly seeking validation, or hide your gifts entirely. You feel like a fraud whenever you receive praise, convinced people don't see the 'real' you. There's a gap between your inner significance and your external expression.", relationships: "You attract relationships where your creative self is either idolized or dismissed. You struggle to share yourself authentically without either diminishing yourself or making it all about you.", challenges: "Constant self-judgment about your creative expression. You may have enormous talent but underutilize it out of fear. Resentment when you see others celebrated for far less triggers both desire and despair.", growth: "Your healing comes through creating not for applause but for the truth it contains. Your wound becomes your gift when you help others find their creative courage — witnessing them the way you wish to be witnessed.", book_references: ["Reinhart, Chiron and the Healing Journey"] },
  { planet: "Chiron", sign: "Virgo", summary: "Your deepest wound is perfectionism coupled with a fear that you're fundamentally inadequate. You learned that your value comes from what you do, not who you are. You're hypercritical of yourself while deeply sensitive to criticism.", life_patterns: "You're driven by impossible standards — in your work, your body, your routines. You notice every flaw first. You're prone to exhaustion from constant self-improvement efforts. Your body often reflects your inner anxiety.", relationships: "You attract relationships where you're doing all the managing, or you retreat into judgment when others don't meet your standards. You struggle to be imperfect with someone and still be loved.", challenges: "Knowing you'll never meet your own standards. You're enslaved to improvement and still feel broken. Deep loneliness — so focused on fixing yourself that you never fully inhabit your own life.", growth: "Healing comes through accepting 'good enough' as genuinely good. Your wound transforms when you redirect your analytical gifts toward helping others stop self-sabotage — you become a healer of perfectionism.", book_references: ["Reinhart, Chiron and the Healing Journey"] },
  { planet: "Chiron", sign: "Libra", summary: "Your deepest wound is in relationships themselves. You learned that love requires you to abandon yourself, that partnership means losing your identity. You're terrified of being alone but equally terrified of disappearing into someone else.", life_patterns: "You swing between codependency and isolation. You're a natural mediator who absorbs others' conflicts. You may stay in relationships long past their expiration because being alone feels like failure.", relationships: "You attract partners who need your balance more than they offer their own. You lose yourself in the other person's preferences. Your relationships often feel one-sided because you've silenced your own needs.", challenges: "The impossibility of needing love while fearing it will erase you. You struggle to have conflict because disagreement feels like abandonment. You people-please automatically and don't realize you're doing it.", growth: "Healing comes through learning that real partnership requires two whole people. Your wound becomes your gift when you teach others that love doesn't require self-abandonment — that conflict can be healthy.", book_references: ["Reinhart, Chiron and the Healing Journey"] },
  { planet: "Chiron", sign: "Scorpio", summary: "Your deepest wound is around trust, intimacy, and power. You've been betrayed or violated in ways that taught you closeness is dangerous. You long for deep connection but the vulnerability it requires feels life-threatening.", life_patterns: "You live behind walls. You test people before letting them in, and even then you hold back the most essential parts. You're drawn to psychological depth but use your insight as a shield. You may struggle with control — needing it to feel safe.", relationships: "You attract intense relationships that mirror your wound — betrayal, power struggles, emotional manipulation. You can love deeply but your fear of vulnerability creates the very distance you dread.", challenges: "The loneliness of being unable to trust. You see through people but can't let them see through you. There's rage underneath — at those who hurt you and at yourself for still needing anyone.", growth: "Healing comes through choosing to trust again despite having every reason not to. Your wound becomes your gift when you help others navigate their own darkness — you understand pain others can't face.", book_references: ["Reinhart, Chiron and the Healing Journey"] },
  { planet: "Chiron", sign: "Sagittarius", summary: "Your deepest wound is about meaning, truth, and faith. Something shattered your belief system — in God, in the universe, in the point of it all. You search for meaning compulsively because the alternative is a void you can't face.", life_patterns: "You may become a perpetual student, traveler, or seeker — always looking for the next answer. Or you cling rigidly to beliefs because losing them again would be unbearable. You're prone to spiritual bypassing or cynical nihilism.", relationships: "You attract partners who either share your search or try to ground you. You struggle with commitment because settling down feels like giving up the quest. Philosophical differences feel like personal attacks.", challenges: "The terror of meaninglessness. You know too much to believe simply but need to believe in something. There's grief for the faith you lost and anger at whatever took it from you.", growth: "Healing comes through finding meaning in the search itself, not the destination. Your wound becomes your gift when you help others find their own truth — not by giving answers, but by showing that the questions themselves matter.", book_references: ["Reinhart, Chiron and the Healing Journey"] },
  { planet: "Chiron", sign: "Capricorn", summary: "Your deepest wound is about authority, achievement, and legacy. You learned that love and approval are earned through performance. Your worth got tangled up with your output, and rest feels like failure.", life_patterns: "You're a compulsive achiever who never feels like enough. You take on more responsibility than anyone should carry, then resent that no one notices. Success doesn't satisfy — there's always the next benchmark.", relationships: "You attract partners who lean on your competence or authority figures who never fully approve. You struggle to be vulnerable because weakness feels dangerous. You show love through providing, not feeling.", challenges: "The exhaustion of building constantly. You've achieved things but none of it fills the hole. There's deep loneliness at the top — you can't show weakness so no one knows the real you.", growth: "Healing comes through learning that your worth isn't your output. Your wound becomes your gift when you mentor others through their own ambition — teaching that real authority includes vulnerability.", book_references: ["Reinhart, Chiron and the Healing Journey"] },
  { planet: "Chiron", sign: "Aquarius", summary: "Your deepest wound is about belonging versus individuality. You feel fundamentally different from others — not in a glamorous way, but in a way that isolates you. You learned that being yourself means being alone.", life_patterns: "You oscillate between desperate conformity and radical detachment. You join groups hoping to belong, then feel alienated within them. You may intellectualize your loneliness instead of feeling it.", relationships: "You attract people who appreciate your uniqueness but can't reach you emotionally. You keep partners at arm's length, connecting through ideas instead of feelings. Intimacy feels like a cage.", challenges: "The isolation of being the perpetual outsider. You want to belong but not at the cost of being yourself. There's grief for the community you've never quite found.", growth: "Healing comes through finding your people — not by becoming normal, but by accepting that your weirdness is your offering. Your wound becomes your gift when you help others embrace what makes them different.", book_references: ["Reinhart, Chiron and the Healing Journey"] },
  { planet: "Chiron", sign: "Pisces", summary: "Your deepest wound is spiritual and boundaryless. You feel everything — other people's pain, the world's suffering, the weight of existence. You learned that sensitivity is a liability and that feeling deeply means drowning.", life_patterns: "You're prone to escapism — substances, fantasy, sleep, spiritual bypassing. You absorb others' emotions and lose track of your own. You may sacrifice yourself for others and feel resentful about it. Boundaries feel mean.", relationships: "You attract people who need saving or people who try to save you. Your empathy makes you a magnet for emotional vampires. You love without limits and get devastated when it's not returned the same way.", challenges: "The overwhelm of feeling everything without filters. You can't tell where you end and others begin. There's deep grief — not just yours but the world's — that you carry without knowing how to put it down.", growth: "Healing comes through learning that boundaries are an act of love, not cruelty. Your wound becomes your gift when you channel your sensitivity into healing work — teaching others that feeling deeply doesn't require losing yourself.", book_references: ["Reinhart, Chiron and the Healing Journey"] },
];

const NORTH_NODE: Entry[] = [
  { planet: "North Node", sign: "Aries", summary: "You're learning to claim your own desires and stand alone. After lifetimes of disappearing into others' needs, your evolution demands courage, assertion, and a strong sense of self. This feels selfish because you're used to self-sacrifice — but it's necessary.", life_patterns: "You keep encountering situations that force you to choose between what others want and what you want. Your life gradually teaches you that your desires matter and that conflict is not catastrophic.", relationships: "True connection requires two whole people, not a caretaker and a dependent. You're discovering that wanting your own life doesn't make you uncaring. Learning to disappoint people is your primary relationship lesson.", challenges: "You battle the impulse to keep the peace at all costs. You're terrified of being seen as selfish. Speaking up feels dangerous, even when nothing bad happens.", growth: "As you develop authentic assertiveness, you become genuinely magnetic. Your growth isn't about becoming aggressive — it's about honoring your own integrity. Courage and kindness can coexist.", book_references: ["Schulman, Karmic Astrology"] },
  { planet: "North Node", sign: "Taurus", summary: "You're learning to build something real and enduring after lifetimes of chaos and intensity. Your growth lies in stability, patience, and sensual grounding. You're being asked to slow down, enjoy what you have, and create security — not drama.", life_patterns: "Your life teaches you the value of simple, steady progress. You encounter repeated lessons about the cost of crisis-seeking and the peace of routine. Comfort, when you finally allow it, becomes your teacher.", relationships: "You're learning that love doesn't require constant intensity or transformation. Steady, reliable partners feel boring until you understand they offer trust. Sensual connection grounds you.", challenges: "Your attraction to deep transformation keeps you in turbulent situations. You struggle to stay with anything calm. The stability you need feels tedious — you sometimes create unnecessary drama to feel alive.", growth: "Real power is building something that lasts. Sensual pleasures, financial security, and consistent relationships become sources of genuine fulfillment. Depth can be found in consistency, not just crisis.", book_references: ["Schulman, Karmic Astrology"] },
  { planet: "North Node", sign: "Gemini", summary: "You're learning to listen, gather information, and honor multiple perspectives after lifetimes of preaching certainty. Your growth demands intellectual humility: admitting what you don't know and changing your mind based on new information.", life_patterns: "You keep encountering situations where your single viewpoint isn't enough. Life teaches you that understanding the other side doesn't weaken your position — it strengthens it. Curiosity becomes your primary tool.", relationships: "Listening is an act of love. Partners need you to hear them, not just convince them. Connection deepens when you ask questions rather than deliver pronouncements.", challenges: "You know too much and listen too little. Your certainty alienates people. The humility to say 'I don't know' feels impossible. You often talk more than you listen.", growth: "Real authority emerges from genuine knowledge, which requires listening first. As you become curious rather than certain, people actually hear you. Communication becomes a dance rather than a platform.", book_references: ["Schulman, Karmic Astrology"] },
  { planet: "North Node", sign: "Cancer", summary: "You're learning vulnerability after lifetimes of achievement and control. Your growth lies in emotional honesty, nurturing, and creating real intimacy — not just impressive results. Feelings aren't weakness; they're the point.", life_patterns: "You keep achieving things that don't satisfy you emotionally. Success feels hollow until you learn to connect with the people in your life. Your lessons come through family, home, and emotional risk.", relationships: "You're learning to need people and let them need you — not as a transaction but as genuine care. Partners want your heart, not your resume. Emotional presence matters more than providing.", challenges: "Vulnerability feels like failure. You default to competence when feelings get complicated. You struggle to ask for help or admit you're hurting. Control is your security blanket.", growth: "When you finally allow yourself to feel and be felt, everything changes. Your ambition gains meaning. You discover that real legacy isn't what you build — it's who you love and how deeply.", book_references: ["Schulman, Karmic Astrology"] },
  { planet: "North Node", sign: "Leo", summary: "You're learning to shine individually after lifetimes of hiding in the collective. Your growth demands creative self-expression, personal visibility, and the courage to stand out. You're meant to be seen — not blend in.", life_patterns: "You keep being pushed into the spotlight even though it terrifies you. Life forces you to take credit, lead from the front, and express what only you can express. Anonymity is no longer an option.", relationships: "You're learning that love includes being adored for who you specifically are — not just appreciated for your contributions to the group. Partners want your unique warmth, not your detachment.", challenges: "Self-consciousness and fear of ego. You've been taught that standing out is selfish. You retreat into group identity when personal expression feels too exposed.", growth: "Your light is needed. As you claim your creative authority, you inspire others to do the same. Leadership that comes from authentic self-expression — not ego — is your gift to the world.", book_references: ["Schulman, Karmic Astrology"] },
  { planet: "North Node", sign: "Virgo", summary: "You're learning practical service and discernment after lifetimes of spiritual escapism. Your growth lies in showing up to the real world — routines, health, useful work, and the discipline of doing things well.", life_patterns: "You keep encountering situations that require practical solutions, not spiritual bypassing. Life teaches you that showing up consistently matters more than transcendent experiences. Details become sacred.", relationships: "You're learning that love is daily — making dinner, being on time, following through. Partners need your presence, not your spiritual wisdom. Showing up reliably is the deepest form of care.", challenges: "The physical world feels limiting after lifetimes in the ethereal. You resist routines, dismiss details, and avoid the unglamorous work of real life. Escapism is your default.", growth: "When you apply your intuitive gifts to practical service, you become genuinely healing. Your spiritual depth gains grounding. You discover that the sacred lives in the ordinary — in every careful, conscious act.", book_references: ["Schulman, Karmic Astrology"] },
  { planet: "North Node", sign: "Libra", summary: "You're learning partnership after lifetimes of going it alone. Your growth demands compromise, diplomacy, and the willingness to consider someone else's needs as important as your own. Independence got you here — it won't take you further.", life_patterns: "You keep encountering relationships that challenge your self-sufficiency. Life forces you to negotiate, collaborate, and see yourself through another's eyes. The mirror of partnership teaches you things solitude can't.", relationships: "This is your primary classroom. You're learning that needing someone isn't weakness. True partnership requires vulnerability, compromise, and the willingness to be changed by another person.", challenges: "Compromise feels like surrender. You're terrified of losing yourself in another person. You default to independence when relationships get uncomfortable, which is exactly when the growth happens.", growth: "Real strength includes the ability to yield. As you learn to partner authentically, you discover dimensions of yourself that only emerge in relationship. Your independence deepens rather than diminishes.", book_references: ["Schulman, Karmic Astrology"] },
  { planet: "North Node", sign: "Scorpio", summary: "You're learning depth and transformation after lifetimes of comfort and security. Your growth demands that you face the uncomfortable truths — about yourself, about others, about what's really going on beneath the surface.", life_patterns: "You keep encountering crises that strip away your comfort zone. Life forces you to deal with loss, power, intimacy, and the parts of yourself you'd rather not see. Superficiality stops working.", relationships: "You're learning that real intimacy requires showing the parts of yourself you hide. Partners want your depth, not your pleasantness. Love that transforms you is the goal, even though it's terrifying.", challenges: "You cling to comfort, routine, and the material world. Change feels like death. You avoid emotional intensity and the vulnerability of truly merging with another person.", growth: "When you let yourself be transformed — by love, by loss, by truth — you discover a power you didn't know you had. Your resilience deepens. You become someone who can hold space for the full spectrum of life.", book_references: ["Schulman, Karmic Astrology"] },
  { planet: "North Node", sign: "Sagittarius", summary: "You're learning big-picture wisdom after lifetimes of surface-level knowledge. Your growth demands you find a philosophy, a belief system, a truth worth living for — not just interesting facts to collect.", life_patterns: "You keep encountering situations that challenge your assumptions and expand your worldview. Travel, education, and exposure to different cultures become catalysts. Life asks you to find meaning, not just information.", relationships: "You're learning that connection deepens when you share beliefs and vision, not just gossip and data. Partners want to know what you stand for. Depth of conviction becomes attractive.", challenges: "You scatter your attention across too many topics without committing to any. You avoid the vulnerability of believing in something because being wrong feels unbearable.", growth: "When you commit to a truth bigger than yourself, everything crystallizes. Your natural curiosity gains direction. You become a teacher and guide, not just a collector of interesting things.", book_references: ["Schulman, Karmic Astrology"] },
  { planet: "North Node", sign: "Capricorn", summary: "You're learning to build something in the world after lifetimes of staying safe at home. Your growth demands ambition, structure, and the willingness to be tested publicly. Comfort zones won't serve your evolution.", life_patterns: "You keep being pushed toward leadership, responsibility, and public contribution. Life forces you to grow up, step out, and create something that matters beyond your inner circle.", relationships: "You're learning that love includes respecting someone's ambitions and supporting their growth in the world. Partners want your strength and direction, not just your emotional availability.", challenges: "The public world feels cold and exposing. You retreat into emotional safety and family when things get hard. You struggle with authority — both being one and dealing with them.", growth: "When you build something real — a career, a legacy, a structure that serves others — your emotional depth gives it meaning. You become an authority who leads with both competence and heart.", book_references: ["Schulman, Karmic Astrology"] },
  { planet: "North Node", sign: "Aquarius", summary: "You're learning to serve the collective after lifetimes of personal glory. Your growth demands that you use your gifts for something bigger than yourself — community, innovation, and the willingness to be one among many.", life_patterns: "You keep encountering situations where individual achievement isn't enough. Life pushes you toward groups, causes, and collective efforts. Your evolution happens through collaboration, not solo performance.", relationships: "You're learning that love isn't just personal — it extends to humanity. Partners want your vision of the future, not just your personal warmth. Friendship becomes as sacred as romance.", challenges: "You crave personal recognition and specialness. Being one of many feels like demotion. You struggle to subordinate your ego to a collective vision.", growth: "When you channel your creative power into serving something larger, your individual gifts actually amplify. You discover that true uniqueness emerges through contribution, not performance.", book_references: ["Schulman, Karmic Astrology"] },
  { planet: "North Node", sign: "Pisces", summary: "You're learning to surrender and trust after lifetimes of controlling every detail. Your growth demands faith — in the universe, in the process, in something you can't see or measure. Letting go is your evolution.", life_patterns: "You keep encountering situations where your plans fall apart and you're forced to trust. Life teaches you that control is an illusion and that the most meaningful experiences can't be engineered.", relationships: "You're learning that love requires surrendering control. Partners want your presence and compassion, not your analysis. Connection deepens when you stop trying to fix everything.", challenges: "Chaos terrifies you. You over-plan, over-analyze, and over-control. Spiritual experiences feel unreliable. You struggle to trust anything you can't verify or measure.", growth: "When you finally let go, grace enters. Your analytical gifts don't disappear — they serve something deeper. You discover that the universe has a plan that's better than yours.", book_references: ["Schulman, Karmic Astrology"] },
];

const SOUTH_NODE: Entry[] = [
  { planet: "South Node", sign: "Libra", summary: "You naturally understand partnership, diplomacy, and keeping the peace. But your comfort zone has become your cage — you lose yourself in relationships, avoid conflict, and abandon your own needs to maintain harmony.", life_patterns: "You immediately see all sides of every situation. You're a natural peacekeeper. But your comfort with compromise keeps you in situations where you accept too little for yourself.", relationships: "Partnership feels natural and necessary — perhaps too natural. You can disappear entirely into a relationship. You're attracted to partners who need your balance.", challenges: "You sacrifice almost anything to keep the peace. Your own needs feel less important than harmony. People-pleasing is so automatic you don't realize you're doing it.", growth: "True balance requires you to take up space. The peace you maintain must include your own truth. Relationships deepen when you stop being the eternal mediator and become a real person with needs.", book_references: ["Schulman, Karmic Astrology"] },
  { planet: "South Node", sign: "Scorpio", summary: "You naturally understand depth, transformation, and hidden psychology. But your comfort with crisis, control, and emotional extremes is keeping you stuck. You're here to learn stability and the value of what's ordinary.", life_patterns: "You're drawn to complexity, mystery, and transformation. But your attraction to chaos keeps you in turbulent situations. You're learning that peace, not crisis, is the real teacher.", relationships: "You need deep connection — nothing superficial will do. But your relationships often involve power struggles. Your growth involves learning that real love allows things to simply be.", challenges: "You seek transformation constantly, even when stability would serve you better. You distrust ease and comfort. Simple happiness feels boring and untrustworthy.", growth: "Real power lies in building something that lasts, not in control or crisis. Trust and simplicity become your unexpected gifts.", book_references: ["Schulman, Karmic Astrology"] },
  { planet: "South Node", sign: "Sagittarius", summary: "You naturally have strong beliefs, philosophical depth, and a sense of knowing the truth. But your certainty has become arrogance — you preach when you should listen, and your big-picture thinking misses crucial details.", life_patterns: "You're a natural teacher and philosopher. But your attachment to being right keeps you from growing. You overgeneralize and miss the nuance that real wisdom requires.", relationships: "You lecture when you should listen. Partners feel talked at, not talked with. Your growth involves genuine curiosity about how others see the world.", challenges: "Admitting you're wrong feels impossible. Your beliefs are your identity, so questioning them feels like losing yourself. You dismiss details as unimportant.", growth: "Real wisdom comes from knowing what you don't know. Listening becomes your greatest teacher. Your authority deepens when it's earned through humility, not asserted through certainty.", book_references: ["Schulman, Karmic Astrology"] },
  { planet: "South Node", sign: "Capricorn", summary: "You naturally understand ambition, structure, and authority. But your drive to achieve has become compulsive — you measure your worth by your output and struggle to let yourself feel or be vulnerable.", life_patterns: "You're a natural leader and builder. But your workaholism and emotional control keep you isolated. You achieve in order to feel safe, but safety never comes.", relationships: "You provide instead of connecting. Partners want your heart, not your resume. Emotional availability is what they need, not more evidence of your competence.", challenges: "Rest feels lazy. Vulnerability feels dangerous. You can't stop building because stopping means facing the emptiness underneath the ambition.", growth: "Your evolution requires letting go of the need to be impressive. When you prioritize feeling over achieving, your accomplishments gain meaning they never had before.", book_references: ["Schulman, Karmic Astrology"] },
  { planet: "South Node", sign: "Aquarius", summary: "You naturally think independently and care about the collective. But your detachment has become emotional avoidance — you hide in ideas, groups, and causes to avoid the vulnerability of personal connection.", life_patterns: "You're comfortable in groups but struggle with one-on-one intimacy. You intellectualize feelings instead of experiencing them. You contribute to humanity while avoiding individual humans.", relationships: "You keep emotional distance and call it independence. Partners feel you're present but unreachable. Your growth requires letting someone matter to you personally, not abstractly.", challenges: "Emotional intimacy feels like a cage. You retreat into your mind when feelings get intense. Being special to one person feels less noble than serving the many.", growth: "Your evolution requires risking personal love — messy, irrational, individual love. When you let yourself be personally adored, your gifts to the collective deepen rather than diminish.", book_references: ["Schulman, Karmic Astrology"] },
  { planet: "South Node", sign: "Pisces", summary: "You naturally understand spiritual reality, compassion, and the interconnectedness of all things. But your sensitivity has become escapism — you dissolve boundaries, avoid practical reality, and lose yourself in fantasy or sacrifice.", life_patterns: "You're naturally intuitive and compassionate. But you avoid the material world — details, deadlines, physical health. You'd rather transcend reality than deal with it.", relationships: "You merge completely with partners, losing track of where you end and they begin. Your compassion becomes codependency. You forgive too easily and enable harmful behavior.", challenges: "Boundaries feel mean. The physical world feels coarse. You'd rather escape than engage with imperfect reality. Your sensitivity makes ordinary life overwhelming.", growth: "Your evolution requires grounding your spiritual gifts in practical service. When you show up to the real world — with all its imperfections — your compassion becomes genuinely healing instead of merely sympathetic.", book_references: ["Schulman, Karmic Astrology"] },
  { planet: "South Node", sign: "Aries", summary: "You naturally take charge, act independently, and fight for what you want. But your self-reliance has become isolation — you go it alone when you should partner, and your directness pushes people away.", life_patterns: "You're a natural initiator and warrior. But your impatience and need for independence keep you from experiencing the depth that only partnership provides.", relationships: "You struggle to compromise. You'd rather leave than negotiate. Partners feel bulldozed by your certainty. Your growth requires learning that yielding isn't losing.", challenges: "Depending on anyone feels dangerous. Compromise feels like surrender. You create conflict where diplomacy would serve you better.", growth: "Real strength includes the ability to be soft. Your independence deepens when it includes the capacity to truly partner — to let someone change your mind and your heart.", book_references: ["Schulman, Karmic Astrology"] },
  { planet: "South Node", sign: "Taurus", summary: "You naturally understand comfort, stability, and the material world. But your attachment to security has become stagnation — you cling to what's familiar even when it's killing you, and you resist the transformation you need.", life_patterns: "You're naturally grounded and reliable. But your resistance to change keeps you in situations long past their expiration. You choose comfort over growth every time.", relationships: "You stay in relationships because they're familiar, not because they're good. You confuse stability with love. Your growth requires accepting that real love sometimes transforms everything.", challenges: "Change feels like death. You grip the known even when it hurts. You accumulate possessions and routines as armor against the unknown.", growth: "Your evolution requires letting go of what's comfortable in service of what's true. When you allow transformation, you discover a security that no external thing could ever provide.", book_references: ["Schulman, Karmic Astrology"] },
  { planet: "South Node", sign: "Gemini", summary: "You naturally gather information, communicate, and see multiple perspectives. But your mental agility has become scattered — you collect facts without forming convictions and talk without saying anything meaningful.", life_patterns: "You're naturally curious and adaptable. But you scatter your energy across too many interests. You know a little about everything and a lot about nothing. Depth eludes you.", relationships: "You charm with conversation but struggle with emotional depth. Partners want substance, not wit. Your growth requires committing to a perspective instead of dancing around every topic.", challenges: "Commitment to a single truth feels claustrophobic. You change your mind to avoid being pinned down. Depth requires focus, which bores you.", growth: "When you commit to a belief bigger than your cleverness, your communication gains weight. People begin to follow you, not just find you entertaining.", book_references: ["Schulman, Karmic Astrology"] },
  { planet: "South Node", sign: "Cancer", summary: "You naturally nurture, protect, and create emotional safety. But your caretaking has become a way to control — you smother in the name of love, and your emotional needs dominate every relationship.", life_patterns: "You're naturally empathetic and domestic. But you use emotional bonds as chains. You struggle to let people grow because their independence threatens your security.", relationships: "You over-nurture and under-respect boundaries. You want to be needed. Partners feel smothered. Your growth requires letting people fail without rescuing them.", challenges: "Emotional independence — yours or anyone else's — feels like abandonment. You retreat into family or home when the world demands you show up publicly.", growth: "When you channel your caring into building something in the world — not just protecting your nest — your nurturing gains purpose beyond codependency.", book_references: ["Schulman, Karmic Astrology"] },
  { planet: "South Node", sign: "Leo", summary: "You naturally command attention, express yourself, and shine. But your need to be special has become narcissistic — you make everything about yourself and struggle to serve something larger.", life_patterns: "You're a natural performer and leader. But your ego demands center stage in every situation. You struggle when you're not the most important person in the room.", relationships: "You dominate relationships with your personality. Partners feel eclipsed. Your growth requires learning that love means making space for someone else's light, not just your own.", challenges: "Being ordinary feels like dying. You need constant recognition. Serving the group without personal credit feels humiliating.", growth: "When you channel your creative power into collective service, your light actually brightens. True leadership means lifting others, not outshining them.", book_references: ["Schulman, Karmic Astrology"] },
  { planet: "South Node", sign: "Virgo", summary: "You naturally analyze, organize, and serve. But your perfectionism has become a prison — you control every detail because trusting anything beyond your analysis feels impossible.", life_patterns: "You're naturally competent and hardworking. But you micro-manage life to avoid uncertainty. You critique instead of create. Spontaneity feels irresponsible.", relationships: "You fix instead of feel. Partners want your heart, not your analysis. Your growth requires letting things be messy and trusting that it'll be okay without your constant management.", challenges: "Chaos is unbearable. You can't let go of control. You judge yourself and others relentlessly. Faith feels naive and irresponsible.", growth: "When you learn to trust what you can't control, your practical gifts gain spiritual depth. Surrender doesn't mean incompetence — it means wisdom.", book_references: ["Schulman, Karmic Astrology"] },
];

export async function GET() {
  const all = [...CHIRON, ...NORTH_NODE, ...SOUTH_NODE];

  // Delete existing entries first
  for (const planet of ["Chiron", "North Node", "South Node"]) {
    await supabase.from("kb_planet_in_sign").delete().eq("planet", planet);
  }

  // Insert all entries
  const { data, error } = await supabase.from("kb_planet_in_sign").insert(all);

  if (error) {
    return NextResponse.json({ error: error.message, details: error }, { status: 500 });
  }

  return NextResponse.json({
    success: true,
    inserted: all.length,
    message: "Seeded Chiron (12), North Node (12), South Node (12) — 36 total entries. You can delete this API route now.",
  });
}
