// Generates src/lib/learn/reference/ingested.ts from the distilled *.reference.json files.
// Dedupes against existing reference entries by a normalized name key.
// Run: npx tsx scripts/ingest/buildReference.ts <dir-with-*.reference.json>
import { ALL_REFERENCE } from "../../src/lib/learn/reference/index";
import type { ReferenceEntry, LearnDomain } from "../../src/lib/learn/types";
import { readFileSync, readdirSync, writeFileSync } from "node:fs";
import { join } from "node:path";

const dir = process.argv[2] || "/root/ingest/out";
const VALID: LearnDomain[] = ["astrology","tarot","numerology","crystals","chakras","herbalism","essential-oils","almanac","meditation","dreams","runes"];
const validSet = new Set<string>(VALID);

// western_core reference duplicates the app's curated signs/planets/houses/angles — skip it.
const SKIP_FILES = new Set(["western_core.reference.json"]);

const norm = (s: string) =>
  s.toLowerCase().replace(/\(.*?\)/g, "").replace(/[^a-z0-9]+/g, "").trim();

const existing = new Set(ALL_REFERENCE.map((e) => `${e.domain}::${norm(e.name)}`));
const seen = new Set<string>();
const usedIds = new Set<string>();
const slug = (s: string) => s.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "").slice(0, 48);

const out: ReferenceEntry[] = [];
let dup = 0, bad = 0;
for (const f of readdirSync(dir).filter((f) => f.endsWith(".reference.json"))) {
  if (SKIP_FILES.has(f)) continue;
  const arr = JSON.parse(readFileSync(join(dir, f), "utf8"));
  for (const r of arr) {
    if (!r?.name || !r?.summary || !Array.isArray(r.fields) || r.fields.length === 0) { bad++; continue; }
    const domain: LearnDomain = validSet.has(r.domain) ? r.domain : "astrology";
    const key = `${domain}::${norm(String(r.name))}`;
    if (existing.has(key) || seen.has(key)) { dup++; continue; }
    seen.add(key);
    let id = `ing-${domain}-${slug(String(r.name))}`;
    let i = 2; while (usedIds.has(id)) id = `ing-${domain}-${slug(String(r.name))}-${i++}`;
    usedIds.add(id);
    const fields = r.fields
      .filter((x: { label?: string; value?: string }) => x?.label && x?.value)
      .map((x: { label: string; value: string }) => ({ label: String(x.label), value: String(x.value) }));
    const entry: ReferenceEntry = {
      id, domain, name: String(r.name), summary: String(r.summary), fields,
      ...(Array.isArray(r.aka) && r.aka.length ? { aka: r.aka.map(String) } : {}),
      ...(r.category ? { category: String(r.category) } : {}),
      ...(r.safety ? { safety: String(r.safety) } : {}),
      ...(Array.isArray(r.tags) && r.tags.length ? { tags: r.tags.map(String) } : {}),
    };
    out.push(entry);
  }
}
out.sort((a, b) => a.domain.localeCompare(b.domain) || a.name.localeCompare(b.name));

const file = `import type { ReferenceEntry } from "../types";

/**
 * Encyclopedia entries distilled from source reference books (public-domain and
 * cited). Auto-generated by scripts/ingest/buildReference.ts — do not edit by hand.
 */
export const ingestedReference: ReferenceEntry[] = ${JSON.stringify(out, null, 2)};
`;
writeFileSync("src/lib/learn/reference/ingested.ts", file);
console.log(`Wrote ${out.length} entries (skipped ${dup} duplicates, ${bad} malformed).`);
const byDom: Record<string, number> = {};
for (const e of out) byDom[e.domain] = (byDom[e.domain] || 0) + 1;
console.log("by domain:", JSON.stringify(byDom));
